export const LIMIT = 100;
export const MAX_RETRIES = 5;
export const INITIAL_BACKOFF_MILLISECONDS = 2000;

export const AP_AGING_REPORT_COLUMNS = [
  "create_by",
  "create_date",
  "doc_num",
  "due_date",
  "last_mod_by",
  "last_mod_date",
  "memo",
  "past_due",
  "term_name",
  "tx_date",
  "txn_type",
  "vend_bill_addr",
  "vend_comp_name",
  "vend_name",
  "vend_pri_cont",
  "vend_pri_email",
  "vend_pri_tel",
  "dept_name",
  "currency",
  "exch_rate",
  "subt_neg_open_bal",
  "subt_neg_amount",
  "neg_foreign_open_bal",
  "subt_neg_home_open_bal",
  "neg_foreign_amount",
  "subt_neg_home_amount",
];

export const PROFIT_LOSS_REPORT_COLUMNS = [
  "create_by",
  "create_date",
  "doc_num",
  "last_mod_by",
  "last_mod_date",
  "memo",
  "name",
  "pmt_mthd",
  "split_acc",
  "tx_date",
  "txn_type",
  "tax_code",
  "klass_name",
  "dept_name",
  "debt_amt",
  "credit_amt",
  "nat_open_bal",
  "subt_nat_amount",
  "subt_nat_amount_nt",
  "rbal_nat_amount",
  "rbal_nat_amount_nt",
  "tax_amount",
  "net_amount",
  "debt_home_amt",
  "credit_home_amt",
  "currency",
  "exch_rate",
  "nat_home_open_bal",
  "nat_foreign_open_bal",
  "subt_nat_home_amount",
  "subt_nat_amount_home_nt",
  "rbal_nat_home_amount",
  "rbal_nat_amount_home_nt",
  "home_tax_amount",
  "home_net_amount",
];

export const DATE_MACRO_OPTIONS = [
  "Today",
  "Yesterday",
  "This Week",
  "Last Week",
  "This Week-to-date",
  "Last Week-to-date",
  "Next Week",
  "Next 4 Weeks",
  "This Month",
  "Last Month",
  "This Month-to-date",
  "Last Month-to-date",
  "Next Month",
  "This Fiscal Quarter",
  "Last Fiscal Quarter",
  "This Fiscal Quarter-to-date",
  "Last Fiscal Quarter-to-date",
  "Next Fiscal Quarter",
  "This Fiscal Year",
  "Last Fiscal Year",
  "This Fiscal Year-to-date",
  "Last Fiscal Year-to-date",
  "Next Fiscal Year",
];

export const PAYMENT_METHOD_OPTIONS = [
  "Cash",
  "Check",
  "Dinners Club",
  "American Express",
  "Discover",
  "MasterCard",
  "Visa",
];

export const ACCOUNT_TYPE_OPTIONS = [
  "AccountsPayable",
  "AccountsReceivable",
  "Bank",
  "CostOfGoodsSold",
  "CreditCard",
  "Equity",
  "Expense",
  "FixedAsset",
  "Income",
  "LongTermLiability",
  "NonPosting",
  "OtherAsset",
  "OtherCurrentAsset",
  "OtherCurrentLiability",
  "OtherExpense",
  "OtherIncome",
];
