export default {
  FIELD_OPTIONS: [
    "addresses",
    "ageRanges",
    "biographies",
    "birthdays",
    "calendarUrls",
    "clientData",
    "coverPhotos",
    "emailAddresses",
    "events",
    "externalIds",
    "genders",
    "imClients",
    "interests",
    "locales",
    "locations",
    "memberships",
    "metadata",
    "miscKeywords",
    "names",
    "nicknames",
    "occupations",
    "organizations",
    "phoneNumbers",
    "photos",
    "relations",
    "sipAddresses",
    "skills",
    "urls",
    "userDefined",
  ],
  UPDATE_PERSON_FIELD_OPTIONS: [
    "names",
    "emailAddresses",
    "phoneNumbers",
    "addresses",
    "biographies",
    "birthdays",
    "calendarUrls",
    "genders",
    "urls",
  ],
  RESOURCE_NAME: "people/me",
  GROUP_FIELDS: [
    "clientData",
    "groupType",
    "memberCount",
    "metadata",
    "name",
  ],
  SOURCE_OPTIONS: [
    {
      label: "Google Workspace domain shared contact",
      value: "DIRECTORY_SOURCE_TYPE_DOMAIN_CONTACT",
    },
    {
      label: "Google Workspace domain profile",
      value: "DIRECTORY_SOURCE_TYPE_DOMAIN_PROFILE",
    },
  ],
  MERGE_SOURCE_OPTIONS: [
    {
      label: "Unspecified",
      value: "DIRECTORY_MERGE_SOURCE_TYPE_UNSPECIFIED",
    },
    {
      label: "User owned contact",
      value: "DIRECTORY_MERGE_SOURCE_TYPE_CONTACT",
    },
  ],
};
