export default {
  FIELD_OPTIONS: [
    "addresses",
    "ageRanges",
    "biographies",
    "birthdays",
    "calendarUrls",
    "clientData",
    "coverPhotos",
    "emailAddresses",
    "events",
    "externalIds",
    "genders",
    "imClients",
    "interests",
    "locales",
    "locations",
    "memberships",
    "metadata",
    "miscKeywords",
    "names",
    "nicknames",
    "occupations",
    "organizations",
    "phoneNumbers",
    "photos",
    "relations",
    "sipAddresses",
    "skills",
    "urls",
    "userDefined",
  ],
  RESOURCE_NAME: "people/me",
  GROUP_FIELDS: [
    "clientData",
    "groupType",
    "memberCount",
    "metadata",
    "name",
  ],
};
