export default {
    "kind": "drive#doc",
    "id": "1MIogJY6eGysghX3aG5CGYTA69IUTZ-vwp",
    "name": "pi-tiny.jpg",
    "mimeType": "image/jpg",
    "starred": true,
    "trashed": true,
    "explicitlyTrashed": true,
    "parents": ["1LtEeLzfyRm1PZCQxth00FV_p-c0pqmJ1"],
    "spaces": ["drive"],
    "version": "2",
    "webContentLink": "https://drive.google.com/uc?id=1MIogJY6eGysghX3aG5CGYTA69IUTZ-vwp&export=download",
    "webViewLink": "https://drive.google.com/file/d/1MIogJY6eGysghX3aG5CGYTA69IUTZ-vwp/view?usp=drivesdk",
    "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/image/jpg",
    "hasThumbnail": false,
    "thumbnailLink": "https://lh4.googleusercontent.com/IHX1zqlVDfhOUPR7DDsDCA1JNpqKfDW7utvo1Jo3YKpakdN8NpgBz_VRK2NlVXSlafxBgaXEdhHEPfY=s221",
    "thumbnailVersion": "2",
    "viewedByMe": false,
    "viewedByMeTime": "2023-06-10T20:20:48.716Z",
    "createdTime": "2023-06-10T20:20:48.716Z",
    "modifiedTime": "2023-06-06T18:29:31.001Z",
    "modifiedByMeTime": "2023-06-06T18:29:31.001Z",
    "modifiedByMe": false,
    "owners": [{
        "kind": "drive#user",
        "displayName": "Dana Vandalay",
        "photoLink": "https://lh4.googleusercontent.com/a/default-user=s65",
        "me": false,
        "permissionId": "02412905735859268338",
        "emailAddress": "dana@pipevision.com"
    }],
    "lastModifyingUser": {
        "kind": "drive#user",
        "displayName": "Dana Vandalay",
        "photoLink": "https://lh4.googleusercontent.com/a/default-user=s65",
        "me": false,
        "permissionId": "02412905735859268338",
        "emailAddress": "dana@pipevision.com"
    },
    "shared": true,
    "ownedByMe": false,
    "capabilities": {
        "canAcceptOwnership": true,
        "canAddChildren": true,
        "canAddMyDriveParent": true,
        "canChangeCopyRequiresWriterPermission": false,
        "canChangeSecurityUpdateEnabled": true,
        "canChangeViewersCanCopyContent": false,
        "canComment": false,
        "canCopy": false,
        "canDelete": false,
        "canDownload": false,
        "canEdit": false,
        "canListChildren": true,
        "canModifyContent": false,
        "canModifyContentRestriction": false,
        "canModifyLabels": true,
        "canMoveChildrenWithinDrive": true,
        "canMoveItemIntoTeamDrive": false,
        "canMoveItemOutOfDrive": false,
        "canMoveItemWithinDrive": false,
        "canReadLabels": true,
        "canReadRevisions": false,
        "canRemoveChildren": true,
        "canRemoveMyDriveParent": false,
        "canRename": false,
        "canShare": false,
        "canTrash": false,
        "canUntrash": false
    },
    "viewersCanCopyContent": false,
    "copyRequiresWriterPermission": true,
    "writersCanShare": false,
    "permissions": [{
        "kind": "drive#permission",
        "id": "02412905735859268338",
        "type": "user",
        "emailAddress": "dana@pipevision.com",
        "role": "editor",
        "displayName": "Dana Vandalay",
        "photoLink": "https://lh4.googleusercontent.com/a/default-user=s65",
        "deleted": true,
        "pendingOwner": true
    }],
    "permissionIds": ["02412905735859268338"],
    "originalFilename": "pi-tiny.jpg",
    "fullFileExtension": "jpg",
    "fileExtension": "jpg",
    "md5Checksum": "e9c88e5a392778edb6b50db4d945866",
    "sha1Checksum": "e65dbcd79a244756c915c8d15be92f8f98e59dc9",
    "sha256Checksum": "96019203d42e274cadecb66da52809cd49452fd974052c2107c0b8be8635612d",
    "size": "182522",
    "quotaBytesUsed": "182522",
    "headRevisionId": "0B-IaF5djEZAoRFKncnZ6ZVJmNkZNZWFZN1k4ZEo5TUQ5ZDlZPQ",
    "imageMediaMetadata": {
        "width": 302,
        "height": 302,
        "rotation": 1
    },
    "isAppAuthorized": true,
    "linkShareMetadata": {
        "securityUpdateEligible": true,
        "securityUpdateEnabled": false
    }    
}