<template><h1 id="changing-how-we-reference-event-and-context" tabindex="-1"><a class="header-anchor" href="#changing-how-we-reference-event-and-context" aria-hidden="true">#</a> Changing how we reference <code>$event</code> and <code>$context</code></h1>
<h2 id="event-is-now-event" tabindex="-1"><a class="header-anchor" href="#event-is-now-event" aria-hidden="true">#</a> <code>$event</code> is now <code>event</code></h2>
<p>Historically, Pipedream provided data on the event that triggered your workflow in a variable called <code>$event</code>. <code>$event</code> was a JavaScript object. For HTTP-triggered workflows, for example, it contained properties like <code>body</code> to represent the body of the HTTP request, and <code>headers</code> for HTTP headers.</p>
<p><strong>Pipedream changed the name of this variable from <code>$event</code> to <code>event</code></strong>. Now, when you want to reference the HTTP payload, for example, you use <code>event.body</code> instead of <code>$event.body</code>. <a href="/workflows/events/#event-format" target="_blank" rel="noopener noreferrer">Read about the full format of <code>event</code> here<ExternalLinkIcon/></a>.</p>
<p><code>$event</code> was also mutable: you could add new properties or modify existing ones. This allowed you to add a property in one step and use that data in the next.</p>
<p><strong><code>event</code> is <em>not</em> mutable</strong> — it's read-only. To share data across steps, <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">use step exports<ExternalLinkIcon/></a>. For example, if you wanted to uppercase the <code>name</code> that arrived in the inbound HTTP request, you could do the following:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>event<span class="token punctuation">.</span>body<span class="token punctuation">.</span>name<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// prints "Luke"</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>uppercasedName <span class="token operator">=</span> event<span class="token punctuation">.</span>body<span class="token punctuation">.</span>name<span class="token punctuation">.</span><span class="token function">toUpperCase</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>If your step was named <code>steps.nodejs</code>, you can reference this data in another step using <code>steps.nodejs.uppercasedName</code>.</p>
<h2 id="context-is-now-steps-trigger-context" tabindex="-1"><a class="header-anchor" href="#context-is-now-steps-trigger-context" aria-hidden="true">#</a> <code>$context</code> is now <code>steps.trigger.context</code></h2>
<p><code>$context</code> provided event-level metadata about the workflow execution: a unique event ID, the workflow ID, and more. <strong>This data is now exposed in <code>steps.trigger.context</code>. You'll need to update any references to <code>$context</code> to use <code>steps.trigger.context</code>, instead</strong>.</p>
<Footer />
</template>
