export default {
  CANDIDATE_ASSIGNED: "candidate.assigned",
  CANDIDATE_CREATED: "candidate.created",
  CANDIDATE_CREATED_TALENTPOOL: "candidate.created.talentpool",
  CANDIDATE_UPDATED: "candidate.updated",
  CANDIDATE_EXTERNAL_PROFILE_UPDATED: "candidate.external.profile.updated",
  CANDIDATE_EXTERNAL_APPLIED_JOBS: "candidate.external.applied.jobs",
  CANDIDATE_HIRINGSTAGE_UPDATED: "candidate.hiringstage.updated",
  CANDIDATE_CLIENTFEEDBACK_RECEIVED: "candidate.clientfeedback.received",
  CONTACT_CREATED: "contact.created",
  CONTACT_UPDATED: "contact.updated",
  COMPANY_CREATED: "company.created",
  COMPANY_UPDATED: "company.updated",
  JOB_CREATED: "job.created",
  JOB_UPDATED: "job.updated",
  JOB_STATUS_UPDATED: "job.status.updated",
  DEAL_CREATED: "deal.created",
  DEAL_UPDATED: "deal.updated",
  DEAL_STAGE_UPDATED: "deal.stage.updated",
  MEETING_CREATED: "meeting.created",
  MEETING_UPDATED: "meeting.updated",
  TASK_CREATED: "task.created",
  TASK_UPDATED: "task.updated",
  NOTE_CREATED: "note.created",
  NOTE_UPDATED: "note.updated",
  CALLLOG_CREATED: "calllog.created",
  CALLLOG_UPDATED: "calllog.updated",
};
