export default {
  "id": "5f4ee830046a92139596173a",
  "badges": {
    "attachmentsByType": {
      "trello": {
        "board": 0,
        "card": 0
      }
    },
    "externalSource": null,
    "location": false,
    "votes": 0,
    "viewingMemberVoted": false,
    "subscribed": false,
    "fogbugz": "",
    "checkItems": 0,
    "checkItemsChecked": 0,
    "checkItemsEarliestDue": null,
    "comments": 0,
    "attachments": 0,
    "description": false,
    "due": null,
    "dueComplete": false,
    "start": null,
    "lastUpdatedByAi": false
  },
  "checkItemStates": [],
  "closed": true,
  "dueComplete": false,
  "dateLastActivity": "2020-09-02T00:34:22.602Z",
  "desc": "",
  "descData": null,
  "due": null,
  "dueReminder": null,
  "email": null,
  "idBoard": "5f4d7be6c45c22583f75fa02",
  "idChecklists": [],
  "idList": "5f4d7f78bdd7ce4d2d25fdda",
  "idMembers": [],
  "idMembersVoted": [],
  "idShort": 10,
  "idAttachmentCover": null,
  "labels": [],
  "idLabels": [],
  "manualCoverAttachment": false,
  "name": "a new card",
  "pinned": false,
  "pos": 65535,
  "shortLink": "eBapV0gL",
  "shortUrl": "https://trello.com/c/eBapV0gL",
  "start": null,
  "subscribed": false,
  "url": "https://trello.com/c/eBapV0gL/10-a-new-card",
  "cover": {
    "idAttachment": null,
    "color": null,
    "idUploadedBackground": null,
    "size": "normal",
    "brightness": "light",
    "idPlugin": null
  },
  "isTemplate": false,
  "cardRole": null
}