const channels = [
  "aircall",
  "api",
  "chat",
  "email",
  "facebook",
  "facebook-mention",
  "facebook-messenger",
  "facebook-recommendations",
  "help-center",
  "instagram-ad-comment",
  "instagram-comment",
  "instagram-mention",
  "instagram-direct-message",
  "internal-note",
  "phone",
  "sms",
  "twitter",
  "twitter-direct-message",
  "yotpo-review",
];

const vias = [
  "help-center",
  "twitter",
  "self_service",
  "api",
  "form",
  "chat",
  "facebook",
  "yotpo-review",
  "twitter-direct-message",
  "rule",
  "twilio",
  "yotpo",
  "gorgias_chat",
  "facebook-messenger",
  "sms",
  "instagram-mention",
  "instagram-ad-comment",
  "facebook-mention",
  "aircall",
  "helpdesk",
  "zendesk",
  "facebook-recommendations",
  "instagram-comment",
  "instagram-direct-message",
  "internal-note",
  "shopify",
  "email",
  "phone",
  "instagram",
];

export default {
  channels,
  vias,
};
