export default {
   "product":{
      "id":123,
      "createdAt":"2025-09-17T20:25:55+00:00",
      "updatedAt":"2025-09-17T20:25:55+00:00",
      "isVisible":true,
      "visibility":"visible",
      "hasMatrix":false,
      "data01":"",
      "data02":"",
      "data03":"",
      "url":"product-test",
      "title":"product test",
      "fulltitle":"product test",
      "description":"",
      "content":"",
      "set":false,
      "brand":{
         "resource":{
            "id":123,
            "url":"brands\/123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/brands\/123.json"
         }
      },
      "categories":{
         "resource":{
            "id":false,
            "url":"categories\/products?product=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/categories\/products.json?product=123"
         }
      },
      "deliverydate":false,
      "image":false,
      "images":false,
      "relations":{
         "resource":{
            "id":false,
            "url":"products\/123\/relations",
            "link":"http:\/\/api.shoplightspeed.com\/en\/products\/123\/relations.json"
         }
      },
      "metafields":{
         "resource":{
            "id":false,
            "url":"products\/123\/metafields",
            "link":"http:\/\/api.shoplightspeed.com\/en\/products\/123\/metafields.json"
         }
      },
      "reviews":{
         "resource":{
            "id":false,
            "url":"reviews?product=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/reviews.json?product=123"
         }
      },
      "type":false,
      "attributes":{
         "resource":{
            "id":false,
            "url":"products\/123\/attributes",
            "link":"http:\/\/api.shoplightspeed.com\/en\/products\/123\/attributes.json"
         }
      },
      "supplier":false,
      "tags":{
         "resource":{
            "id":false,
            "url":"tags\/products?product=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/tags\/products.json?product=123"
         }
      },
      "variants":{
         "resource":{
            "id":false,
            "url":"variants?product=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/variants.json?product=123"
         }
      },
      "movements":{
         "resource":{
            "id":false,
            "url":"variants\/movements?product=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/variants\/movements.json?product=123"
         }
      },
      "templateDataFields":[
         
      ]
   }
}