export default {
  "v": 1,
  "matches_filters": {
    "current": []
  },
  "meta": {
    "action": "added",
    "change_source": "api",
    "company_id": 1234567890,
    "host": "subdomain.pipedrive.com",
    "id": 10,
    "is_bulk_update": false,
    "matches_filters": {
      "current": []
    },
    "object": "deal",
    "permitted_user_ids": [
      1234567890
    ],
    "pipedrive_service_name": false,
    "timestamp": 1739826584,
    "timestamp_micro": 1739826584443168,
    "prepublish_timestamp": 1739826584525,
    "trans_pending": false,
    "user_id": 1234567890,
    "v": 1,
    "webhook_id": "1234567890"
  },
  "current": {
    "email_messages_count": 0,
    "cc_email": "subomain+deal11@pipedrivemail.com",
    "channel": 8,
    "products_count": 0,
    "archive_time": null,
    "acv_currency": null,
    "next_activity_date": null,
    "acv": null,
    "next_activity_type": null,
    "local_close_date": null,
    "next_activity_duration": null,
    "id": 11,
    "person_id": null,
    "creator_user_id": 1234567890,
    "expected_close_date": null,
    "owner_name": "Owner Name",
    "arr_currency": null,
    "participants_count": 0,
    "stage_id": 1,
    "probability": null,
    "undone_activities_count": 0,
    "active": true,
    "local_lost_date": null,
    "person_name": null,
    "last_activity_date": null,
    "close_time": null,
    "org_hidden": false,
    "next_activity_id": null,
    "weighted_value_currency": "USD",
    "local_won_date": null,
    "stage_order_nr": 0,
    "next_activity_subject": null,
    "rotten_time": null,
    "is_archived": false,
    "user_id": 1234567890,
    "visible_to": "3",
    "org_id": null,
    "notes_count": 0,
    "next_activity_time": null,
    "channel_id": "Pipedream",
    "formatted_value": "$ 0",
    "status": "open",
    "formatted_weighted_value": "$ 0",
    "mrr_currency": null,
    "first_won_time": null,
    "origin": "Marketplace",
    "last_outgoing_mail_time": null,
    "origin_id": "5d80274eae050b58",
    "title": "Deal Title",
    "last_activity_id": null,
    "update_time": "2025-02-17 21:09:44",
    "activities_count": 0,
    "pipeline_id": 1,
    "lost_time": null,
    "currency": "USD",
    "weighted_value": 0,
    "org_name": null,
    "value": 0,
    "person_hidden": false,
    "next_activity_note": null,
    "arr": null,
    "files_count": 0,
    "last_incoming_mail_time": null,
    "label": null,
    "mrr": null,
    "lost_reason": null,
    "deleted": false,
    "won_time": null,
    "followers_count": 0,
    "stage_change_time": null,
    "add_time": "2025-02-17 21:09:44",
    "done_activities_count": 0
  },
  "previous": null,
  "retry": 0,
  "event": "added.deal"
}