import rebrandly from "../../rebrandly.app.mjs";

export default {
  name: "Create Link",
  version: "0.0.2",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: false,
  },
  key: "rebrandly-create-link",
  description: "Creates a link. [See docs here](https://developers.rebrandly.com/docs/create-a-new-link)",
  type: "action",
  props: {
    rebrandly,
    destination: {
      label: "Destination",
      description: "The destination URL you want your branded short link to point to. E.g. `https://pipedream.com`",
      type: "string",
    },
    slashtag: {
      label: "Slashtag",
      description: "The keyword portion of your branded short link. If not specified, will be autogenerated",
      type: "string",
      optional: true,
    },
    title: {
      label: "Title",
      description: "A title you assign to the branded short link in order to remember what's behind it",
      type: "string",
      optional: true,
    },
    domain: {
      description: "A reference to the branded domain resource for this branded short link.",
      optional: true,
      propDefinition: [
        rebrandly,
        "domain",
      ],
    },
  },
  async run({ $ }) {
    const response = await this.rebrandly.createLink({
      $,
      data: {
        destination: this.destination,
        slashtag: this.slashtag,
        title: this.title,
        domain: this.domain,
      },
    });

    if (response) {
      $.export("$summary", `Successfully created link with id ${response.id}`);
    }

    return response;
  },
};
