const DOMAIN_SUFFIX = ".myshopify.com";
const WEBHOOK_ID = "webhookId";

const HEADER = {
  SHOP_DOMAIN: "x-shopify-shop-domain",
  TOPIC: "x-shopify-topic",
};

const EVENT_TOPIC = {
  APP_SCOPES_UPDATE: "app/scopes_update",
  APP_UNINSTALLED: "app/uninstalled",
  BULK_OPERATIONS_FINISH: "bulk_operations/finish",
  COLLECTION_LISTINGS_ADD: "collection_listings/add",
  COLLECTION_LISTINGS_REMOVE: "collection_listings/remove",
  COLLECTION_LISTINGS_UPDATE: "collection_listings/update",
  COLLECTIONS_CREATE: "collections/create",
  COLLECTIONS_DELETE: "collections/delete",
  COLLECTIONS_UPDATE: "collections/update",
  DISCOUNTS_CREATE: "discounts/create",
  DISCOUNTS_DELETE: "discounts/delete",
  DISCOUNTS_UPDATE: "discounts/update",
  DISCOUNTS_REDEEMCODE_ADDED: "discounts/redeemcode_added",
  DISCOUNTS_REDEEMCODE_REMOVED: "discounts/redeemcode_removed",
  DOMAINS_CREATE: "domains/create",
  DOMAINS_DESTROY: "domains/destroy",
  DOMAINS_UPDATE: "domains/update",
  FULFILLMENT_HOLDS_ADDED: "fulfillment_holds/added",
  FULFILLMENT_HOLDS_RELEASED: "fulfillment_holds/released",
  FULFILLMENT_ORDERS_CANCELLATION_REQUEST_ACCEPTED: "fulfillment_orders/cancellation_request_accepted",
  FULFILLMENT_ORDERS_CANCELLATION_REQUEST_REJECTED: "fulfillment_orders/cancellation_request_rejected",
  FULFILLMENT_ORDERS_CANCELLATION_REQUEST_SUBMITTED: "fulfillment_orders/cancellation_request_submitted",
  FULFILLMENT_ORDERS_CANCELLED: "fulfillment_orders/cancelled",
  FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_ACCEPTED: "fulfillment_orders/fulfillment_request_accepted",
  FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_REJECTED: "fulfillment_orders/fulfillment_request_rejected",
  FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_SUBMITTED: "fulfillment_orders/fulfillment_request_submitted",
  FULFILLMENT_ORDERS_FULFILLMENT_SERVICE_FAILED_TO_COMPLETE: "fulfillment_orders/fulfillment_service_failed_to_complete",
  FULFILLMENT_ORDERS_HOLD_RELEASED: "fulfillment_orders/hold_released",
  FULFILLMENT_ORDERS_LINE_ITEMS_PREPARED_FOR_LOCAL_DELIVERY: "fulfillment_orders/line_items_prepared_for_local_delivery",
  FULFILLMENT_ORDERS_LINE_ITEMS_PREPARED_FOR_PICKUP: "fulfillment_orders/line_items_prepared_for_pickup",
  FULFILLMENT_ORDERS_MERGED: "fulfillment_orders/merged",
  FULFILLMENT_ORDERS_MOVED: "fulfillment_orders/moved",
  FULFILLMENT_ORDERS_ORDER_ROUTING_COMPLETE: "fulfillment_orders/order_routing_complete",
  FULFILLMENT_ORDERS_PLACED_ON_HOLD: "fulfillment_orders/placed_on_hold",
  FULFILLMENT_ORDERS_RESCHEDULED: "fulfillment_orders/rescheduled",
  FULFILLMENT_ORDERS_SCHEDULED_FULFILLMENT_ORDER_READY: "fulfillment_orders/scheduled_fulfillment_order_ready",
  FULFILLMENT_ORDERS_SPLIT: "fulfillment_orders/split",
  INVENTORY_ITEMS_CREATE: "inventory_items/create",
  INVENTORY_ITEMS_DELETE: "inventory_items/delete",
  INVENTORY_ITEMS_UPDATE: "inventory_items/update",
  INVENTORY_LEVELS_CONNECT: "inventory_levels/connect",
  INVENTORY_LEVELS_DISCONNECT: "inventory_levels/disconnect",
  INVENTORY_LEVELS_UPDATE: "inventory_levels/update",
  LOCALES_CREATE: "locales/create",
  LOCALES_UPDATE: "locales/update",
  LOCATIONS_CREATE: "locations/create",
  LOCATIONS_DELETE: "locations/delete",
  LOCATIONS_UPDATE: "locations/update",
  LOCATIONS_ACTIVATE: "locations/activate",
  LOCATIONS_DEACTIVATE: "locations/deactivate",
  MARKETS_CREATE: "markets/create",
  MARKETS_DELETE: "markets/delete",
  MARKETS_UPDATE: "markets/update",
  PAYMENT_SCHEDULE_DUE: "payment_schedules/due",
  PRODUCT_LISTINGS_ADD: "product_listings/add",
  PRODUCT_LISTINGS_REMOVE: "product_listings/remove",
  PRODUCT_LISTINGS_UPDATE: "product_listings/update",
  PRODUCTS_CREATE: "products/create",
  PRODUCTS_DELETE: "products/delete",
  PRODUCTS_UPDATE: "products/update",
  REFUNDS_CREATE: "refunds/create",
  RETURNS_APPROVE: "returns/approve",
  RETURNS_CANCEL: "returns/cancel",
  RETURNS_CLOSE: "returns/close",
  RETURNS_DECLINE: "returns/decline",
  RETURNS_PROCESS: "returns/process",
  RETURNS_REOPEN: "returns/reopen",
  RETURNS_REQUEST: "returns/request",
  RETURNS_UPDATE: "returns/update",
  SCHEDULED_PRODUCT_LISTINGS_ADD: "scheduled_product_listings/add",
  SCHEDULED_PRODUCT_LISTINGS_REMOVE: "scheduled_product_listings/remove",
  SCHEDULED_PRODUCT_LISTINGS_UPDATE: "scheduled_product_listings/update",
  SEGMENTS_CREATE: "segments/create",
  SEGMENTS_DELETE: "segments/delete",
  SEGMENTS_UPDATE: "segments/update",
  SELLING_PLAN_GROUPS_CREATE: "selling_plan_groups/create",
  SELLING_PLAN_GROUPS_DELETE: "selling_plan_groups/delete",
  SELLING_PLAN_GROUPS_UPDATE: "selling_plan_groups/update",
  SHOP_UPDATE: "shop/update",
  SUBSCRIPTION_CONTRACTS_ACTIVATE: "subscription_contracts/activate",
  SUBSCRIPTION_CONTRACTS_CANCEL: "subscription_contracts/cancel",
  SUBSCRIPTION_CONTRACTS_EXPIRE: "subscription_contracts/expire",
  SUBSCRIPTION_CONTRACTS_FAIL: "subscription_contracts/fail",
  SUBSCRIPTION_CONTRACTS_PAUSE: "subscription_contracts/pause",
  SUBSCRIPTION_CONTRACTS_CREATE: "subscription_contracts/create",
  SUBSCRIPTION_CONTRACTS_UPDATE: "subscription_contracts/update",
  THEMES_CREATE: "themes/create",
  THEMES_DELETE: "themes/delete",
  THEMES_PUBLISH: "themes/publish",
  THEMES_UPDATE: "themes/update",
  VARIANTS_IN_STOCK: "variants/in_stock",
  VARIANTS_OUT_OF_STOCK: "variants/out_of_stock",
  EVENT_TOPICS_THEMES_UPDATE: "event-topics-themes-update",
};

const EVENT_TOPICS = Object.values(EVENT_TOPIC);

export default {
  DOMAIN_SUFFIX,
  WEBHOOK_ID,
  HEADER,
  EVENT_TOPIC,
  EVENT_TOPICS,
};
