<template><h1 id="http" tabindex="-1"><a class="header-anchor" href="#http" aria-hidden="true">#</a> HTTP</h1>
<p>HTTP Destinations allow you to send data to another HTTP endpoint URL outside of Pipedream. This can be an endpoint you own and operate, or a URL tied to a service you use (for example, a <a href="https://api.slack.com/incoming-webhooks" target="_blank" rel="noopener noreferrer">Slack Incoming Webhook<ExternalLinkIcon/></a>).</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#using-send-http-in-workflows">Using $.send.http in workflows</RouterLink></li><li><RouterLink to="#using-send-http-in-component-actions">Using $.send.http in component actions</RouterLink></li><li><RouterLink to="#http-destination-delivery">HTTP Destination delivery</RouterLink></li><li><RouterLink to="#http-request-and-response-logs">HTTP request and response logs</RouterLink></li><li><RouterLink to="#what-if-i-need-to-access-the-http-response-in-my-workflow">What if I need to access the HTTP response in my workflow?</RouterLink></li><li><RouterLink to="#timeout">Timeout</RouterLink></li><li><RouterLink to="#retries">Retries</RouterLink></li><li><RouterLink to="#ip-addresses-for-pipedream-http-requests">IP addresses for Pipedream HTTP requests</RouterLink></li></ul></nav>
<h2 id="using-send-http-in-workflows" tabindex="-1"><a class="header-anchor" href="#using-send-http-in-workflows" aria-hidden="true">#</a> Using <code>$.send.http</code> in workflows</h2>
<p>You can send HTTP requests in <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">Node.js code steps<ExternalLinkIcon/></a> using <code>$.send.http()</code>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
 <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">http</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
    <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"[YOUR URL HERE]"</span><span class="token punctuation">,</span>
    <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke Skywalker"</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  
 <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p><code>$.send.http()</code> accepts an object with all of the following properties:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">http</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      method<span class="token punctuation">,</span> <span class="token comment">// Required, HTTP method, a string, e.g. POST, GET</span>
      url<span class="token punctuation">,</span> <span class="token comment">// Required, the URL to send the HTTP request to</span>
      data<span class="token punctuation">,</span> <span class="token comment">// HTTP payload</span>
      headers<span class="token punctuation">,</span> <span class="token comment">// An object containing custom headers, e.g. { "Content-Type": "application/json" }</span>
      params<span class="token punctuation">,</span> <span class="token comment">// An object containing query string parameters as key-value pairs</span>
      auth<span class="token punctuation">,</span> <span class="token comment">// An object that contains a username and password property, for HTTP basic auth</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p><strong>Destination delivery is asynchronous</strong>: the HTTP requests are sent after your workflow finishes. This means <strong>you cannot write code that operates on the HTTP response</strong>. The benefit of using <code>$.send.http()</code>, though, is that these HTTP requests also don't count against your <a href="/limits/#compute-time-per-day" target="_blank" rel="noopener noreferrer">compute time quota<ExternalLinkIcon/></a> on the <a href="/pricing/#developer-tier" target="_blank" rel="noopener noreferrer">free tier<ExternalLinkIcon/></a>.</p>
<p>If you iterate over an array of values and send an HTTP request for each:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>
<span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> names <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Luke"</span><span class="token punctuation">,</span> <span class="token string">"Han"</span><span class="token punctuation">,</span> <span class="token string">"Leia"</span><span class="token punctuation">,</span> <span class="token string">"Obi Wan"</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    names<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">name</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">http</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"[YOUR URL HERE]"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          name<span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><p>you won't have to <code>await</code> the execution of the HTTP requests in your workflow. We'll collect every <code>$.send.http()</code> call and defer those HTTP requests, sending them after your workflow finishes.</p>
<h2 id="using-send-http-in-component-actions" tabindex="-1"><a class="header-anchor" href="#using-send-http-in-component-actions" aria-hidden="true">#</a> Using <code>$.send.http</code> in component actions</h2>
<p>If you're authoring a <a href="/components/actions/" target="_blank" rel="noopener noreferrer">component action<ExternalLinkIcon/></a>, you can deliver data to an HTTP destination using <code>$.send.http</code>.</p>
<p><code>$.send.http</code> functions the same as <a href="#using-send-http-in-workflows"><code>$.send.http</code> in workflow code steps</a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">http</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="http-destination-delivery" tabindex="-1"><a class="header-anchor" href="#http-destination-delivery" aria-hidden="true">#</a> HTTP Destination delivery</h2>
<p>HTTP Destination delivery is handled asynchronously, separate from the execution of a workflow. However, we deliver the specified payload to HTTP destinations for every event sent to your workflow.</p>
<p>Generally, this means it should only take a few seconds for us to send the event to the destination you specify. In some cases, delivery will take longer.</p>
<p>The time it takes to make HTTP requests sent with <code>$.send.http()</code> does not count against your workflow quota.</p>
<h2 id="http-request-and-response-logs" tabindex="-1"><a class="header-anchor" href="#http-request-and-response-logs" aria-hidden="true">#</a> HTTP request and response logs</h2>
<p>Below your code step, you'll see both the data that was sent in the HTTP request, and the HTTP response that was issued. If you issue multiple HTTP requests, we'll show the request and response data for each.</p>
<h2 id="what-if-i-need-to-access-the-http-response-in-my-workflow" tabindex="-1"><a class="header-anchor" href="#what-if-i-need-to-access-the-http-response-in-my-workflow" aria-hidden="true">#</a> What if I need to access the HTTP response in my workflow?</h2>
<p>Since HTTP requests sent with <code>$.send.http()</code> are sent asynchronously, after your workflow runs, <strong>you cannot access the HTTP response in your workflow</strong>.</p>
<p>If you need to access the HTTP response data in your workflow, <a href="/workflows/steps/code/nodejs/http-requests/" target="_blank" rel="noopener noreferrer">use <code>axios</code><ExternalLinkIcon/></a> or another HTTP client.</p>
<h2 id="timeout" tabindex="-1"><a class="header-anchor" href="#timeout" aria-hidden="true">#</a> Timeout</h2>
<p>The timeout on HTTP request sent with <code>$.send.http()</code> is currently <strong>5 seconds</strong>. This time includes DNS resolution, connecting to the host, writing the request body, server processing, and reading the response body.</p>
<p>Any requests that exceed 5 seconds will yield a <code>timeout</code> error.</p>
<h2 id="retries" tabindex="-1"><a class="header-anchor" href="#retries" aria-hidden="true">#</a> Retries</h2>
<p>Currently, Pipedream will not retry any failed request. If your HTTP destination endpoint is down, or returns an error response, we'll display that response in the observability associated with the Destination in the relevant step.</p>
<h2 id="ip-addresses-for-pipedream-http-requests" tabindex="-1"><a class="header-anchor" href="#ip-addresses-for-pipedream-http-requests" aria-hidden="true">#</a> IP addresses for Pipedream HTTP requests</h2>
<p>When you make an HTTP request using <code>$.send.http()</code>, the traffic will come from one of the following IP addresses:</p>
<p>&lt;&lt;&lt; @/docs/snippets/public-node-ips.txt</p>
<p>This list may change over time. If you've previously whitelisted these IP addresses and are having trouble sending HTTP requests to your target service, please check to ensure this list matches your firewall rules.</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>These IP addresses are tied specifically to the <code>$.send.http()</code> service. If you send traffic directly from a workflow, it will be sent from one of Pipedream's general range of IP addresses. <a href="/workflows/networking/" target="_blank" rel="noopener noreferrer">See our networking docs for more information<ExternalLinkIcon/></a>.</p>
</div>
<Footer />
</template>
