export default {
  ADMIN_PROMOTED: "AdminPromoted",
  ADMIN_DEMOTED: "AdminDemoted",
  DATASOURCE_UPDATED: "DatasourceUpdated",
  DATASOURCE_CREATED: "DatasourceCreated",
  DATASOURCE_DELETED: "DatasourceDeleted",
  DATASOURCE_REFRESH_STARTED: "DatasourceRefreshStarted",
  DATASOURCE_REFRESH_SUCCEEDED: "DatasourceRefreshSucceeded",
  DATASOURCE_REFRESH_FAILED: "DatasourceRefreshFailed",
  LABEL_CREATED: "LabelCreated",
  LABEL_UPDATED: "LabelUpdated",
  LABEL_DELETED: "LabelDeleted",
  SITE_CREATED: "SiteCreated",
  SITE_UPDATED: "SiteUpdated",
  SITE_DELETED: "SiteDeleted",
  USER_DELETED: "UserDeleted",
  VIEW_DELETED: "ViewDeleted",
  WORKBOOK_UPDATED: "WorkbookUpdated",
  WORKBOOK_CREATED: "WorkbookCreated",
  WORKBOOK_DELETED: "WorkbookDeleted",
  WORKBOOK_REFRESH_STARTED: "WorkbookRefreshStarted",
  WORKBOOK_REFRESH_SUCCEEDED: "WorkbookRefreshSucceeded",
  WORKBOOK_REFRESH_FAILED: "WorkbookRefreshFailed",
};
