export default {
  "orderId": "123",
  "order": {
    "address": {
      "country": "",
      "address": "",
      "city": "",
      "name": "",
      "mobile": "",
      "state": "",
    },
    "orderId": "123",
    "grandTotal": 1,
    "weight": 1,
    "salesChannel": "manual",
    "createdDate": "2025-05-08T16:18:03Z",
    "warehouseId": 24801,
    "otoId": 30911387,
    "paymentMethod": "paid",
    "currency": "SAR",
    "incrementId": "123",
    "items": [
      {
        "itemId": 14437928,
        "productId": 6350018,
        "qtyOrdered": 1,
        "sku": "1234",
        "productName": "product1",
      },
    ],
    "status": "assignedToWarehouse",
  },
  "status": "assignedToWarehouse",
  "timestamp": 1746721083000,
};
