export default {
  "id": 138745,
  "organization_id": 14799,
  "company_id": 14799,
  "job_id": 203439,
  "department_id": 155885,
  "location_id": null,
  "buddy_id": 138750,
  "manager_id": 138750,
  "indirect_manager_id": null,
  "hr_manager_id": 138751,
  "cost_center_id": null,
  "cost_unit_id": null,
  "first_name": "Chantalle",
  "initials": "C.H.",
  "last_name": "Titulaer",
  "last_name_prefix": "van",
  "last_name_composition": "own_name",
  "composed_last_name": "Titulaer",
  "composed_last_name_prefix": "van",
  "full_name": "Chantalle van Titulaer",
  "full_name_alt": "Titulaer, Chantalle van",
  "gender": "female",
  "number": "1",
  "exact_employee_number": "5",
  "nationality": "NR",
  "national_id": "hyqflu",
  "birth_place": "Rotterdam",
  "birth_date": "1992-09-03",
  "marital_status": "single",
  "marital_date": "2019-07-01",
  "partner_last_name": null,
  "partner_last_name_prefix": null,
  "work_email": "hey@buddee.nl",
  "work_phone": "0678605343",
  "work_phone_extension": null,
  "work_mobile": "0612345678",
  "personal_email": null,
  "personal_phone": "0645632145",
  "personal_mobile": null,
  "street": "Hoofdstraat",
  "street_number": "124",
  "street_number_suffix": "B",
  "postal_code": "3062 DF",
  "city": "Amsterdam",
  "country": "NL",
  "bank_account_holder": "C. Titulaer",
  "bank_account_iban": "NL68INGB9012918502",
  "emergency_contact_name": "Hans",
  "emergency_contact_relation": "Vader",
  "emergency_contact_email": null,
  "emergency_contact_phone": "0627472838",
  "hire_date": null,
  "employment_date": "2021-11-15",
  "first_day_at_work_date": "2021-11-15",
  "seniority_date": "2021-11-15",
  "archived_at": null,
  "created_at": "2021-04-19 12:39:15",
  "updated_at": "2024-11-11 09:28:35",
  "_permissions": [
    "create",
    "delete",
    "invite",
    "read",
    "read.full",
    "update"
  ],
  "salutation": "Mevr."
}