export default {
  DEFAULT_BATCH_SIZE: 100,
  MAX_PAYLOAD_SIZE_MB: 5,
  MIN_LIMIT: 1,
  MAX_LIMIT: 1000,
  MIN_PAYLOAD_SIZE_MB: 1,
  MAX_PAYLOAD_SIZE_MB_MAX: 10,
  INSERT_BATCH_THRESHOLD: 50,
  BATCH_SAFETY_MARGIN: 0.8,
  MIN_ROWS_PER_BATCH: 10,
  MAX_ROWS_PER_BATCH: 500,
  BATCH_DELAY_MS: 100,
  SAMPLE_ROW_COUNT: 10,
};
