const COURSE_STATE_OPTIONS = [
  "COURSE_STATE_UNSPECIFIED",
  "ACTIVE",
  "ARCHIVED",
  "PROVISIONED",
  "DECLINED",
  "SUSPENDED",
];

const COURSEWORK_STATE_OPTIONS = [
  "COURSE_WORK_STATE_UNSPECIFIED",
  "PUBLISHED",
  "DRAFT",
  "DELETED",
];

export default {
  COURSE_STATE_OPTIONS,
  COURSEWORK_STATE_OPTIONS,
};
