export default {
  "id": 6214722,
  "fname": "John",
  "lname": "Doe",
  "email": "john.doe@example.com",
  "phone_number": "+15555555555",
  "company": "Example Inc.",
  "category": "Lead",
  "source": "Pipedream",
  "crm": "1234567890",
  "comments": "This is a test comment",
  "comments_formatted": "This is a test comment",
  "lead_owner": "John Doe",
  "notes": [
    {
      "id": 512020,
      "user_id": 27405,
      "call_id": null,
      "content": "This is a test note",
      "created_at": "2026-01-29T20:49:41.000000Z"
    },
    {
      "id": 512018,
      "user_id": 27405,
      "call_id": null,
      "content": "This is a test note 2",
      "created_at": "2026-01-29T20:46:41.000000Z"
    }
  ],
  "tags": [],
  "status": "missed",
  "result": "missed",
  "stage": "contacted",
  "team": {
    "id": 19094,
    "name": "Main Team"
  },
  "updatedField": "note",
  "updatedValue": {
    "id": 512020,
    "account_id": 11157,
    "user_id": 27405,
    "call_id": null,
    "lead_id": 6214722,
    "content": "This is a test note",
    "created_at": "2026-01-29T20:49:41.000000Z",
    "updated_at": "2026-01-29T20:49:41.000000Z",
    "created_at_formatted": "01/29/26 5:49pm",
    "user": {
      "id": 27405,
      "account_id": 11157,
      "account_override_id": null,
      "on_call_id": null,
      "fname": "John",
      "lname": "Doe",
      "email": "john.doe@example.com",
      "two_factor_secret": null,
      "two_factor_recovery_codes": null,
      "phone_number": "+15555555555",
      "ext": null,
      "country_code": "US",
      "timezone": "America/Sao_Paulo",
      "ip": "2804:1254:2088:5a00:a53b:3b25:abb8:62d8",
      "role": "owner",
      "source": "Pipedream",
      "send_emails": true,
      "send_sms": false,
      "send_web": true,
      "donotdisturb": false,
      "donotdisturb_until": null,
      "is_online_web": true,
      "is_online_app": false,
      "is_reset_password": 0,
      "paid_invoices": null,
      "crm": "1234567890",
      "last_login": "2026-01-29T15:25:01.000000Z",
      "last_app_online": null,
      "is_show_banner": true,
      "is_record": 0,
      "aircall_id": null,
      "gcal_id": null,
      "hubspot_id": null,
      "fub_id": null,
      "is_all_categories": 1,
      "categories": null,
      "custom_id": null,
      "callerid_id": null,
      "is_verified": 0,
      "last_called_at": null,
      "created_at": "2026-01-29T15:25:01.000000Z",
      "updated_at": "2026-01-29T19:28:17.000000Z",
      "deleted_at": null,
      "is_superadmin": false,
      "pipedrive_id": null,
      "identifier": null,
      "salesforce_id": null,
      "is_show_banner2": true,
      "activecampaign_id": null,
      "outbound_number_id": null,
      "is_app_only": false,
      "last_completed_call_at": null,
      "is_mobile": false,
      "mobile_not_ringing_count": 0,
      "busy_signal_count": 0,
      "missed_call_count": 0,
      "is_app_contacts": 0,
      "profile_picture": "https://ui-avatars.com/api/Luan+Cazarine/80/003C4D/FFFFFF/2/0.5",
      "wiseagent_id": null,
      "last_mobile_login": null,
      "brivity_id": null,
      "cinc_id": null,
      "is_free": 0,
      "is_admin_only": false,
      "visitor_id": "1234567890",
      "lofty_id": null,
      "is_phone_accepted_call": 0,
      "is_phone_forwarding": 0,
      "phone_type": "mobile",
      "phone_carrier": "Example Carrier",
      "keap_id": null,
      "is_onboarding_emails": true,
      "gohighlevel_id": null,
      "recording_url": null,
      "whispertext_loops": null,
      "last_app_offline": null,
      "kit_id": 3890870603,
      "last_app_ping": null,
      "full_name": "John Doe",
      "permissions": [
        "recordings",
        "scheduled_calls:delete"
      ],
      "phone_number_formatted": "(555) 555-5555",
      "account": {
        "id": 11157,
        "org_id": null,
        "admin_id": null,
        "name": "PipedreamDev",
        "billing_email": "john.doe@example.com",
        "date_time_format": "US",
        "timezone": "America/Sao_Paulo",
        "country_code": "US",
        "is_active": true,
        "is_company_field": 0,
        "is_verified": 0,
        "is_billing_error": 0,
        "is_silence_rate_errors": 0,
        "is_over_limit": 0,
        "is_flagged": 0,
        "is_agency": false,
        "last_billed_at": null,
        "ai_started_at": null,
        "first_url": "",
        "first_referrer": "",
        "surcharge": null,
        "discount_percent": null,
        "stripe_id": null,
        "zip_code": null,
        "plan_id": 38,
        "expires_at": null,
        "canceled_at": null,
        "outbound_number_id": 14,
        "upgraded_at": null,
        "is_hangup_vm": 0,
        "is_retry_voicemail": true,
        "is_machine_result": true,
        "lead_owner_auto": true,
        "lead_owner_routing": "owner_first",
        "lead_permissions": "all",
        "manager_lead_permissions": "all",
        "is_sms_disposition": 0,
        "is_user_daily_cap": false,
        "is_agent_schedule": false,
        "is_duplicate_leads": 0,
        "is_legacy_webhooks": 0,
        "is_queue": true,
        "is_app_only": 0,
        "whispertext_loop": 20,
        "schedule_interval": 0,
        "ring_timeout": 60,
        "cohort": "5-2026",
        "total_paid": null,
        "last_paid": null,
        "trial_ended_at": null,
        "logo_url": null,
        "custom_css": null,
        "sso_domain": null,
        "rate_limit": 0.06,
        "sms_rate_limit": 0.05,
        "autodetect_threshold": 30,
        "hubspot_id": null,
        "created_at": "2026-01-29T15:25:00.000000Z",
        "updated_at": "2026-01-29T20:00:18.000000Z",
        "identifier": null,
        "is_enterprise": 0,
        "primary_profile_id": 19094,
        "primary_number_id": null,
        "is_charge_usage": 0,
        "deleted_at": null,
        "cooldown_seconds": 60,
        "cooldown_missed_seconds": 300,
        "is_simultaneous_calls": 0,
        "is_realestate": 0,
        "morning_time": "08:00:00",
        "midday_time": "12:00:00",
        "afternoon_time": "15:00:00",
        "evening_time": "18:00:00",
        "last_inbound_call_at": null,
        "auto_lead_owner_type": "called",
        "gpt_summary_prompt": null,
        "gpt_advice_prompt": null,
        "is_free_email": 0,
        "openai_key": null,
        "is_sso_only": 0,
        "deactivated_at": null,
        "archived_at": null,
        "min_seats": null,
        "max_seats": null,
        "is_sms_override": 0,
        "is_agent_sms": 1,
        "is_manager_sms": 1,
        "referral_id": null,
        "industry": null,
        "website": null,
        "billing_quantity_updated_at": "2026-01-29 19:21:16",
        "pm_type": null,
        "pm_last_four": null,
        "trial_ends_at": "2026-02-12T15:25:00.000000Z",
        "webhook_slug": "TuArXm6DyhdPPXfzD8qt",
        "primary_crm_id": null,
        "is_ai_trial": 1,
        "ai_trial_calls_included": 100,
        "ai_calls_max": 500,
        "ai_usage_hourly_percent": "0.00",
        "is_manual_call_ratio_exception": 0
      }
    }
  },
  "agent": {
    "name": "John Doe",
    "phone_number": "+15555555555",
    "custom_id": null
  },
  "user": {
    "name": "John Doe",
    "phone_number": "+15555555555",
    "custom_id": null
  }
}
