export default {
  CONTACT_ADDED: "CONTACT_ADDED",
  CONTACT_UPDATED: "CONTACT_UPDATED",
  CONTACT_TAGS_CHANGED: "CONTACT_TAGS_CHANGED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
};
