import { allOptional } from "../../common/action-schema.mjs";
import { optionalParsedInt } from "../../common/payload.mjs";

/** Dispatch board status values (API `status`, max 20 characters). */
const JOB_STATUS_OPTIONS = [
  "Quote",
  "Work Order",
  "Unsuccessful",
  "Completed",
];

/**
 * ServiceM8 job create/update body fields.
 * Aligned with [Create jobs](https://developer.servicem8.com/reference/createjobs)
 * and [Update jobs](https://developer.servicem8.com/reference/updatejobs).
 */
export const jobCreateFields = [
  {
    prop: "companyUuid",
    api: "company_uuid",
    propDefinition: "companyUuid",
    description:
      "Client/company record for this job (billing and contact relationship).",
  },
  {
    prop: "jobAddress",
    api: "job_address",
    type: "string",
    label: "Job Address",
    description: "Work site address (max 500 characters); used for geocoding and maps.",
  },
  {
    prop: "billingAddress",
    api: "billing_address",
    type: "string",
    label: "Billing Address",
    optional: true,
    description: "Where to send invoices; defaults to job address if omitted (max 500).",
  },
  {
    prop: "status",
    api: "status",
    type: "string",
    label: "Status",
    description: "Controls dispatch board placement (max 20 characters).",
    options: JOB_STATUS_OPTIONS,
  },
  {
    prop: "createdByStaffUuid",
    api: "created_by_staff_uuid",
    propDefinition: "staffUuid",
    optional: true,
    description: "Staff member who created the job.",
  },
  {
    prop: "date",
    api: "date",
    type: "string",
    label: "Date",
    optional: true,
    description: "Job created or scheduled date (reporting / chronology).",
  },
  {
    prop: "categoryUuid",
    api: "category_uuid",
    propDefinition: "categoryUuid",
    optional: true,
    description: "Job category (type of work / department).",
  },
  {
    prop: "lng",
    api: "lng",
    type: "string",
    label: "Longitude",
    optional: true,
    description: "Usually auto-filled from geocoding the job address.",
  },
  {
    prop: "lat",
    api: "lat",
    type: "string",
    label: "Latitude",
    optional: true,
    description: "Usually auto-filled from geocoding the job address.",
  },
  {
    prop: "paymentDate",
    api: "payment_date",
    type: "string",
    label: "Payment Date",
    optional: true,
    description: "Not used on Job; use the JobPayment endpoint.",
  },
  {
    prop: "paymentActionedByUuid",
    api: "payment_actioned_by_uuid",
    propDefinition: "staffUuid",
    optional: true,
    description: "Not used on Job; use the JobPayment endpoint.",
  },
  {
    prop: "paymentMethod",
    api: "payment_method",
    type: "string",
    label: "Payment Method",
    optional: true,
    description: "Not used on Job; use the JobPayment endpoint.",
  },
  {
    prop: "paymentAmount",
    api: "payment_amount",
    type: "string",
    label: "Payment Amount",
    optional: true,
    description: "Not used on Job; use the JobPayment endpoint.",
  },
  {
    prop: "paymentNote",
    api: "payment_note",
    type: "string",
    label: "Payment Note",
    optional: true,
    description: "Not used on Job; use the JobPayment endpoint.",
  },
  {
    prop: "geoIsValid",
    api: "geo_is_valid",
    type: "string",
    label: "Geo Is Valid",
    optional: true,
    description: "Whether geocoding for the job address succeeded.",
  },
  {
    prop: "purchaseOrderNumber",
    api: "purchase_order_number",
    type: "string",
    label: "Purchase Order Number",
    optional: true,
    description: "Client PO reference (max 100 characters).",
  },
  {
    prop: "invoiceSent",
    api: "invoice_sent",
    type: "string",
    label: "Invoice Sent",
    optional: true,
    description: "0 or 1 — whether an invoice has been sent.",
    transform: optionalParsedInt,
  },
  {
    prop: "invoiceSentStamp",
    api: "invoice_sent_stamp",
    type: "string",
    label: "Invoice Sent Timestamp",
    optional: true,
    description: "When the invoice was sent (`YYYY-MM-DD HH:MM:SS`).",
  },
  {
    prop: "readyToInvoice",
    api: "ready_to_invoice",
    type: "string",
    label: "Ready To Invoice",
    optional: true,
    description: "Deprecated in the API.",
  },
  {
    prop: "readyToInvoiceStamp",
    api: "ready_to_invoice_stamp",
    type: "string",
    label: "Ready To Invoice Timestamp",
    optional: true,
    description: "Deprecated in the API.",
  },
  {
    prop: "geoCountry",
    api: "geo_country",
    type: "string",
    label: "Geo Country",
    optional: true,
    description: "Country from geocoded address.",
  },
  {
    prop: "geoPostcode",
    api: "geo_postcode",
    type: "string",
    label: "Geo Postcode",
    optional: true,
    description: "Postal code from geocoded address.",
  },
  {
    prop: "geoState",
    api: "geo_state",
    type: "string",
    label: "Geo State",
    optional: true,
    description: "State/province from geocoded address.",
  },
  {
    prop: "geoCity",
    api: "geo_city",
    type: "string",
    label: "Geo City",
    optional: true,
    description: "City from geocoded address.",
  },
  {
    prop: "geoStreet",
    api: "geo_street",
    type: "string",
    label: "Geo Street",
    optional: true,
    description: "Street name from geocoded address.",
  },
  {
    prop: "geoNumber",
    api: "geo_number",
    type: "string",
    label: "Geo Street Number",
    optional: true,
    description: "Street number from geocoded address.",
  },
  {
    prop: "queueUuid",
    api: "queue_uuid",
    propDefinition: "queueUuid",
    optional: true,
    description: "Queue this job belongs to.",
  },
  {
    prop: "queueExpiryDate",
    api: "queue_expiry_date",
    type: "string",
    label: "Queue Expiry Date",
    optional: true,
    description: "When the job expires from the queue.",
  },
  {
    prop: "queueAssignedStaffUuid",
    api: "queue_assigned_staff_uuid",
    propDefinition: "staffUuid",
    optional: true,
    description: "Staff assigned to this job in the queue.",
  },
  {
    prop: "badges",
    api: "badges",
    type: "string",
    label: "Badges",
    optional: true,
    description: "JSON array of badge UUIDs as a string.",
  },
  {
    prop: "quoteDate",
    api: "quote_date",
    type: "string",
    label: "Quote Date",
    optional: true,
    description: "When status became Quote.",
  },
  {
    prop: "quoteSent",
    api: "quote_sent",
    type: "string",
    label: "Quote Sent",
    optional: true,
    description: "0 or 1 — whether a quote was sent.",
    transform: optionalParsedInt,
  },
  {
    prop: "quoteSentStamp",
    api: "quote_sent_stamp",
    type: "string",
    label: "Quote Sent Timestamp",
    optional: true,
    description: "When the quote was sent (`YYYY-MM-DD HH:MM:SS`).",
  },
  {
    prop: "workOrderDate",
    api: "work_order_date",
    type: "string",
    label: "Work Order Date",
    optional: true,
    description: "When status became Work Order.",
  },
  {
    prop: "activeNetworkRequestUuid",
    api: "active_network_request_uuid",
    type: "string",
    label: "Active Network Request UUID",
    optional: true,
    description: "Deprecated in the API.",
  },
  {
    prop: "relatedKnowledgeArticles",
    api: "related_knowledge_articles",
    type: "string",
    label: "Related Knowledge Articles",
    optional: true,
    description: "Deprecated in the API.",
  },
  {
    prop: "jobDescription",
    api: "job_description",
    type: "string",
    label: "Job Description",
    optional: true,
  },
  {
    prop: "workDoneDescription",
    api: "work_done_description",
    type: "string",
    label: "Work Done Description",
    optional: true,
    description: "Description of work completed.",
  },
  {
    prop: "paymentProcessed",
    api: "payment_processed",
    type: "string",
    label: "Payment Processed",
    optional: true,
    description: "0 or 1 — exported to the connected accounting package.",
    transform: optionalParsedInt,
  },
  {
    prop: "paymentReceived",
    api: "payment_received",
    type: "string",
    label: "Payment Received",
    optional: true,
    description: "0 or 1 — full payment received for the job.",
    transform: optionalParsedInt,
  },
  {
    prop: "completionDate",
    api: "completion_date",
    type: "string",
    label: "Completion Date",
    optional: true,
    description: "When status became Completed.",
  },
  {
    prop: "unsuccessfulDate",
    api: "unsuccessful_date",
    type: "string",
    label: "Unsuccessful Date",
    optional: true,
    description: "When status became Unsuccessful.",
  },
];

export const jobUpdateFields = allOptional(jobCreateFields);
