export default {
   "triggeredAlert":{
      "id":25764,
      "boundary":"lower",
      "value":"45",
      "type":"concurrents"
   },
   "siteDetails":{
      "user_id":1,
      "acct":"GSN-123456-A",
      "email":"you@example.com",
      "first_name":"John",
      "last_name":"Smith",
      "site_name":"GoSquared",
      "domain":"www.gosquared.com",
      "url":"https://www.gosquared.com/",
      "timezone":"Europe/London"
   },
   "snapshot":{
      "time":{
         "time":1449912849464,
         "local":"2015-12-12T09:34:09+00:00"
      },
      "concurrents":{
         "visitors":44,
         "returning":34,
         "pages":43,
         "active":21,
         "tagged":36
      },
      "timeSeries":{
         "visitors.total":[
            {
               "time":"2015-12-12T09:05:00+00:00",
               "value":43
            }
         ]
      },
      "pages":{
         "list":[
            {
               "protocol":"https:",
               "slashes":true,
               "auth":null,
               "host":"www.gosquared.com",
               "port":null,
               "hostname":"www.gosquared.com",
               "hash":null,
               "search":null,
               "query":null,
               "pathname":"/example",
               "path":"/example/details",
               "href":"https://www.gosquared.com/example/details",
               "visitors":3,
               "engagedTime":142214,
               "title":"GoSquared - Example"
            }
         ],
         "cardinality":43
      },
      "sources":{
         "direct":34,
         "site":{
            "list":[
               {
                  "domain":"tatete.blogspot.jp",
                  "visitors":1,
                  "list":[
                     {
                        "protocol":"http:",
                        "slashes":true,
                        "auth":null,
                        "host":"tatete.blogspot.jp",
                        "port":null,
                        "hostname":"tatete.blogspot.jp",
                        "hash":null,
                        "search":null,
                        "query":null,
                        "pathname":"/2012/04/androidui3000.html",
                        "path":"/2012/04/androidui3000.html",
                        "href":"http://tatete.blogspot.jp/2012/04/androidui3000.html",
                        "visitors":1
                     }
                  ],
                  "cardinality":1
               }
            ],
            "visitors":5,
            "cardinality":5
         },
         "social":{
            "list":[
               
            ],
            "visitors":0,
            "cardinality":0
         },
         "organic":{
            "list":[
               {
                  "engine":"google",
                  "query":"",
                  "visitors":1
               }
            ],
            "visitors":1,
            "cardinality":1
         },
         "internal":{
            "list":[
               {
                  "protocol":"https:",
                  "slashes":true,
                  "auth":null,
                  "host":"www.gosquared.com",
                  "port":null,
                  "hostname":"www.gosquared.com",
                  "hash":null,
                  "search":null,
                  "query":null,
                  "pathname":"/",
                  "path":"/",
                  "href":"https://www.gosquared.com/",
                  "visitors":3
               }
            ],
            "visitors":4,
            "cardinality":2
         }
      },
      "engagement":{
         "timeOnSite":{
            "breakdown":{
               "0":0,
               "10":0,
               "30":0,
               "60":5,
               "300":5,
               "900":3,
               "1800":31
            },
            "average":8270.89
         },
         "visitDepth":{
            "breakdown":{
               "1":10,
               "2":15,
               "5":9,
               "15":3,
               "30":4,
               "60":3
            },
            "detailedBreakdown":{
               "1":10,
               "2":8,
               "3":5,
               "4":2,
               "5":2,
               "6":1,
               "8":1,
               "9":3,
               "10":1,
               "11":1,
               "15":2,
               "21":1,
               "30":2,
               "36":2,
               "65":1,
               "465":1,
               "700":1
            },
            "average":34.86363636363637
         }
      }
   },
   "concurrents":44
}