export default {
  "Particpants": [
    {
      "WaiverParticipantID": "d28b597a-db42-4ea0-87c7-5f50056ad1b1",
      "WaiverID": "f8d2b231-a50f-4c02-a728-090404cb6698",
      "ParticipantName": "Doe",
      "ParticipantNameFirst": "Janet",
      "DOB": "9/8/1982",
      "IsCheckedIn": false,
      "ValuesXml": "",
      "IsSignee": true
    }
  ],
  "EmailVerification": {
    "WaiverID": "b6f05bad-6b4f-4e1c-b9d1-d31c41b06ad2",
    "RequestLastSent": "1753-01-01T00:00:00",
    "CodeExpires": "1753-01-01T00:00:00",
    "Code": "",
    "VerifiedOn": "1753-01-01T00:00:00",
    "TypeTwiceVerified": false,
    "VerifyStatus": 0,
    "WPObjectStatus": 0
  },
  "Images": [],
  "Attachments": [
    {
      "TimesAdjustedForLocalRendering": false,
      "SiteID": "00000000-0000-0000-0000-000000000000",
      "ID": "c3c56181-304e-4237-a10c-3633bbfda2b3",
      "WaiverID": "f8d2b231-a50f-4c02-a728-090404cb6698",
      "FileSizeKB": 452,
      "BlobData": "<WaiverImageBlobInfo xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><Filename>c3c56181-304e-4237-a10c-3633bbfda2b3.jpg</Filename><OriginalFilename>george.jpg</OriginalFilename><Extension>jpg</Extension><Uri>https://wfliveblobstorage03.blob.core.windows.net/waiverimages/c3c56181-304e-4237-a10c-3633bbfda2b3.jpg</Uri><Filesize>452</Filesize></WaiverImageBlobInfo>",
      "DateCreated": "2024-01-18T20:20:35.687",
      "MetaData": "",
      "UploadStatus": 3,
      "WPUserID": "00000000-0000-0000-0000-000000000000",
      "AttachmentStepID": "7d99bac3-64cb-4034-910c-445f7023ff1d",
      "WPObjectStatus": 1,
      "User": null,
      "BlobInfo": {
        "Filename": "c3c56181-304e-4237-a10c-3633bbfda2b3.jpg",
        "OriginalFilename": "george.jpg",
        "Extension": "jpg",
        "Uri": "https://wfliveblobstorage03.blob.core.windows.net/waiverimages/c3c56181-304e-4237-a10c-3633bbfda2b3.jpg",
        "Filesize": "452"
      }
    }
  ],
  "WaiverEvent": {
    "WPObjectStatus": 1,
    "Waivers": [],
    "WaiverForms": [],
    "ManagerIDs": [],
    "ExtraParticipants": null,
    "NumSignedWaivers": 0,
    "Category": null,
    "TimesAdjustedForLocalRendering": false,
    "Settings": {
      "MaxParticipants": -1,
      "Location": "",
      "SigningCutoff": "9999-12-31T00:00:00",
      "Description": ""
    },
    "WaiverEventID": "00000000-0000-0000-0000-000000000000",
    "SiteID": "00000000-0000-0000-0000-000000000000",
    "Name": "",
    "DateStart": "1755-01-01T00:00:00",
    "DateEnd": "1755-01-01T00:00:00",
    "IsDeleted": true,
    "NumWaiverForms": -1,
    "SpotsRemaining": -1,
    "MaxParts": -1,
    "Headcount": -1,
    "ManagerEmailList": null,
    "LastModified": "2024-01-18T20:20:40.4831254Z",
    "Created": "2024-01-18T20:20:40.4831254Z",
    "IsAllDay": false,
    "WaiverEventRecurringID": "00000000-0000-0000-0000-000000000000",
    "CategoryID": "00000000-0000-0000-0000-000000000000",
    "TimeLabel": "12/31/1754 7:00 PM",
    "TimeLabelLine1": "",
    "TimeLabelLine2": "",
    "SettingsXml": "",
    "WorkflowIDs": [],
    "WaiverEventFormIDs": []
  },
  "WaiverFormInstanceObj": {
    "WPObjectStatus": 1,
    "Labels": [],
    "FieldsDoc": null,
    "ParticipantFieldsDoc": null,
    "ID": "8da2c440-2373-425c-a4dc-6f9a9f6e586c",
    "WaiverFormID": "d3c19ee3-b3b9-4088-8a4a-5b02b3220f1e",
    "DateSaved": "2023-12-30T17:45:46.323",
    "IsCurrent": true,
    "AgreementText": "<p>I represent that I am a legal, responsible adult.<span> </span>I represent and warrant that I am signing this<span> </span>document for myself and my children as to any facility usage on School District property to<span> </span>include, but not limited to, <span>the weight room or other workout facility</span>.<span> </span>I am fully aware of the<span> </span>risks and dangers of such usage.<span> </span>I understand that the usage of the <span>weight room and workout</span><span> </span><span>facilities</span> is voluntary, at my and my children&rsquo;s own risk, and that the School District is not<span> </span>responsible in any manner for my or my children&rsquo;s usage or any personal injury or property<span> </span>damage to me or my children as a result of the usage of any such facility.<span> </span>I further understand<span> </span>that I am solely responsible for any personal injury or property damage caused by me or my<span> </span>children as a result of the usage of any such facility. <span>&nbsp; </span><span>I acknowledge that, in the middle of a</span><span> </span><span>global pandemic, there is a serious risk that, by using the facility, I or my children could contract</span><span> </span><span>a dangerous virus or other health condition, and that I accept this risk and nonetheless voluntarily</span><span> </span><span>choose</span><span> </span><span>to allow</span><span> </span><span>my children to use</span><span> </span><span>the facility.</span></p>\n<p>In<span> </span>consideration<span> </span>of<span> </span>my<span> </span>children<span> </span>being<span> </span>allowed<span> </span>usage<span> </span>of<span> </span>any<span> </span>District<span> </span>property<span> </span>or<span> </span>facility<span> </span><span>during</span><span> </span><span>the COVID-19 pandemic</span> and for other good and valuable consideration, receipt of which is<span> </span>hereby acknowledged, on behalf of myself, my children and all others who may claim by, under,<span> </span>or through myself I do hereby agree to indemnify and hold harmless and do hereby release,<span> </span>acquit, and forever discharge the School District and all of its officers, employees, agents and<span> </span>assigns, and all other persons or companies from any and all claims, actions, or causes of action<span> </span>which I or my children now have, or which may hereafter accrue, whether for personal injury or<span> </span>property damage, whether known or unknown, arising out of or in any way resulting from my<span> </span>and/or my children&rsquo;s usage of any District property or facility <span>during the COVID-19 pandemic</span>,<span> </span>including<span> </span>the summer months of 2020.</p>\n<p>I understand and agree that my signature below represents a signature on behalf of myself and<span> </span>each<span> </span>of<span> </span>my<span> </span>children.</p>\n<br />",
    "FieldsXml": "",
    "ParticipantFieldsXml": "",
    "Options": "<Settings><setting key=\"OPT_IN_LABEL\" value=\"Join our mailing list\" /><setting key=\"OPT_IN_HELP_BLOCK\" value=\"\" /><setting key=\"SIGNING_OPTION_ADULT\" value=\"true\" /><setting key=\"SIGNING_OPTION_CHILDREN\" value=\"false\" /><setting key=\"SIGNING_OPTION_ADULT_CHILDREN\" value=\"true\" /><setting key=\"EMAIL_CONFIRM_ENABLED\" value=\"false\" /><setting key=\"EMAIL_VERIFY_ENABLED\" value=\"false\" /><setting key=\"OPT_IN_SELECTION\" value=\"ASK_DEFAULT_CHECKED\" /></Settings>",
    "LabelData": "",
    "SavedBy": "67e89d3f-245f-4f8b-969f-dd9d2a8f947f"
  },
  "WaiverText": {
    "WPObjectStatus": 1,
    "Labels": [],
    "FieldsDoc": null,
    "ParticipantFieldsDoc": null,
    "ID": "8da2c440-2373-425c-a4dc-6f9a9f6e586c",
    "WaiverFormID": "d3c19ee3-b3b9-4088-8a4a-5b02b3220f1e",
    "DateSaved": "2023-12-30T17:45:46.323",
    "IsCurrent": true,
    "AgreementText": "<p>I represent that I am a legal, responsible adult.<span> </span>I represent and warrant that I am signing this<span> </span>document for myself and my children as to any facility usage on School District property to<span> </span>include, but not limited to, <span>the weight room or other workout facility</span>.<span> </span>I am fully aware of the<span> </span>risks and dangers of such usage.<span> </span>I understand that the usage of the <span>weight room and workout</span><span> </span><span>facilities</span> is voluntary, at my and my children&rsquo;s own risk, and that the School District is not<span> </span>responsible in any manner for my or my children&rsquo;s usage or any personal injury or property<span> </span>damage to me or my children as a result of the usage of any such facility.<span> </span>I further understand<span> </span>that I am solely responsible for any personal injury or property damage caused by me or my<span> </span>children as a result of the usage of any such facility. <span>&nbsp; </span><span>I acknowledge that, in the middle of a</span><span> </span><span>global pandemic, there is a serious risk that, by using the facility, I or my children could contract</span><span> </span><span>a dangerous virus or other health condition, and that I accept this risk and nonetheless voluntarily</span><span> </span><span>choose</span><span> </span><span>to allow</span><span> </span><span>my children to use</span><span> </span><span>the facility.</span></p>\n<p>In<span> </span>consideration<span> </span>of<span> </span>my<span> </span>children<span> </span>being<span> </span>allowed<span> </span>usage<span> </span>of<span> </span>any<span> </span>District<span> </span>property<span> </span>or<span> </span>facility<span> </span><span>during</span><span> </span><span>the COVID-19 pandemic</span> and for other good and valuable consideration, receipt of which is<span> </span>hereby acknowledged, on behalf of myself, my children and all others who may claim by, under,<span> </span>or through myself I do hereby agree to indemnify and hold harmless and do hereby release,<span> </span>acquit, and forever discharge the School District and all of its officers, employees, agents and<span> </span>assigns, and all other persons or companies from any and all claims, actions, or causes of action<span> </span>which I or my children now have, or which may hereafter accrue, whether for personal injury or<span> </span>property damage, whether known or unknown, arising out of or in any way resulting from my<span> </span>and/or my children&rsquo;s usage of any District property or facility <span>during the COVID-19 pandemic</span>,<span> </span>including<span> </span>the summer months of 2020.</p>\n<p>I understand and agree that my signature below represents a signature on behalf of myself and<span> </span>each<span> </span>of<span> </span>my<span> </span>children.</p>\n<br />",
    "FieldsXml": "",
    "ParticipantFieldsXml": "",
    "Options": "<Settings><setting key=\"OPT_IN_LABEL\" value=\"Join our mailing list\" /><setting key=\"OPT_IN_HELP_BLOCK\" value=\"\" /><setting key=\"SIGNING_OPTION_ADULT\" value=\"true\" /><setting key=\"SIGNING_OPTION_CHILDREN\" value=\"false\" /><setting key=\"SIGNING_OPTION_ADULT_CHILDREN\" value=\"true\" /><setting key=\"EMAIL_CONFIRM_ENABLED\" value=\"false\" /><setting key=\"EMAIL_VERIFY_ENABLED\" value=\"false\" /><setting key=\"OPT_IN_SELECTION\" value=\"ASK_DEFAULT_CHECKED\" /></Settings>",
    "LabelData": "",
    "SavedBy": "67e89d3f-245f-4f8b-969f-dd9d2a8f947f"
  },
  "WaiverForm": {
    "CurrentInstance": null,
    "WorkflowStepFormRef": null,
    "WPObjectStatus": 1,
    "ID": "d3c19ee3-b3b9-4088-8a4a-5b02b3220f1e",
    "SiteID": "9d61e9ea-11bf-4ae3-9215-4d92d8814ea8",
    "Name": "Educational Facility Waiver",
    "Questions": "",
    "NumParticipantsPerForm": 0,
    "MinAge": 18,
    "AgreementLabelText": "",
    "FieldInclude_Email": true,
    "FieldInclude_Address": true,
    "FieldInclude_Phone": true,
    "FieldInclude_DOB": true,
    "FieldRequire_Email": true,
    "FieldRequire_Address": true,
    "FieldRequire_Phone": true,
    "FieldRequire_DOB": true,
    "MinAgeParticipant": 0,
    "FieldInclude_DOB_Participant": true,
    "FieldRequire_DOB_Participant": true,
    "GeneralAdm_show": true,
    "DashIconColor": "",
    "Created": "2023-12-30T17:45:46.323",
    "LastModified": "1753-01-01T00:00:00",
    "LastModifiedBy": "00000000-0000-0000-0000-000000000000",
    "Status": 0,
    "LeadInText": "",
    "IncludeSignature": true,
    "AllowSigningForSomeoneElse": true,
    "MaxAgeParticipant": 0,
    "Options": ""
  },
  "Device": null,
  "OriginalDataObj": null,
  "Signatures": null,
  "WPObjectStatus": 1,
  "ExportFileRelativePath": null,
  "Expired": false,
  "EncryptedDataFetched": false,
  "WPEList": null,
  "EncryptedQRCode": "https://wfl.ink?FYhnr5WV0v+LgB6SynOv1JzkLotcdrup4VkrBq9xQGvaWXfZgzymrkD40hSY02a08TC+eJ8FHRTkGa+Bd8A5COV91n4ii9Olg/r64KrEJkY=",
  "EmailRequested": false,
  "EmailTypeTwiceVerified": false,
  "WaiverID": "f8d2b231-a50f-4c02-a728-090404cb6698",
  "SiteID": "9d61e9ea-11bf-4ae3-9215-4d92d8814ea8",
  "WaiverEventID": "00000000-0000-0000-0000-000000000000",
  "WaiverTextID": "00000000-0000-0000-0000-000000000000",
  "WaiverFormInstanceID": "8da2c440-2373-425c-a4dc-6f9a9f6e586c",
  "DateSigned": "2024-01-18T20:20:35.593",
  "Address": "44 Montgomery St.",
  "Address2": "",
  "City": "San Francisco",
  "State": "CA",
  "Zip": "94104",
  "Phone": "5555555555",
  "DOB": "9/8/1982",
  "Email": "test4@example.com",
  "SignedName": "Doe",
  "SignedNameFirst": "Janet",
  "WPUserID": "67e89d3f-245f-4f8b-969f-dd9d2a8f947f",
  "WPSMSMobileNumID": "00000000-0000-0000-0000-000000000000",
  "ClientIP": "47.225.32.185",
  "FieldsXml": "",
  "ValuesXml": "<data />",
  "Age": 0,
  "DateAttending": "1753-01-01T00:00:00",
  "WaiverFormID": "d3c19ee3-b3b9-4088-8a4a-5b02b3220f1e",
  "HasSignature": true,
  "OptIn": false,
  "ClientType": 0,
  "deviceID": -1,
  "WaiverIsDeleted": false,
  "OriginalData": null,
  "OriginalDataVerified": false,
  "WorkflowStepID": "00000000-0000-0000-0000-000000000000",
  "WorkflowSessionID": "00000000-0000-0000-0000-000000000000",
  "IsWorkflowSessionPrimary": false,
  "ReferenceID1": null,
  "ReferenceID2": null,
  "ReferenceID3": null,
  "CustomFields": {}
}