export default {
  "fullName": "Lawrence Edward Page",
  "firstName": "Lawrence",
  "middleName": "Edward",
  "lastName": "Page",
  "company": "Alphabet Inc",
  "companyDomain": "google.com",
  "account": "Test account",
  "department": "Operations",
  "title": "CEO",
  "location": "California",
  "phone": "+1000000000",
  "email": "larry@google.com",
  "twitterId": "@Iarrypage",
  "linkedinURL": "linkedin@url.co",
  "companyEmail": "info@google.com",
  "companyPhone": "+11111111111",
  "city": "Palo Alto",
  "country": "U.S",
  "tags": "Tag1,Tag2",
  "list": "default",
  "event": "startCadence",
  "prospectOwner": "prospectOwner",
  "cadenceOwner": "cadenceOwner",
  "cadenceName": "Test Cadence"
}