export default {
  "workspace_id": 1922,
  "first_name": "John",
  "last_name": "Smith",
  "email": "john@smith.co",
  "company": null,
  "job_title": null,
  "address": null,
  "city": null,
  "state": null,
  "country": null,
  "phone_number": null,
  "id": 128964,
  "uuid": "bf8515a8-a582-40d8-9865-76d274d92b56",
  "name": "John Smith",
  "tags": [],
  "custom_fields": [],
  "owner": {
    "first_name": null,
    "last_name": null,
    "email": "john@smith.co",
    "phone_number": null,
    "signup_type": "GENERAL",
    "id": 2038,
    "uuid": "3495df3c-d3e4-4c95-8cb8-de52033dfc47",
    "created_at": "2024-07-23T17:48:26.000000Z",
    "updated_at": "2024-07-23T18:14:29.000000Z",
    "created_by": null,
    "updated_by": null,
    "deleted_at": null,
    "deleted_by": null,
    "is_locked_sidebar": false,
    "birthday": null,
    "phone_code": null,
    "stripe_customer_id": null,
    "name": " ",
    "is_password_set": true,
    "profile_completed": 50,
    "media": null
  },
  "media": null
}