export default {
	"id": 2,
	"contactId": 11,
	"memberId": 0,
	"token": "c8c7bb62-a014-4e74-a1fd-96bd7c718a94",
	"invoiceNo": 1,
	"created": 1752522276,
	"createdTimeFormatted": "14/07/2025 16:44",
	"customerName": "Customer Name",
	"customerEmail": "customer@email.com",
	"billingAddress": {
		"name": "",
		"phone": "",
		"companyName": "",
		"companyId": "",
		"vatId": "",
		"country": "DE",
		"state": "",
		"city": "",
		"zipCode": "",
		"address": "",
		"address2": ""
	},
	"shippingAddress": {
		"name": "",
		"phone": "",
		"companyName": "",
		"companyId": "",
		"vatId": "",
		"country": "DE",
		"state": "",
		"city": "",
		"zipCode": "",
		"address": "",
		"address2": ""
	},
	"shippingRequired": false,
	"weight": 0,
	"weightUnit": "kg",
	"subTotal": 0,
	"total": 0,
	"discountCode": null,
	"discountType": null,
	"transactionId": "",
	"shippingAmount": 0,
	"shippingName": "",
	"paid": true,
	"paymentMethod": "no-payment",
	"status": "completed",
	"discountAmount": 0,
	"taxes": [],
	"items": [
		{
			"id": 2,
			"name": "Product Name",
			"url": "product-name",
			"productId": 20,
			"sku": "",
			"quantity": 1,
			"weight": 0,
			"total": 0,
			"type": "service",
			"shippingRequired": false,
			"images": [],
			"variation": [],
			"additions": []
		}
	],
	"tags": [],
	"additionalFields": null,
	"currency": "EUR",
	"fulfillment": null,
	"notes": []
}