export default {
  data: {
    thumb:
      "string",
    private: null,
    updated_at: "datetime",
    deleted_at: null,
    device_channel_input_id: null,
    annotation: null,
    _type: "comment",
    id: "string",
    completer_id: null,
    completed: false,
    parent_id: null,
    target_asset_id: null,
    timestamp_microseconds: null,
    review_link_id: null,
    text: "string",
    duration: null,
    owner_id: "string",
    fov: 65,
    read_count: 0,
    owner: {
      image_128:
        "string",
      joined_via: "organic",
      integrations: {},
      roles: null,
      updated_at: "datetime",
      user_default_color: "#40ff9f",
      deleted_at: null,
      next_digest_date: "datetime",
      location: null,
      _type: "user",
      from_google: true,
      image_256:
        "string",
      id: "string",
      profile_image:
        "string",
      mfa_enforced_at: null,
      name: "string",
      last_seen: null,
      from_adobe: false,
      inserted_at: "datetime",
      bio: null,
      account_id: "string",
      highest_account_role: null,
      features_seen: null,
      phone: null,
      email_confirm_by: null,
      upload_url:
        "string",
      first_login_at: "datetime",
      timezone_value: "America/New_York",
      email_preferences: null,
      image_64:
        "string",
      profile_image_original: null,
      context: null,
      digest_frequency: "0 * * * *",
      image_32:
        "string",
      email: "string",
    },
    yaw: null,
    aspect_ratio: 1.777778,
    inserted_at: "2024-04-18T23:52:37.051534Z",
    like_count: 0,
    frame: null,
    timestamp: null,
    comment_entities: [],
    completed_at: null,
    asset_id: "f963d1b3-23c5-48d5-a2a2-4107211e81e6",
    text_edited_at: null,
    pitch: null,
    has_replies: false,
    anonymous_user_id: null,
    page: null,
  },
  project: {
    id: "string",
  },
  resource: {
    id: "string",
    type: "comment",
  },
  team: {
    id: "string",
  },
  type: "comment.created",
  user: {
    id: "string",
  },
};
