# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # Installs the PD CLI and configures it to use the PD_API_KEY in the user's Gitpod settings
  # Add your ENV key here: https://gitpod.io/variables
  - name: Install PD CLI
    before: |
      curl https://cli.pipedream.com/linux/amd64/latest/pd.zip --output pd.zip && \
      unzip pd.zip -d pd && \
      sudo mv pd/pd /usr/local/bin/ && \
      rm -r pd && rm pd.zip
    init: |
      eval $(command gp env -e) &&
      mkdir ~/.config/pipedream &&
      touch ~/.config/pipedream/config &&
      echo "api_key = ${PD_API_KEY}" >> ~/.config/pipedream/config
    command: pd
  - name: Install pnpm deps
    init: pnpm install