github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Monorepo setup
    init: npm install --frozen-lockfile
    command: gp preview https://pipedream.com/docs/components/
    openMode: split-right
  # Installs the PD CLI and configures it to use the PD_API_KEY in the user's Gitpod settings
  # Add your ENV key here: https://gitpod.io/variables
  - name: PD CLI
    command: pd
