export default {
    "id": "",
    "hash": "",
    "branch": "master",
    "ref": "refs/heads/master",
    "author_date": "2015-08-09T05:25:54Z",
    "author_avatar_url": "",
    "author_url": "",
    "author_html_url": "",
    "author_username": "",
    "author_id": null,
    "author_name": "",
    "author_email": "",
    "committer_date": "2015-08-09T05:25:54Z",
    "committer_avatar_url": "",
    "committer_url": "",
    "committer_html_url": "",
    "committer_username": "",
    "committer_name": "",
    "committer_email": "",
    "message": "First commit",
    "url": "",
    "html_url": "",
    "created_at": "2025-05-13T18:29:30Z",
    "human_readable_total_with_seconds": "unknown",
    "human_readable_natural_date": "",
    "human_readable_date": "Aug 9, 2015",
    "truncated_hash": "ab9e353",
    "is_author_found": true,
    "human_readable_total": "unknown",
    "total_seconds": 0
  }