export const USER_LIST_TYPES = {
  CRM_BASED: "crmBasedUserList",
  RULE_BASED: "ruleBasedUserList",
  LOGICAL: "logicalUserList",
  BASIC: "basicUserList",
  LOOKALIKE: "lookalikeUserList",
};
export const USER_LIST_TYPE_OPTIONS = [
  {
    label: "CRM-based - a list of provided customers",
    value: USER_LIST_TYPES.CRM_BASED,
    docsLink:
      "https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#CrmBasedUserListInfo",
    props: USER_LIST_CRM_BASED_PROPS,
  },
  {
    label: "Rule-Based - a customer list generated by a rule",
    value: USER_LIST_TYPES.RULE_BASED,
    docsLink:
      "https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#RuleBasedUserListInfo",
  },
  {
    label: "Logical - a custom combination of customer lists",
    value: USER_LIST_TYPES.LOGICAL,
    docsLink:
      "https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#LogicalUserListInfo",
  },
  {
    label:
      "Basic - a customer list targeting as a collection of conversions or remarketing actions",
    value: USER_LIST_TYPES.BASIC,
    docsLink:
      "https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#BasicUserListInfo",
  },
  {
    label:
      "Lookalike - a list composed of customers similar to those of a configurable seed",
    value: USER_LIST_TYPES.LOOKALIKE,
    docsLink:
      "https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#LookalikeUserListInfo",
  },
];

export const USER_LIST_CRM_BASED_PROPS = {
  uploadKeyType: {
    type: "string",
    label: "Upload Key Type",
    description:
      "Matching key type of the list. Mixed data types are not allowed on the same list.",
    options: [
      {
        label:
          "Members are matched from customer info such as email address, phone number or physical address.",
        value: "CONTACT_INFO",
      },
      {
        label:
          "Members are matched from a user id generated and assigned by the advertiser.",
        value: "CRM_ID",
      },
      {
        label: "Members are matched from mobile advertising IDs.",
        value: "MOBILE_ADVERTISING_ID",
      },
    ],
  },
  dataSourceType: {
    type: "string",
    label: "Data Source Type",
    description:
      "Data source of the list. Only customers on the allow-list can create third-party sourced CRM lists.",
    optional: true,
    default: "FIRST_PARTY",
    options: [
      {
        label: "The uploaded data is first-party data.",
        value: "FIRST_PARTY",
      },
      {
        label: "The uploaded data is from a third-party credit bureau,",
        value: "THIRD_PARTY_CREDIT_BUREAU",
      },
      {
        label: "The uploaded data is from a third-party voter file.",
        value: "THIRD_PARTY_VOTER_FILE",
      },
    ],
  },
  appId: {
    type: "string",
    label: "App ID",
    description: "A string that uniquely identifies a mobile application from which the data was collected. [See the documentation](https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserList#CrmBasedUserListInfo) for more details.",
    optional: true,
  },
};
