const COMPANY_SIZE_RANGES = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10001+",
];

const COMPANY_REVENUE_RANGES = [
  "0-500K",
  "500K-1M",
  "1M-5M",
  "5M-10M",
  "10M-25M",
  "25M-75M",
  "75M-200M",
  "200M-500M",
  "500M-1B",
  "1B-10B",
  "10B-100B",
  "100B-1T",
  "1T-10T",
  "10T+",
];

const PROSPECT_JOB_LEVELS = [
  "owner",
  "cxo",
  "vp",
  "director",
  "senior",
  "manager",
  "partner",
  "non-managerial",
  "entry",
  "training",
  "unpaid",
  "unknown",
];

const PROSPECT_JOB_DEPARTMENTS = [
  "Real estate",
  "Customer service",
  "Trades",
  "Unknown",
  "Public relations",
  "Legal",
  "Operations",
  "Media",
  "Sales",
  "Marketing",
  "Finance",
  "Engineering",
  "Education",
  "General",
  "Health",
  "Design",
  "Human resources",
];

const BUSINESS_ENRICHMENT_TYPES = [
  "firmographics",
  "technographics",
  "linkedin_posts",
  "company_ratings_by_employees",
  "company_website_keywords",
  "financial_indicators",
  "funding_and_acquisition",
  "pc_business_challenges_10k",
  "pc_competitive_landscape_10k",
  "pc_strategy_10k",
  "website_changes",
  "workforce_trends",
];

const PROSPECT_ENRICHMENT_TYPES = [
  "contacts_information",
  "linkedin_posts",
  "profiles",
];

const BUSINESS_EVENT_TYPES = [
  "ipo_announcement",
  "new_funding_round",
  "new_investment",
  "new_product",
  "new_office",
  "closing_office",
  "new_partnership",
  "increase_in_engineering_department",
  "increase_in_sales_department",
  "increase_in_marketing_department",
  "increase_in_operations_department",
  "increase_in_customer_service_department",
  "increase_in_all_departments",
  "decrease_in_engineering_department",
  "decrease_in_sales_department",
  "decrease_in_marketing_department",
  "decrease_in_operations_department",
  "decrease_in_customer_service_department",
  "decrease_in_all_departments",
  "employee_joined_company",
  "hiring_in_creative_department",
  "hiring_in_education_department",
  "hiring_in_engineering_department",
  "hiring_in_finance_department",
  "hiring_in_health_department",
  "hiring_in_human_resources_department",
  "hiring_in_legal_department",
  "hiring_in_marketing_department",
  "hiring_in_operations_department",
  "hiring_in_professional_service_department",
  "hiring_in_sales_department",
  "hiring_in_support_department",
  "hiring_in_trade_department",
  "hiring_in_unknown_department",
  "company_award",
  "outages_and_security_breaches",
  "cost_cutting",
  "merger_and_acquisitions",
  "lawsuits_and_legal_issues",
];

const PROSPECT_EVENT_TYPES = [
  "prospect_changed_role",
  "prospect_changed_company",
  "prospect_job_start_anniversary",
];

export default {
  COMPANY_SIZE_RANGES,
  COMPANY_REVENUE_RANGES,
  PROSPECT_JOB_LEVELS,
  PROSPECT_JOB_DEPARTMENTS,
  BUSINESS_ENRICHMENT_TYPES,
  PROSPECT_ENRICHMENT_TYPES,
  BUSINESS_EVENT_TYPES,
  PROSPECT_EVENT_TYPES,
};
