const DATA_TYPES = [
  {
    value: "tableData",
    label: "Record and cell value changes",
  },
  {
    value: "tableFields",
    label: "Field changes",
  },
  {
    value: "tableMetadata",
    label: "Table name and description changes",
  },
];

const CHANGE_TYPES = [
  {
    label: "Created",
    value: "add",
  },
  {
    label: "Deleted",
    value: "remove",
  },
  {
    label: "Updated/Modified",
    value: "update",
  },
];

const FROM_SOURCES = [
  {
    value: "client",
    label: "Changes generated by a user through the web or mobile clients",
  },
  {
    value: "publicApi",
    label: "Changes generated through the Airtable API",
  },
  {
    value: "formSubmission",
    label: "Changes generated when a form view is submitted",
  },
  {
    value: "formPageSubmission",
    label:
      "Changes generated when an interface form builder page, form layout page, or record creation button page is submitted",
  },
  {
    value: "automation",
    label: "Changes generated through an automation action",
  },
  {
    value: "system",
    label:
      "Changes generated by system events, such as processing time function formulas",
  },
  {
    value: "sync",
    label: "Changes generated through Airtable Sync",
  },
  {
    value: "anonymousUser",
    label: "Changes generated by an anonymous user",
  },
  {
    value: "unknown",
    label: "Unknown",
  },
];

const FIELD_TYPES = [
  "singleLineText",
  "email",
  "url",
  "multilineText",
  "number",
  "percent",
  "currency",
  "singleSelect",
  "multipleSelects",
  "singleCollaborator",
  "multipleCollaborators",
  "multipleRecordLinks",
  "date",
  "dateTime",
  "phoneNumber",
  "multipleAttachments",
  "checkbox",
  "formula",
  "createdTime",
  "rollup",
  "count",
  "lookup",
  "multipleLookupValues",
  "autoNumber",
  "barcode",
  "rating",
  "richText",
  "duration",
  "lastModifiedTime",
  "button",
  "createdBy",
  "lastModifiedBy",
  "externalSyncSource",
  "aiText",
];

export default {
  DATA_TYPES,
  CHANGE_TYPES,
  FROM_SOURCES,
  FIELD_TYPES,
};
