export default {
  "id": "jLxz55idEps7XRAgsWMz",
  "locationId": "t8lsEHvfdlZugCobd4t7",
  "contactName": "(example) casey morgan",
  "firstName": "(example) casey",
  "lastName": "morgan",
  "firstNameRaw": "(Example) Casey",
  "lastNameRaw": "Morgan",
  "companyName": "(Example) Dunder Mifflin",
  "email": null,
  "phone": "+16541234567",
  "dnd": false,
  "dndSettings": {},
  "type": "lead",
  "source": null,
  "assignedTo": null,
  "city": null,
  "state": null,
  "postalCode": null,
  "address1": null,
  "dateAdded": "2025-04-04T16:00:08.369Z",
  "dateUpdated": "2025-04-04T16:00:12.888Z",
  "dateOfBirth": null,
  "businessId": "67f001fe6b2c160e6f140161",
  "tags": [
    "high priority",
    "follow-up"
  ],
  "followers": [],
  "country": "US",
  "website": null,
  "timezone": null,
  "additionalEmails": [],
  "customFields": []
}