const ORDER_FULFILMENT_METHOD_OPTIONS = [
  "FBR",
  "FBB",
  "ALL",
];

const ORDER_STATUS_OPTIONS = [
  "OPEN",
  "SHIPPED",
  "ALL",
];

const HANDLING_RESULT_OPTIONS = [
  "RETURN_RECEIVED",
  "EXCHANGE_PRODUCT",
  "RETURN_DOES_NOT_MEET_CONDITIONS",
  "REPAIR_PRODUCT",
  "CUSTOMER_KEEPS_PRODUCT_PAID",
];

const INVOICE_REQUEST_STATE_OPTIONS = [
  "OPEN",
  "UPLOAD_ERROR",
  "ALL",
];

const COUNTRY_CODE_OPTIONS = [
  "NL",
  "BE",
];

const PRODUCT_SORT_OPTIONS = [
  "RELEVANCE",
  "POPULARITY",
  "PRICE_ASC",
  "PRICE_DESC",
  "RELEASE_DATE",
  "RATING",
  "WISHLIST",
];

const FULFILMENT_METHOD_OPTIONS = [
  "FBR",
  "FBB",
];

export default {
  ORDER_FULFILMENT_METHOD_OPTIONS,
  ORDER_STATUS_OPTIONS,
  HANDLING_RESULT_OPTIONS,
  INVOICE_REQUEST_STATE_OPTIONS,
  COUNTRY_CODE_OPTIONS,
  PRODUCT_SORT_OPTIONS,
  FULFILMENT_METHOD_OPTIONS,
};
