export default {
  "store_id": 68000,
  "id": 6,
  "hash": "b91uOjW",
  "created_at": "2026-01-16T11:35:09-05:00",
  "updated_at": "2026-01-16T11:35:09-05:00",
  "status": "pending",
  "invoice_number": "",
  "invoice_date": "",
  "receipt_number": "",
  "receipt_date": "",
  "credit_number": "",
  "credit_date": "",
  "email_sent": false,
  "abandoned": false,
  "note_administrator": "",
  "customer": {
    "id": 5,
    "group_id": 1,
    "subscriber_id": 2,
    "first_name": "Test",
    "last_name": "Person",
    "email": "test@example.com",
    "note": "",
    "geoip": {
      "ip": "71.82.95.96",
      "city": "Rockford",
      "state": "Michigan",
      "country": "United States",
      "country_iso": "US",
      "timezone": "",
      "lat": -85.5136,
      "lng": 43.1152
    },
    "custom_fields": []
  },
  "products": [
    {
      "id": 4,
      "product_id": 2,
      "variant_id": 2,
      "quantity": 1,
      "url": "https://jr9hq.cloudcart.net/product/rustic-serving-bowl",
      "image": "https://cdncloudcart.com/68000/logo/temp_logo_69694ec71c6d0_600x600.png?1768509128",
      "name": "Rustic Serving Bowl",
      "sku": "",
      "barcode": "",
      "weight": 0,
      "sale": false,
      "digital": false,
      "digital_files": [],
      "tracked": false,
      "vendor": "",
      "category": {
        "id": 1,
        "name": "Arts & Entertainment"
      },
      "variant": [],
      "unit": "",
      "dimensions": {
        "unit_system": "metric",
        "width": 0,
        "height": 0,
        "depth": 0
      },
      "options": [],
      "tax_vat": "",
      "discounts": [],
      "unit_line_price": 55,
      "unit_line_discount_amount": 0,
      "unit_line_price_total": 55,
      "line_price": 55,
      "line_discount_amount": 0,
      "line_price_total": 55,
      "has_modifications": false,
      "modifications": []
    }
  ],
  "weight": 0,
  "shipping": [
    {
      "id": 1,
      "status": "not_fulfilled",
      "provider_name": "Delivery to address",
      "provider_key": "price",
      "provider_amount": 5,
      "amount_with_vat": false,
      "provider_insurance": 0,
      "order_has_insurance": false,
      "service_id": "1",
      "service_name": "Delivery to address",
      "geo_zone": "",
      "desired_delivery_date": "",
      "waybill_id": "",
      "fulfilled_at": "",
      "delivery_at": "",
      "expedition_at": "",
      "products": []
    }
  ],
  "shipping_address": {
    "id": 1,
    "first_name": "Api",
    "last_name": "Customer",
    "phone": "+359888888888",
    "country": "BG",
    "state": "Sofia",
    "city": "Sofia",
    "street": "Todor Kableshkov",
    "street_number": "55A",
    "postal_code": "1680",
    "additional_info": "",
    "formatted": "Todor Kableshkov 55A, 1680 Sofia, Bulgaria",
    "gmap_address": "Todor Kableshkov 55A, 1680 Sofia, Bulgaria",
    "lat": "",
    "lng": "",
    "office_id": "",
    "marketplace_id": ""
  },
  "billing_address": {
    "id": 1,
    "company": false,
    "company_name": "",
    "company_registration_number": "",
    "company_vat": "",
    "company_person": "",
    "first_name": "Api",
    "last_name": "Customer",
    "phone": "+359888888888",
    "country": "BG",
    "state": "Sofia",
    "city": "Sofia",
    "street": "Todor Kableshkov",
    "street_number": "55A",
    "postal_code": "1680",
    "additional_info": "",
    "formatted": "Todor Kableshkov 55A, 1680 Sofia, Bulgaria",
    "gmap_address": "Todor Kableshkov 55A, 1680 Sofia, Bulgaria",
    "lat": "",
    "lng": "",
    "office_id": "",
    "marketplace_id": ""
  },
  "payments": [
    {
      "id": 3,
      "provider_reference_id": "",
      "provider_name": "Cash on delivery",
      "provider": "cod",
      "amount": 60,
      "status": "requested",
      "created_at": "2026-01-16T11:35:10-05:00",
      "updated_at": "2026-01-16T11:35:10-05:00"
    }
  ],
  "payment": {
    "id": 3,
    "provider_reference_id": "",
    "provider_name": "Cash on delivery",
    "provider": "cod",
    "amount": 60,
    "status": "requested",
    "created_at": "2026-01-16T11:35:10-05:00",
    "updated_at": "2026-01-16T11:35:10-05:00"
  },
  "discounts": [],
  "tax_vat": [],
  "fees": [],
  "order_subtotal": 55,
  "order_total": 60,
  "currency": "USD",
  "language": "en"
}