export default {
  WORKFLOWEXECUTION_STARTED: "workflowExecution.started",
  WORKFLOWEXECUTION_COMPLETED: "workflowExecution.completed",
  WORKFLOWEXECUTION_WAITINGFORTRIGGER: "workflowExecution.waitingForTrigger",
  WORKFLOWEXECUTION_ACTIONEXECUTED: "workflowExecution.actionExecuted",
  WORKFLOWEXECUTION_CANCELED: "workflowExecution.canceled",
  WORKFLOWEXECUTION_FAILED: "workflowExecution.failed",
  OPENID4VC_ISSUANCE_OFFERED: "openid4vc.issuance.offered",
  OPENID4VC_ISSUANCE_COMPLETED: "openid4vc.issuance.completed",
  OPENID4VC_ISSUANCE_FAILED: "openid4vc.issuance.failed",
  OPENID4VC_ISSUANCE_PARTIALLYISSUED: "openid4vc.issuance.partiallyIssued",
  OPENID4VC_VERIFICATION_FAILED: "openid4vc.verification.failed",
  OPENID4VC_VERIFICATION_REQUESTED: "openid4vc.verification.requested",
  OPENID4VC_VERIFICATION_VERIFIED: "openid4vc.verification.verified",
  DIDCOMM_CONNECTION_CREATED: "didcomm.connection.created",
  DIDCOMM_CONNECTION_REUSED: "didcomm.connection.reused",
  DIDCOMM_MESSAGING_BASIC_RECEIVED: "didcomm.messaging.basic.received",
  DIDCOMM_MESSAGING_CUSTOM_RECEIVED: "didcomm.messaging.custom.received",
  DIDCOMM_ISSUANCE_OFFERED: "didcomm.issuance.offered",
  DIDCOMM_ISSUANCE_COMPLETED: "didcomm.issuance.completed",
  DIDCOMM_ISSUANCE_FAILED: "didcomm.issuance.failed",
  DIDCOMM_VERIFICATION_FAILED: "didcomm.verification.failed",
  DIDCOMM_VERIFICATION_REQUESTED: "didcomm.verification.requested",
  DIDCOMM_VERIFICATION_VERIFIED: "didcomm.verification.verified",
};
