// The following are the activity types that are available in OneDesk according to the Support team.
export default {
  ADDED_CUSTOMER_REPLY: "added a Customer Reply",
  REMOVED_CUSTOMER_REPLY: "removed a Customer Reply",
  CHANGED_CUSTOMER_REPLY: "changed a Customer Reply",
  REMOVED_CUSTOM_FIELD: "removed the custom field",
  PROJECT_ARCHIVED: "project archived",
  UPDATE_ORGANIZATION_FINANCIAL: "update organization financial",
  ADDED_ATTACHMENT: "added an attachment",
  REMOVED_ATTACHMENT: "attachment(s) removed",
  ADDED_ASSIGNEE: "added an assignee",
  REMOVED_ASSIGNEE: "removed an assignee",
  ADDED_TEAM_ASSIGNMENT: "added a team assignment",
  REMOVED_TEAM_ASSIGNMENT: "removed a team assignment",
  ADDED_LINK_TO_ITEM: "added a link to an item",
  REMOVED_LINK_TO_ITEM: "removed a link to an item",
  SENT_EMAIL: "sent email",
  EMAIL_SENT: "email sent",
  LOGGED_IN: "logged in",
  LOGGED_OUT: "logged out",
  FIRST_NAME_UPDATED: "first name updated",
  LAST_NAME_UPDATED: "last name updated",
  ADDED_FOLLOWER: "added follower",
  REMOVED_FOLLOWER: "removed follower",
  CREATED_WORK_ITEM: "created work item",
  DELETED_WORK_ITEM: "deleted work item",
  CREATED_PROJECT: "created project",
  DELETED_PROJECT: "deleted project",
  CREATED_PORTFOLIO: "created portfolio",
  DELETED_PORTFOLIO: "deleted portfolio",
  CREATED_MARKER: "created marker",
  DELETED_MARKER: "deleted marker",
  USER_JOINED_PROJECT: "user joined project",
  USER_LEFT_PROJECT: "user left project",
  CREATED_USER: "created user",
  DEACTIVATED_USER: "deactivated user",
  REACTIVATED_USER: "reactivated user",
  ASSIGNED_TO_SLA: "assigned to SLA",
  CHANGED_SLA: "changed the SLA",
  ADDED_PROJECT_FOLLOWER: "added project follower",
  REMOVED_PROJECT_FOLLOWER: "removed project follower",
  CREATE_INVOICE: "create invoice",
  UPDATE_INVOICE: "update invoice",
  NUMBER_OF_USER_LICENSES_UPDATED: "number of user licenses updated",
  COMPLETE_UPDATED: "complete updated",
  ACTUAL_COST_UPDATED: "actual cost updated",
  ACTUAL_FINISH_DATE_UPDATED: "actual finish date updated",
  ACTUAL_START_DATE_UPDATED: "actual start date updated",
  // This was given by OneDesk Support team however it returns 500 when used so the correct
  // one right now is `changed the actual work`
  // ACTUAL_WORK_UPDATED: "actual work updated",
  ACTUAL_WORK_UPDATED: "changed the actual work",
  ADDED_INTERNAL_MESSAGE: "added a Internal message",
  AGILE_POINTS_CAPACITY_UPDATED: "agile points capacity updated",
  AGILE_POINTS_UPDATED: "agile points updated",
  CHANGED_INTERNAL_MESSAGE: "changed a Internal message",
  CUSTOM_FIELD_UPDATED: "custom field updated",
  DELETED_USER: "deleted user",
  DESCRIPTION_UPDATED: "description updated",
  ESTIMATION_TYPE_UPDATED: "estimation type updated",
  LIFECYCLE_STATUS_UPDATED: "lifecycle status updated",
  NAME_UPDATED: "name updated",
  ONE_TIME_ACCESS_GRANTED: "one-time access granted",
  ONE_TIME_ACCESS_REVOKED: "one-time access revoked",
  PLANNED_CONSTRAINT_DATE_UPDATED: "planned constraint date updated",
  PLANNED_CONSTRAINT_TYPE_UPDATED: "planned constraint type updated",
  PLANNED_COST_UPDATED: "planned cost updated",
  PLANNED_DURATION_AMOUNT_UPDATED: "planned duration amount updated",
  PLANNED_DURATION_UNIT_UPDATED: "planned duration unit updated",
  PLANNED_ESTIMATED_REVENUE_UPDATED: "planned estimated revenue updated",
  PLANNED_FINISH_DATE_UPDATED: "planned finish date updated",
  PLANNED_START_DATE_UPDATED: "planned start date updated",
  PLANNED_WORK_AMOUNT_UPDATED: "planned work amount updated",
  PLANNED_WORK_UNIT_UPDATED: "planned work unit updated",
  PRIORITY_UPDATED: "priority updated",
  PROJECT_PLANNED_START_DATE_UPDATED: "project planned start date updated",
  PROJECT_PRIVACY_UPDATED: "project privacy updated",
  PROJECT_UPDATED: "project updated",
  PUBLISHED_STATE_UPDATED: "published state updated",
  REMOVED_INTERNAL_MESSAGE: "removed a Internal message",
  SCHEDULED_FOR_DELETION: "scheduled for deletion",
  SUPPORT_TEAM_LOGGED_IN: "support team logged in",
  TYPE_UPDATED: "type updated",
  UPDATED_REMAINING_PREPAID_HOURS: "updated remaining prepaid hours",
};
