export default {
  "leadStageKey": "cS9VMUFoWFo5UHdpb1hmWE9HL2pDQT090",
  "lastActivitySubject": "",
  "updatedByKey": "YWlRZmlOQlAzS0duTUtob0x6SDgrQT090",
  "folderName": "",
  "contactKey": "cVdRK1BmaUxOUGc5QUVCRzhXM0FaZz090",
  "glCompanyKey": "",
  "margin": "",
  "mediaGross": "0.0000",
  "multipleSegments": "",
  "email": "",
  "dateAdded": "2018-04-30T17:15:00",
  "closedDate": "",
  "companyName": "Streamline Technologies",
  "opportunityKey": "TjJGYXJzNnRWNHNhU09oTG81R29TQT090",
  "mediaPerc": "0.0000",
  "startDate": "",
  "subAmount": "0.0000",
  "subject": "f91f21f1",
  "competitors": "",
  "projectTypeName": "",
  "comments": "",
  "months": "",
  "outcomeComment": "",
  "bid": "0",
  "lastActivityKey": "",
  "contactCompanyKey": "M3JQUkxqUXFFb1BvUGZvWHcyUFJrZz090",
  "dateUpdated": "2018-04-30T17:15:00",
  "opportunityID": "152",
  "opportunityOwner": "",
  "outcome": "",
  "saleAmount": "0.0000",
  "leadStatusKey": "eS9vbExTV1RTSXIvWUJaU0Y4ZnpYUT090",
  "outsideCostsGross": "0.0000",
  "glCompany": "",
  "probability": "0",
  "labor": "",
  "lastActivityDate": "",
  "bidDate": "",
  "modifiedByName": "",
  "leadStatusName": "Open",
  "accountManagerKey": "YWlRZmlOQlAzS0duTUtob0x6SDgrQT090",
  "leadStageName": "set to 50 %",
  "outsideCostsPerc": "0.0000",
  "agi": "0.0000",
  "estimateType": "1",
  "contactName": "API TEST",
  "phone": ""
}