export default {
  "id": "evt_74634adca96c",
  "type_string": "donation.created",
  "api_version": "2019-03-15",
  "created": 1783626150000,
  "object": "donation",
  "object_data": {
    "id": "dnt_7c35e729a8eb",
    "object": "donation",
    "donation_type": "cash/check",
    "processor": "N/A",
    "status": "processed",
    "livemode": null,
    "donation_date": 1783626144000,
    "amount_in_cents": 50,
    "currency": "usd",
    "recurring": null,
    "refunded": null,
    "transaction_id": null,
    "created": 1783626144000,
    "updated": 1783626144000,
    "amount_formatted": "$0.50",
    "anonymous": false,
    "on_behalf_of": null,
    "comment": null,
    "tracking_codes": null,
    "meta_data": {},
    "dtd_company_name": null,
    "person": {
      "id": "per_ba25a0440913",
      "object": "person",
      "email": "dntlymail+per_ba25a0440913@donate.ly",
      "first_name": null,
      "last_name": null,
      "phone_number": null,
      "street_address": null,
      "street_address_2": null,
      "city": null,
      "state": null,
      "zip_code": null,
      "country": null
    },
    "account": {
      "id": "act_30f454b5bc71",
      "object": "account",
      "title": "Test User",
      "subdomain": "test-user",
      "donately_homepage_url": "https://pages.donately.com/test-user",
      "status": "published",
      "currency": "usd"
    },
    "campaign": {},
    "fundraiser": {},
    "subscription": {},
    "refunds": [],
    "form": {},
    "referrer_id": null,
    "remote_ip": "34.239.118.140",
    "fee_in_cents": 0,
    "form_version": null,
    "session_id": null,
    "created_formatted": "2026-07-09 19:42:24 +00:00"
  },
  "event_data": {
    "event": "create"
  }
}