const SORT_ORDER_OPTIONS = [
  "ASCENDING",
  "DESCENDING",
];

const TIME_ENTRY_TYPE_OPTIONS = [
  "REGULAR",
  "BREAK",
];

const INVOICE_STATUS_OPTIONS = [
  "UNSENT",
  "SENT",
  "PAID",
  "PARTIALLY_PAID",
  "VOID",
  "OVERDUE",
];

const INVOICE_TIME_VIEW_MODE_OPTIONS = [
  "TIME_SENSITIVE_VIEW",
  "AGGREGATED_TIME_VIEW",
];

const INVOICE_IMPORT_TIME_ENTRY_GROUP_TYPE_OPTIONS = [
  "SINGLE_ITEM",
  "GROUPED",
  "DETAILED",
];

const PROJECT_CLIENT_STATUS_OPTIONS = [
  "ACTIVE",
  "ARCHIVED",
  "ALL",
];

const PROJECT_USER_STATUS_OPTIONS = [
  "PENDING",
  "ACTIVE",
  "DECLINED",
  "INACTIVE",
  "ALL",
];

const PROJECT_SORT_COLUMN_OPTIONS = [
  "ID",
  "NAME",
  "CLIENT_NAME",
  "DURATION",
  "BUDGET",
  "PROGRESS",
];

const PROJECT_ACCESS_OPTIONS = [
  "PUBLIC",
  "PRIVATE",
];

const TASK_SORT_COLUMN_OPTIONS = [
  "ID",
  "NAME",
];

export default {
  SORT_ORDER_OPTIONS,
  TIME_ENTRY_TYPE_OPTIONS,
  INVOICE_STATUS_OPTIONS,
  INVOICE_TIME_VIEW_MODE_OPTIONS,
  INVOICE_IMPORT_TIME_ENTRY_GROUP_TYPE_OPTIONS,
  PROJECT_CLIENT_STATUS_OPTIONS,
  PROJECT_USER_STATUS_OPTIONS,
  PROJECT_SORT_COLUMN_OPTIONS,
  PROJECT_ACCESS_OPTIONS,
  TASK_SORT_COLUMN_OPTIONS,
};
