export default {
  "attempt_count": 0,
  "autopay": false,
  "balance": 51.15,
  "closed": false,
  "created_at": 1415229884,
  "currency": "usd",
  "customer": 15444,
  "date": 1416290400,
  "discounts": [],
  "draft": false,
  "due_date": 1417500000,
  "id": 46225,
  "items": [
      {
          "amount": 45,
          "catalog_item": null,
          "description": null,
          "discountable": true,
          "discounts": [],
          "id": 7,
          "metadata": [],
          "name": "Copy Paper, Case",
          "object": "line_item",
          "quantity": 1,
          "taxable": true,
          "taxes": [],
          "type": "product",
          "unit_cost": 45
      },
      {
          "amount": 10,
          "catalog_item": "delivery",
          "description": null,
          "discountable": true,
          "discounts": [],
          "id": 8,
          "metadata": [],
          "name": "Delivery",
          "object": "line_item",
          "quantity": 1,
          "taxable": true,
          "taxes": [],
          "type": "service",
          "unit_cost": 10
      }
  ],
  "metadata": [],
  "name": null,
  "next_payment_attempt": null,
  "notes": null,
  "number": "INV-0016",
  "object": "invoice",
  "paid": false,
  "payment_plan": null,
  "payment_terms": "NET 14",
  "payment_url": "https://dundermifflin.invoiced.com/invoices/IZmXbVOPyvfD3GPBmyd6FwXY/payment",
  "pdf_url": "https://dundermifflin.invoiced.com/invoices/IZmXbVOPyvfD3GPBmyd6FwXY/pdf",
  "purchase_order": null,
  "ship_to": null,
  "status": "not_sent",
  "subscription": null,
  "subtotal": 55,
  "taxes": [
      {
          "amount": 3.85,
          "id": 20554,
          "object": "tax",
          "tax_rate": null
      }
  ],
  "total": 51.15,
  "updated_at": 1415229884,
  "url": "https://dundermifflin.invoiced.com/invoices/IZmXbVOPyvfD3GPBmyd6FwXY"
}