export default {
  "id": "string",
  "user": {
    "id": "string",
    "name": "string",
    "username": "string",
    "profilePicture": "string",
    "description": "string",
    "website": "string",
    "imagesGenerated": 0,
    "imagesAvailable": 0,
    "modelsAvailable": 0,
    "followersCount": 0,
    "followingCount": 0,
    "isVerified": true
  },
  "imageEdit": {
    "id": "string",
    "originalImageCompletion": {
      "id": "string",
      "user": {
        "id": "string",
        "name": "string",
        "username": "string",
        "profilePicture": "string",
        "description": "string",
        "website": "string",
        "imagesGenerated": 0,
        "imagesAvailable": 0,
        "modelsAvailable": 0,
        "followersCount": 0,
        "followingCount": 0,
        "isVerified": true
      },
      "userId": "string",
      "regeneratedFromId": "string",
      "originalImageCompletion": "string",
      "imageEdit": "string",
      "prompt": "string",
      "baseModel": "string",
      "promptSystem": "string",
      "status": "string",
      "statusDetail": "string",
      "progress": 0,
      "previewImage": "string",
      "username": "string",
      "queue": "string",
      "isUserVerified": true,
      "isHot": true,
      "privacy": "string",
      "likes": 0,
      "comments": 0,
      "liked": true,
      "regenerations": 0,
      "reports": 0,
      "storageBucket": "string",
      "storagePath": "string",
      "generationSettings": {},
      "generationData": "string",
      "generatedByUnit": "string",
      "generationSeconds": 0,
      "imagePaths": {},
      "imageVersions": {},
      "systemVersion": 0,
      "hasWatermark": true,
      "isNsfw": true,
      "webhookUrl": "string",
      "isBookmarked": true,
      "isUnsafe": true,
      "blockedAt": "2025-05-07T12:48:08.610Z",
      "createdAt": "2025-05-07T12:48:08.610Z",
      "models": [
        {
          "id": "string",
          "user": {
            "id": "string",
            "name": "string",
            "username": "string",
            "profilePicture": "string",
            "description": "string",
            "website": "string",
            "imagesGenerated": 0,
            "imagesAvailable": 0,
            "modelsAvailable": 0,
            "followersCount": 0,
            "followingCount": 0,
            "isVerified": true
          },
          "userId": "string",
          "name": "string",
          "username": "string",
          "class": "string",
          "type": "string",
          "description": "string",
          "website": "string",
          "status": "string",
          "progress": 0,
          "privacy": "string",
          "usages": 0,
          "imagesAvailable": 0,
          "likes": 0,
          "version": 0,
          "thumbnail": "string",
          "thumbnailOptions": {},
          "settings": {},
          "images": {},
          "isActive": true,
          "blockedAt": "2025-05-07T12:48:08.610Z",
          "createdAt": "2025-05-07T12:48:08.610Z",
          "systemVersions": [
            "string"
          ],
          "versions": [
            {
              "id": "string",
              "version": 0,
              "storagePath": "string",
              "systemVersions": [
                "string"
              ],
              "status": "string",
              "createdAt": "2025-05-07T12:48:08.610Z",
              "trainedAt": "2025-05-07T12:48:08.610Z"
            }
          ]
        }
      ]
    },
    "originalImageEdit": "string",
    "generatedImageCompletion": {
      "id": "string",
      "user": {
        "id": "string",
        "name": "string",
        "username": "string",
        "profilePicture": "string",
        "description": "string",
        "website": "string",
        "imagesGenerated": 0,
        "imagesAvailable": 0,
        "modelsAvailable": 0,
        "followersCount": 0,
        "followingCount": 0,
        "isVerified": true
      },
      "userId": "string",
      "regeneratedFromId": "string",
      "originalImageCompletion": "string",
      "imageEdit": "string",
      "prompt": "string",
      "baseModel": "string",
      "promptSystem": "string",
      "status": "string",
      "statusDetail": "string",
      "progress": 0,
      "previewImage": "string",
      "username": "string",
      "queue": "string",
      "isUserVerified": true,
      "isHot": true,
      "privacy": "string",
      "likes": 0,
      "comments": 0,
      "liked": true,
      "regenerations": 0,
      "reports": 0,
      "storageBucket": "string",
      "storagePath": "string",
      "generationSettings": {},
      "generationData": "string",
      "generatedByUnit": "string",
      "generationSeconds": 0,
      "imagePaths": {},
      "imageVersions": {},
      "systemVersion": 0,
      "hasWatermark": true,
      "isNsfw": true,
      "webhookUrl": "string",
      "isBookmarked": true,
      "isUnsafe": true,
      "blockedAt": "2025-05-07T12:48:08.611Z",
      "createdAt": "2025-05-07T12:48:08.611Z",
      "models": [
        {
          "id": "string",
          "user": {
            "id": "string",
            "name": "string",
            "username": "string",
            "profilePicture": "string",
            "description": "string",
            "website": "string",
            "imagesGenerated": 0,
            "imagesAvailable": 0,
            "modelsAvailable": 0,
            "followersCount": 0,
            "followingCount": 0,
            "isVerified": true
          },
          "userId": "string",
          "name": "string",
          "username": "string",
          "class": "string",
          "type": "string",
          "description": "string",
          "website": "string",
          "status": "string",
          "progress": 0,
          "privacy": "string",
          "usages": 0,
          "imagesAvailable": 0,
          "likes": 0,
          "version": 0,
          "thumbnail": "string",
          "thumbnailOptions": {},
          "settings": {},
          "images": {},
          "isActive": true,
          "blockedAt": "2025-05-07T12:48:08.611Z",
          "createdAt": "2025-05-07T12:48:08.611Z",
          "systemVersions": [
            "string"
          ],
          "versions": [
            {
              "id": "string",
              "version": 0,
              "storagePath": "string",
              "systemVersions": [
                "string"
              ],
              "status": "string",
              "createdAt": "2025-05-07T12:48:08.611Z",
              "trainedAt": "2025-05-07T12:48:08.611Z"
            }
          ]
        }
      ]
    },
    "imageCompletionChoices": [
      "string"
    ],
    "mode": "string",
    "width": 0,
    "height": 0,
    "imageCompletionsCount": 0,
    "prompt": "string",
    "mask": "string",
    "inputImageUrl": "string",
    "webhookUrl": "string",
    "settings": {},
    "models": [
      {
        "id": "string",
        "user": {
          "id": "string",
          "name": "string",
          "username": "string",
          "profilePicture": "string",
          "description": "string",
          "website": "string",
          "imagesGenerated": 0,
          "imagesAvailable": 0,
          "modelsAvailable": 0,
          "followersCount": 0,
          "followingCount": 0,
          "isVerified": true
        },
        "userId": "string",
        "name": "string",
        "username": "string",
        "class": "string",
        "type": "string",
        "description": "string",
        "website": "string",
        "status": "string",
        "progress": 0,
        "privacy": "string",
        "usages": 0,
        "imagesAvailable": 0,
        "likes": 0,
        "version": 0,
        "thumbnail": "string",
        "thumbnailOptions": {},
        "settings": {},
        "images": {},
        "isActive": true,
        "blockedAt": "2025-05-07T12:48:08.611Z",
        "createdAt": "2025-05-07T12:48:08.611Z",
        "systemVersions": [
          "string"
        ],
        "versions": [
          {
            "id": "string",
            "version": 0,
            "storagePath": "string",
            "systemVersions": [
              "string"
            ],
            "status": "string",
            "createdAt": "2025-05-07T12:48:08.611Z",
            "trainedAt": "2025-05-07T12:48:08.611Z"
          }
        ]
      }
    ],
    "status": "string"
  },
  "prompt": "string",
  "status": "string",
  "progressMessage": "string",
  "progress": 0,
  "previewImage": "string",
  "isHot": true,
  "privacy": "string",
  "likes": 0,
  "regenerations": 0,
  "imageVersions": {},
  "systemVersion": 0,
  "hasWatermark": true,
  "isNsfw": true,
  "webhookUrl": "string",
  "createdAt": "2025-05-07T12:48:08.611Z",
  "models": [
    {
      "id": "string",
      "user": {
        "id": "string",
        "name": "string",
        "username": "string",
        "profilePicture": "string",
        "description": "string",
        "website": "string",
        "imagesGenerated": 0,
        "imagesAvailable": 0,
        "modelsAvailable": 0,
        "followersCount": 0,
        "followingCount": 0,
        "isVerified": true
      },
      "userId": "string",
      "name": "string",
      "username": "string",
      "class": "string",
      "type": "string",
      "description": "string",
      "website": "string",
      "status": "string",
      "progress": 0,
      "privacy": "string",
      "usages": 0,
      "imagesAvailable": 0,
      "likes": 0,
      "version": 0,
      "thumbnail": "string",
      "thumbnailOptions": {},
      "settings": {},
      "images": {},
      "isActive": true,
      "blockedAt": "2025-05-07T12:48:08.611Z",
      "createdAt": "2025-05-07T12:48:08.611Z",
      "systemVersions": [
        "string"
      ],
      "versions": [
        {
          "id": "string",
          "version": 0,
          "storagePath": "string",
          "systemVersions": [
            "string"
          ],
          "status": "string",
          "createdAt": "2025-05-07T12:48:08.611Z",
          "trainedAt": "2025-05-07T12:48:08.611Z"
        }
      ]
    }
  ]
}