// This list comes from the Procore API documentation.
// https://developers.procore.com/documentation/webhooks-api an you can find it as a CSV file in the Procore API documentation here https://developers.procore.com/assets/static/webhook-resources.csv
export default {
  BUDGET_LINE_ITEMS: "Budget Line Items",
  BUDGET_MODIFICATIONS: "Budget Modifications",
  BUDGET_CHANGES: "Budget Changes",
  BUDGET_CHANGE_ADJUSTMENTS: "Budget Change Adjustments",
  BUDGET_CHANGE_ADJUSTMENT_LINE_ITEMS: "Budget Change Adjustment Line Items",
  BUDGET_CHANGE_PRODUCTION_QUANTITIES: "Budget Change Production Quantities",
  BUDGET_VIEW_SNAPSHOTS: "Budget View Snapshots",
  CHANGE_EVENTS: "Change Events",
  CHANGE_EVENT_LINE_ITEMS: "Change Event Line Items",
  CHANGE_ORDER_PACKAGES: "Change Order Packages",
  CHANGE_ORDER_REQUESTS: "Change Order Requests",
  POTENTIAL_CHANGE_ORDER_LINE_ITEMS: "Potential Change Order Line Items",
  POTENTIAL_CHANGE_ORDERS: "Potential Change Orders",
  CONTRACT_PAYMENTS: "Contract Payments",
  DRAW_REQUESTS: "Draw Requests",
  PURCHASE_ORDER_CONTRACT_LINE_ITEMS: "Purchase Order Contract Line Items",
  PURCHASE_ORDER_CONTRACTS: "Purchase Order Contracts",
  RFQ_QUOTES: "RFQ Quotes",
  RFQ_RESPONSES: "RFQ Responses",
  RFQS: "RFQs",
  WORK_ORDER_CONTRACT_LINE_ITEMS: "Work Order Contract Line Items",
  WORK_ORDER_CONTRACTS: "Work Order Contracts",
  DIRECT_COST_LINE_ITEMS: "Direct Cost Line Items",
  DIRECT_COSTS: "Direct Costs",
  PAYMENT_APPLICATIONS: "Payment Applications",
  PRIME_CONTRACT_LINE_ITEMS: "Prime Contract Line Items",
  PRIME_CONTRACTS: "Prime Contracts",
  COST_CODES: "Cost Codes",
  SUB_JOBS: "Sub Jobs",
  LOCATIONS: "Locations",
  PROJECT_DATES: "Project Dates",
  PROJECT_INSURANCES: "Project Insurances",
  PROJECT_USERS: "Project Users",
  PROJECT_VENDORS: "Project Vendors",
  FILE_VERSIONS: "File Versions",
  PROJECT_FILE_VERSIONS: "Project File Versions",
  PROJECT_FILES: "Project Files",
  PROJECT_FOLDERS: "Project Folders",
  TASK_ITEMS: "Task Items",
  EQUIPMENT_LOGS: "Equipment Logs",
  TIMECARD_ENTRIES: "Timecard Entries",
  COORDINATION_ISSUE_ACTIVITIES: "Coordination Issue Activities",
  COORDINATION_ISSUES: "Coordination Issues",
  ACCIDENT_LOGS: "Accident Logs",
  CALL_LOGS: "Call Logs",
  DAILY_CONSTRUCTION_REPORT_LOGS: "Daily Construction Report Logs",
  DAILY_LOG_ENTRIES: "Daily Log/Entries",
  DAILY_LOGS: "Daily Logs",
  DELIVERY_LOGS: "Delivery Logs",
  DUMPSTER_LOGS: "Dumpster Logs",
  INSPECTION_LOGS: "Inspection Logs",
  MANPOWER_LOGS: "Manpower Logs",
  NOTES_LOGS: "Notes Logs",
  PLAN_REVISION_LOGS: "Plan Revision Logs",
  PRODUCTIVITY_LOGS: "Productivity Logs",
  QUANTITY_LOGS: "Quantity Logs",
  SAFETY_VIOLATION_LOGS: "Safety Violation Logs",
  VISITOR_LOGS: "Visitor Logs",
  WASTE_LOGS: "Waste Logs",
  WEATHER_LOGS: "Weather Logs",
  WORK_LOGS: "Work Logs",
  DRAWING_AREAS: "Drawing Areas",
  DRAWING_SETS: "Drawing Sets",
  DRAWING_UPLOADS: "Drawing Uploads",
  DRAWINGS: "Drawings",
  MARKUP_LAYERS: "Markup Layers",
  PDF_DOWNLOAD_PAGES: "Pdf Download Pages",
  GENERIC_TOOL_ITEMS: "Generic Tool Items",
  SITE_INSTRUCTIONS: "Site Instructions",
  MEETING_ATTENDEES: "Meeting Attendees",
  MEETING_CATEGORIES: "Meeting Categories",
  MEETING_TOPICS: "Meeting Topics",
  MEETINGS: "Meetings",
  BIM_FILE_EXTRATIONS: "Bim File Extractions",
  BIM_MODEL_REVISIONS: "Bim Model Revisions",
  BIM_MODELS: "Bim Models",
  IMAGE_CATEGORIES: "Image Categories",
  IMAGES: "Images",
  TASKS: "Tasks",
  TODOS: "ToDos",
  RFI_REPLIES: "RFI Replies",
  RFIS: "RFIs",
  SPECIFICATION_SECTION_DIVISIONS: "Specification Section Divisions",
  SPECIFICATION_SECTION_REVISIONS: "Specification Section Revisions",
  SPECIFICATION_SECTIONS: "Specification Sections",
  SPECIFICATION_SETS: "Specification Sets",
  SUBMITTAL_PACKAGES: "Submittal Packages",
  SUBMITTALS: "Submittals",
  FORMS: "Forms",
  INCIDENTS: "Incidents",
  INSPECTION_CHECKLISTS: "Inspection Checklists",
  OBSERVATION_ITEM_RESPONSE_LOGS: "Observation Item Response Logs",
  OBSERVATION_ITEMS: "Observation Items",
  PUNCH_ITEMS: "Punch Items",
  CHANGE_TYPES: "Change Types",
  CHANGE_ORDER_CHANGE_REASONS: "Change Order Change Reasons",
  LINE_ITEM_TYPES: "Line Item Types",
  ERP_REQUESTS: "ERP Requests",
  OFFICES: "Offices",
  PROGRAMS: "Programs",
  PROJECT_BID_TYPES: "Project Bid Types",
  PROJECT_OWNER_TYPES: "Project Owner Types",
  PROJECT_REGIONS: "Project Regions",
  PROJECT_STAGES: "Project Stages",
  PROJECT_TYPES: "Project Types",
  TRADES: "Trades",
  COMPANY_INSURANCES: "Company Insurances",
  COMPANY_USERS: "Company Users",
  COMPANY_VENDORS: "Company Vendors",
  COMPANY_FILE_VERSIONS: "Company File Versions",
  COMPANY_FILES: "Company Files",
  COMPANY_FOLDERS: "Company Folders",
  STANDARD_COST_CODE_LISTS: "Standard Cost Code Lists",
  STANDARD_COST_CODES: "Standard Cost Codes",
  PROJECTS: "Projects",
  DEPARTMENTS: "Departments",
  BIDS: "Bids",
  TIMECARD_TIME_TYPES: "Timecard Time Types",
  FORM_TEMPLATES: "Form Templates",
};
