export default {
  "id": "2-leads",
  "type": "leads",
  "isCurrentUserWatching": false,
  "deletedTime": null,
  "name": "Sample Won Lead",
  "value": {
    "amount": "55000.00",
    "currency": "USD",
    "formatted": "$55,000.00",
  },
  "number": "2",
  "description": "",
  "createdTime": {
    "absoluteLocalizedString": "May 10, 2026",
    "timestamp": 1778442165,
    "value": "May 10, 2026",
  },
  "closedTime": {
    "absoluteLocalizedString": "June 17, 2026",
    "timestamp": 1781725365,
    "value": "June 17, 2026",
  },
  "dueTime": null,
  "anticipatedClosedTime": null,
  "ownerType": "users",
  "mcfxContactIds": [],
  "status": "won",
  "lastContactedTime": null,
  "pieState": "10",
  "isOverdue": false,
  "href": "https://app.nutshell.com/rest/leads/2-leads",
  "confidence": 100,
  "priority": 0,
  "htmlUrl": "https://app.nutshell.com/lead/2",
  "htmlUrlPath": "/lead/2",
  "initials": null,
  "links": {
    "accounts": [
      "1-accounts",
    ],
    "contacts": [],
    "tags": [],
    "sources": [],
    "owner": "1-users",
    "files": [],
    "relatedFiles": [],
    "territory": null,
    "destinations": [],
    "stage": "1-stages",
    "stageset": "1-stagesets",
    "creator": "1-users",
    "products": [],
    "productMaps": [],
    "competitors": [],
    "competitorMaps": [],
    "outcome": "1-outcomes",
    "watchers": [],
    "market": "1-markets",
  },
};
