export default {
  "custom": {},
  "id": 3641,
  "created": "2024-08-05T22:19:14-06:00",
  "modified": "2024-08-05T22:19:14-06:00",
  "creator": "/crew/33",
  "displayname": "Teatro dell'Opera di Roma",
  "folder": "/folders/35",
  "type": "company",
  "ext_name_line": "",
  "firstname": "",
  "distance": 0,
  "travel_time": 0,
  "surfix": "",
  "surname": "",
  "longitude": 0,
  "latitude": 0,
  "code": "24",
  "accounting_code": "",
  "name": "Teatro dell'Opera di Roma",
  "gender": "",
  "mailing_city": "Rome",
  "mailing_street": "Piazza Beniamino Gigli",
  "mailing_number": "",
  "mailing_postalcode": "00184",
  "mailing_state": "",
  "mailing_country": "mx",
  "visit_city": "Rome",
  "visit_street": "Piazza Beniamino Gigli",
  "visit_number": "",
  "visit_postalcode": "00184",
  "visit_state": "",
  "country": "mx",
  "invoice_city": "Rome",
  "invoice_street": "Piazza Beniamino Gigli",
  "invoice_number": "",
  "invoice_postalcode": "00184",
  "invoice_state": "",
  "invoice_country": "mx",
  "phone_1": "",
  "phone_2": "",
  "email_1": "",
  "email_2": "",
  "website": "",
  "VAT_code": "",
  "fiscal_code": "",
  "commerce_code": "",
  "purchase_number": "",
  "bic": "",
  "bank_account": "",
  "default_person": null,
  "admin_contactperson": null,
  "discount_crew": 0,
  "discount_transport": 0,
  "discount_rental": 0,
  "discount_sale": 0,
  "discount_total": 0,
  "projectnote": "",
  "projectnote_title": "",
  "contact_warning": "",
  "discount_subrent": 0,
  "tags": "trial",
  "updateHash": "7b1f676960e0837a9c80756bc0ebe07e"
}