export default {
  "id": "Opnel5aKBz",
  "contacts": [
    {
      "id": "Opnel5aKBz",
      "user_id": "Opnel5aKBz",
      "client_id": "Opnel5aKBz",
      "first_name": "John",
      "last_name": "Doe",
      "phone": "555-152-4524",
      "custom_value1": "",
      "custom_value2": "",
      "custom_value3": "",
      "custom_value4": "",
      "email": "",
      "accepted_terms_version": "A long set of ToS",
      "password": "*****",
      "confirmation_code": "333-sdjkh34gbasd",
      "token": "333-sdjkh34gbasd",
      "contact_key": "JD0X52bkfZlJRiroCJ0tcSiAjsJTntZ5uqKdiZ0a",
      "is_primary": true,
      "confirmed": true,
      "is_locked": true,
      "send_email": true,
      "failed_logins": "3",
      "email_verified_at": "134341234234",
      "last_login": "134341234234",
      "created_at": "134341234234",
      "updated_at": "134341234234",
      "deleted_at": "134341234234"
    }
  ],
  "user_id": "Ua6Rw4pVbS",
  "assigned_user_id": "Ua6Rw4pVbS",
  "name": "Jim's Housekeeping",
  "website": "https://www.jims-housekeeping.com",
  "private_notes": "Client prefers email communication over phone calls",
  "client_hash": "asdfkjhk342hjhbfdvmnfb1",
  "industry_id": "5",
  "size_id": "2",
  "address1": "123 Main St",
  "address2": "Apt 4B",
  "city": "Beverly Hills",
  "state": "California",
  "postal_code": "90210",
  "phone": "555-3434-3434",
  "country_id": "1",
  "custom_value1": "Preferred contact: Email",
  "custom_value2": "Account manager: John Doe",
  "custom_value3": "VIP client: Yes",
  "custom_value4": "Annual contract value: $50,000",
  "vat_number": "VAT123456",
  "id_number": "…",
  "number": "CL-0001",
  "shipping_address1": "5 Wallaby Way",
  "shipping_address2": "Suite 5",
  "shipping_city": "Perth",
  "shipping_state": "Western Australia",
  "shipping_postal_code": "6110",
  "shipping_country_id": "4",
  "is_deleted": false,
  "balance": "500.00",
  "paid_to_date": "2000.00",
  "credit_balance": "100.00",
  "last_login": "1628686031",
  "created_at": "1617629031",
  "updated_at": "1628445631",
  "group_settings_id": "Opnel5aKBz",
  "routing_id": "Opnel5aKBz3489-dfkiu-2239-sdsd",
  "is_tax_exempt": false,
  "has_valid_vat_number": false,
  "payment_balance": 100,
  "settings": {
    "currency_id": true,
    "timezone_id": "15",
    "date_format_id": "15",
    "military_time": true,
    "language_id": "1",
    "show_currency_code": true,
    "payment_terms": "1",
    "company_gateway_ids": "1,2,3,4",
    "custom_value1": "Custom Label",
    "custom_value2": "Custom Label",
    "custom_value3": "Custom Label",
    "custom_value4": "Custom Label",
    "default_task_rate": "10.00",
    "send_reminders": true,
    "enable_client_portal_tasks": true,
    "email_style": "light",
    "reply_to_email": "email@gmail.com",
    "bcc_email": "email@gmail.com, contact@gmail.com",
    "pdf_email_attachment": true,
    "ubl_email_attachment": true,
    "email_style_custom": "<HTML></HTML>",
    "counter_number_applied": "when_sent",
    "quote_number_applied": "when_sent",
    "custom_message_dashboard": "Please pay invoices immediately",
    "custom_message_unpaid_invoice": "Please pay invoices immediately",
    "custom_message_paid_invoice": "Thanks for paying this invoice!",
    "custom_message_unapproved_quote": "Please approve quote",
    "lock_invoices": true,
    "auto_archive_invoice": true,
    "auto_archive_quote": true,
    "auto_convert_quote": true,
    "inclusive_taxes": true,
    "task_number_pattern": "{$year}-{$counter}",
    "task_number_counter": "1",
    "reminder_send_time": "32400",
    "expense_number_pattern": "{$year}-{$counter}",
    "expense_number_counter": "1",
    "vendor_number_pattern": "{$year}-{$counter}",
    "vendor_number_counter": "1",
    "ticket_number_pattern": "{$year}-{$counter}",
    "ticket_number_counter": "1",
    "payment_number_pattern": "{$year}-{$counter}",
    "payment_number_counter": "1",
    "invoice_number_pattern": "{$year}-{$counter}",
    "invoice_number_counter": "1",
    "quote_number_pattern": "{$year}-{$counter}",
    "quote_number_counter": "1",
    "client_number_pattern": "{$year}-{$counter}",
    "client_number_counter": "1",
    "credit_number_pattern": "{$year}-{$counter}",
    "credit_number_counter": "1",
    "recurring_invoice_number_prefix": "R",
    "reset_counter_frequency_id": "1",
    "reset_counter_date": "2019-01-01",
    "counter_padding": "1",
    "shared_invoice_quote_counter": true,
    "update_products": true,
    "convert_products": true,
    "fill_products": true,
    "invoice_terms": "Invoice Terms are...",
    "quote_terms": "Quote Terms are...",
    "invoice_taxes": "1",
    "invoice_design_id": "1",
    "quote_design_id": "1",
    "invoice_footer": "1",
    "invoice_labels": "1",
    "tax_rate1": "10",
    "tax_name1": "GST",
    "tax_rate2": "10",
    "tax_name2": "GST",
    "tax_rate3": "10",
    "tax_name3": "GST",
    "payment_type_id": "1",
    "custom_fields": "{}",
    "email_footer": "A default email footer",
    "email_sending_method": "default",
    "gmail_sending_user_id": "F76sd34D",
    "email_subject_invoice": "Your Invoice Subject",
    "email_subject_quote": "Your Quote Subject",
    "email_subject_payment": "Your Payment Subject",
    "email_template_invoice": "<HTML></HTML>",
    "email_template_quote": "<HTML></HTML>",
    "email_template_payment": "<HTML></HTML>",
    "email_subject_reminder1": "<HTML></HTML>",
    "email_subject_reminder2": "<HTML></HTML>",
    "email_subject_reminder3": "<HTML></HTML>",
    "email_subject_reminder_endless": "<HTML></HTML>",
    "email_template_reminder1": "<HTML></HTML>",
    "email_template_reminder2": "<HTML></HTML>",
    "email_template_reminder3": "<HTML></HTML>",
    "email_template_reminder_endless": "<HTML></HTML>",
    "enable_portal_password": true,
    "show_accept_invoice_terms": true,
    "show_accept_quote_terms": true,
    "require_invoice_signature": true,
    "require_quote_signature": true,
    "name": "Acme Co",
    "company_logo": "logo.png",
    "website": "www.acme.com",
    "address1": "Suite 888",
    "address2": "5 Jimbo Way",
    "city": "Sydney",
    "state": "Florisa",
    "postal_code": "90210",
    "phone": "555-213-3948",
    "email": "joe@acme.co",
    "country_id": "1",
    "vat_number": "32 120 377 720",
    "page_size": "A4",
    "font_size": "9",
    "primary_font": "roboto",
    "secondary_font": "roboto",
    "hide_paid_to_date": false,
    "embed_documents": false,
    "all_pages_header": false,
    "all_pages_footer": false,
    "document_email_attachment": false,
    "enable_client_portal_password": false,
    "enable_email_markup": false,
    "enable_client_portal_dashboard": false,
    "enable_client_portal": false,
    "email_template_statement": "template matter",
    "email_subject_statement": "subject matter",
    "signature_on_pdf": false,
    "quote_footer": "the quote footer",
    "email_subject_custom1": "Custom Subject 1",
    "email_subject_custom2": "Custom Subject 2",
    "email_subject_custom3": "Custom Subject 3",
    "email_template_custom1": "<HTML>",
    "email_template_custom2": "<HTML>",
    "email_template_custom3": "<HTML>",
    "enable_reminder1": false,
    "enable_reminder2": false,
    "enable_reminder3": false,
    "num_days_reminder1": "9",
    "num_days_reminder2": "9",
    "num_days_reminder3": "9",
    "schedule_reminder1": "after_invoice_date",
    "schedule_reminder2": "after_invoice_date",
    "schedule_reminder3": "after_invoice_date",
    "late_fee_amount1": 10,
    "late_fee_amount2": 20,
    "late_fee_amount3": 100,
    "endless_reminder_frequency_id": "1",
    "client_online_payment_notification": false,
    "client_manual_payment_notification": false,
    "enable_e_invoice": false,
    "default_expense_payment_type_id": "0",
    "e_invoice_type": "EN16931",
    "mailgun_endpoint": "api.mailgun.net or api.eu.mailgun.net",
    "client_initiated_payments": false,
    "client_initiated_payments_minimum": 10,
    "sync_invoice_quote_columns": false,
    "show_task_item_description": false,
    "allow_billable_task_items": false,
    "accept_client_input_quote_approval": false,
    "custom_sending_email": "bob@gmail.com",
    "show_paid_stamp": false,
    "show_shipping_address": false,
    "company_logo_size": 100,
    "show_email_footer": false,
    "email_alignment": "left",
    "auto_bill_standard_invoices": false,
    "postmark_secret": "123456",
    "mailgun_secret": "123456",
    "mailgun_domain": "sandbox123456.mailgun.org",
    "send_email_on_mark_paid": false,
    "vendor_portal_enable_uploads": false,
    "besr_id": "123456",
    "qr_iban": "CH123456",
    "email_subject_purchase_order": "Purchase Order",
    "email_template_purchase_order": "Please see attached your purchase order.",
    "require_purchase_order_signature": false,
    "purchase_order_public_notes": "Please see attached your purchase order.",
    "purchase_order_terms": "Please see attached your purchase order.",
    "purchase_order_footer": "Please see attached your purchase order.",
    "purchase_order_design_id": "hd677df",
    "purchase_order_number_pattern": "PO-000000",
    "purchase_order_number_counter": 1,
    "page_numbering_alignment": "left",
    "page_numbering": false,
    "auto_archive_invoice_cancelled": false,
    "email_from_name": "Bob Smith",
    "show_all_tasks_client_portal": false,
    "entity_send_time": 9,
    "shared_invoice_credit_counter": false,
    "reply_to_name": "Bob Smith",
    "hide_empty_columns_on_pdf": false,
    "enable_reminder_endless": false,
    "use_credits_payment": false,
    "recurring_invoice_number_pattern": "R-000000",
    "recurring_invoice_number_counter": 1,
    "client_portal_under_payment_minimum": 10,
    "auto_bill_date": "on_send_date",
    "primary_color": "#ffffff",
    "secondary_color": "#ffffff",
    "client_portal_allow_under_payment": false,
    "client_portal_allow_over_payment": false,
    "auto_bill": "off",
    "client_portal_terms": "Please see attached your invoice.",
    "client_portal_privacy_policy": "These are the terms of use for using the client portal.",
    "client_can_register": false,
    "portal_design_id": "hd677df",
    "late_fee_endless_percent": 10,
    "late_fee_endless_amount": 10,
    "auto_email_invoice": false,
    "email_signature": "Bob Smith"
  }
}