<template><h1 id="triggers" tabindex="-1"><a class="header-anchor" href="#triggers" aria-hidden="true">#</a> Triggers</h1>
<p><strong>Triggers</strong> define the type of event that runs your workflow. For example, HTTP triggers expose a URL where you can send any HTTP requests. Pipedream will run your workflow on each request. The Cron Scheduler trigger runs your workflow on a schedule.</p>
<p>Today, we support the following triggers:</p>
<ul>
<li><a href="#app-based-triggers">Triggers for apps like Twitter, Github, and more</a></li>
<li><a href="#http">HTTP / Webhook</a></li>
<li><a href="#schedule">Schedule</a></li>
<li><a href="#email">Email</a></li>
<li><a href="#rss">RSS</a></li>
</ul>
<p>If there's a specific trigger you'd like supported, please <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">let us know<ExternalLinkIcon/></a>.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#app-based-triggers">App-based Triggers</RouterLink><ul><li><RouterLink to="#what-s-the-difference-between-an-event-source-and-a-trigger">What&#39;s the difference between an event source and a trigger?</RouterLink></li><li><RouterLink to="#dependent-and-independent-sources">Dependent and Independent Sources</RouterLink></li><li><RouterLink to="#shape-of-the-steps-trigger-event-object">Shape of the steps.trigger.event object</RouterLink></li></ul></li><li><RouterLink to="#http">HTTP</RouterLink><ul><li><RouterLink to="#accessing-http-request-data">Accessing HTTP request data</RouterLink></li><li><RouterLink to="#valid-requests">Valid Requests</RouterLink></li><li><RouterLink to="#how-pipedream-handles-json-payloads">How Pipedream handles JSON payloads</RouterLink></li><li><RouterLink to="#how-pipedream-handles-multipart-form-data">How Pipedream handles multipart/form-data</RouterLink></li><li><RouterLink to="#sending-large-payloads">Sending large payloads</RouterLink></li><li><RouterLink to="#large-file-support">Large File Support</RouterLink></li><li><RouterLink to="#cross-origin-http-requests">Cross-Origin HTTP Requests</RouterLink></li><li><RouterLink to="#http-responses">HTTP Responses</RouterLink></li><li><RouterLink to="#errors">Errors</RouterLink></li><li><RouterLink to="#validating-requests">Validating requests</RouterLink></li></ul></li><li><RouterLink to="#schedule">Schedule</RouterLink><ul><li><RouterLink to="#choosing-a-cron-trigger">Choosing a cron trigger</RouterLink></li><li><RouterLink to="#testing-a-cron-job">Testing a cron job</RouterLink></li><li><RouterLink to="#future-executions-of-your-cron-job">Future executions of your cron job</RouterLink></li><li><RouterLink to="#job-history">Job History</RouterLink></li><li><RouterLink to="#trigger-a-notification-to-an-external-service-email-slack-etc">Trigger a notification to an external service (email, Slack, etc.)</RouterLink></li><li><RouterLink to="#rate-limit">Rate Limit</RouterLink></li><li><RouterLink to="#troubleshooting-your-scheduled-jobs">Troubleshooting your scheduled jobs</RouterLink></li><li><RouterLink to="#limitations">Limitations</RouterLink></li></ul></li><li><RouterLink to="#email">Email</RouterLink><ul><li><RouterLink to="#sending-large-emails">Sending large emails</RouterLink></li><li><RouterLink to="#appending-metadata-to-the-incoming-email-address-with-data">Appending metadata to the incoming email address with +data</RouterLink></li></ul></li><li><RouterLink to="#rss">RSS</RouterLink></li><li><RouterLink to="#sdk">SDK</RouterLink></li><li><RouterLink to="#don-t-see-a-trigger-you-need">Don&#39;t see a trigger you need?</RouterLink></li><li><RouterLink to="#multiple-triggers-for-one-workflow">Multiple triggers for one workflow</RouterLink></li></ul></nav>
<h2 id="app-based-triggers" tabindex="-1"><a class="header-anchor" href="#app-based-triggers" aria-hidden="true">#</a> App-based Triggers</h2>
<p>You can trigger a workflow on events from apps like Twitter, Google Calendar, and more using <a href="/event-sources" target="_blank" rel="noopener noreferrer">event sources<ExternalLinkIcon/></a>. Event sources run as separate resources from your workflow, which allows you to trigger <em>multiple</em> workflows using the same source. Here, we'll refer to event sources and workflow triggers interchangeably.</p>
<p>When you create a workflow, you'll see your available triggers:</p>
<div>
<img alt="App triggers" src="@source/workflows/steps/triggers/images/app-triggers.png">
</div>
<p>Search by <strong>app name</strong> to find triggers associated with your app. For Google Calendar, for example, you can run your workflow every time a new event is <strong>added</strong> to your calendar, each time an event <strong>starts</strong>, <strong>ends</strong>, and more:</p>
<div>
<img alt="Google Calendar sources" src="@source/workflows/steps/triggers/images/google-calendar-triggers.png">
</div>
<p>Once you select your trigger, you'll be asked to connect any necessary accounts (for example, Google Calendar sources require you authorize Pipedream access to your Google account), and enter the values for any configuration settings.</p>
<p>Some sources are configured to retrieve an initial set of events when they're created. Others require you to generate events in the app to trigger your workflow. If your source generates an initial set of events, you'll see them appear in the <strong>test</strong> menu in the trigger step:</p>
<div>
<img alt="Airtable test events" src="@source/workflows/steps/triggers/images/airtable-test-events.png">
</div>
<p>Then you can select a specific test event and manually trigger your workflow with that event data by clicking <strong>Send Test Event</strong>.</p>
<p>Moreover, since event sources can produce a large stream of events, the workflow is configured to <strong>pause</strong> the stream of events from source to workflow when you first create your workflow. This way, you can author your workflow without it being triggered automatically by your source, sending test events manually during development, instead. <strong>Once you're done, you can toggle the source on in the top-right of the trigger step</strong>:</p>
<div>
<img alt="Turn your trigger on" width="300px" src="@source/workflows/steps/triggers/images/turn-trigger-on.gif">
</div>
<h3 id="what-s-the-difference-between-an-event-source-and-a-trigger" tabindex="-1"><a class="header-anchor" href="#what-s-the-difference-between-an-event-source-and-a-trigger" aria-hidden="true">#</a> What's the difference between an event source and a trigger?</h3>
<p>You'll notice the docs use the terms <strong>event source</strong> and <strong>trigger</strong> interchangeably above. It's useful to clarify the distinction in the context of workflows.</p>
<p><a href="/event-sources" target="_blank" rel="noopener noreferrer"><strong>Event sources</strong><ExternalLinkIcon/></a> run code that collects events from some app or service and emits events as the source produces them. An event source can be used to <strong>trigger</strong> any number of workflows.</p>
<p>For example, you might create a single source to listen for new Twitter mentions for a keyword, then trigger multiple workflows each time a new tweet is found: one to <a href="https://pipedream.com/@pravin/twitter-mentions-slack-p_dDCA5e/edit" target="_blank" rel="noopener noreferrer">send new tweets to Slack<ExternalLinkIcon/></a>, another to <a href="https://pipedream.com/@dylan/twitter-to-s3-p_KwCZGA/readme" target="_blank" rel="noopener noreferrer">save those tweets to an Amazon S3 bucket<ExternalLinkIcon/></a>, etc.</p>
<p><strong>This model allows you to separate the data produced by a service (the event source) from the logic to process those events in different contexts (the workflow)</strong>.</p>
<p>Moreover, you can access events emitted by sources using Pipedream's <a href="/api/sse/" target="_blank" rel="noopener noreferrer">SSE<ExternalLinkIcon/></a> and <a href="/api/rest/" target="_blank" rel="noopener noreferrer">REST APIs<ExternalLinkIcon/></a>. This allows you to access these events in your own app, outside Pipedream's platform.</p>
<h3 id="dependent-and-independent-sources" tabindex="-1"><a class="header-anchor" href="#dependent-and-independent-sources" aria-hidden="true">#</a> Dependent and Independent Sources</h3>
<p>In order to reduce unintentional workflow invocations, certain sources are classified as &quot;dependent&quot; and will mirror the state of their parent workflow. For example,</p>
<ul>
<li>When adding a source to a new workflow, that source will initially be set as dependent. If you pause or delete the workflow, that source will also be paused or deleted. If you re-enable the workflow after pausing it, the source will be re-enabled as well.</li>
<li>If you add that same source to another workflow, or create a workflow then later remove and add a different source, the source will be independent from the workflow, which means pausing, re-enabling, or deleting the workflow will not impact the source.</li>
</ul>
<p>There is not currently any user-facing indication for dependent vs. independent sources at this time.</p>
<h3 id="shape-of-the-steps-trigger-event-object" tabindex="-1"><a class="header-anchor" href="#shape-of-the-steps-trigger-event-object" aria-hidden="true">#</a> Shape of the <code>steps.trigger.event</code> object</h3>
<p>In all workflows, you have access to <a href="/workflows/events/#event-format" target="_blank" rel="noopener noreferrer">event data<ExternalLinkIcon/></a> using one the variable <code>steps.trigger.event</code>.</p>
<p>The shape of the event is specific to the source. For example, RSS sources produce events with a <code>url</code> and <code>title</code> property representing the data provided by new items from a feed. Google Calendar sources produce events with a meeting title, start date, etc.</p>
<h2 id="http" tabindex="-1"><a class="header-anchor" href="#http" aria-hidden="true">#</a> HTTP</h2>
<p>When you select the <strong>HTTP API</strong> trigger:</p>
<div>
<img alt="HTTP API trigger" width="400px" src="@source/workflows/steps/triggers/images/http-api-trigger.png">
</div>
<p>Pipedream creates a URL endpoint specific to your workflow:</p>
<div>
<img alt="HTTP API trigger endpoint" width="400px" src="@source/workflows/steps/triggers/images/http-endpoint.png">
</div>
<p>You can send any HTTP requests to this endpoint, from anywhere on the web. You can configure the endpoint as the destination URL for a webhook or send HTTP traffic from your application - we'll accept any <a href="#valid-requests">valid HTTP request</a>.</p>
<h3 id="accessing-http-request-data" tabindex="-1"><a class="header-anchor" href="#accessing-http-request-data" aria-hidden="true">#</a> Accessing HTTP request data</h3>
<p>You can access properties of the HTTP request, like the method, payload, headers, and more, in <a href="/workflows/events/#event-format" target="_blank" rel="noopener noreferrer">the <code>event</code> object<ExternalLinkIcon/></a>, accessible in any <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">code<ExternalLinkIcon/></a> or <a href="/components/actions/" target="_blank" rel="noopener noreferrer">action<ExternalLinkIcon/></a> step.</p>
<h3 id="valid-requests" tabindex="-1"><a class="header-anchor" href="#valid-requests" aria-hidden="true">#</a> Valid Requests</h3>
<p>You can send a request to your endpoint using any valid HTTP method: <code>GET</code>, <code>POST</code>, <code>HEAD</code>, and more.</p>
<p>We default to generating HTTPS URLs in the UI, but will accept HTTP requests against the same endpoint URL.</p>
<p>You can send data to any path on this host, with any query string parameters. You can access the full URL in the <code>event</code> object if you'd like to write code that interprets requests with different URLs differently.</p>
<p>You can send data of any <a href="https://www.iana.org/assignments/media-types/media-types.xhtml" target="_blank" rel="noopener noreferrer">Media Type<ExternalLinkIcon/></a> in the body of your request.</p>
<p>The primary limit we impose is on the size of the request body: we'll issue a <code>413 Payload Too Large</code> status when the body <a href="#request-entity-too-large">exceeds our specified limit</a>.</p>
<h3 id="how-pipedream-handles-json-payloads" tabindex="-1"><a class="header-anchor" href="#how-pipedream-handles-json-payloads" aria-hidden="true">#</a> How Pipedream handles JSON payloads</h3>
<p>JSON is the main data exchange format on the web today. Pipedream optimizes for the case where you've sent JSON as the source event to a workflow.</p>
<p>When you send JSON in the HTTP payload, or when JSON data is sent in the payload from a webhook provider, <strong>Pipedream converts that JSON to its equivalent JavaScript object</strong>. The trigger data can be referenced using either <code>event</code> or the <code>steps</code> object.</p>
<p>You can confirm this JSON to JavaScript object conversion occurred by examining the <code>event.inferred_body_type</code> property. If this is JSON, we correctly recognized the payload as such, and converted <code>event.body</code> to an object accordingly.</p>
<p>In the <a href="/workflows/events/inspect/" target="_blank" rel="noopener noreferrer">Inspector<ExternalLinkIcon/></a>, we present <code>event.body</code> cleanly, indenting nested properties, to make the payload easy to read. Since <code>event.body</code> is a JavaScript object, it's easy to reference and manipulate properties of the payload using dot-notation.</p>
<h3 id="how-pipedream-handles-multipart-form-data" tabindex="-1"><a class="header-anchor" href="#how-pipedream-handles-multipart-form-data" aria-hidden="true">#</a> How Pipedream handles <code>multipart/form-data</code></h3>
<p>When you send <a href="https://ec.haxx.se/http/http-multipart" target="_blank" rel="noopener noreferrer">form data<ExternalLinkIcon/></a> to Pipedream using a <code>Content-Type</code> of <code>multipart/form-data</code>, Pipedream parses the payload and converts it to a JavaScript object with a property per form field. For example, if you send a request with two fields:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -F <span class="token string">'name=Leia'</span> -F <span class="token string">'title=General'</span> https://myendpoint.m.pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Pipedream will convert that to a JavaScript object, <code>event.body</code>, with the following shape:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token punctuation">{</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Leia"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">title</span><span class="token operator">:</span> <span class="token string">"General"</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>In this case, the <code>inferred_body_type</code> property of the <code>event</code> object will be set to <code>MULTIPART_FORM</code> to signal that we inferred form data and applied the conversion.</p>
<h4 id="limits" tabindex="-1"><a class="header-anchor" href="#limits" aria-hidden="true">#</a> Limits</h4>
<p>You can send any content, up to the <a href="/limits/#http-request-body-size" target="_blank" rel="noopener noreferrer">HTTP payload size limit<ExternalLinkIcon/></a>, as a part of the form request. The content of uploaded images or other binary files does not contribute to this limit — the contents of the file will be uploaded at a Pipedream URL you have access to within your source or workflow. See the section on <a href="#large-file-support">Large File Support</a> for more detail.</p>
<h3 id="sending-large-payloads" tabindex="-1"><a class="header-anchor" href="#sending-large-payloads" aria-hidden="true">#</a> Sending large payloads</h3>
<p><em>If you're uploading files, like images or videos, you should use the <a href="#large-file-support">large file upload interface</a>, instead</em>.</p>
<p>By default, the body of HTTP requests sent to a source or workflow is limited to <code>{{$site.themeConfig.PAYLOAD_SIZE_LIMIT}}</code>. <strong>But you can send an HTTP payload of any size to a <a href="/workflows/" target="_blank" rel="noopener noreferrer">workflow<ExternalLinkIcon/></a> or an <a href="/event-sources/" target="_blank" rel="noopener noreferrer">event source<ExternalLinkIcon/></a> by including the <code>pipedream_upload_body=1</code> query string or an <code>x-pd-upload-body: 1</code> HTTP header in your request</strong>.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -d <span class="token string">'{ "name": "Yoda" }'</span> <span class="token punctuation">\</span>
  https://endpoint.m.pipedream.net<span class="token punctuation">\</span>?pipedream_upload_body<span class="token punctuation">\</span><span class="token operator">=</span><span class="token number">1</span>

<span class="token function">curl</span> -d <span class="token string">'{ "name": "Yoda" }'</span> <span class="token punctuation">\</span>
  -H <span class="token string">"x-pd-upload-body: 1"</span> <span class="token punctuation">\</span>
  https://endpoint.m.pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>In workflows, Pipedream saves the raw payload data in a file whose URL you can reference in the variable <code>steps.trigger.event.body.raw_body_url</code>.</p>
<div>
<img alt="Raw body URL in event data" width="600px" src="@source/workflows/steps/triggers/images/raw_body_url.png">
</div>
<p>Within your workflow, you can download the contents of this data using the <strong>Send HTTP Request</strong> action, or <a href="/workflows/steps/code/nodejs/working-with-files/" target="_blank" rel="noopener noreferrer">by saving the data as a file to the <code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<h4 id="example-download-the-http-payload-using-the-send-http-request-action" tabindex="-1"><a class="header-anchor" href="#example-download-the-http-payload-using-the-send-http-request-action" aria-hidden="true">#</a> Example: Download the HTTP payload using the Send HTTP Request action</h4>
<p><em>Note: you can only download payloads at most <code>{{$site.themeConfig.FUNCTION_PAYLOAD_LIMIT}}</code> in size using this method. Otherwise, you may encounter a <a href="/errors/#function-payload-limit-exceeded" target="_blank" rel="noopener noreferrer">Function Payload Limit Exceeded<ExternalLinkIcon/></a> error.</em></p>
<p>You can download the HTTP payload using the <strong>Send HTTP Request</strong> action. <a href="https://pipedream.com/@dylburger/example-download-http-payload-p_6lC1ynx/edit" target="_blank" rel="noopener noreferrer"><strong>Copy this workflow to see how this works</strong><ExternalLinkIcon/></a>.</p>
<p>This will return the data in the variable <code>steps.send_http_request.$return_value</code>:</p>
<div>
<img alt="HTTP response data" width="600px" src="@source/workflows/steps/triggers/images/send_http_request_action.png">
</div>
<h4 id="example-download-the-http-payload-to-the-tmp-directory" tabindex="-1"><a class="header-anchor" href="#example-download-the-http-payload-to-the-tmp-directory" aria-hidden="true">#</a> Example: Download the HTTP payload to the <code>/tmp</code> directory</h4>
<p><a href="https://pipedream.com/@dylburger/example-download-raw-body-to-tmp-p_YyCoqPb/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> downloads the HTTP payload, saving it as a file to the <a href="/workflows/steps/code/nodejs/working-with-files/#the-tmp-directory" target="_blank" rel="noopener noreferrer"><code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> stream <span class="token keyword">from</span> <span class="token string">"stream"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> promisify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"util"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> got <span class="token keyword">from</span> <span class="token string">"got"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> pipeline <span class="token operator">=</span> <span class="token function">promisify</span><span class="token punctuation">(</span>stream<span class="token punctuation">.</span>pipeline<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> <span class="token function">pipeline</span><span class="token punctuation">(</span>
  got<span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>body<span class="token punctuation">.</span>raw_body_url<span class="token punctuation">)</span><span class="token punctuation">,</span>
  fs<span class="token punctuation">.</span><span class="token function">createWriteStream</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">/tmp/raw_body</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>You can <a href="/workflows/steps/code/nodejs/working-with-files/#reading-a-file-from-tmp" target="_blank" rel="noopener noreferrer">read this file<ExternalLinkIcon/></a> in subsequent steps of your workflow.</p>
<h4 id="how-the-payload-data-is-saved" tabindex="-1"><a class="header-anchor" href="#how-the-payload-data-is-saved" aria-hidden="true">#</a> How the payload data is saved</h4>
<p>Your raw payload is saved to a Pipedream-owned <a href="https://aws.amazon.com/s3/" target="_blank" rel="noopener noreferrer">Amazon S3 bucket<ExternalLinkIcon/></a>. Pipedream generates a <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html" target="_blank" rel="noopener noreferrer">signed URL<ExternalLinkIcon/></a> that allows you to access to that file for up to 30 minutes. After 30 minutes, the signed URL will be invalidated, and the file will be deleted.</p>
<h4 id="limits-1" tabindex="-1"><a class="header-anchor" href="#limits-1" aria-hidden="true">#</a> Limits</h4>
<p><strong>You can upload payloads up to 5TB in size</strong>. However, payloads that large may trigger <a href="/limits/" target="_blank" rel="noopener noreferrer">other Pipedream limits<ExternalLinkIcon/></a>. Please <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">reach out<ExternalLinkIcon/></a> with any specific questions or issues.</p>
<h3 id="large-file-support" tabindex="-1"><a class="header-anchor" href="#large-file-support" aria-hidden="true">#</a> Large File Support</h3>
<p><em>This interface is best used for uploading large files, like images or videos. If you're sending JSON or other data directly in the HTTP payload, and encountering a <strong>Request Entity Too Large</strong> error, review the section above for <a href="#sending-large-payloads">sending large payloads</a></em>.</p>
<p>You can upload any file to a <a href="/workflows/" target="_blank" rel="noopener noreferrer">workflow<ExternalLinkIcon/></a> or an <a href="/event-sources/" target="_blank" rel="noopener noreferrer">event source<ExternalLinkIcon/></a> by making a <code>multipart/form-data</code> HTTP request with the file as one of the form parts. <strong>Pipedream saves that file to a Pipedream-owned <a href="https://aws.amazon.com/s3/" target="_blank" rel="noopener noreferrer">Amazon S3 bucket<ExternalLinkIcon/></a>, generating a <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html" target="_blank" rel="noopener noreferrer">signed URL<ExternalLinkIcon/></a> that allows you to access to that file for up to 30 minutes</strong>. After 30 minutes, the signed URL will be invalidated, and the file will be deleted.</p>
<p>In workflows, these file URLs are provided in the <code>steps.trigger.event.body</code> variable, so you can download the file using the URL within your workflow, or pass the URL on to another third-party system for it to process.</p>
<div>
<img alt="Raw file URL in event data" width="600px" src="@source/workflows/steps/triggers/images/file-upload-urls.png">
</div>
<p>Within your workflow, you can download the contents of this data using the <strong>Send HTTP Request</strong> action, or <a href="/workflows/steps/code/nodejs/working-with-files/" target="_blank" rel="noopener noreferrer">by saving the data as a file to the <code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<h4 id="example-upload-a-file-using-curl" tabindex="-1"><a class="header-anchor" href="#example-upload-a-file-using-curl" aria-hidden="true">#</a> Example: upload a file using <code>cURL</code></h4>
<p>For example, you can upload an image to a workflow using <code>cURL</code>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -F <span class="token string">'image=@my_image.png'</span> https://myendpoint.m.pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>The <code>-F</code> tells <code>cURL</code> we're sending form data, with a single &quot;part&quot;: a field named <code>image</code>, with the content of the image as the value (the <code>@</code> allows <code>cURL</code> to reference a local file).</p>
<p>When you send this image to a workflow, Pipedream <a href="#how-pipedream-handles-multipart-form-data">parses the form data</a> and converts it to a JavaScript object, <code>event.body</code>. Select the event from the <a href="/workflows/events/inspect/#the-inspector" target="_blank" rel="noopener noreferrer">inspector<ExternalLinkIcon/></a>, and you'll see the <code>image</code> property under <code>event.body</code>:</p>
<div>
<img alt="Image form data" src="@source/workflows/steps/triggers/images/image_form_data.png">
</div>
<p>When you upload a file as a part of the form request, Pipedream saves it to a Pipedream-owned <a href="https://aws.amazon.com/s3/" target="_blank" rel="noopener noreferrer">Amazon S3 bucket<ExternalLinkIcon/></a>, generating a <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html" target="_blank" rel="noopener noreferrer">signed URL<ExternalLinkIcon/></a> that allows you to access to that file for up to 30 minutes. After 30 minutes, the signed URL will be invalidated, and the file will be deleted.</p>
<p>Within the <code>image</code> property of <code>event.body</code>, you'll see the value of this URL in the <code>url</code> property, along with the <code>filename</code> and <code>mimetype</code> of the file. Within your workflow, you can download the file, or pass the URL to a third party system to handle, and more.</p>
<h4 id="example-download-this-file-to-the-tmp-directory" tabindex="-1"><a class="header-anchor" href="#example-download-this-file-to-the-tmp-directory" aria-hidden="true">#</a> Example: Download this file to the <code>/tmp</code> directory</h4>
<p><a href="https://pipedream.com/@dylburger/example-download-an-image-to-tmp-p_KwC2Ad/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> downloads an image passed in the <code>image</code> field in the form request, saving it to the <a href="/workflows/steps/code/nodejs/working-with-files/#the-tmp-directory" target="_blank" rel="noopener noreferrer"><code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> stream <span class="token keyword">from</span> <span class="token string">"stream"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> promisify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"util"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> got <span class="token keyword">from</span> <span class="token string">"got"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> pipeline <span class="token operator">=</span> <span class="token function">promisify</span><span class="token punctuation">(</span>stream<span class="token punctuation">.</span>pipeline<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> <span class="token function">pipeline</span><span class="token punctuation">(</span>
  got<span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>body<span class="token punctuation">.</span>image<span class="token punctuation">.</span>url<span class="token punctuation">)</span><span class="token punctuation">,</span>
  fs<span class="token punctuation">.</span><span class="token function">createWriteStream</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">/tmp/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>body<span class="token punctuation">.</span>image<span class="token punctuation">.</span>filename<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h4 id="example-upload-image-to-your-own-amazon-s3-bucket" tabindex="-1"><a class="header-anchor" href="#example-upload-image-to-your-own-amazon-s3-bucket" aria-hidden="true">#</a> Example: Upload image to your own Amazon S3 bucket</h4>
<p><a href="https://pipedream.com/@dylburger/example-save-uploaded-file-to-amazon-s3-p_o7Cm9z/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> streams the uploaded file to an Amazon S3 bucket you specify, allowing you to save the file to long-term storage.</p>
<h4 id="limits-2" tabindex="-1"><a class="header-anchor" href="#limits-2" aria-hidden="true">#</a> Limits</h4>
<p>Since large files are uploaded using a <code>Content-Type</code> of <code>multipart/form-data</code>, the limits that apply to <a href="#how-pipedream-handles-multipart-form-data">form data</a> also apply here.</p>
<p>The content of the file itself does not contribute to the HTTP payload limit imposed for forms. <strong>You can upload files up to 5TB in size</strong>. However, files that large may trigger <a href="/limits/" target="_blank" rel="noopener noreferrer">other Pipedream limits<ExternalLinkIcon/></a>. Please <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">reach out<ExternalLinkIcon/></a> with any specific questions or issues.</p>
<h3 id="cross-origin-http-requests" tabindex="-1"><a class="header-anchor" href="#cross-origin-http-requests" aria-hidden="true">#</a> Cross-Origin HTTP Requests</h3>
<p>We return the following headers on HTTP <code>OPTIONS</code> requests:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>Thus, your endpoint will accept <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS" target="_blank" rel="noopener noreferrer">cross-origin HTTP requests<ExternalLinkIcon/></a> from any domain, using any standard HTTP method.</p>
<h3 id="http-responses" tabindex="-1"><a class="header-anchor" href="#http-responses" aria-hidden="true">#</a> HTTP Responses</h3>
<h4 id="default-http-response" tabindex="-1"><a class="header-anchor" href="#default-http-response" aria-hidden="true">#</a> Default HTTP response</h4>
<p>By default, when you send a <a href="#valid-requests">valid HTTP request</a> to your endpoint URL, you should expect to receive a <code>200 OK</code> status code with the following payload:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>&lt;p>&lt;b>Success!&lt;/b>&lt;/p>
&lt;p>To customize this response, check out our docs &lt;a href="https://docs.pipedream.com/workflows/steps/triggers/#http-responses">here&lt;/a>&lt;/p>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>When you're processing HTTP requests, you often don't need to issue any special response to the client. We issue this default response so you don't have to write any code to do it yourself.</p>
<h4 id="customizing-the-http-response" tabindex="-1"><a class="header-anchor" href="#customizing-the-http-response" aria-hidden="true">#</a> Customizing the HTTP response</h4>
<p>If you need to issue a custom HTTP response from a workflow, <strong>you can use the <code>$.respond()</code> function in a Code or Action step</strong>.</p>
<p><code>$.respond()</code> takes a single argument: an object with properties that specify the body, headers, and HTTP status code you'd like to respond with:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span><span class="token function">respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
      <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token string-property property">"my-custom-header"</span><span class="token operator">:</span> <span class="token string">"value"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">"My custom response"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token comment">// This can be any string, object, Buffer, or Readable stream</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>The <code>$.respond</code> function is currently only available in Node.js (Javascript) workflow steps.</p>
</div>
<p>The value of the <code>body</code> property can be either a string, object, a <a href="https://nodejs.org/api/buffer.html#buffer_buffer" target="_blank" rel="noopener noreferrer">Buffer<ExternalLinkIcon/></a> (binary data), or a <a href="https://nodejs.org/api/stream.html#stream_readable_streams" target="_blank" rel="noopener noreferrer">Readable stream<ExternalLinkIcon/></a>. Attempting to return any other data may yield an error.</p>
<p>In the case where you return a Readable stream:</p>
<ul>
<li>You must <code>await</code> the <code>$.respond</code> function (<code>await $.respond({ ... }</code>)</li>
<li>The stream must close and be finished reading within your <a href="/limits/#time-per-execution" target="_blank" rel="noopener noreferrer">workflow execution timeout<ExternalLinkIcon/></a>.</li>
<li>You cannot return a Readable and use the <a href="#returning-a-response-immediately"><code>immediate: true</code></a> property of <code>$.respond</code>.</li>
</ul>
<p>You can <strong>Copy</strong> <a href="https://pipedream.com/@dylburger/issue-an-http-response-from-a-workflow-p_ljCRdv/edit" target="_blank" rel="noopener noreferrer">this example workflow<ExternalLinkIcon/></a> and make an HTTP request to its endpoint URL to experiment with this.</p>
<h4 id="timing-of-respond-execution" tabindex="-1"><a class="header-anchor" href="#timing-of-respond-execution" aria-hidden="true">#</a> Timing of <code>$.respond()</code> execution</h4>
<p>You may notice some response latency calling workflows that use <code>$.respond()</code> from your HTTP client. By default, <code>$.respond()</code> is called at the end of your workflow, after all other code is done executing, so it may take some time to issue the response back.</p>
<p>If you need to issue an HTTP response in the middle of a workflow, see the section on <a href="#returning-a-response-immediately">returning a response immediately</a>.</p>
<h4 id="returning-a-response-immediately" tabindex="-1"><a class="header-anchor" href="#returning-a-response-immediately" aria-hidden="true">#</a> Returning a response immediately</h4>
<p>You can issue an HTTP response within a workflow, and continue the rest of the workflow execution, by setting the <code>immediate</code> property to <code>true</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">await</span> $<span class="token punctuation">.</span><span class="token function">respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">immediate</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
      <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token string-property property">"my-custom-header"</span><span class="token operator">:</span> <span class="token string">"value"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">"My custom response"</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>Passing <code>immediate: true</code> tells <code>$.respond()</code> to issue a response back to the client at this point in the workflow. After the HTTP response has been issued, the remaining code in your workflow runs.</p>
<p>This can be helpful, for example, when you're building a Slack bot. When you send a message to a bot, Slack requires a <code>200 OK</code> response be issued immediately, to confirm receipt:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">await</span> $<span class="token punctuation">.</span><span class="token function">respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">immediate</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
      <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>Once you issue the response, you'll probably want to process the message from the user and respond back with another message or data requested by the user.</p>
<p><a href="https://pipedream.com/@dylburger/issue-http-response-immediately-continue-running-workflow-p_pWCWGJ" target="_blank" rel="noopener noreferrer">Here's an example workflow<ExternalLinkIcon/></a> that shows how to use <code>immediate: true</code> and run code after the HTTP response is issued.</p>
<h4 id="errors-with-http-responses" tabindex="-1"><a class="header-anchor" href="#errors-with-http-responses" aria-hidden="true">#</a> Errors with HTTP Responses</h4>
<p>If you use <code>$.respond()</code> in a workflow, <strong>you must always make sure <code>$.respond()</code> is called in your code</strong>. If you make an HTTP request to a workflow, and run code where <code>$.respond()</code> is <em>not</em> called, your endpoint URL will issue a <code>400 Bad Request</code> error with the following body:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>No $.respond called in workflow
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>This might happen if:</p>
<ul>
<li>You call <code>$.respond()</code> conditionally, where it does not run under certain conditions.</li>
<li>Your workflow throws an Error before you run <code>$.respond()</code>.</li>
<li>You return data in the <code>body</code> property that isn't a string, object, or Buffer.</li>
</ul>
<p>If you can't handle the <code>400 Bad Request</code> error in the application calling your workflow, you can implement <code>try</code> / <code>finally</code> logic to ensure <code>$.respond()</code> always gets called with some default message. For example:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
      <span class="token comment">// Your code here that might throw an exception or not run</span>
      <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'Whoops, something unexpected happened.'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
      $<span class="token punctuation">.</span><span class="token function">respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
        <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          <span class="token literal-property property">msg</span><span class="token operator">:</span> <span class="token string">"Default response"</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="errors" tabindex="-1"><a class="header-anchor" href="#errors" aria-hidden="true">#</a> Errors</h3>
<p>Occasionally, you may encounter errors when sending requests to your endpoint:</p>
<h4 id="request-entity-too-large" tabindex="-1"><a class="header-anchor" href="#request-entity-too-large" aria-hidden="true">#</a> Request Entity Too Large</h4>
<p>The endpoint will issue a <code>413 Payload Too Large</code> status code when the body of your request exceeds <code>{{$site.themeConfig.PAYLOAD_SIZE_LIMIT}}</code>.</p>
<p>In this case, the request will still appear in the inspector, with information on the error.</p>
<h4 id="api-key-does-not-exist" tabindex="-1"><a class="header-anchor" href="#api-key-does-not-exist" aria-hidden="true">#</a> API key does not exist</h4>
<p>Your API key is the host part of the endpoint, e.g. the <code>eniqtww30717</code> in <code>eniqtww30717.m.pipedream.net</code>. If you attempt to send a request to an endpoint that does not exist, we'll return a <code>404 Not Found</code> error.</p>
<p>We'll also issue a 404 response on workflows with an HTTP trigger that have been <a href="/workflows/managing/#deactivating-workflows" target="_blank" rel="noopener noreferrer">deactivated<ExternalLinkIcon/></a>.</p>
<h4 id="too-many-requests" tabindex="-1"><a class="header-anchor" href="#too-many-requests" aria-hidden="true">#</a> Too Many Requests</h4>
<p>If you send too many requests to your HTTP source within a small period of time, we may issue a <code>429 Too Many Requests</code> response. <a href="/limits/" target="_blank" rel="noopener noreferrer">Review our limits<ExternalLinkIcon/></a> to understand the conditions where you might be throttled.</p>
<p>You can also <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">reach out<ExternalLinkIcon/></a> to inquire about raising this rate limit.</p>
<p>If you control the application sending requests, you should implement <a href="https://medium.com/clover-platform-blog/conquering-api-rate-limiting-dcac5552714d" target="_blank" rel="noopener noreferrer">a backoff strategy<ExternalLinkIcon/></a> to temporarily slow the rate of events.</p>
<h3 id="validating-requests" tabindex="-1"><a class="header-anchor" href="#validating-requests" aria-hidden="true">#</a> Validating requests</h3>
<p>Since you have access to the entire request object, and can issue any HTTP response from a workflow, you can implement custom logic to validate requests using any <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">Node code<ExternalLinkIcon/></a>.</p>
<p>For example, you can <a href="https://pipedream.com/@dylburger/end-a-workflow-early-on-invalid-secret-p_YyCmmK/edit" target="_blank" rel="noopener noreferrer">require requests pass a specific secret in a header<ExternalLinkIcon/></a>. Just copy the workflow and add your secret as the value of the the <strong>Secret</strong> param. Add the rest of your code in steps below this initial one. Requests must contain the secret:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> -H <span class="token string">'X-Pipedream-Secret: abc123'</span> https://myendpoint.m.pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Otherwise, the workflow will <a href="/workflows/steps/code/#end" target="_blank" rel="noopener noreferrer">end early<ExternalLinkIcon/></a>.</p>
<p>Since you can <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">run any Node code<ExternalLinkIcon/></a> in a workflow, you can implement more complex validation. For example, you could require JWT tokens and validate those tokens using the <a href="https://www.npmjs.com/package/jsonwebtoken" target="_blank" rel="noopener noreferrer"><code>jsonwebtoken</code> package<ExternalLinkIcon/></a> at the start of your workflow.</p>
<h2 id="schedule" tabindex="-1"><a class="header-anchor" href="#schedule" aria-hidden="true">#</a> Schedule</h2>
<p>Pipedream allows you to run hosted scheduled jobs — commonly-referred to as a &quot;cron job&quot; — <a href="/pricing" target="_blank" rel="noopener noreferrer">for free<ExternalLinkIcon/></a>.</p>
<p>We call these cron jobs &quot;<a href="/workflows" target="_blank" rel="noopener noreferrer">workflows<ExternalLinkIcon/></a>&quot;. Workflows are just scripts that run on a schedule.</p>
<p>You can write a cron job to:</p>
<ul>
<li><a href="https://pipedream.com/@dylburger/send-an-http-post-request-on-a-schedule-p_KwCYBx/readme" target="_blank" rel="noopener noreferrer">Send an HTTP request to any URL on a schedule<ExternalLinkIcon/></a></li>
<li><a href="https://pipedream.com/@dylburger/541cd2a9ef220f04fefa8f2d440c38d2-p_q6CMjp/readme" target="_blank" rel="noopener noreferrer">Send a scheduled message to email<ExternalLinkIcon/></a>, Slack, Discord, or any messaging app</li>
<li>Pull data from an API, process it, and send the results to Slack, or even data stores like Amazon S3</li>
<li><a href="https://pipedream.com/@dylburger/email-the-top-story-from-hacker-news-every-day-p_JZC28O/readme" target="_blank" rel="noopener noreferrer">Run any Node.js (JavaScript) code, using almost any npm package<ExternalLinkIcon/></a>. <strong>This lets you do almost anything you want on a schedule</strong>.</li>
</ul>
<p>Pipedream manages the servers where these cron jobs run, so you don't have to worry about setting up a server of your own or operating some service just to run code on a schedule. You write the workflow, we take care of the rest.</p>
<h3 id="choosing-a-cron-trigger" tabindex="-1"><a class="header-anchor" href="#choosing-a-cron-trigger" aria-hidden="true">#</a> Choosing a cron trigger</h3>
<p>To create a cron job, create a new workflow and search for the <strong>Schedule</strong> trigger:</p>
<div>
<img alt="Cron Scheduler source" width="400px" src="@source/workflows/steps/triggers/images/schedule.png">
</div>
<p>By default, your cron job will be turned <strong>Off</strong>. <strong>To enable it, select either of the scheduling options</strong>:</p>
<ul>
<li><strong>Every</strong> : run the job every N days, hours, minutes (e.g. every 1 day, every 3 hours).</li>
<li><strong>Cron Expression</strong> : schedule your job using a cron expression. For example, the expression <code>0 0 * * *</code> will run the job every day at midnight. Cron expressions can be tied to any timezone.</li>
</ul>
<h3 id="testing-a-cron-job" tabindex="-1"><a class="header-anchor" href="#testing-a-cron-job" aria-hidden="true">#</a> Testing a cron job</h3>
<p>If you're running a cron job once a day, you probably don't want to wait until the next day's run to test your new code. You can manually run the workflow associated with a cron job at any time by pressing the <strong>Run Now</strong> button.</p>
<h3 id="future-executions-of-your-cron-job" tabindex="-1"><a class="header-anchor" href="#future-executions-of-your-cron-job" aria-hidden="true">#</a> Future executions of your cron job</h3>
<p>You'll see the time your job is scheduled to run next under the <strong>Next Job</strong> section of the <a href="/workflows/events/inspect/" target="_blank" rel="noopener noreferrer">Inspector<ExternalLinkIcon/></a>.</p>
<h3 id="job-history" tabindex="-1"><a class="header-anchor" href="#job-history" aria-hidden="true">#</a> Job History</h3>
<p>You'll see the history of job executions under the <strong>Job History</strong> section of the <a href="/workflows/events/inspect/" target="_blank" rel="noopener noreferrer">Inspector<ExternalLinkIcon/></a>.</p>
<p>Clicking on a specific job shows the execution details for that job — all the logs and observability associated with that run of the workflow.</p>
<h3 id="trigger-a-notification-to-an-external-service-email-slack-etc" tabindex="-1"><a class="header-anchor" href="#trigger-a-notification-to-an-external-service-email-slack-etc" aria-hidden="true">#</a> Trigger a notification to an external service (email, Slack, etc.)</h3>
<p>You can send yourself a notification — for example, an email or a Slack message — at any point in a workflow by using the relevant <a href="/components/actions/" target="_blank" rel="noopener noreferrer">Action<ExternalLinkIcon/></a> or <a href="/destinations/" target="_blank" rel="noopener noreferrer">Destination<ExternalLinkIcon/></a>.</p>
<p>If you'd like to email yourself when a job finishes successfully, you can use the <a href="/destinations/email/" target="_blank" rel="noopener noreferrer">Email Destination<ExternalLinkIcon/></a>. You can send yourself a Slack message using the Slack Action, or trigger an <a href="/destinations/http/" target="_blank" rel="noopener noreferrer">HTTP request<ExternalLinkIcon/></a> to an external service.</p>
<p>You can also <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">write code<ExternalLinkIcon/></a> to trigger any complex notification logic you'd like.</p>
<h3 id="rate-limit" tabindex="-1"><a class="header-anchor" href="#rate-limit" aria-hidden="true">#</a> Rate Limit</h3>
<p>When you're testing cron jobs, you may encounter <strong>Rate Limit Exceeded</strong> errors. Cron jobs can be tested no more than twice a minute. If you encounter this error, wait one minute and try again.</p>
<h3 id="troubleshooting-your-scheduled-jobs" tabindex="-1"><a class="header-anchor" href="#troubleshooting-your-scheduled-jobs" aria-hidden="true">#</a> Troubleshooting your scheduled jobs</h3>
<p>When you run a cron job, you may need to troubleshoot errors or other execution issues. Pipedream offers built-in, step-level logs that show you detailed execution information that should aid troubleshooting.</p>
<p>Any time a cron job runs, you'll see a new execution appear in the <a href="/workflows/events/inspect/" target="_blank" rel="noopener noreferrer">Inspector<ExternalLinkIcon/></a>. This shows you when the cron job ran, how long it took to run, and any errors that might have occurred. <strong>Click on any of these lines in the Inspector to view the details for a given run</strong>.</p>
<p>Code steps show <a href="/workflows/steps/code/#logs" target="_blank" rel="noopener noreferrer">Logs<ExternalLinkIcon/></a> below the step itself. Any time you run <code>console.log()</code> or other functions that print output, you should see the logs appear directly below the step where the code ran.</p>
<p><a href="/components/actions/" target="_blank" rel="noopener noreferrer">Actions<ExternalLinkIcon/></a> and <a href="/destinations/" target="_blank" rel="noopener noreferrer">Destinations<ExternalLinkIcon/></a> also show execution details relevant to the specific Action or Destination. For example, when you use the <a href="/destinations/http/" target="_blank" rel="noopener noreferrer">HTTP Destination<ExternalLinkIcon/></a> to make an HTTP request, you'll see the HTTP request and response details tied to that Destination step:</p>
<h3 id="limitations" tabindex="-1"><a class="header-anchor" href="#limitations" aria-hidden="true">#</a> Limitations</h3>
<p>Cron jobs can be run at most once a minute. Any cron expression that specifies a higher frequency will be rejected.</p>
<p>Cron jobs can run for at most 30 seconds, by default. You can raise this up to 300 seconds by <a href="/workflows/settings/#execution-timeout-limit" target="_blank" rel="noopener noreferrer">setting your workflow's execution timeout<ExternalLinkIcon/></a>. If your workflow runs longer than the configured timeout, you'll see a <code>TIMEOUT</code> error for that run, and will be able to review all logs up until the timeout occurred.</p>
<h2 id="email" tabindex="-1"><a class="header-anchor" href="#email" aria-hidden="true">#</a> Email</h2>
<p>When you select the <strong>Email</strong> trigger:</p>
<div>
<img alt="Email source" width="400px" src="@source/workflows/steps/triggers/images/email.png">
</div>
<p>Pipedream creates an email address specific to your workflow. Any email sent to this address triggers your workflow:</p>
<div>
<img alt="Custom workflow email address" width="400px" src="@source/workflows/steps/triggers/images/email-addr.png">
</div>
<p>As soon as you send an email to the workflow-specific address, Pipedream parses its body, headers, and attachments into a JavaScript object it exposes in the <code>steps.trigger.event</code> variable that you can access within your workflow. This transformation can take a few seconds to perform. Once done, Pipedream will immediately trigger your workflow with the transformed payload.</p>
<p><a href="/workflows/events/#email" target="_blank" rel="noopener noreferrer">Read more about the shape of the email trigger event<ExternalLinkIcon/></a>.</p>
<h3 id="sending-large-emails" tabindex="-1"><a class="header-anchor" href="#sending-large-emails" aria-hidden="true">#</a> Sending large emails</h3>
<p>By default, you can send emails up to <code>{{$site.themeConfig.EMAIL_PAYLOAD_SIZE_LIMIT}}</code> in total size (content, headers, attachments). Emails over this size will be rejected, and you will not see them appear in your workflow.</p>
<p><strong>You can send emails up to <code>30MB</code> in size by sending emails to <code>[YOUR EMAIL ENDPOINT]@upload.pipedream.net</code></strong>. If your workflow-specific email address is <code>endpoint@pipedream.net</code>, your &quot;large email address&quot; is <code>endpoint@upload.pipedream.net</code>.</p>
<p>Emails delivered to this address are uploaded to a private URL you have access to within your workflow, at the variable <code>steps.trigger.event.mail.content_url</code>. You can download and parse the email within your workflow using that URL. This content contains the <em>raw</em> email. Unlike the standard email interface, you must parse this email on your own - see the examples below.</p>
<h4 id="example-download-the-email-using-the-send-http-request-action" tabindex="-1"><a class="header-anchor" href="#example-download-the-email-using-the-send-http-request-action" aria-hidden="true">#</a> Example: Download the email using the Send HTTP Request action</h4>
<p><em>Note: you can only download emails at most <code>{{$site.themeConfig.FUNCTION_PAYLOAD_LIMIT}}</code> in size using this method. Otherwise, you may encounter a <a href="/errors/#function-payload-limit-exceeded" target="_blank" rel="noopener noreferrer">Function Payload Limit Exceeded<ExternalLinkIcon/></a> error.</em></p>
<p>You can download the email using the <strong>Send HTTP Request</strong> action. <a href="https://pipedream.com/@dylburger/example-download-large-email-content-p_A2CQedw/edit" target="_blank" rel="noopener noreferrer"><strong>Copy this workflow to see how this works</strong><ExternalLinkIcon/></a>.</p>
<p>This workflow also parses the contents of the email and exposes it as a JavaScript object using the <a href="https://nodemailer.com/extras/mailparser/" target="_blank" rel="noopener noreferrer"><code>mailparser</code> library<ExternalLinkIcon/></a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> simpleParser <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"mailparser"</span><span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>parsed <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">simpleParser</span><span class="token punctuation">(</span>steps<span class="token punctuation">.</span>send_http_request<span class="token punctuation">.</span>$return_value<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h4 id="example-download-the-email-to-the-tmp-directory-read-it-and-parse-it" tabindex="-1"><a class="header-anchor" href="#example-download-the-email-to-the-tmp-directory-read-it-and-parse-it" aria-hidden="true">#</a> Example: Download the email to the <code>/tmp</code> directory, read it and parse it</h4>
<p><a href="https://pipedream.com/@dylburger/example-download-large-email-content-to-tmp-p_KwC1YOn/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> downloads the email, saving it as a file to the <a href="/workflows/steps/code/nodejs/working-with-files/#the-tmp-directory" target="_blank" rel="noopener noreferrer"><code>/tmp</code> directory<ExternalLinkIcon/></a>. Then it reads the same file (as an example), and parses it using the <a href="https://nodemailer.com/extras/mailparser/" target="_blank" rel="noopener noreferrer"><code>mailparser</code> library<ExternalLinkIcon/></a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> stream <span class="token keyword">from</span> <span class="token string">"stream"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> promisify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"util"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> got <span class="token keyword">from</span> <span class="token string">"got"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> simpleParser <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"mailparser"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> pipeline <span class="token operator">=</span> <span class="token function">promisify</span><span class="token punctuation">(</span>stream<span class="token punctuation">.</span>pipeline<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> <span class="token function">pipeline</span><span class="token punctuation">(</span>
  got<span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>mail<span class="token punctuation">.</span>content_url<span class="token punctuation">)</span><span class="token punctuation">,</span>
  fs<span class="token punctuation">.</span><span class="token function">createWriteStream</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">/tmp/raw_email</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Now read the file and parse its contents into the `parsed` variable</span>
<span class="token comment">// See https://nodemailer.com/extras/mailparser/ for parsing options</span>
<span class="token keyword">const</span> f <span class="token operator">=</span> fs<span class="token punctuation">.</span><span class="token function">readFileSync</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">/tmp/raw_email</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>parsed <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">simpleParser</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><h4 id="how-the-email-is-saved" tabindex="-1"><a class="header-anchor" href="#how-the-email-is-saved" aria-hidden="true">#</a> How the email is saved</h4>
<p>Your email is saved to a Pipedream-owned <a href="https://aws.amazon.com/s3/" target="_blank" rel="noopener noreferrer">Amazon S3 bucket<ExternalLinkIcon/></a>. Pipedream generates a <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html" target="_blank" rel="noopener noreferrer">signed URL<ExternalLinkIcon/></a> that allows you to access to that file for up to 30 minutes. After 30 minutes, the signed URL will be invalidated, and the file will be deleted.</p>
<h3 id="appending-metadata-to-the-incoming-email-address-with-data" tabindex="-1"><a class="header-anchor" href="#appending-metadata-to-the-incoming-email-address-with-data" aria-hidden="true">#</a> Appending metadata to the incoming email address with <code>+data</code></h3>
<p>Pipedream provides a way to append metadata to incoming emails by adding a <code>+</code> sign to the incoming email key, followed by any arbitrary string:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>myemailaddr+test@pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Any emails sent to your workflow-specific email address will resolve to that address, triggering your workflow, no matter the data you add after the <code>+</code> sign. Sending an email to both of these addresses triggers the workflow with the address <code>myemailaddr@pipedream.net</code>:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>myemailaddr+test@pipedream.net
myemailaddr+unsubscribe@pipedream.net
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>This allows you implement conditional logic in your workflow based on the data in that string.</p>
<h2 id="rss" tabindex="-1"><a class="header-anchor" href="#rss" aria-hidden="true">#</a> RSS</h2>
<p>Choose the RSS trigger to watch an RSS feed for new items:</p>
<div>
<img alt="RSS source" width="400px" src="@source/workflows/steps/triggers/images/rss.png">
</div>
<p>This will create an RSS <a href="/event-sources" target="_blank" rel="noopener noreferrer">event source<ExternalLinkIcon/></a> that polls the feed for new items on the schedule you select. Every time a new item is found, your workflow will run.</p>
<h2 id="sdk" tabindex="-1"><a class="header-anchor" href="#sdk" aria-hidden="true">#</a> SDK</h2>
<p>You can trigger workflows using the Pipedream JavaScript and Ruby SDKs, as well.</p>
<p>Select the <strong>SDK</strong> trigger to generate workflow-specific code samples for sending events to your workflow using each of the SDKs.</p>
<h2 id="don-t-see-a-trigger-you-need" tabindex="-1"><a class="header-anchor" href="#don-t-see-a-trigger-you-need" aria-hidden="true">#</a> Don't see a trigger you need?</h2>
<p>If you don't see a trigger you'd like us to support, please <a href="https://pipedream.com/community/" target="_blank" rel="noopener noreferrer">let us know<ExternalLinkIcon/></a>.</p>
<h2 id="multiple-triggers-for-one-workflow" tabindex="-1"><a class="header-anchor" href="#multiple-triggers-for-one-workflow" aria-hidden="true">#</a> Multiple triggers for one workflow</h2>
<p>Want to trigger a workflow on a schedule, but at the same time trigger it on demand with a Slack message? Yes this is possible and yes it's very cool.</p>
<p>Click the top right menu in the trigger itself, and select &quot;Add trigger&quot;.</p>
<p>Now you can add an additional trigger to the same workflow, opening up multiple ways that a workflow can be started.</p>
<div>
<img src="@source/workflows/steps/triggers/images/add-multi-trigger.gif" alt="Add multiple triggers to a workflow" />
</div>
<Footer />
</template>
