export default {
  "primaryLoungeSessionOpen": false,
  "eventSeries": null,
  "stage": {
    "isRecording": false,
    "streamingToMobile": false,
    "streamingActive": false,
    "recordingInstanceReady": true,
    "agenda": {
      "data": {
        "id": "22415",
        "type": "agenda",
        "attributes": {
          "id": 22415,
          "hashid": "Y0fAke",
          "published": null,
          "stageId": 28334,
          "unassignedAssetsOrderingOverride": [
            {
              "order": 0,
              "assetId": "55565",
              "assetType": "DynamicEventAsset"
            },
            {
              "order": 1,
              "assetId": "55566",
              "assetType": "DynamicEventAsset"
            },
            {
              "order": 2,
              "assetId": "233792",
              "assetType": "EventAsset"
            },
            {
              "order": 3,
              "assetId": "55567",
              "assetType": "DynamicEventAsset"
            }
          ],
          "durationsEnabled": false,
          "agendaItems": {
            "data": []
          }
        }
      }
    },
    "id": 28334,
    "hashid": "yVfbBW",
    "eventId": 26778,
    "name": "Test 1",
    "description": "",
    "status": "closed",
    "startTime": "2024-08-16T14:00:00.000Z",
    "endTime": "2024-08-16T15:00:00.000Z",
    "timeZone": "America/Bogota",
    "registerDisplayName": "Register",
    "alreadyRegisteredDisplayName": "Already Registered?",
    "auditoriumDisplayName": "Auditorium",
    "breakoutDisplayName": "Breakout",
    "loungeDisplayName": "Lounge",
    "primaryInfoDisplayName": "Info",
    "secondaryInfoDisplayName": "Secondary Info",
    "staffDisplayName": "staff",
    "speakerDisplayName": "speaker",
    "attendeeDisplayName": "attendee",
    "defaultLoungeViewMode": "card",
    "speakerGreetingText": null,
    "raiseHandEnabled": true,
    "primaryInfoPageUrl": null,
    "primaryInfoImageUrl": null,
    "secondaryInfoPageUrl": null,
    "secondaryInfoImageUrl": null,
    "stageUrl": "/events/mqubWG/stages/yVfbBW",
    "logoUrl": null,
    "iconUrl": null,
    "coverImageUrl": "https://d30kg4wnmf2rd.cloudfront.net/event_assets/mqubWG/cover/people-and-things.gif-b02f1732-d8aa-4db4-a3e9-a460f68f5bc1",
    "publicChatEnabled": true,
    "publicChatSlowModeEnabled": false,
    "qnaEnabled": true,
    "qnaModerationEnabled": false,
    "qnaHiddenNamesEnabled": false,
    "qnaAllHiddenNamesEnabled": false,
    "peopleListEnabled": true,
    "peopleListShowCountEnabled": true,
    "pollsShowVoteCountEnabled": true,
    "directMessagesEnabled": true,
    "videoCallEnabled": true,
    "highChatTrafficExpected": false,
    "breakoutsEnabled": true,
    "assetPreviewPopperEnabled": true,
    "agendaVisibleEnabled": true,
    "closedCaptionsEnabled": true,
    "lowerThirdEnabled": true,
    "speakerBubblesEnabled": true,
    "speakerNamesEnabled": true,
    "overlayFadeEnabled": true,
    "activeLoungeSessionOpen": false,
    "nameTagsAutoDismiss": false,
    "translationServiceUrl": null,
    "primaryColor": "#000000",
    "secondaryColor": "#000000",
    "signedStageId": "eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qZ3pNelE9IiwiZXhwIjpudWxsLCJwdXIiOiJzdGFnZS93cyJ9fQ==--c4097b23f5d8f62e14d448a621b94114d473b5a2abd1f8bd36467d735a6d192b"
  },
  "stages": [
    {
      "isRecording": false,
      "streamingToMobile": false,
      "streamingActive": false,
      "recordingInstanceReady": true,
      "agenda": {
        "data": {
          "id": "22415",
          "type": "agenda",
          "attributes": {
            "id": 22415,
            "hashid": "Y0fAke",
            "published": null,
            "stageId": 28334,
            "unassignedAssetsOrderingOverride": [
              {
                "order": 0,
                "assetId": "55565",
                "assetType": "DynamicEventAsset"
              },
              {
                "order": 1,
                "assetId": "55566",
                "assetType": "DynamicEventAsset"
              },
              {
                "order": 2,
                "assetId": "233792",
                "assetType": "EventAsset"
              },
              {
                "order": 3,
                "assetId": "55567",
                "assetType": "DynamicEventAsset"
              }
            ],
            "durationsEnabled": false,
            "agendaItems": {
              "data": []
            }
          }
        }
      },
      "id": 28334,
      "hashid": "yVfbBW",
      "eventId": 26778,
      "name": "Test 1",
      "description": "",
      "status": "closed",
      "startTime": "2024-08-16T14:00:00.000Z",
      "endTime": "2024-08-16T15:00:00.000Z",
      "timeZone": "America/Bogota",
      "registerDisplayName": "Register",
      "alreadyRegisteredDisplayName": "Already Registered?",
      "auditoriumDisplayName": "Auditorium",
      "breakoutDisplayName": "Breakout",
      "loungeDisplayName": "Lounge",
      "primaryInfoDisplayName": "Info",
      "secondaryInfoDisplayName": "Secondary Info",
      "staffDisplayName": "staff",
      "speakerDisplayName": "speaker",
      "attendeeDisplayName": "attendee",
      "defaultLoungeViewMode": "card",
      "speakerGreetingText": null,
      "raiseHandEnabled": true,
      "primaryInfoPageUrl": null,
      "primaryInfoImageUrl": null,
      "secondaryInfoPageUrl": null,
      "secondaryInfoImageUrl": null,
      "stageUrl": "/events/mqubWG/stages/yVfbBW",
      "logoUrl": null,
      "iconUrl": null,
      "coverImageUrl": "https://d30kg4wnmf2rd.cloudfront.net/event_assets/mqubWG/cover/people-and-things.gif-b02f1732-d8aa-4db4-a3e9-a460f68f5bc1",
      "publicChatEnabled": true,
      "publicChatSlowModeEnabled": false,
      "qnaEnabled": true,
      "qnaModerationEnabled": false,
      "qnaHiddenNamesEnabled": false,
      "qnaAllHiddenNamesEnabled": false,
      "peopleListEnabled": true,
      "peopleListShowCountEnabled": true,
      "pollsShowVoteCountEnabled": true,
      "directMessagesEnabled": true,
      "videoCallEnabled": true,
      "highChatTrafficExpected": false,
      "breakoutsEnabled": true,
      "assetPreviewPopperEnabled": true,
      "agendaVisibleEnabled": true,
      "closedCaptionsEnabled": true,
      "lowerThirdEnabled": true,
      "speakerBubblesEnabled": true,
      "speakerNamesEnabled": true,
      "overlayFadeEnabled": true,
      "activeLoungeSessionOpen": false,
      "nameTagsAutoDismiss": false,
      "translationServiceUrl": null,
      "primaryColor": "#000000",
      "secondaryColor": "#000000",
      "signedStageId": "eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1qZ3pNelE9IiwiZXhwIjpudWxsLCJwdXIiOiJzdGFnZS93cyJ9fQ==--c4097b23f5d8f62e14d448a621b94114d473b5a2abd1f8bd36467d735a6d192b"
    }
  ],
  "restrictedSigninTypes": [
    "google",
    "linkedin",
    "outlook",
    "email"
  ],
  "id": 26778,
  "hashid": "mqubWG",
  "name": "Test 1",
  "description": "",
  "updatedAt": "2024-08-15T22:11:38.060Z",
  "startTime": "2024-08-16T14:00:00.000Z",
  "endTime": "2024-08-16T15:00:00.000Z",
  "timeZone": "America/Bogota",
  "primaryColor": "#000000",
  "secondaryColor": "#000000",
  "logoUrl": null,
  "iconUrl": null,
  "coverImageUrl": "https://d30kg4wnmf2rd.cloudfront.net/event_assets/mqubWG/cover/people-and-things.gif-b02f1732-d8aa-4db4-a3e9-a460f68f5bc1",
  "accessType": "registration_required",
  "registrationsCount": 1,
  "eventUrl": "https://app.experiencewelcome.com/events/mqubWG/stages/yVfbBW",
  "eventLoginUrl": "https://app.experiencewelcome.com/events/mqubWG",
  "loungeUrl": "/events/mqubWG/stages/yVfbBW?initialStageArea=lounge",
  "alwaysShowWelcomeRegForm": false,
  "demoMode": false,
  "quickRegEnabled": true,
  "emailReminder24hPriorEnabled": false,
  "emailReminder1hPriorEnabled": false,
  "emailPostEventEnabled": false,
  "recordingsAvailable": false,
  "recordingsAutoPublish": true,
  "recordingsRegistrationRequired": false,
  "agendaRegistrationRequired": false,
  "registerDisplayName": "Register",
  "alreadyRegisteredDisplayName": "Already Registered?",
  "staffDisplayName": "staff",
  "speakerDisplayName": "speaker",
  "attendeeDisplayName": "attendee",
  "defaultLoungeViewMode": "card",
  "speakerGreetingText": null,
  "breakoutsEnabled": true,
  "speakersCanModerate": false,
  "postEventSurvey": true,
  "noEmailConfirmation": true,
  "clipsCustomLinkText": null,
  "clipsCustomLinkUrl": null,
  "postEventMarketingUrl": null,
  "eventType": "live",
  "primaryStageId": 28334,
  "welcomeRegRequired": false
};
