const DEFAULT_METHOD = "get";
const TEAM_PROVISIONING_OPTION = "Team";
const DEFAULT_MAX_ITEMS = 10;
const DEFAULT_PAGE_LIMIT = 2;

export default {
  DEFAULT_MAX_ITEMS,
  DEFAULT_PAGE_LIMIT,
  DEFAULT_METHOD,
  TEAM_PROVISIONING_OPTION,
};
