export default {
  "id": "Opnel5aKBz",
  "user_id": "Opnel5aKBz",
  "assigned_user_id": "Opnel5aKBz",
  "client_id": "Opnel5aKBz",
  "status_id": "4",
  "number": "INV_101",
  "po_number": "PO-1234",
  "terms": "These are invoice terms",
  "public_notes": "These are some public notes",
  "private_notes": "These are some private notes",
  "footer": "",
  "custom_value1": "2022-10-01",
  "custom_value2": "Something custom",
  "custom_value3": "",
  "custom_value4": "",
  "tax_name1": "",
  "tax_name2": "",
  "tax_rate1": "10.00",
  "tax_rate2": "10.00",
  "tax_name3": "",
  "tax_rate3": "10.00",
  "total_taxes": "10.00",
  "line_items": [
    {
      "quantity": 1,
      "cost": 10,
      "product_key": "Product key",
      "product_cost": 10,
      "notes": "Item notes",
      "discount": 5,
      "is_amount_discount": false,
      "tax_name1": "GST",
      "tax_rate1": 10,
      "tax_name2": "VAT",
      "tax_rate2": 5,
      "tax_name3": "CA Sales Tax",
      "tax_rate3": 3,
      "sort_id": "0",
      "line_total": 10,
      "gross_line_total": 15,
      "tax_amount": 1,
      "date": "2023-03-19T00:00:00Z",
      "custom_value1": "Custom value 1",
      "custom_value2": "Custom value 2",
      "custom_value3": "Custom value 3",
      "custom_value4": "Custom value 4",
      "type_id": "1",
      "tax_id": "1"
    }
  ],
  "invitations": [],
  "amount": "10.00",
  "balance": "10.00",
  "paid_to_date": "10.00",
  "discount": "10.00",
  "partial": "10.00",
  "is_amount_discount": true,
  "is_deleted": true,
  "uses_inclusive_taxes": true,
  "date": "1994-07-30",
  "last_sent_date": "1994-07-30",
  "next_send_date": "1994-07-30",
  "partial_due_date": "1994-07-30",
  "due_date": "1994-07-30",
  "last_viewed": "1434342123",
  "updated_at": "1434342123",
  "created_at": "1434342123",
  "archived_at": "1434342123",
  "custom_surcharge1": "10.00",
  "custom_surcharge2": "10.00",
  "custom_surcharge3": "10.00",
  "custom_surcharge4": "10.00",
  "custom_surcharge_tax1": true,
  "custom_surcharge_tax2": true,
  "custom_surcharge_tax3": true,
  "custom_surcharge_tax4": true,
  "project_id": "Opnel5aKBz",
  "auto_bill_tries": "1",
  "auto_bill_enabled": true,
  "subscription_id": "Opnel5aKBz"
}