export default {
  "archivedAt": 0,
  "archivedInDashboard": false,
  "attachedStylesheets": [],
  "authorName": "Author",
  "categoryId": 3,
  "contentGroupId": "23646627706",
  "contentTypeCategory": 3,
  "created": "2024-06-20T22:37:03.004Z",
  "createdById": "9555737",
  "currentState": "DRAFT",
  "currentlyPublished": false,
  "domain": "",
  "enableGoogleAmpOutputOverride": false,
  "featuredImage": "",
  "featuredImageAltText": "",
  "htmlTitle": "Blog Post",
  "id": "170912644748",
  "language": "en",
  "layoutSections": {},
  "linkRelCanonicalUrl": "",
  "metaDescription": "",
  "name": "Blog Post",
  "publicAccessRules": [],
  "publicAccessRulesEnabled": false,
  "publishDate": "2024-06-20T22:37:02Z",
  "slug": "",
  "state": "DRAFT",
  "tagIds": [],
  "translations": {},
  "updated": "2024-06-20T22:37:23.772Z",
  "updatedById": "9555737",
  "url": "",
  "useFeaturedImage": true,
  "widgetContainers": {},
  "widgets": {}
}