export default {
  "id": "1-leads",
  "type": "leads",
  "isCurrentUserWatching": false,
  "deletedTime": null,
  "name": "Sample Lead",
  "value": {
    "amount": "900.00",
    "currency": "USD",
    "formatted": "$900.00",
  },
  "number": "1",
  "description": "",
  "createdTime": {
    "absoluteLocalizedString": "May 15, 2026",
    "timestamp": 1778874165,
    "value": "May 15, 2026",
  },
  "closedTime": null,
  "dueTime": {
    "absoluteLocalizedString": "June 21, 2026",
    "timestamp": 1782070965,
    "value": "Yesterday",
  },
  "anticipatedClosedTime": {
    "absoluteLocalizedString": "June 21, 2026",
    "timestamp": 1782070965,
    "value": "Yesterday",
  },
  "ownerType": "users",
  "mcfxContactIds": [],
  "status": "open",
  "lastContactedTime": null,
  "pieState": "01",
  "isOverdue": true,
  "overdueTime": {
    "fromNowLocalizedString": "17 hours",
    "timestamp": 1782070965,
    "value": "Yesterday",
  },
  "href": "https://app.nutshell.com/rest/leads/1-leads",
  "confidence": 20,
  "priority": 0,
  "htmlUrl": "https://app.nutshell.com/lead/1",
  "htmlUrlPath": "/lead/1",
  "initials": null,
  "links": {
    "accounts": [
      "1-accounts",
    ],
    "contacts": [
      "1-contacts",
    ],
    "tags": [],
    "sources": [],
    "owner": "1-users",
    "files": [],
    "relatedFiles": [],
    "territory": null,
    "destinations": [],
    "stage": "1-stages",
    "stageset": "1-stagesets",
    "creator": "1-users",
    "products": [],
    "productMaps": [],
    "competitors": [],
    "competitorMaps": [],
    "outcome": null,
    "watchers": [],
    "market": "1-markets",
  },
};
