export default {
  "type": "team_join",
  "user": {
    "id": "U080GULP8SD",
    "team_id": "TS8319547",
    "name": "",
    "deleted": false,
    "color": "9b3b45",
    "real_name": "",
    "tz": "America/New_York",
    "tz_label": "Eastern Standard Time",
    "tz_offset": -18000,
    "profile": {
      "title": "",
      "phone": "",
      "skype": "",
      "real_name": "",
      "real_name_normalized": "",
      "display_name": "",
      "display_name_normalized": "",
      "fields": {},
      "status_text": "",
      "status_emoji": "",
      "status_emoji_display_info": [],
      "status_expiration": 0,
      "avatar_hash": "g96b6e8b38c2",
      "email": "",
      "first_name": "",
      "last_name": "",
      "status_text_canonical": "",
      "team": "TS8319547"
    },
    "is_admin": false,
    "is_owner": false,
    "is_primary_owner": false,
    "is_restricted": false,
    "is_ultra_restricted": false,
    "is_bot": false,
    "is_app_user": false,
    "updated": 1731094476,
    "is_email_confirmed": true,
    "who_can_share_contact_card": "EVERYONE",
    "presence": "away"
  },
  "cache_ts": 1731094476,
  "event_ts": "1731094477.001400",
  "pipedream_msg_id": "pd_1731094479305_v1ic236by8"
}