<template><h1 id="make-http-requests-with-node-js" tabindex="-1"><a class="header-anchor" href="#make-http-requests-with-node-js" aria-hidden="true">#</a> Make HTTP Requests with Node.js</h1>
<p>HTTP requests are fundamental to working with APIs or other web services. You can make HTTP requests to retrieve data from APIs, fetch HTML from websites, or do pretty much anything your web browser can do.</p>
<p><strong>Below, we'll review how to make HTTP requests using Node.js code on Pipedream.</strong></p>
<p>We'll use the <a href="https://github.com/axios/axios" target="_blank" rel="noopener noreferrer"><code>axios</code><ExternalLinkIcon/></a> and <a href="https://github.com/sindresorhus/got" target="_blank" rel="noopener noreferrer"><code>got</code><ExternalLinkIcon/></a> HTTP clients in the examples below, but <a href="/workflows/steps/code/#using-npm-packages" target="_blank" rel="noopener noreferrer">you can use any npm package you'd like<ExternalLinkIcon/></a> on Pipedream, so feel free to experiment with other clients, too.</p>
<p>If you're developing Pipedream components, you may find the <a href="/pipedream-axios" target="_blank" rel="noopener noreferrer"><code>@pipedream/platform</code> version of <code>axios</code><ExternalLinkIcon/></a> helpful for displaying error data clearly in the Pipedream UI.</p>
<p>If you're new to HTTP, see our <a href="https://requestbin.com/blog/working-with-webhooks/#webhooks-glossary-common-terms" target="_blank" rel="noopener noreferrer">glossary of HTTP terms<ExternalLinkIcon/></a> for a helpful introduction.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#basic-axios-usage-notes">Basic axios usage notes</RouterLink></li><li><RouterLink to="#send-a-get-request-to-fetch-data">Send a GET request to fetch data</RouterLink></li><li><RouterLink to="#send-a-post-request-to-submit-data">Send a POST request to submit data</RouterLink></li><li><RouterLink to="#pass-query-string-parameters-to-a-get-request">Pass query string parameters to a GET request</RouterLink></li><li><RouterLink to="#send-a-request-with-http-headers">Send a request with HTTP headers</RouterLink></li><li><RouterLink to="#send-a-request-with-a-secret-or-api-key">Send a request with a secret or API key</RouterLink></li><li><RouterLink to="#send-multiple-http-requests-in-sequence">Send multiple HTTP requests in sequence</RouterLink></li><li><RouterLink to="#send-multiple-http-requests-in-parallel">Send multiple HTTP requests in parallel</RouterLink></li><li><RouterLink to="#send-a-multipart-form-data-request">Send a multipart/form-data request</RouterLink></li><li><RouterLink to="#download-a-file-to-the-tmp-directory">Download a file to the /tmp directory</RouterLink></li><li><RouterLink to="#upload-a-file-from-the-tmp-directory">Upload a file from the /tmp directory</RouterLink></li><li><RouterLink to="#use-an-http-proxy-to-proxy-requests-through-another-host">Use an HTTP proxy to proxy requests through another host</RouterLink></li><li><RouterLink to="#ip-addresses-for-http-requests-made-from-pipedream-workflows">IP addresses for HTTP requests made from Pipedream workflows</RouterLink></li><li><RouterLink to="#stream-a-downloaded-file-directly-to-another-url">Stream a downloaded file directly to another URL</RouterLink></li><li><RouterLink to="#catch-and-process-http-errors">Catch and process HTTP errors</RouterLink></li><li><RouterLink to="#paginating-api-requests">Paginating API requests</RouterLink></li></ul></nav>
<h2 id="basic-axios-usage-notes" tabindex="-1"><a class="header-anchor" href="#basic-axios-usage-notes" aria-hidden="true">#</a> Basic <code>axios</code> usage notes</h2>
<p>To use <code>axios</code> on Pipedream, you'll just need to import the <code>axios</code> npm package:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>You make HTTP requests by passing a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects" target="_blank" rel="noopener noreferrer">JavaScript object<ExternalLinkIcon/></a> to <code>axios</code> that defines the parameters of the request. For example, you'll typically want to define the HTTP method and the URL you're sending data to:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p><code>axios</code> returns a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises" target="_blank" rel="noopener noreferrer">Promise<ExternalLinkIcon/></a>, which is just a fancy way of saying that it makes the HTTP request in the background (asynchronously) while the rest of your code runs. On Pipedream, <a href="/workflows/steps/code/async/" target="_blank" rel="noopener noreferrer">all asynchronous code must be run synchronously<ExternalLinkIcon/></a>, which means you'll need to wait for the HTTP request to finish before moving on to the next step. You do this by adding an <code>await</code> in front of the call to <code>axios</code>.</p>
<p><strong>Putting all of this together, here's how to make a basic HTTP request on Pipedream:</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>The response object <code>resp</code> contains a lot of information about the response: its data, headers, and more. Typically, you just care about the data, which you can access in the <code>data</code> property of the response:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// HTTP response data is in the data property</span>
<span class="token keyword">const</span> data <span class="token operator">=</span> resp<span class="token punctuation">.</span>data<span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>Alternatively, you can access the data using <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring" target="_blank" rel="noopener noreferrer">object destructuring<ExternalLinkIcon/></a>, which is equivalent to the above and preferred in modern JavaScript:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token punctuation">{</span> data <span class="token punctuation">}</span> <span class="token operator">=</span> resp<span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="send-a-get-request-to-fetch-data" tabindex="-1"><a class="header-anchor" href="#send-a-get-request-to-fetch-data" aria-hidden="true">#</a> Send a <code>GET</code> request to fetch data</h2>
<p>Make a request to retrieve Star Wars films from the Star Wars API:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token comment">// Make an HTTP GET request using axios</span>
<span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Retrieve just the data from the response</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> data <span class="token punctuation">}</span> <span class="token operator">=</span> resp<span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p><a href="https://pipedream.com/@dylburger/make-an-http-get-request-to-the-star-wars-api-p_OKC2KA/edit" target="_blank" rel="noopener noreferrer">Copy this workflow to run this example on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="send-a-post-request-to-submit-data" tabindex="-1"><a class="header-anchor" href="#send-a-post-request-to-submit-data" aria-hidden="true">#</a> Send a <code>POST</code> request to submit data</h2>
<p>POST sample JSON to <a href="https://jsonplaceholder.typicode.com/" target="_blank" rel="noopener noreferrer">JSONPlaceholder<ExternalLinkIcon/></a>, a free mock API service:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token comment">// Make an HTTP POST request using axios</span>
<span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://jsonplaceholder.typicode.com/posts</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke"</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Retrieve just the data from the response</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> data <span class="token punctuation">}</span> <span class="token operator">=</span> resp<span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>When you make a <code>POST</code> request, you pass <code>POST</code> as the <code>method</code>, and include the data you'd like to send in the <code>data</code> object.</p>
<p><a href="https://pipedream.com/@dylburger/make-an-http-post-request-using-axios-p_o7CbpY/edit" target="_blank" rel="noopener noreferrer">Copy this workflow to run this example on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="pass-query-string-parameters-to-a-get-request" tabindex="-1"><a class="header-anchor" href="#pass-query-string-parameters-to-a-get-request" aria-hidden="true">#</a> Pass query string parameters to a <code>GET</code> request</h2>
<p>Retrieve fake comment data on a specific post using <a href="https://jsonplaceholder.typicode.com/" target="_blank" rel="noopener noreferrer">JSONPlaceholder<ExternalLinkIcon/></a>, a free mock API service. Here, you fetch data from the <code>/comments</code> resource, retrieving data for a specific post by query string parameter: <code>/comments?postId=1</code>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token comment">// Make an HTTP GET request using axios</span>
<span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://jsonplaceholder.typicode.com/comments</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">params</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">postId</span><span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Retrieve just the data from the response</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> data <span class="token punctuation">}</span> <span class="token operator">=</span> resp<span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>You should pass query string parameters using the <code>params</code> object, like above. When you do, <code>axios</code> automatically <a href="https://www.w3schools.com/tags/ref_urlencode.ASP" target="_blank" rel="noopener noreferrer">URL-encodes<ExternalLinkIcon/></a> the parameters for you, which you'd otherwise have to do manually.</p>
<p><a href="https://pipedream.com/@dylburger/pass-query-string-parameters-to-an-http-get-request-p_xMCOvj/edit" target="_blank" rel="noopener noreferrer">Copy this workflow to run this code on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="send-a-request-with-http-headers" tabindex="-1"><a class="header-anchor" href="#send-a-request-with-http-headers" aria-hidden="true">#</a> Send a request with HTTP headers</h2>
<p>You pass HTTP headers in the <code>headers</code> object of the <code>axios</code> request:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token comment">// Make an HTTP POST request using axios</span>
<span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://jsonplaceholder.typicode.com/posts</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token string-property property">"Content-Type"</span><span class="token operator">:</span> <span class="token string">"application/json"</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke"</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h2 id="send-a-request-with-a-secret-or-api-key" tabindex="-1"><a class="header-anchor" href="#send-a-request-with-a-secret-or-api-key" aria-hidden="true">#</a> Send a request with a secret or API key</h2>
<p>Most APIs require you authenticate HTTP requests with an API key or other token. <strong>Please review the docs for your service to understand how they accept this data.</strong></p>
<p>Here's an example showing an API key passed in an HTTP header:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token comment">// Make an HTTP POST request using axios</span>
<span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://jsonplaceholder.typicode.com/posts</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token string-property property">"Content-Type"</span><span class="token operator">:</span> <span class="token string">"application/json"</span><span class="token punctuation">,</span>
    <span class="token string-property property">"X-API-Key"</span><span class="token operator">:</span> <span class="token string">"123"</span><span class="token punctuation">,</span> <span class="token comment">// API KEY</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke"</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p><a href="https://pipedream.com/@dylburger/send-an-http-request-with-headers-p_q6ClzO/edit" target="_blank" rel="noopener noreferrer">Copy this workflow to run this code on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="send-multiple-http-requests-in-sequence" tabindex="-1"><a class="header-anchor" href="#send-multiple-http-requests-in-sequence" aria-hidden="true">#</a> Send multiple HTTP requests in sequence</h2>
<p>There are many ways to make multiple HTTP requests. This code shows you a simple example that sends the numbers <code>1</code>, <code>2</code>, and <code>3</code> in the body of an HTTP POST request:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// We'll store each response and return them in this array</span>
    <span class="token keyword">const</span> responses <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>

    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> num <span class="token keyword">of</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          num<span class="token punctuation">,</span> <span class="token comment">// Will send the current value of num in the loop</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      responses<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>resp<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">return</span> responses<span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br></div></div><p>This sends each HTTP request <em>in sequence</em>, one after another, and returns an array of response data returned from the URL to which you send the POST request. If you need to make requests <em>in parallel</em>, <a href="#send-multiple-http-requests-in-parallel">see these docs</a>.</p>
<p><a href="https://pipedream.com/@dylburger/iterate-over-a-pipedream-step-export-sending-multiple-http-requests-p_ljCAPN/edit" target="_blank" rel="noopener noreferrer">Copy this workflow<ExternalLinkIcon/></a> and fill in your destination URL to see how this works. <strong>This workflow iterates over the value of a Pipedream <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">step export<ExternalLinkIcon/></a></strong> - data returned from a previous step. Since you often want to iterate over data returned from a Pipedream action or other code step, this is a common use case.</p>
<h2 id="send-multiple-http-requests-in-parallel" tabindex="-1"><a class="header-anchor" href="#send-multiple-http-requests-in-parallel" aria-hidden="true">#</a> Send multiple HTTP requests in parallel</h2>
<p>Sometimes you'll want to make multiple HTTP requests in parallel. If one request doesn't depend on the results of another, this is a nice way to save processing time in a workflow. It can significantly cut down on the time you spend waiting for one request to finish, and for the next to begin.</p>
<p>To make requests in parallel, you can use two techniques. By default, we recommend using <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled" target="_blank" rel="noopener noreferrer"><code>promise.allSettled</code><ExternalLinkIcon/></a>, which makes all HTTP requests and returns data on their success / failure. If an HTTP request fails, all other requests will proceed.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span>
      <span class="token string">"https://www.example.com"</span><span class="token punctuation">,</span>
      <span class="token string">"https://www.cnn.com"</span><span class="token punctuation">,</span>
      <span class="token string">"https://www.espn.com"</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> promises <span class="token operator">=</span> arr<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">url</span><span class="token punctuation">)</span> <span class="token operator">=></span> axios<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> Promise<span class="token punctuation">.</span><span class="token function">allSettled</span><span class="token punctuation">(</span>promises<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>First, we generate an array of <code>axios.get</code> requests (which are all <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise" target="_blank" rel="noopener noreferrer">Promises<ExternalLinkIcon/></a>), and then call <code>Promise.allSettled</code> to run them in parallel.</p>
<p>When you want to stop future requests when <em>one</em> of the requests fails, you can use <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all" target="_blank" rel="noopener noreferrer"><code>Promise.all</code><ExternalLinkIcon/></a>, instead:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span>
      <span class="token string">"https://www.example.com"</span><span class="token punctuation">,</span>
      <span class="token string">"https://www.cnn.com"</span><span class="token punctuation">,</span>
      <span class="token string">"https://www.espn.com"</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> promises <span class="token operator">=</span> arr<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">url</span><span class="token punctuation">)</span> <span class="token operator">=></span> axios<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> Promise<span class="token punctuation">.</span><span class="token function">all</span><span class="token punctuation">(</span>promises<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>The Mozilla docs expand on the difference between these methods, and when you may want to use one or the other:</p>
<blockquote>
<p>The <code>Promise.allSettled()</code> method returns a promise that resolves after all of the given promises have either fulfilled or rejected, with an array of objects that each describes the outcome of each promise.<br /></br >
It is typically used when you have multiple asynchronous tasks that are not dependent on one another to complete successfully, or you'd always like to know the result of each promise.<br /></br >
In comparison, the Promise returned by <code>Promise.all()</code> may be more appropriate if the tasks are dependent on each other / if you'd like to immediately reject upon any of them rejecting.</p>
</blockquote>
<h2 id="send-a-multipart-form-data-request" tabindex="-1"><a class="header-anchor" href="#send-a-multipart-form-data-request" aria-hidden="true">#</a> Send a <code>multipart/form-data</code> request</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> FormData <span class="token keyword">from</span> <span class="token string">"form-data"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> formData <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FormData</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    formData<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"Luke Skywalker"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> headers <span class="token operator">=</span> formData<span class="token punctuation">.</span><span class="token function">getHeaders</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span><span class="token punctuation">,</span>
      headers<span class="token punctuation">,</span>
      <span class="token literal-property property">data</span><span class="token operator">:</span> formData<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><p><a href="https://pipedream.com/@dylburger/send-a-multipart-form-data-request-p_WxCQRyr/edit" target="_blank" rel="noopener noreferrer">Copy this workflow<ExternalLinkIcon/></a> to run this example.</p>
<h2 id="download-a-file-to-the-tmp-directory" tabindex="-1"><a class="header-anchor" href="#download-a-file-to-the-tmp-directory" aria-hidden="true">#</a> Download a file to the <code>/tmp</code> directory</h2>
<p>This example shows you how to download a file to a file in <a href="/workflows/steps/code/nodejs/working-with-files/" target="_blank" rel="noopener noreferrer">the <code>/tmp</code> directory<ExternalLinkIcon/></a>. This can be especially helpful for downloading large files: it streams the file to disk, minimizing the memory the workflow uses when downloading the file.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> stream <span class="token keyword">from</span> <span class="token string">"stream"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> promisify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"util"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> got <span class="token keyword">from</span> <span class="token string">"got"</span><span class="token punctuation">;</span>

<span class="token comment">// DOWNLOAD</span>
<span class="token keyword">const</span> pipeline <span class="token operator">=</span> <span class="token function">promisify</span><span class="token punctuation">(</span>stream<span class="token punctuation">.</span>pipeline<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> <span class="token function">pipeline</span><span class="token punctuation">(</span>
  got<span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span><span class="token string">"https://example.com"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  fs<span class="token punctuation">.</span><span class="token function">createWriteStream</span><span class="token punctuation">(</span><span class="token string">'/tmp/file.html'</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p><a href="https://pipedream.com/@dylburger/download-a-file-from-a-url-to-tmp-p_pWCYA8y/edit" target="_blank" rel="noopener noreferrer">Copy this workflow<ExternalLinkIcon/></a> to run this example.</p>
<h2 id="upload-a-file-from-the-tmp-directory" tabindex="-1"><a class="header-anchor" href="#upload-a-file-from-the-tmp-directory" aria-hidden="true">#</a> Upload a file from the <code>/tmp</code> directory</h2>
<p>This example shows you how to make a <code>multipart/form-data</code> request with a file as a form part. You can store and read any files from <a href="/workflows/steps/code/nodejs/working-with-files/" target="_blank" rel="noopener noreferrer">the <code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<p>This can be especially helpful for uploading large files: it streams the file from disk, minimizing the memory the workflow uses when uploading the file.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> FormData <span class="token keyword">from</span> <span class="token string">"form-data"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> formData <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FormData</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    formData<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token string">"file"</span><span class="token punctuation">,</span> fs<span class="token punctuation">.</span><span class="token function">createReadStream</span><span class="token punctuation">(</span><span class="token string">'/tmp/file.pdf'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> headers <span class="token operator">=</span> formData<span class="token punctuation">.</span><span class="token function">getHeaders</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"POST"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span><span class="token punctuation">,</span>
      headers<span class="token punctuation">,</span>
      <span class="token literal-property property">data</span><span class="token operator">:</span> formData<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><p><a href="https://pipedream.com/@dylburger/stream-a-file-upload-p_6lC1d2Z/edit" target="_blank" rel="noopener noreferrer">Copy this workflow<ExternalLinkIcon/></a> to run this example.</p>
<h2 id="use-an-http-proxy-to-proxy-requests-through-another-host" tabindex="-1"><a class="header-anchor" href="#use-an-http-proxy-to-proxy-requests-through-another-host" aria-hidden="true">#</a> Use an HTTP proxy to proxy requests through another host</h2>
<p>When you make HTTP requests to certain services, they might require you whitelist a set of IP addresses those requests come from. Often, this is to improve the security of the target service.</p>
<p>By default, HTTP requests made from Pipedream can come from a range of IP addresses. <strong>If you need to make requests from a single IP address, you can route traffic through an HTTP proxy</strong>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> httpsProxyAgent <span class="token keyword">from</span> <span class="token string">"https-proxy-agent"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> agent <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">httpsProxyAgent</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">http://</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>user<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>pass<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">@</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>host<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>port<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">httpsAgent</span><span class="token operator">:</span> agent<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>

    <span class="token keyword">return</span> <span class="token keyword">await</span> axios<span class="token punctuation">.</span><span class="token function">request</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p><strong>If you don't have access to an HTTP proxy, and you are a paying Pipedream customer, <a href="https://pipedream.com/support" target="_blank" rel="noopener noreferrer">reach out to our team<ExternalLinkIcon/></a></strong>. We operate a proxy that you can use for HTTP requests made through Pipedream.</p>
<p><a href="https://pipedream.com/@dylburger/make-an-http-request-through-a-proxy-p_ezC6RD/edit" target="_blank" rel="noopener noreferrer">Copy this workflow to run this code on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="ip-addresses-for-http-requests-made-from-pipedream-workflows" tabindex="-1"><a class="header-anchor" href="#ip-addresses-for-http-requests-made-from-pipedream-workflows" aria-hidden="true">#</a> IP addresses for HTTP requests made from Pipedream workflows</h2>
<p>By default, <a href="/workflows/networking/" target="_blank" rel="noopener noreferrer">HTTP requests made from Pipedream can come from a large range of IP addresses<ExternalLinkIcon/></a>. <strong>If you need to restrict the IP addresses HTTP requests come from, you have two options</strong>:</p>
<ul>
<li><a href="#use-an-http-proxy-to-proxy-requests-through-another-host">Use an HTTP proxy to proxy requests</a></li>
<li>If you don't need to access the HTTP response data, you can <a href="/destinations/http/" target="_blank" rel="noopener noreferrer">use <code>$send.http()</code><ExternalLinkIcon/></a> to send requests from a <a href="/destinations/http/#ip-addresses-for-pipedream-http-requests" target="_blank" rel="noopener noreferrer">limited set of IP addresses<ExternalLinkIcon/></a>.</li>
</ul>
<h2 id="stream-a-downloaded-file-directly-to-another-url" tabindex="-1"><a class="header-anchor" href="#stream-a-downloaded-file-directly-to-another-url" aria-hidden="true">#</a> Stream a downloaded file directly to another URL</h2>
<p>Sometimes you need to upload a downloaded file directly to another service, without processing the downloaded file. You could <a href="#download-a-file-to-the-tmp-directory">download the file</a> and then <a href="#upload-a-file-from-the-tmp-directory">upload it</a> to the other URL, but these intermediate steps are unnecessary: you can just stream the download to the other service directly, without saving the file to disk.</p>
<p>This method is especially effective for large files that exceed the <a href="/limits/#disk" target="_blank" rel="noopener noreferrer">limits of the <code>/tmp</code> directory<ExternalLinkIcon/></a>.</p>
<p><a href="https://pipedream.com/@dylburger/stream-download-to-upload-p_5VCLoa1/edit" target="_blank" rel="noopener noreferrer">Copy this workflow<ExternalLinkIcon/></a> or paste this code into a <a href="/workflows/steps/code/#adding-a-code-step" target="_blank" rel="noopener noreferrer">new Node.js code step<ExternalLinkIcon/></a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> stream <span class="token keyword">from</span> <span class="token string">"stream"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> promisify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"util"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> got <span class="token keyword">from</span> <span class="token string">"got"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> pipeline <span class="token operator">=</span> <span class="token function">promisify</span><span class="token punctuation">(</span>stream<span class="token punctuation">.</span>pipeline<span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">await</span> <span class="token function">pipeline</span><span class="token punctuation">(</span>
      got<span class="token punctuation">.</span><span class="token function">stream</span><span class="token punctuation">(</span><span class="token string">"https://example.com"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
      got<span class="token punctuation">.</span>stream<span class="token punctuation">.</span><span class="token function">post</span><span class="token punctuation">(</span><span class="token string">"https://example2.com"</span><span class="token punctuation">)</span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p>You'll want to replace <code>https://example.com</code> with the URL you'd like to stream data from, and replace <code>https://example2.com</code> with the URL you'd like to send the data <em>to</em>. <code>got</code> streams the content directly, downloading the file using a <code>GET</code> request and uploading it as a <code>POST</code> request.</p>
<p>If you need to modify this behavior, <a href="https://github.com/sindresorhus/got#gotstreamurl-options" target="_blank" rel="noopener noreferrer">see the <code>got</code> Stream API<ExternalLinkIcon/></a>.</p>
<h2 id="catch-and-process-http-errors" tabindex="-1"><a class="header-anchor" href="#catch-and-process-http-errors" aria-hidden="true">#</a> Catch and process HTTP errors</h2>
<p>By default, <code>axios</code> throws an error when the HTTP response code is in the 400-500 range (a client or server error). If you'd like to process the error data instead of throwing an error, you can pass a custom function to the <code>validateStatus</code> property:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> axios <span class="token keyword">from</span> <span class="token string">"axios"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://httpstat.us/400"</span><span class="token punctuation">,</span>
      <span class="token function-variable function">validateStatus</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">// will not throw error when axios gets a 400+ status code (the default behavior)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>resp<span class="token punctuation">.</span>status <span class="token operator">>=</span> <span class="token number">400</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>debug <span class="token operator">=</span> resp<span class="token punctuation">;</span>
      <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>resp<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// This can be modified to throw any error you'd like</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> resp<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><p>See <a href="https://github.com/axios/axios#request-config" target="_blank" rel="noopener noreferrer">the <code>axios</code> docs<ExternalLinkIcon/></a> for more details.</p>
<h2 id="paginating-api-requests" tabindex="-1"><a class="header-anchor" href="#paginating-api-requests" aria-hidden="true">#</a> Paginating API requests</h2>
<p>When you fetch data from an API, the API may return records in &quot;pages&quot;. For example, if you're trying to fetch a list of 1,000 records, the API might return those in groups of 100 items.</p>
<p>Different APIs paginate data in different ways. You'll need to consult the docs of your API provider to see how they suggest you paginate through records.</p>
</template>
