export default {
  "id": 999999999,
  "created_at": "2014-12-19T02:02:39.276Z",
  "account_id": 55555,
  "user_id": 88888888,
  "event_type_id": 117,
  "notes": null,
  "ipaddr": "11.111.11.111",
  "actor_user_id": 7777777,
  "assuming_acting_user_id": null,
  "role_id": null,
  "app_id": null,
  "group_id": null,
  "otp_device_id": null,
  "policy_id": null,
  "actor_system": "",
  "custom_message": null,
  "role_name": null,
  "app_name": null,
  "group_name": null,
  "actor_user_name": "Xavier Wong",
  "user_name": "Xavier Wong",
  "policy_name": null,
  "otp_device_name": null,
  "operation_name": null,
  "directory_sync_run_id": 123,
  "directory_id": null,
  "resolution": null,
  "client_id": null,
  "resource_type_id": null,
  "error_description": null,
  "proxy_ip": null,
  "risk_score": null,
  "risk_reasons": null,
  "risk_cookie_id": null,
  "browser_fingerprint": null
}