export default {
  "customerId": "69703923-0f72-421f-a2ab-aeddc1c37f05",
  "customerNumber": "",
  "customerName": "Pipedream",
  "companyName": "Pipedream",
  "contactFirstName": "John",
  "contactLastName": "Doe",
  "emailAddress": "",
  "phoneNumber": "",
  "mobileNumber": "",
  "onHold": false,
  "billingCustomerOnHold": false,
  "streetLine1": "",
  "streetLine2": "",
  "streetSuburb": "",
  "streetPostcode": "",
  "streetState": null,
  "streetCountry": "United States",
  "streetLongitude": null,
  "streetLatitude": null,
  "postalLine1": "",
  "postalLine2": "",
  "postalSuburb": "",
  "postalState": "",
  "postalPostcode": "",
  "postalCountry": "United States",
  "customerType": null,
  "leadSource": null,
  "billingCustomer": null,
  "assignedUser": null,
  "customFields": null
}