export default {
  firstName: {
    type: "string",
    label: "First Name",
    description: "Contact's first name",
    optional: true,
  },
  middleName: {
    type: "string",
    label: "Middle Name",
    description: "Contact's middle name",
    optional: true,
  },
  lastName: {
    type: "string",
    label: "Last Name",
    description: "Contact's last name",
    optional: true,
  },
  email: {
    type: "string",
    label: "Email Address",
    description: "Contact's email address",
    optional: true,
  },
  phoneNumber: {
    type: "string",
    label: "Phone Number",
    description: "Contact's phone number",
    optional: true,
  },
  streetAddress: {
    type: "string",
    label: "Street Address",
    description: "Contact's street address",
    optional: true,
  },
  city: {
    type: "string",
    label: "City",
    description: "Contact's city",
    optional: true,
  },
  state: {
    type: "string",
    label: "State",
    description: "Contact's state/region",
    optional: true,
  },
  zipCode: {
    type: "string",
    label: "Zip Code",
    description: "Contact's zip code",
    optional: true,
  },
  country: {
    type: "string",
    label: "Country",
    description: "Contact's country",
    optional: true,
  },
  biography: {
    type: "string",
    label: "Biography",
    description: "Contact's biography",
    optional: true,
  },
  birthday: {
    type: "string",
    label: "Birthday",
    description: "Contact's birthday, in `YYYY-MM-DD` format",
    optional: true,
  },
  calendarUrl: {
    type: "string",
    label: "Calendar URL",
    description: "Contact's Calendar URL",
    optional: true,
  },
  gender: {
    type: "string",
    label: "Gender",
    description: "Contact's gender",
    options: [
      "male",
      "female",
      "unspecified",
    ],
    optional: true,
  },
  urls: {
    type: "string[]",
    label: "URLs",
    description: "The contact's associated URLs.",
    optional: true,
  },
  additionalFields: {
    type: "object",
    label: "Additional Fields",
    description: "Additional Person resource fields merged into the request body. Each value will be parsed as a JSON object, and keys that have the same name as other props will override them. [See the documentation](https://developers.google.com/people/api/rest/v1/people#resource:-person) for all available fields and their structure. Example value: `{ \"organizations\": [{ \"name\": \"Acme\", \"title\": \"Engineer\" }] }`",
    optional: true,
  },
};
