export default {
  "code": 0,
  "message": "success",
  "event": {
    "event_id": "12312312312312312",
    "event_type": "subscription_created",
    "event_time": "2023-08-02",
    "event_source": "user",
    "payload": {
      "created_time": "2023-08-02T15:28:59-0400",
      "event_id": "123123123123123123",
      "event_type": "subscription_created",
      "data": {
        "subscription": {
          "invoice_notes": "Thanks for your business.",
          "next_shipment_day": "",
          "updated_time": "2023-08-02T15:28:59-0400",
          "notes": [],
          "zcrm_potential_id": "",
          "reference_id": "",
          "trial_extended_count": 0,
          "addons": [],
          "next_billing_at": "2023-09-02",
          "taxes": [
            {
              "tax_amount": 0.06,
              "tax_name": "tax name test (6%)",
              "tax_id": "4352827000000080117"
            }
          ],
          "discount": 0,
          "coupon_duration": "",
          "subscription_id": "123123123123123",
          "last_modified_by_id": "123123123123123",
          "end_of_term": false,
          "product_id": "123123123123123123",
          "plan": {
            "setup_fee_tax_exemption_code": "",
            "discount_amount": 0,
            "setup_fee_tax_percentage": "",
            "plan_code": "planTest",
            "description": "",
            "discount": 0,
            "setup_fee_tax_id": "",
            "total": 1,
            "internal_name": "",
            "setup_fee_tax_name": "",
            "discounts": [],
            "price": 1,
            "setup_fee_tax_type": "",
            "pricing_scheme": "unit",
            "setup_fee": 0,
            "quantity": 1,
            "tax_name": "tax name tesdt",
            "setup_fee_tax_exemption_id": "",
            "item_custom_fields": [],
            "tax_id": "123131231231232",
            "tags": [],
            "unit": "",
            "tax_type": "tax",
            "name": "planTest",
            "tax_percentage": 6,
            "discount_formatted": "$0.00",
            "plan_id": "123123123123123"
          },
          "pricebook_id": "",
          "created_time": "2023-08-02T15:28:59-0400",
          "shipping_interval_unit": "months",
          "exchange_rate": 1,
          "is_inclusive_tax": false,
          "orders_remaining": 0,
          "custom_fields": [],
          "last_shipment_at": "",
          "auto_apply_credits": [],
          "product_name": "Name Test",
          "can_invoice_prorated_amount": true,
          "tax_id": "123123123123123",
          "apply_changes_on": "",
          "activated_at": "2023-08-02",
          "is_metered_billing": false,
          "name": "Name Test-planTest",
          "zcrm_potential_name": "",
          "interval": 1,
          "created_by_id": "12312312312312",
          "discount_percent": 0,
          "crm_owner_id": "",
          "status": "live",
          "items_associated": [],
          "discount_total": 0,
          "billing_mode": "prepaid",
          "is_discount_before_tax": true,
          "channel_reference_id": "",
          "created_at": "2023-08-02",
          "shipping_interval": 1,
          "payment_terms": 2,
          "last_billing_at": "2023-08-02",
          "currency_code": "USD",
          "can_prorate": true,
          "scheduled_cancellation_date": "",
          "expires_at": "",
          "interval_unit": "months",
          "end_of_term_scheduled_date": "",
          "can_add_bank_account": false,
          "custom_field_hash": {},
          "is_advance_invoice_present": false,
          "last_shipment_day": "",
          "tax_rounding": "entity_level",
          "start_date": "2023-08-02",
          "next_shipment_at": "",
          "payment_gateways": [
            {
              "payment_gateway": "test_gateway"
            }
          ],
          "bcy_discount_total": 0,
          "amount": 1.06,
          "remaining_billing_cycles": -1,
          "discount_applied_on_amount": 0,
          "subscription_number": "SUB-00008",
          "currency_symbol": "$",
          "current_term_starts_at": "2023-08-02",
          "reactivate_date": "",
          "tax_name": "tax name test",
          "current_term_ends_at": "2023-09-02",
          "total_orders": 0,
          "discount_type": "item_level",
          "salesperson_name": "",
          "pending_addons": [],
          "salesperson_id": "",
          "child_invoice_id": "12312312312312312",
          "contactpersons": [
            {
              "zcrm_contact_id": "",
              "phone": "+111111111",
              "mobile": "+111111111",
              "last_name": "Last name Test",
              "first_name": "FirstnameTest",
              "email": "customerTest01@customerTest01.com",
              "contactperson_id": "123123123123123123"
            }
          ],
          "auto_collect": false,
          "channel_source": "app",
          "sub_total": 1,
          "tax_percentage": 6,
          "created_date": "2023-08-02",
          "allow_partial_payments": false,
          "is_scheduled_update": false,
          "orders_created": 0,
          "customer_id": "123123123123123123",
          "is_taxable": true,
          "payment_terms_label": "payment terms label test",
          "customer": {
            "channel_reference_id": "",
            "billing_address": {
              "zip": "12312",
              "country": "country test",
              "city": "city test",
              "phone": "",
              "street": "street test",
              "attention": "attention test",
              "street2": "",
              "state": "state test",
              "fax": "213123123"
            },
            "payment_terms": 2,
            "zcrm_contact_id": "",
            "custom_field_hash": {
              "cf_field01_unformatted": "test",
              "cf_field01": "test"
            },
            "shipping_address": {
              "zip": "12345",
              "country": "country test 2",
              "city": "city test 2",
              "phone": "",
              "street": "street test 2",
              "attention": "attention test 2",
              "street2": "",
              "state": "state test 2",
              "fax": "678678"
            },
            "first_name": "FirstnameTest",
            "email": "customerTest01@customerTest01.com",
            "website": "https://websitetest.com",
            "zcrm_account_id": "",
            "custom_fields": [
              {
                "field_id": "1231231231231312",
                "customfield_id": "123123123123123",
                "show_in_store": false,
                "show_in_portal": false,
                "is_active": true,
                "index": 1,
                "label": "field01",
                "show_on_pdf": false,
                "edit_on_portal": false,
                "edit_on_store": false,
                "api_name": "cf_field01",
                "show_in_all_pdf": false,
                "value_formatted": "asdasdas",
                "search_entity": "contact",
                "data_type": "string",
                "placeholder": "cf_field01",
                "value": "asdasdas",
                "is_dependent_field": false
              }
            ],
            "tax_name": "tax name test",
            "last_name": "Last name Test",
            "ip_address": "12.34.567.0",
            "display_name": "customer test 01",
            "channel_customer_id": "",
            "tax_id": "123123123123123",
            "tags": [],
            "company_name": "compay name test",
            "tax_percentage": 6,
            "cf_field01_unformatted": "test",
            "salutation": "Sr.",
            "cf_field01": "test",
            "customer_id": "123123123123123",
            "is_taxable": true,
            "payment_terms_label": "payment terms label test"
          }
        }
      },
      "event_time_formatted": "02 Aug 2023",
      "event_source": "user",
      "event_time": "2023-08-02"
    },
    "webhooks": []
  }
}