<template><h1 id="migrating-from-legacy-actions-to-component-actions" tabindex="-1"><a class="header-anchor" href="#migrating-from-legacy-actions-to-component-actions" aria-hidden="true">#</a> Migrating from Legacy Actions to Component Actions</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#overview">Overview</RouterLink></li><li><RouterLink to="#key-changes">Key Changes</RouterLink></li><li><RouterLink to="#getting-started">Getting Started</RouterLink></li><li><RouterLink to="#migration-example">Migration Example</RouterLink><ul><li><RouterLink to="#legacy-code-example">Legacy Code Example</RouterLink></li><li><RouterLink to="#converting-to-the-component-model">Converting to the Component Model</RouterLink></li><li><RouterLink to="#advanced-using-async-options">Advanced: Using Async Options</RouterLink></li><li><RouterLink to="#publishing-and-using-actions">Publishing and Using Actions</RouterLink></li></ul></li></ul></nav>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>This document is for developers who created legacy actions in <a href="https://pipedream.com/actions" target="_blank" rel="noopener noreferrer">Pipedream's UI<ExternalLinkIcon/></a>. The purpose is to help users migrate legacy actions to Pipedream's new <a href="/components/" target="_blank" rel="noopener noreferrer">component model<ExternalLinkIcon/></a>.</p>
<h2 id="key-changes" tabindex="-1"><a class="header-anchor" href="#key-changes" aria-hidden="true">#</a> Key Changes</h2>
<p><strong>Capture user input via <code>props</code> instead of <code>params</code></strong></p>
<p>The component model does not support <code>params</code>. You need to migrate <code>params</code> references to <a href="/components/api/#props" target="_blank" rel="noopener noreferrer"><code>props</code><ExternalLinkIcon/></a>. Unlike <code>params</code>, <code>props</code> must be explicitly declared and defined prior to using them in code (in the old model, an input form was automatically generated when <code>params</code> were used in code — <code>params</code> were not explicitly declared).</p>
<p><strong>Declare app <code>props</code> to use managed auth</strong></p>
<p>The model for linking an app to legacy actions as well as the syntax for referencing credentials is different with Pipedream components. In the old model, apps were linked to steps in Pipedream's workflow builder UI, and credentials were referenced via the <code>auths</code> object.</p>
<p>When using the component model, apps are defined as <code>props</code> and credentials are referenced as properties of the app. For example, to use managed auth for GitHub, the component <code>props</code> must contain a key (<code>gh</code> in the example below) with an app definition for the value (the app definition is an object):</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token literal-property property">gh</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"app"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">app</span><span class="token operator">:</span> <span class="token string">"github"</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>The component's <code>run()</code> method can then reference the credentials for GitHub via <code>this.gh.$auth.oauth_access_token</code>.</p>
<p><strong>Develop locally and host on GitHub</strong>
Actions are no longer developed in Pipedream's UI. Develop actions locally using your preferred editor, publish to Pipedream via CLI and maintain the code in your own GitHub repo.</p>
<p><strong>Update with a click</strong>
When you publish a new version of an action, you can update actions used in workflows with a click (updating legacy actions in workflows requires action steps to be deleted, re-added and re-configured).</p>
<p><strong>Support for async options</strong>
Async options allow action authors to render a paginated drop down menu allowing users to select from values that are programmatically-generated. The most common use case is to populate the drop down based on results of an API request (e.g., to list Google Sheets in a user's drive).</p>
<p><strong>Simplified discovery</strong>
Actions you publish are now grouped under <strong>My Actions</strong> when adding a step to a workflow. NOTE: this option will appear in the workflow builder <em>after</em> you publish your first action.</p>
<h2 id="getting-started" tabindex="-1"><a class="header-anchor" href="#getting-started" aria-hidden="true">#</a> Getting Started</h2>
<p>Ready to develop your first component action? We recommend starting with our <a href="/components/quickstart/nodejs/actions/" target="_blank" rel="noopener noreferrer">quickstart guide<ExternalLinkIcon/></a>. Then review both our <a href="/components/api/" target="_blank" rel="noopener noreferrer">component API reference<ExternalLinkIcon/></a> and <a href="https://github.com/PipedreamHQ/pipedream/tree/master/components" target="_blank" rel="noopener noreferrer">actions published to Pipedream’s GitHub repo<ExternalLinkIcon/></a>.</p>
<h2 id="migration-example" tabindex="-1"><a class="header-anchor" href="#migration-example" aria-hidden="true">#</a> Migration Example</h2>
<p>Let's walk through an example that migrates code for a legacy action to a Pipedream component.</p>
<h3 id="legacy-code-example" tabindex="-1"><a class="header-anchor" href="#legacy-code-example" aria-hidden="true">#</a> Legacy Code Example</h3>
<p>Following is the code for the legacy action to get a GitHub repo (GitHub was linked to this action via Pipedream's UI, so it's not declared in the code):</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://api.github.com/repos/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>params<span class="token punctuation">.</span>owner<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>params<span class="token punctuation">.</span>repo<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">Authorization</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Bearer </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>auths<span class="token punctuation">.</span>github<span class="token punctuation">.</span>oauth_access_token<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">return</span> <span class="token keyword">await</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@pipedreamhq/platform"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">axios</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> config<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>Also, following is the associated JSON schema that defines metadata for the <code>params</code> inputs:</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">{</span>
  <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"object"</span><span class="token punctuation">,</span>
  <span class="token property">"properties"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"owner"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"string"</span><span class="token punctuation">,</span>
      <span class="token property">"description"</span><span class="token operator">:</span> <span class="token string">"Name of repository owner."</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token property">"repo"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"string"</span><span class="token punctuation">,</span>
      <span class="token property">"description"</span><span class="token operator">:</span> <span class="token string">"Name of repository."</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token property">"required"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token string">"owner"</span><span class="token punctuation">,</span>
    <span class="token string">"repo"</span>
  <span class="token punctuation">]</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h3 id="converting-to-the-component-model" tabindex="-1"><a class="header-anchor" href="#converting-to-the-component-model" aria-hidden="true">#</a> Converting to the Component Model</h3>
<p>To convert the code above to the component model, we need to:</p>
<ol>
<li>Link the GitHub app to the component using <code>props</code> (so we can use Pipedream managed auth for GitHub)</li>
<li>Define <code>props</code> for <code>owner</code> and <code>repo</code> so we can capture user input. The definition for each prop includes the <code>type</code> and <code>description</code> metadata. Additionally, since all the fields are required, we do not need to set the <code>optional</code>  property (set <code>optional</code> to <code>true</code> for optional <code>props</code>). This metadata was previously captured in the JSON schema.</li>
<li>Replace references to <code>params</code> in the <code>run()</code> method. <code>props</code> are bound to <code>this</code> (e.g., <code>this.owner</code> and <code>this.repo</code>).</li>
<li>Update the reference to the GitHub OAuth token from <code>auths.github.oauth_access_token</code> to <code>this.github.$auth.oauth_access_token</code> (note: <code>github</code> in this context references the name of the prop, not the name of the app; if the prop was named <code>gh</code> then the auth would be referenced via <code>this.gh.$auth.oauth_access_token</code>).</li>
<li>Replace the <code>@pipedreamhq/platform</code> npm package with the standard <code>axios</code> package.</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> axios <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"axios"</span><span class="token punctuation">)</span>

module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"action"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Get Repo Example"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">"github_get-repo-example"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">version</span><span class="token operator">:</span> <span class="token string">"0.0.1"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">props</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  	<span class="token literal-property property">github</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  	  <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"app"</span><span class="token punctuation">,</span>
  	  <span class="token literal-property property">app</span><span class="token operator">:</span> <span class="token string">"github"</span><span class="token punctuation">,</span>
  	<span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token literal-property property">owner</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"string"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">description</span><span class="token operator">:</span> <span class="token string">"Name of repository owner."</span><span class="token punctuation">,</span>
  	<span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token literal-property property">repo</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"string"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">description</span><span class="token operator">:</span> <span class="token string">"Name of repository."</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://api.github.com/repos/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>owner<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>repo<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
      <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">Authorization</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Bearer </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>github<span class="token punctuation">.</span>$auth<span class="token punctuation">.</span>oauth_access_token<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>data
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br></div></div><h3 id="advanced-using-async-options" tabindex="-1"><a class="header-anchor" href="#advanced-using-async-options" aria-hidden="true">#</a> Advanced: Using Async Options</h3>
<p>Next, let's take the example one step further. Instead of asking users to enter the owner and repo name, let's use <code>async options</code> so users can select the repo from a drop-down menu. To do that, we'll:</p>
<ol>
<li>Remove the <code>owner</code> and <code>repo</code> props</li>
<li>Add a <code>repoFullName</code> prop that makes a request to <code>https://api.github.com/user/repos</code> to retrieve a list of (paginated) repos</li>
<li>Update the <code>run()</code> function to use the <code>repoFullName</code> prop</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> axios <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"axios"</span><span class="token punctuation">)</span>

module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"action"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Get Repo Example"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">key</span><span class="token operator">:</span> <span class="token string">"github_get-repo-example"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">version</span><span class="token operator">:</span> <span class="token string">"0.0.2"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">props</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  	<span class="token literal-property property">github</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  	  <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"app"</span><span class="token punctuation">,</span>
  	  <span class="token literal-property property">app</span><span class="token operator">:</span> <span class="token string">"github"</span><span class="token punctuation">,</span>
  	<span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token literal-property property">repoFullName</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"string"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">label</span><span class="token operator">:</span> <span class="token string">"Repo"</span><span class="token punctuation">,</span>
      <span class="token keyword">async</span> <span class="token function">options</span><span class="token punctuation">(</span><span class="token parameter">page</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> repos <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
          <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"https://api.github.com/user/repos"</span><span class="token punctuation">,</span>
          <span class="token literal-property property">params</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            page<span class="token punctuation">,</span>
            <span class="token literal-property property">per_page</span><span class="token operator">:</span> <span class="token number">100</span><span class="token punctuation">,</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
          <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">Authorization</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Bearer </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>github<span class="token punctuation">.</span>$auth<span class="token punctuation">.</span>oauth_access_token<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
          <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>data
        <span class="token keyword">return</span> repos<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">repo</span><span class="token punctuation">)</span> <span class="token operator">=></span> repo<span class="token punctuation">.</span>full_name<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> config <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://api.github.com/repos/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>repoFullName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
      <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">Authorization</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Bearer </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">this</span><span class="token punctuation">.</span>github<span class="token punctuation">.</span>$auth<span class="token punctuation">.</span>oauth_access_token<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span>config<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>data
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br></div></div><h3 id="publishing-and-using-actions" tabindex="-1"><a class="header-anchor" href="#publishing-and-using-actions" aria-hidden="true">#</a> Publishing and Using Actions</h3>
<p>In the legacy model, actions were published via Pipedream's UI. To learn how to publish component-based actions using Pipedream's CLI and use them in workflows, review our <a href="/components/quickstart/nodejs/actions/" target="_blank" rel="noopener noreferrer">quickstart guide<ExternalLinkIcon/></a>. To contribute actions to the Pipedream registry, review our <a href="/components/guidelines/" target="_blank" rel="noopener noreferrer">guidelines<ExternalLinkIcon/></a>.</p>
</template>
