<template><h1 id="email" tabindex="-1"><a class="header-anchor" href="#email" aria-hidden="true">#</a> Email</h1>
<p>The Email Destination allows you send an email to <em>yourself</em> — the email address tied to the account you signed up with — at any step of a workflow. You can also email <a href="#emailing-workflow-collaborators">any collaborators on your workflow</a>.</p>
<p>You can use this to email yourself when you receive a specific event, for example when a user signs up on your app. You can send yourself an email when a cron job finishes running, or when a job fails. Anywhere you need an email notification, you can use the Email Destination!</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#adding-an-email-destination">Adding an Email Destination</RouterLink><ul><li><RouterLink to="#adding-an-email-action">Adding an Email Action</RouterLink></li><li><RouterLink to="#using-send-email-in-workflows">Using $.send.email in workflows</RouterLink></li><li><RouterLink to="#using-send-email-in-component-actions">Using $.send.email in component actions</RouterLink></li></ul></li><li><RouterLink to="#emailing-workflow-collaborators">Emailing workflow collaborators</RouterLink></li><li><RouterLink to="#delivery-details">Delivery details</RouterLink></li></ul></nav>
<h2 id="adding-an-email-destination" tabindex="-1"><a class="header-anchor" href="#adding-an-email-destination" aria-hidden="true">#</a> Adding an Email Destination</h2>
<h3 id="adding-an-email-action" tabindex="-1"><a class="header-anchor" href="#adding-an-email-action" aria-hidden="true">#</a> Adding an Email Action</h3>
<p>First, <a href="/workflows/steps/actions/#adding-a-new-action" target="_blank" rel="noopener noreferrer">add a new Action<ExternalLinkIcon/></a>, then select the <strong>Send Yourself an Email</strong> Action. You can modify the <strong>Subject</strong> and the message (either <strong>Plain Text</strong> or <strong>HTML</strong>) however you want.</p>
<h3 id="using-send-email-in-workflows" tabindex="-1"><a class="header-anchor" href="#using-send-email-in-workflows" aria-hidden="true">#</a> Using <code>$.send.email</code> in workflows</h3>
<p>You can send data to an Email Destination in <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">Node.js code steps<ExternalLinkIcon/></a>, too, using the <code>$.send.email()</code> function. <strong>This allows you to send emails to yourself programmatically, if you need more control than actions provide</strong>.</p>
<p><code>$.send.email()</code> takes the same parameters as the corresponding action:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">email</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">subject</span><span class="token operator">:</span> <span class="token string">"Your subject"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">text</span><span class="token operator">:</span> <span class="token string">"Plain text email body"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">html</span><span class="token operator">:</span> <span class="token string">"HTML email body"</span>
      <span class="token literal-property property">include_collaborators</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>The <code>html</code> property is optional. If you include both the <code>text</code> and <code>html</code> properties, email clients that support HTML will prefer that over the plaintext version.</p>
<p>Like with any <code>$.send</code> function, you can use <code>$.send.email()</code> conditionally, within a loop, or anywhere you'd use a function normally in Node.js.</p>
<h3 id="using-send-email-in-component-actions" tabindex="-1"><a class="header-anchor" href="#using-send-email-in-component-actions" aria-hidden="true">#</a> Using <code>$.send.email</code> in component actions</h3>
<p>If you're authoring a <a href="/components/actions/" target="_blank" rel="noopener noreferrer">component action<ExternalLinkIcon/></a>, you can deliver data to an email destination using <code>$.send.email</code>.</p>
<p><code>$.send.email</code> functions the same as <a href="#using-send-email-in-workflows"><code>$.send.email</code> in workflow code steps</a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">email</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">subject</span><span class="token operator">:</span> <span class="token string">"Your subject"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">text</span><span class="token operator">:</span> <span class="token string">"Plain text email body"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">html</span><span class="token operator">:</span> <span class="token string">"HTML email body"</span>
      <span class="token literal-property property">include_collaborators</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="emailing-workflow-collaborators" tabindex="-1"><a class="header-anchor" href="#emailing-workflow-collaborators" aria-hidden="true">#</a> Emailing workflow collaborators</h2>
<p>The <code>include_collaborators</code> flag defaults to <code>false</code>. When set to <code>true</code>, <code>$.send.email()</code> will email any <a href="/workflows/settings/#collaborators" target="_blank" rel="noopener noreferrer">collaborators<ExternalLinkIcon/></a> you've added to your workflow.</p>
<h2 id="delivery-details" tabindex="-1"><a class="header-anchor" href="#delivery-details" aria-hidden="true">#</a> Delivery details</h2>
<p>All emails come from <strong>notifications@pipedream.com</strong>.</p>
<Footer />
</template>
