const PROJECT_TYPES = [
  "android",
  "angular",
  "asgi",
  "aspnet",
  "aspnet_core",
  "backbone",
  "bottle",
  "cocos2dx",
  "connect",
  "django",
  "dotnet",
  "dotnet_desktop",
  "dotnet_mvc",
  "electron",
  "ember",
  "eventmachine",
  "expo",
  "express",
  "flask",
  "flutter",
  "gin",
  "go",
  "go_net_http",
  "heroku",
  "ios",
  "java",
  "java_desktop",
  "js",
  "koa",
  "laravel",
  "lumen",
  "magento",
  "martini",
  "minidump",
  "ndk",
  "negroni",
  "nintendo_switch",
  "node",
  "osx",
  "other_desktop",
  "other_mobile",
  "other_tv",
  "php",
  "python",
  "rack",
  "rails",
  "react",
  "reactnative",
  "restify",
  "revel",
  "ruby",
  "silex",
  "sinatra",
  "spring",
  "symfony",
  "tornado",
  "tvos",
  "unity",
  "unrealengine",
  "vue",
  "watchos",
  "webapi",
  "wordpress",
  "wpf",
  "wsgi",
  "other",
];

const ERROR_SEVERITIES = [
  {
    value: "info",
    label: "Info - Can be used in manual Bugsnag.notify calls",
  },
  {
    value: "warning",
    label: "Warning - The default severity when Bugsnag.notify is called manually",
  },
  {
    value: "error",
    label: "Error - The default severity for uncaught exceptions and crashes",
  },
];

export default {
  PROJECT_TYPES,
  ERROR_SEVERITIES,
};
