const WRITE_DISPOSITION = {
  WRITE_TRUNCATE: "WRITE_TRUNCATE",
  WRITE_APPEND: "WRITE_APPEND",
};

const DATA_SOURCE_ID = {
  SCHEDULED_QUERY: "scheduled_query",
};

export default {
  WRITE_DISPOSITION,
  DATA_SOURCE_ID,
};
