const DEFAULT_DOMAIN = "e2b.app";
const CODE_INTERPRETER_PORT = 49999;
const TEMPLATE_ID = "code-interpreter-v1";
const DEFAULT_SANDBOX_TIMEOUT_SECONDS = 300;

export default {
  DEFAULT_DOMAIN,
  CODE_INTERPRETER_PORT,
  TEMPLATE_ID,
  DEFAULT_SANDBOX_TIMEOUT_SECONDS,
};
