export default  {
  "kind": "t3",
  "data": {
   "approved_at_utc": null,
   "subreddit": "aww",
   "selftext": "",
   "author_fullname": "t2_b8ft4fsj",
   "saved": false,
   "mod_reason_title": null,
   "gilded": 0,
   "clicked": false,
   "title": "Teach a cat to fish...",
   "link_flair_richtext": [],
   "subreddit_name_prefixed": "r/aww",
   "hidden": false,
   "pwls": 6,
   "link_flair_css_class": "lc",
   "downs": 0,
   "thumbnail_height": 140,
   "top_awarded_type": null,
   "hide_score": true,
   "name": "t3_15n8kon",
   "quarantine": false,
   "link_flair_text_color": "dark",
   "upvote_ratio": 0.99,
   "author_flair_background_color": null,
   "subreddit_type": "public",
   "ups": 130,
   "total_awards_received": 0,
   "media_embed": {},
   "thumbnail_width": 140,
   "author_flair_template_id": null,
   "is_original_content": false,
   "user_reports": [],
   "secure_media": null,
   "is_reddit_media_domain": true,
   "is_meta": false,
   "category": null,
   "secure_media_embed": {},
   "link_flair_text": null,
   "can_mod_post": false,
   "score": 130,
   "approved_by": null,
   "is_created_from_ads_ui": false,
   "author_premium": false,
   "thumbnail": "https://b.thumbs.redditmedia.com/89ZOWRWYzCBqwmFqzgfuOkn1GgPY5EkcnSNviecPbVQ.jpg",
   "edited": false,
   "author_flair_css_class": null,
   "author_flair_richtext": [],
   "gildings": {},
   "post_hint": "image",
   "content_categories": null,
   "is_self": false,
   "mod_note": null,
   "created": 1691663173,
   "link_flair_type": "text",
   "wls": 6,
   "removed_by_category": null,
   "banned_by": null,
   "author_flair_type": "text",
   "domain": "i.redd.it",
   "allow_live_comments": false,
   "selftext_html": null,
   "likes": null,
   "suggested_sort": null,
   "banned_at_utc": null,
   "url_overridden_by_dest": "https://i.redd.it/07fi3jiqe9hb1.jpg",
   "view_count": null,
   "archived": false,
   "no_follow": false,
   "is_crosspostable": true,
   "pinned": false,
   "over_18": false,
   "preview": {
    "images": [
     {
      "source": {
       "url": "https://preview.redd.it/07fi3jiqe9hb1.jpg?auto=webp&amp;s=30bd05bbe720b00735257e87a33dff0d219b025f",
       "width": 800,
       "height": 977
      },
      "resolutions": [
       {
        "url": "https://preview.redd.it/07fi3jiqe9hb1.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=b44e312f862d9fc102db2462f1dad1d824bf8954",
        "width": 108,
        "height": 131
       },
       {
        "url": "https://preview.redd.it/07fi3jiqe9hb1.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=c8b09d5887238e2798f7909d73ac180d199cc418",
        "width": 216,
        "height": 263
       },
       {
        "url": "https://preview.redd.it/07fi3jiqe9hb1.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=32586cfbe348de1cf287035b64ba633fa27702cd",
        "width": 320,
        "height": 390
       },
       {
        "url": "https://preview.redd.it/07fi3jiqe9hb1.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=ea3d1a07c4102991f8d998aae4b5afdb214d6425",
        "width": 640,
        "height": 781
       }
      ],
      "variants": {},
      "id": "WvICtMA4eRBhM3wVJQrhBZBNwQXotdFpiWjCLyEQ8QI"
     }
    ],
    "enabled": true
   },
   "all_awardings": [],
   "awarders": [],
   "media_only": false,
   "can_gild": true,
   "spoiler": false,
   "locked": false,
   "author_flair_text": null,
   "treatment_tags": [],
   "visited": false,
   "removed_by": null,
   "num_reports": null,
   "distinguished": null,
   "subreddit_id": "t5_2qh1o",
   "author_is_blocked": false,
   "mod_reason_by": null,
   "removal_reason": null,
   "link_flair_background_color": "",
   "id": "15n8kon",
   "is_robot_indexable": true,
   "report_reasons": null,
   "author": "Detterius",
   "discussion_type": null,
   "num_comments": 8,
   "send_replies": true,
   "whitelist_status": "all_ads",
   "contest_mode": false,
   "mod_reports": [],
   "author_patreon_flair": false,
   "author_flair_text_color": null,
   "permalink": "/r/aww/comments/15n8kon/teach_a_cat_to_fish/",
   "parent_whitelist_status": "all_ads",
   "stickied": false,
   "url": "https://i.redd.it/07fi3jiqe9hb1.jpg",
   "subreddit_subscribers": 34398617,
   "created_utc": 1691663173,
   "num_crossposts": 0,
   "media": null,
   "is_video": false
  }
 }