export default {
   "customer":{
      "id":123,
      "createdAt":"2025-09-17T20:23:06+00:00",
      "updatedAt":"2025-09-17T20:23:06+00:00",
      "isConfirmed":false,
      "type":"registered",
      "lastOnlineAt":null,
      "remoteIp":false,
      "userAgent":false,
      "referralId":false,
      "gender":false,
      "birthDate":false,
      "nationalId":"",
      "email":"customer@email.com",
      "firstname":"John",
      "middlename":"",
      "lastname":"Doe",
      "phone":"",
      "mobile":"",
      "isCompany":false,
      "companyName":"",
      "companyCoCNumber":"",
      "companyVatNumber":"",
      "addressBillingName":"John Doe",
      "addressBillingStreet":"",
      "addressBillingStreet2":"",
      "addressBillingNumber":"",
      "addressBillingExtension":"",
      "addressBillingZipcode":"",
      "addressBillingCity":"",
      "addressBillingRegion":"",
      "addressBillingCountry":{
         "id":150,
         "code":"nl",
         "code3":"nld",
         "title":"Netherlands, The"
      },
      "addressShippingCompany":false,
      "addressShippingName":"John Doe",
      "addressShippingStreet":"",
      "addressShippingStreet2":"",
      "addressShippingNumber":"",
      "addressShippingExtension":"",
      "addressShippingZipcode":"",
      "addressShippingCity":"",
      "addressShippingRegion":"",
      "addressShippingCountry":{
         "id":150,
         "code":"nl",
         "code3":"nld",
         "title":"Netherlands, The"
      },
      "memo":"",
      "doNotifyRegistered":false,
      "doNotifyConfirmed":false,
      "doNotifyPassword":false,
      "groups":{
         "resource":{
            "id":false,
            "url":"groups\/customers?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/groups\/customers.json?customer=123"
         }
      },
      "invoices":{
         "resource":{
            "id":false,
            "url":"invoices?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/invoices.json?customer=123"
         }
      },
      "language":false,
      "orders":{
         "resource":{
            "id":false,
            "url":"orders?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/orders.json?customer=123"
         }
      },
      "reviews":{
         "resource":{
            "id":false,
            "url":"reviews?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/reviews.json?customer=123"
         }
      },
      "shipments":{
         "resource":{
            "id":false,
            "url":"shipments?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/shipments.json?customer=123"
         }
      },
      "tickets":{
         "resource":{
            "id":false,
            "url":"tickets?customer=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/tickets.json?customer=123"
         }
      },
      "metafields":{
         "resource":{
            "id":false,
            "url":"customers\/123\/metafields",
            "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123\/metafields.json"
         }
      },
      "login":{
         "resource":{
            "id":false,
            "url":"customers\/123\/login",
            "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123\/login.json"
         }
      }
   }
}