export const MEDIA_FIELD_OPTIONS = [
  "duration_ms",
  "height",
  "media_key",
  "preview_image_url",
  "type",
  "url",
  "width",
  "public_metrics",
  "non_public_metrics",
  "organic_metrics",
  "promoted_metrics",
  "alt_text",
  "variants",
];

export const POLL_FIELD_OPTIONS = [
  "duration_minutes",
  "end_datetime",
  "id",
  "options",
  "voting_status",
];

export const TWEET_FIELD_OPTIONS = [
  "attachments",
  "author_id",
  "context_annotations",
  "conversation_id",
  "created_at",
  "edit_controls",
  "entities",
  "geo",
  "id",
  "in_reply_to_user_id",
  "lang",
  "non_public_metrics",
  "public_metrics",
  "organic_metrics",
  "promoted_metrics",
  "possibly_sensitive",
  "referenced_tweets",
  "reply_settings",
  "source",
  "text",
  "withheld",
];

export const USER_FIELD_OPTIONS = [
  "created_at",
  "description",
  "entities",
  "id",
  "location",
  "name",
  "pinned_tweet_id",
  "profile_image_url",
  "protected",
  "public_metrics",
  "url",
  "username",
  "verified",
  "verified_type",
  "withheld",
];
