export default {
  "ach_gateway": null,
  "address1": "342 Amber St",
  "address2": null,
  "attention_to": "Sarah Fisher",
  "autopay": false,
  "autopay_delay_days": null,
  "avalara_entity_use_code": null,
  "avalara_exemption_number": null,
  "cc_gateway": null,
  "chase": true,
  "chasing_cadence": null,
  "city": "Hill Valley",
  "country": "US",
  "created_at": 1415222128,
  "credit_hold": false,
  "credit_limit": null,
  "currency": null,
  "email": "billing@acmecorp.com",
  "id": 15444,
  "language": null,
  "metadata": [],
  "name": "Acme",
  "next_chase_step": null,
  "notes": null,
  "number": "CUST-0001",
  "object": "customer",
  "owner": null,
  "parent_customer": null,
  "payment_source": null,
  "payment_terms": "NET 30",
  "phone": "(820) 297-2983",
  "postal_code": "94523",
  "sign_up_page": null,
  "sign_up_url": null,
  "state": "CA",
  "statement_pdf_url": "https://dundermifflin.invoiced.com/statements/t3NmhUomra3g3ueSNnbtUgrr/pdf",
  "tax_id": "893-934835",
  "taxable": true,
  "taxes": [],
  "type": "company",
  "updated_at": 1415222128
}