export default {
  "action_id": "d6658a5a-6154-4802-b1f3-953a67e492c6",
  "creator": {
    "id": "c3aa4fae-bbad-4abf-8550-29c683012796",
    "firstname": "SafetyCulture",
    "lastname": "User"
  },
  "title": "Test Action",
  "description": "This is a test action generated by the SafetyCulture API.",
  "created_at": "2023-09-13T17:25:59.187Z",
  "modified_at": "2023-09-13T17:25:59.187Z",
  "completed_at": null,
  "due_at": "2023-09-20T17:25:41.635Z",
  "priority_id": "16ba4717-adc9-4d48-bf7c-044cfe0d2727",
  "status_id": "17e793a1-26a3-4ecd-99ca-f38ecc6eaa2e",
  "site": null,
  "collaborators": [
    {
      "assigned_role": "COLLABORATOR_ROLE_ASSIGNEE",
      "collaborator_type": "COLLABORATOR_TYPE_USER",
      "user": {
        "id": "c3aa4fae-bbad-4abf-8550-29c683012796",
        "firstname": "SafetyCulture",
        "lastname": "User"
      }
    }
  ],
  "reference": null,
  "status": {
    "status_id": "17e793a1-26a3-4ecd-99ca-f38ecc6eaa2e",
    "label": "To Do"
  }
}