export default {
  "id": "358",
  "share_type": 3,
  "uid_owner": "test@test.com",
  "displayname_owner": "test@test.com",
  "permissions": 17,
  "can_edit": true,
  "can_delete": true,
  "stime": 1711420687,
  "parent": null,
  "expiration": null,
  "token": "xLoyTbxpaR6fP8J",
  "uid_file_owner": "test@test.com",
  "note": "",
  "label": "",
  "displayname_file_owner": "test@test.com",
  "path": "/Nextcloud intro.mp4",
  "item_type": "file",
  "item_permissions": 27,
  "mimetype": "video/mp4",
  "has_preview": false,
  "storage_id": "home::test@test.com",
  "storage": 1069,
  "item_source": 457256,
  "file_source": 457256,
  "file_parent": 457235,
  "file_target": "/Nextcloud intro.mp4",
  "item_size": 3963036,
  "item_mtime": 1711418296,
  "share_with": null,
  "share_with_displayname": "(Shared link)",
  "password": null,
  "send_password_by_talk": false,
  "url": "https://kim.nl.tab.digital/s/xLoyTbxpaR6fP8J",
  "mail_send": 0,
  "hide_download": 0,
  "attributes": null
}