export default {
  ASYNC_OPTIONS_LIMIT: 20,
  DEPLOY_LIMIT: 25,
  PAGINATION_LIMIT: 50,
  SORT_CRITERIA: {
    CREATED: "CREATED",
    START_DATE: "START_DATE",
    SEPARATION_DATE: "SEPARATION_DATE",
  },
};
