const BASE_URL = "https://generativelanguage.googleapis.com";
const VERSION_PATH = "/v1beta";

const MODEL_METHODS = {
  GENERATE_CONTENT: "generateContent",
  EMBED_CONTENT: "embedContent",
};

const HARM_CATEGORIES = {
  HARASSMENT: "HARM_CATEGORY_HARASSMENT",
  HATE_SPEECH: "HARM_CATEGORY_HATE_SPEECH",
  SEXUALLY_EXPLICIT: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
  DANGEROUS: "HARM_CATEGORY_DANGEROUS_CONTENT",
  CIVIC: "HARM_CATEGORY_CIVIC_INTEGRITY",
};

const BLOCK_THRESHOLDS = {
  BLOCK_NONE: "BLOCK_NONE",
  BLOCK_ONLY_HIGH: "BLOCK_ONLY_HIGH",
  BLOCK_MEDIUM_AND_ABOVE: "BLOCK_MEDIUM_AND_ABOVE",
  BLOCK_LOW_AND_ABOVE: "BLOCK_LOW_AND_ABOVE",
};

const TASK_TYPE = {
  SEMANTIC_SIMILARITY: "SEMANTIC_SIMILARITY",
  CLASSIFICATION: "CLASSIFICATION",
  CLUSTERING: "CLUSTERING",
  RETRIEVAL_DOCUMENT: "RETRIEVAL_DOCUMENT",
  RETRIEVAL_QUERY: "RETRIEVAL_QUERY",
  QUESTION_ANSWERING: "QUESTION_ANSWERING",
  FACT_VERIFICATION: "FACT_VERIFICATION",
  CODE_RETRIEVAL_QUERY: "CODE_RETRIEVAL_QUERY",
};

export default {
  BASE_URL,
  VERSION_PATH,
  MODEL_METHODS,
  TASK_TYPE,
  HARM_CATEGORIES,
  BLOCK_THRESHOLDS,
};
