export default {
  "id": "123123",
  "lead_status": {
    "value": 123123,
    "label": "Pending Approval",
  },
  "assigned_to": null,
  "tags": [],
  "lead_source": "Desktop Manual",
  "creator": {
    "value": 123123,
    "label": "John Doe",
  },
  "lead_date_updated": true,
  "lead_date_created": true,
  "last_exported_date": true,
  "matched_lead": false,
  "lists": [],
  "number_of_stacked_lists": 0,
  "campaign_status": {
    "value": "Mail Sequence Not Started",
    "label": "Mail Sequence Not Started",
  },
  "mail_sequence": {
    "value": 0,
    "label": "No Mail Sequence",
  },
  "mail_design": {
    "value": 0,
    "label": "No Mail Design",
  },
  "total_times_mail_was_sent": 0,
  "last_mail_sent_date": null,
  "primary_image": null,
  "image_info": null,
  "did_skip_trace": false,
  "skip_trace_successful": false,
  "mailing_addresses": [],
  "number_of_mailing_addresses": 1,
  "phone_numbers": [],
  "number_of_phone_numbers": 0,
  "email_addresses": [],
  "number_of_email_addresses": 0,
  "last_updated_from_data_provider": true,
  "sale_price": null,
  "sale_date": null,
  "estimated_value": null,
  "calculated_total_value": null,
  "calculated_improvement_value": null,
  "calculated_land_value": null,
  "tax_market_improvements_percent": null,
  "mortgage_amount": null,
  "lender_name": null,
  "mortgage_date": null,
  "mortgage_term": null,
  "mortgage_due_date": null,
  "second_mortgage_amount": null,
  "equity_percent": null,
  "preforeclosure_status": "",
  "mortgage_interest_rate": null,
  "mortgage_financing_type": null,
  "mortgage_loan_type": null,
  "second_mortgage_interest_rate": null,
  "second_mortgage_financing_type": null,
  "second_mortgage_loan_type": null,
  "market_status": {
    "label": "Off Market",
    "value": "Off Market",
  },
  "initial_listing_date": null,
  "days_on_market": null,
  "current_listing_price": null,
  "highest_list_price": null,
  "lowest_list_price": null,
  "mls_sold_price": null,
  "mls_sold_date": null,
  "mls_data_updated_date": null,
  "building_square_feet": null,
  "units_count": null,
  "lot_acreage": null,
  "lot_square_feet": null,
  "total_baths": null,
  "total_bedrooms": null,
  "year_built": "",
  "property_flags": [
    {
      "value": "off_market",
      "label": "Off Market",
    },
    {
      "value": "absentee_owner",
      "label": "Absentee Owner",
    },
    {
      "value": "free_and_clear",
      "label": "Free And Clear",
    },
  ],
  "property_type": {
    "value": "Other",
    "label": "Other",
  },
  "property_use_standardized": {
    "value": null,
    "label": null,
  },
  "parcel_id": null,
  "geographic_features": {
    "value": null,
    "label": null,
  },
  "flood_zone": {
    "value": null,
    "label": null,
  },
  "construction_type": {
    "value": null,
    "label": null,
  },
  "property_address_full": "123 1th Ave, City, ST 11111",
  "property_address_line_1": "123 1th Ave",
  "property_address_line_2": "",
  "property_address_city": "City",
  "property_address_county": {
    "value": null,
    "label": null,
  },
  "property_address_state": "ST",
  "property_address_zipcode": "11111",
  "property_latitude": "0",
  "property_longitude": "0",
  "property_latlng": "0,0",
  "owner_type": "Owner Not Found",
  "unique_owner_type": "Owner Not Found",
  "has_usps_address": true,
  "is_vacant": false,
  "owner_has_multiple_properties": false,
  "house_flippers": false,
  "owner_name": "",
  "owner_first_name": "",
  "owner_last_name": "",
  "owner_2_name": "",
  "owner_2_first_name": "",
  "owner_2_last_name": "",
  "owner_address_full": "123 1th Ave, City, ST 11111",
  "owner_address_line_1": "123 1th Ave",
  "owner_address_line_2": "",
  "owner_address_city": "City",
  "owner_address_state": "ST",
  "owner_address_zipcode": "11111",
  "active_lien": false,
};
