export default {
  id: 1,
  accommodation_management_fee: 20.0,
  accomodation_total: 362.45,
  arrival_time: "15:00:00",
  automated_messages_enabled: true,
  automated_reviews_enabled: false,
  booked_at: "2021-11-26T11:19:59Z",
  channel: "airbnb_official",
  check_in: "2021-12-03",
  check_out: "2021-12-05",
  cleaning_fee: 40.0,
  cleaning_management_fee: 4.0,
  commission: 14.0,
  currency: "GBP",
  departure_time: "11:00:00",
  direct: false,
  external_reservation_id: "ABC2DEF3YZ",
  guest_email: "jon.snow@castleblack.com",
  guest_name: "Jon Snow",
  guest_phone: "+44797978889991",
  manually_moved: false,
  mutli_unit_id: null,
  mutli_unit_name: null,
  note: "Bringing the dragon",
  number_of_guests: 3,
  number_of_nights: 7,
  other_charges: null,
  preferred_guest_name: "King of the North",
  property_id: 2,
  property_name: "Mi Casa",
  source: null,
  status: "confirmed",
  timestamp: "2021-11-26T11:20:00Z",
  total_management_fee: 48,
  total_payout: 388
}