<template><h1 id="running-asynchronous-code-in-node-js" tabindex="-1"><a class="header-anchor" href="#running-asynchronous-code-in-node-js" aria-hidden="true">#</a> Running asynchronous code in Node.js</h1>
<p>If you're not familiar with asynchronous programming concepts like <a href="https://developer.mozilla.org/en-US/docs/Glossary/Callback_function" target="_blank" rel="noopener noreferrer">callback functions<ExternalLinkIcon/></a> or <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises" target="_blank" rel="noopener noreferrer">Promises<ExternalLinkIcon/></a>, see <a href="https://eloquentjavascript.net/11_async.html" target="_blank" rel="noopener noreferrer">this overview<ExternalLinkIcon/></a>.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#the-problem">The problem</RouterLink></li><li><RouterLink to="#solutions">Solutions</RouterLink><ul><li><RouterLink to="#await-all-promises">await all Promises</RouterLink></li><li><RouterLink to="#wrap-callback-functions-in-a-promise">Wrap callback functions in a Promise</RouterLink></li><li><RouterLink to="#other-solutions">Other solutions</RouterLink></li></ul></li><li><RouterLink to="#false-positives">False positives</RouterLink></li></ul></nav>
<h2 id="the-problem" tabindex="-1"><a class="header-anchor" href="#the-problem" aria-hidden="true">#</a> The problem</h2>
<p><strong>Any asynchronous code within a Node.js code step must complete before the next step runs</strong>. This ensures future steps have access to its data. If Pipedream detects that code is still running by the time the step completes, you'll see the following warning below the code step:</p>
<blockquote>
<p><strong>This step was still trying to run code when the step ended. Make sure you await all Promises, or promisify callback functions.</strong></p>
</blockquote>
<p>As the warning notes, this often arises from one of two issues:</p>
<ul>
<li>You forgot to <code>await</code> a Promise. <a href="#await-all-promises">All Promises must be awaited</a> within a step so they resolve before the step finishes.</li>
<li>You tried to run a callback function. Since callback functions run asynchronously, they typically will not finish before the step ends. <a href="#wrap-callback-functions-in-a-promise">You can wrap your function in a Promise</a> to make sure it resolves before the step finishes.</li>
</ul>
<h2 id="solutions" tabindex="-1"><a class="header-anchor" href="#solutions" aria-hidden="true">#</a> Solutions</h2>
<h3 id="await-all-promises" tabindex="-1"><a class="header-anchor" href="#await-all-promises" aria-hidden="true">#</a> <code>await</code> all Promises</h3>
<p>Most Node.js packages that run async code return Promises as the result of method calls. For example, <a href="https://docs.pipedream.com/workflows/steps/code/nodejs/http-requests/#basic-axios-usage-notes" target="_blank" rel="noopener noreferrer"><code>axios</code><ExternalLinkIcon/></a> is an HTTP client. If you make an HTTP request like this in a Pipedream code step:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>It won't send the HTTP request, since <strong><code>axios</code> returns a Promise</strong>. Instead, add an <code>await</code> in front of the call to <code>axios</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">axios</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">method</span><span class="token operator">:</span> <span class="token string">"GET"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://swapi.co/api/films/</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>In short, always do this:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> res <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">runAsyncCode</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>instead of this:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// This code may not finish by the time the workflow finishes</span>
<span class="token function">runAsyncCode</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="wrap-callback-functions-in-a-promise" tabindex="-1"><a class="header-anchor" href="#wrap-callback-functions-in-a-promise" aria-hidden="true">#</a> Wrap callback functions in a Promise</h3>
<p>Before support for Promises was widespread, <a href="https://developer.mozilla.org/en-US/docs/Glossary/Callback_function" target="_blank" rel="noopener noreferrer">callback functions<ExternalLinkIcon/></a> were a popular way to run some code asynchronously, after some operation was completed. For example, <a href="https://pdfkit.org/" target="_blank" rel="noopener noreferrer">PDFKit<ExternalLinkIcon/></a> lets you pass a callback function that runs when certain events fire, like when the PDF has been finalized:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> PDFDocument <span class="token keyword">from</span> <span class="token string">"pdfkit"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>

<span class="token keyword">let</span> doc <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">PDFDocument</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">size</span><span class="token operator">:</span> <span class="token string">"A4"</span><span class="token punctuation">,</span> <span class="token literal-property property">margin</span><span class="token operator">:</span> <span class="token number">50</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>fileName <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">tmp/test.pdf</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
<span class="token keyword">let</span> file <span class="token operator">=</span> fs<span class="token punctuation">.</span><span class="token function">createWriteStream</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>fileName<span class="token punctuation">)</span><span class="token punctuation">;</span>
doc<span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span>file<span class="token punctuation">)</span><span class="token punctuation">;</span>
doc<span class="token punctuation">.</span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string">"Hello world!"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Finalize PDF file</span>
doc<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
file<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"finish"</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>fs<span class="token punctuation">.</span><span class="token function">statSync</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>fileName<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p>This is the callback function:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>fs<span class="token punctuation">.</span><span class="token function">statSync</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>fileName<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>and <strong>it will not run</strong>. By running a callback function in this way, we're saying that we want the function to be run asynchronously. But on Pipedream, this code must finish by the time the step ends. <strong>You can wrap this callback function in a Promise to make sure that happens</strong>. Instead of running:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>file<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"finish"</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>fs<span class="token punctuation">.</span><span class="token function">statSync</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>fileName<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>run:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Wait for PDF to finalize</span>
<span class="token keyword">await</span> <span class="token keyword">new</span> <span class="token class-name">Promise</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">resolve</span><span class="token punctuation">)</span> <span class="token operator">=></span> file<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"finish"</span><span class="token punctuation">,</span> resolve<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Once done, get stats</span>
<span class="token keyword">const</span> stats <span class="token operator">=</span> fs<span class="token punctuation">.</span><span class="token function">statSync</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>filePath<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>This is called &quot;<a href="https://javascript.info/promisify" target="_blank" rel="noopener noreferrer">promisification<ExternalLinkIcon/></a>&quot;.</p>
<p>You can often promisify a function in one line using Node.js' <a href="https://2ality.com/2017/05/util-promisify.html" target="_blank" rel="noopener noreferrer"><code>util.promisify</code> function<ExternalLinkIcon/></a>.</p>
<h3 id="other-solutions" tabindex="-1"><a class="header-anchor" href="#other-solutions" aria-hidden="true">#</a> Other solutions</h3>
<p>If a specific library doesn't support Promises, you can often find an equivalent library that does. For example, many older HTTP clients like <code>request</code> didn't support Promises natively, but the community <a href="https://www.npmjs.com/package/request#promises--asyncawait" target="_blank" rel="noopener noreferrer">published packages that wrapped it with a Promise-based interface<ExternalLinkIcon/></a> (note: <code>request</code> has been deprecated, this is just an example).</p>
<h2 id="false-positives" tabindex="-1"><a class="header-anchor" href="#false-positives" aria-hidden="true">#</a> False positives</h2>
<p>This warning can also be a false positive. If you're successfully awaiting all Promises, Pipedream could be throwing the warning in error. If you observe this, please <a href="https://github.com/PipedreamHQ/pipedream/issues/new?assignees=&amp;labels=bug&amp;template=bug_report.md&amp;title=%5BBUG%5D+" target="_blank" rel="noopener noreferrer">file a bug<ExternalLinkIcon/></a>.</p>
<p>Packages that make HTTP requests or read data from disk (for example) fail to resolve Promises at the right time, or at all. This means that Pipedream is correctly detecting that code is still running, but there's also no issue - the library successfully ran, but just failed to resolve the Promise. You can safely ignore the error if all relevant operations are truly succeeding.</p>
</template>
