<template><h1 id="managing" tabindex="-1"><a class="header-anchor" href="#managing" aria-hidden="true">#</a> Managing</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#workflow-settings">Workflow Settings</RouterLink><ul><li><RouterLink to="#errors">Errors</RouterLink></li><li><RouterLink to="#execution-controls">Execution Controls</RouterLink></li><li><RouterLink to="#current-checkpoint-values">Current checkpoint values</RouterLink></li><li><RouterLink to="#attachments">Attachments</RouterLink></li></ul></li><li><RouterLink to="#copying-workflows">Copying Workflows</RouterLink></li><li><RouterLink to="#environment-variables">Environment Variables</RouterLink><ul><li><RouterLink to="#creating-updating-environment-variables">Creating, updating environment variables</RouterLink></li><li><RouterLink to="#referencing-environment-variables-in-code">Referencing environment variables in code</RouterLink></li><li><RouterLink to="#referencing-environment-variables-in-actions">Referencing environment variables in actions</RouterLink></li><li><RouterLink to="#copying-workflows-that-use-environment-variables">Copying workflows that use environment variables</RouterLink></li><li><RouterLink to="#limits-1">Limits</RouterLink></li></ul></li></ul></nav>
<h2 id="workflow-settings" tabindex="-1"><a class="header-anchor" href="#workflow-settings" aria-hidden="true">#</a> Workflow Settings</h2>
<p>You can control workflow-specific settings in the <strong>Settings</strong> header, just above your workflow's code.</p>
<div>
<img alt="Workflow settings" src="@source/workflows/managing/images/workflow-settings.png">
</div>
<h3 id="errors" tabindex="-1"><a class="header-anchor" href="#errors" aria-hidden="true">#</a> Errors</h3>
<p>By default, any errors raised in a workflow are sent to the <strong>Global Error Workflow</strong>. This workflow sends you an email with the details of this error, once per error, per workflow, per 24-hour period.</p>
<p>But the Global Error Workflow is just another workflow, and lives in your account. So you can modify it however you'd like. For example, you can send errors to Slack, or send critical issues to Pagerduty, or log all errors to a table in the <a href="/destinations/sql/" target="_blank" rel="noopener noreferrer">SQL service<ExternalLinkIcon/></a> for later analysis.</p>
<h3 id="execution-controls" tabindex="-1"><a class="header-anchor" href="#execution-controls" aria-hidden="true">#</a> Execution Controls</h3>
<h4 id="execution-timeout-limit" tabindex="-1"><a class="header-anchor" href="#execution-timeout-limit" aria-hidden="true">#</a> Execution Timeout Limit</h4>
<p>Workflows have a default <a href="/limits/#time-per-execution" target="_blank" rel="noopener noreferrer">execution limit<ExternalLinkIcon/></a>, which defines the time workflows can run for a single invocation until they're timed out.</p>
<p>If your workflow times out, and needs to run for longer than the <a href="/limits/#time-per-execution" target="_blank" rel="noopener noreferrer">default limit<ExternalLinkIcon/></a>, you can change that limit here.</p>
<h4 id="memory" tabindex="-1"><a class="header-anchor" href="#memory" aria-hidden="true">#</a> Memory</h4>
<p>By default, workflows run with <code>{{$site.themeConfig.MEMORY_LIMIT}}</code> of memory. If you're processing a lot of data in memory, you might need to raise that limit. Here, you can increase the memory of your workflow up to <code>{{$site.themeConfig.MEMORY_ABSOLUTE_LIMIT}}</code>.</p>
<p><strong>Pipedream charges invocations proportional to your memory configuration</strong>. When you modify your memory settings, Pipedream will show you the number of invocations you'll be charged per execution. <a href="/pricing/#how-does-workflow-memory-affect-billable-invocations" target="_blank" rel="noopener noreferrer">Read more here<ExternalLinkIcon/></a>.</p>
<h4 id="concurrency-and-throttling" tabindex="-1"><a class="header-anchor" href="#concurrency-and-throttling" aria-hidden="true">#</a> Concurrency and Throttling</h4>
<p><a href="/workflows/events/concurrency-and-throttling/" target="_blank" rel="noopener noreferrer">Manage the concurrency and rate<ExternalLinkIcon/></a> at which events from a source trigger your workflow code.</p>
<h3 id="current-checkpoint-values" tabindex="-1"><a class="header-anchor" href="#current-checkpoint-values" aria-hidden="true">#</a> Current checkpoint values</h3>
<p>If you're using <a href="/workflows/steps/code/#workflow-level-state-checkpoint" target="_blank" rel="noopener noreferrer"><code>$checkpoint</code><ExternalLinkIcon/></a> or <a href="/workflows/steps/code/#step-level-state-this-checkpoint" target="_blank" rel="noopener noreferrer"><code>this.$checkpoint</code><ExternalLinkIcon/></a> to manage state in your workflow, you can view their values here. You can also modify the values or clear the whole contents of a given checkpoint.</p>
<h3 id="attachments" tabindex="-1"><a class="header-anchor" href="#attachments" aria-hidden="true">#</a> Attachments</h3>
<p>Sometimes, you'll need to reference static files in your workflow, like a CSV. Files uploaded in the <strong>Attachments</strong> section can be referenced in your workflow using the <code>$attachments</code> object.</p>
<p>For example, if you upload a file named <code>test.csv</code>, Pipedream will expose the <em>file path</em> of the uploaded file at <code>$attachments[&quot;test.csv&quot;]</code>. You can read the contents of the file using <code>fs.readFileSync</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> fileData <span class="token operator">=</span> fs<span class="token punctuation">.</span><span class="token function">readFileSync</span><span class="token punctuation">(</span>$attachments<span class="token punctuation">[</span><span class="token string">"test.csv"</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>fileData<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><div>
<img alt="File attachment data" src="@source/workflows/managing/images/attachment-file-data.png">
</div>
<h4 id="limits" tabindex="-1"><a class="header-anchor" href="#limits" aria-hidden="true">#</a> Limits</h4>
<p>Each attachment is limited to <code>10MB</code> in size. The total size of all attachments within a single workflow cannot exceed <code>200MB</code>.</p>
<h2 id="copying-workflows" tabindex="-1"><a class="header-anchor" href="#copying-workflows" aria-hidden="true">#</a> Copying Workflows</h2>
<p>When you find a public workflow that you want to use, you <strong>Copy</strong> it into your own account. You own the copy, and can run and modify that copy however you'd like.</p>
<p>When you find the workflow that you'd like to copy, click the big green <strong>Copy</strong> button near the top-right corner of the workflow.</p>
<p>If you're not signed into your Pipedream account, or haven't yet signed up, you'll be prompted to.</p>
<h2 id="environment-variables" tabindex="-1"><a class="header-anchor" href="#environment-variables" aria-hidden="true">#</a> Environment Variables</h2>
<p><strong>Environment variables</strong> enable you to separate secrets and other data from your code.</p>
<p>You should not include API keys or other sensitive data directly in your workflow's code. This is especially important if you <a href="/public-workflows/" target="_blank" rel="noopener noreferrer">make your workflow public<ExternalLinkIcon/></a>, since anyone would be able to see your API key in plain sight. By referencing the value of an environment variable, instead, your workflow includes a reference to that variable — <code>process.env.API_KEY</code> — instead of the API key itself.</p>
<p>Environment variables are defined at the account-level, and can be referenced in <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">workflow code<ExternalLinkIcon/></a> or <a href="/workflows/steps/params/" target="_blank" rel="noopener noreferrer">step params<ExternalLinkIcon/></a>.</p>
<h3 id="creating-updating-environment-variables" tabindex="-1"><a class="header-anchor" href="#creating-updating-environment-variables" aria-hidden="true">#</a> Creating, updating environment variables</h3>
<p>Environment variables are managed at the account-level. You can access your environment variables at <a href="https://pipedream.com/settings/env-vars">{{$site.themeConfig.PIPEDREAM_BASE_URL}}/settings/env-vars</a>.</p>
<p>To add an environment variable, click the <strong>New Environment Variable</strong> button.</p>
<p>To edit an environment variable, click the <strong>Reveal / Edit</strong> button next to a specific variable.</p>
<p>Updates to environment variables will be made available to your workflows as soon as the save operation is complete — typically a few seconds after you click <strong>Save</strong>. If you update the value of an environment variable in the UI, your workflow should automatically use that new value where it's referenced.</p>
<h3 id="referencing-environment-variables-in-code" tabindex="-1"><a class="header-anchor" href="#referencing-environment-variables-in-code" aria-hidden="true">#</a> Referencing environment variables in code</h3>
<p>You can reference the value of any environment variable using the object <a href="https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_process_env" target="_blank" rel="noopener noreferrer"><code>process.env</code><ExternalLinkIcon/></a>. This object contains environment variables as key-value pairs.</p>
<p>For example, let's say you have an environment variable named <code>API_KEY</code>. You can reference its value using <code>process.env.API_KEY</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> url <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">http://yourapi.com/endpoint/?api_key=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>process<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">API_KEY</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Variable names are case-sensitive. Use the name you defined in your Environment settings in the app when referencing your variable in <code>process.env</code>.</p>
<p>Referencing an environment variable that doesn't exist returns the value <code>undefined</code> in Node.js. For example, if you try to reference <code>process.env.API_KEY</code> without first defining the <code>API_KEY</code> variable in your environment settings, it will return the value <code>undefined</code>.</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>Logging the value of any environment variables — for example, using <code>console.log</code> — will include that value in the logs associated with the cell. Please keep this in mind and take care not to print the values of sensitive secrets.</p>
</div>
<h3 id="referencing-environment-variables-in-actions" tabindex="-1"><a class="header-anchor" href="#referencing-environment-variables-in-actions" aria-hidden="true">#</a> Referencing environment variables in actions</h3>
<p><a href="/components/actions/" target="_blank" rel="noopener noreferrer">Actions<ExternalLinkIcon/></a> are prebuilt code steps that provide a form for passing <a href="/workflows/steps/params/" target="_blank" rel="noopener noreferrer">params<ExternalLinkIcon/></a> as input.</p>
<p>You can reference the value of environment variables using <code v-pre>{{process.env.YOUR_ENV_VAR}}</code>. You'll see a list of your environment variables in the <a href="/workflows/steps/params/#use-the-object-explorer" target="_blank" rel="noopener noreferrer">object explorer<ExternalLinkIcon/></a>:</p>
<div>
<img alt="Environment variables in the object explorer" width="300px" src="@source/workflows/managing/images/env-vars-object-explorer.png">
</div>
<h3 id="copying-workflows-that-use-environment-variables" tabindex="-1"><a class="header-anchor" href="#copying-workflows-that-use-environment-variables" aria-hidden="true">#</a> Copying workflows that use environment variables</h3>
<p>Your environment variables are made available to any running workflow. <strong>If you copy a public workflow that uses an environment variable, make sure you review the code to see what environment variables it's using</strong>.</p>
<p>Reviewing the code ensures you have the necessary variables defined for the workflow to run correctly, and makes sure the original workflow author isn't reading variables that you don't need for the workflow to function. You can always modify the code for the workflow after copying to remove these variables, or change their names.</p>
<h3 id="limits-1" tabindex="-1"><a class="header-anchor" href="#limits-1" aria-hidden="true">#</a> Limits</h3>
<p>Currently, <strong>environment variables are only exposed in Pipedream workflows, <a href="https://github.com/PipedreamHQ/pipedream/issues/583" target="_blank" rel="noopener noreferrer">not event sources<ExternalLinkIcon/></a></strong>.</p>
<p>The value of any environment variable may be no longer than <code>64KB</code>.</p>
<p>The names of environment variables must start with a letter or underscore. Pipedream also reserves environment variables that start with <code>PIPEDREAM_</code> for internal use. You cannot create an environment variable that begins with that prefix.</p>
<Footer />
</template>
