import enrichlayer from "../../enrichlayer.app.mjs";

export default {
  key: "enrichlayer-search-people",
  name: "Search People",
  description: "Search for people who meet a set of criteria. Returns up to 10,000,000 results. Cost: 3 credits per profile URL returned. [See the docs](https://enrichlayer.com/docs).",
  version: "0.0.1",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: true,
  },
  props: {
    enrichlayer,
    country: {
      propDefinition: [
        enrichlayer,
        "country",
      ],
      description: "Filter people located in this country (Alpha-2 ISO 3166 code).",
    },
    firstName: {
      type: "string",
      label: "First Name",
      description: "Filter by first name using boolean search.",
      optional: true,
    },
    lastName: {
      type: "string",
      label: "Last Name",
      description: "Filter by last name using boolean search.",
      optional: true,
    },
    currentRoleTitle: {
      type: "string",
      label: "Current Role Title",
      description: "Filter by current job title using boolean search (e.g., `CEO || Founder`).",
      optional: true,
    },
    pastRoleTitle: {
      type: "string",
      label: "Past Role Title",
      description: "Filter by past job title using boolean search.",
      optional: true,
    },
    currentCompanyName: {
      type: "string",
      label: "Current Company Name",
      description: "Filter by current company name using boolean search.",
      optional: true,
    },
    pastCompanyName: {
      type: "string",
      label: "Past Company Name",
      description: "Filter by past company name using boolean search.",
      optional: true,
    },
    currentCompanyProfileUrl: {
      type: "string",
      label: "Current Company Profile URL",
      description: "Filter by current company profile URL.",
      optional: true,
    },
    pastCompanyProfileUrl: {
      type: "string",
      label: "Past Company Profile URL",
      description: "Filter by past company profile URL.",
      optional: true,
    },
    city: {
      type: "string",
      label: "City",
      description: "Filter by city. Wrap names with spaces in double quotes.",
      optional: true,
    },
    region: {
      type: "string",
      label: "Region",
      description: "Filter by region/state/province.",
      optional: true,
    },
    headline: {
      type: "string",
      label: "Headline",
      description: "Filter by headline using boolean search.",
      optional: true,
    },
    summary: {
      type: "string",
      label: "Summary",
      description: "Filter by summary using boolean search.",
      optional: true,
    },
    educationFieldOfStudy: {
      type: "string",
      label: "Education Field of Study",
      description: "Filter by field of study.",
      optional: true,
    },
    educationDegreeName: {
      type: "string",
      label: "Education Degree Name",
      description: "Filter by degree name (e.g., `MBA`).",
      optional: true,
    },
    educationSchoolName: {
      type: "string",
      label: "Education School Name",
      description: "Filter by school name.",
      optional: true,
    },
    educationSchoolProfileUrl: {
      type: "string",
      label: "Education School Profile URL",
      description: "Filter by school profile URL.",
      optional: true,
    },
    currentRoleBefore: {
      type: "string",
      label: "Current Role Started Before",
      description: "Filter people who started their current role before this date (ISO 8601).",
      optional: true,
    },
    currentRoleAfter: {
      type: "string",
      label: "Current Role Started After",
      description: "Filter people who started their current role after this date (ISO 8601).",
      optional: true,
    },
    currentJobDescription: {
      type: "string",
      label: "Current Job Description",
      description: "Filter by current job description.",
      optional: true,
    },
    pastJobDescription: {
      type: "string",
      label: "Past Job Description",
      description: "Filter by past job description.",
      optional: true,
    },
    industries: {
      type: "string",
      label: "Industries",
      description: "Filter by person's inferred industry.",
      optional: true,
    },
    interests: {
      type: "string",
      label: "Interests",
      description: "Filter by interests.",
      optional: true,
    },
    skills: {
      type: "string",
      label: "Skills",
      description: "Filter by skills using boolean search. Cannot combine with Skills All In List.",
      optional: true,
    },
    skillsAllInList: {
      type: "string",
      label: "Skills All In List",
      description: "Comma-separated list of skills. Returns profiles with ALL listed skills. Cannot combine with Skills.",
      optional: true,
    },
    languages: {
      type: "string",
      label: "Languages",
      description: "Filter by language.",
      optional: true,
    },
    groups: {
      type: "string",
      label: "Groups",
      description: "Filter by group membership.",
      optional: true,
    },
    currentCompanyCountry: {
      type: "string",
      label: "Current Company Country",
      description: "Filter by current company's country (Alpha-2 ISO 3166 code).",
      optional: true,
    },
    currentCompanyRegion: {
      type: "string",
      label: "Current Company Region",
      description: "Filter by current company's region.",
      optional: true,
    },
    currentCompanyCity: {
      type: "string",
      label: "Current Company City",
      description: "Filter by current company's city.",
      optional: true,
    },
    currentCompanyType: {
      type: "string",
      label: "Current Company Type",
      description: "Filter by current company type.",
      optional: true,
      options: [
        "EDUCATIONAL",
        "GOVERNMENT_AGENCY",
        "NON_PROFIT",
        "PARTNERSHIP",
        "PRIVATELY_HELD",
        "PUBLIC_COMPANY",
        "SELF_EMPLOYED",
        "SELF_OWNED",
      ],
    },
    currentCompanyIndustry: {
      type: "string",
      label: "Current Company Industry",
      description: "Filter by current company's industry (includes inferred).",
      optional: true,
    },
    currentCompanyPrimaryIndustry: {
      type: "string",
      label: "Current Company Primary Industry",
      description: "Filter by current company's primary industry.",
      optional: true,
    },
    currentCompanySpecialities: {
      type: "string",
      label: "Current Company Specialities",
      description: "Filter by current company's specialities.",
      optional: true,
    },
    currentCompanyEmployeeCountCategory: {
      type: "string",
      label: "Current Company Employee Count Category",
      description: "Filter by current company's size.",
      optional: true,
      options: [
        {
          label: "Custom (default)",
          value: "custom",
        },
        {
          label: "Startup (1-10)",
          value: "startup",
        },
        {
          label: "Small (11-50)",
          value: "small",
        },
        {
          label: "Medium (51-250)",
          value: "medium",
        },
        {
          label: "Large (251-1000)",
          value: "large",
        },
        {
          label: "Enterprise (1001+)",
          value: "enterprise",
        },
      ],
    },
    currentCompanyEmployeeCountMin: {
      type: "string",
      label: "Current Company Employee Count Min",
      description: "Filter by minimum current company employee count.",
      optional: true,
    },
    currentCompanyEmployeeCountMax: {
      type: "string",
      label: "Current Company Employee Count Max",
      description: "Filter by maximum current company employee count.",
      optional: true,
    },
    currentCompanyDescription: {
      type: "string",
      label: "Current Company Description",
      description: "Filter by current company's description.",
      optional: true,
    },
    currentCompanyFoundedAfterYear: {
      type: "string",
      label: "Current Company Founded After Year",
      description: "Filter by current company founded after this year.",
      optional: true,
    },
    currentCompanyFoundedBeforeYear: {
      type: "string",
      label: "Current Company Founded Before Year",
      description: "Filter by current company founded before this year.",
      optional: true,
    },
    currentCompanyFundingAmountMin: {
      type: "string",
      label: "Current Company Funding Amount Min (USD)",
      description: "Filter by minimum current company funding amount.",
      optional: true,
    },
    currentCompanyFundingAmountMax: {
      type: "string",
      label: "Current Company Funding Amount Max (USD)",
      description: "Filter by maximum current company funding amount.",
      optional: true,
    },
    currentCompanyFundingRaisedAfter: {
      type: "string",
      label: "Current Company Funding Raised After",
      description: "Filter by funding raised after this date (ISO 8601).",
      optional: true,
    },
    currentCompanyFundingRaisedBefore: {
      type: "string",
      label: "Current Company Funding Raised Before",
      description: "Filter by funding raised before this date (ISO 8601).",
      optional: true,
    },
    currentCompanyDomainName: {
      type: "string",
      label: "Current Company Domain Name",
      description: "Filter by current company's domain name.",
      optional: true,
    },
    currentCompanyFollowerCountMin: {
      type: "string",
      label: "Current Company Follower Count Min",
      description: "Filter by minimum current company follower count.",
      optional: true,
    },
    currentCompanyFollowerCountMax: {
      type: "string",
      label: "Current Company Follower Count Max",
      description: "Filter by maximum current company follower count.",
      optional: true,
    },
    followerCountMin: {
      type: "string",
      label: "Follower Count Min",
      description: "Filter people with more than this many followers.",
      optional: true,
    },
    followerCountMax: {
      type: "string",
      label: "Follower Count Max",
      description: "Filter people with fewer than this many followers.",
      optional: true,
    },
    publicIdentifierInList: {
      type: "string",
      label: "Public Identifier In List",
      description: "Comma-separated list of person public identifiers to include.",
      optional: true,
    },
    publicIdentifierNotInList: {
      type: "string",
      label: "Public Identifier Not In List",
      description: "Comma-separated list of person public identifiers to exclude.",
      optional: true,
    },
    enrichProfiles: {
      propDefinition: [
        enrichlayer,
        "enrichProfiles",
      ],
    },
    pageSize: {
      propDefinition: [
        enrichlayer,
        "pageSize",
      ],
      description: "Max results per call. Default is 100 (max 100). When enriching, max is 10.",
    },
    useCache: {
      propDefinition: [
        enrichlayer,
        "useCache",
      ],
    },
  },
  async run({ $ }) {
    const response = await this.enrichlayer._makeRequest({
      $,
      path: "/api/v2/search/person",
      params: {
        country: this.country,
        first_name: this.firstName,
        last_name: this.lastName,
        current_role_title: this.currentRoleTitle,
        past_role_title: this.pastRoleTitle,
        current_company_name: this.currentCompanyName,
        past_company_name: this.pastCompanyName,
        current_company_profile_url: this.currentCompanyProfileUrl,
        past_company_profile_url: this.pastCompanyProfileUrl,
        city: this.city,
        region: this.region,
        headline: this.headline,
        summary: this.summary,
        education_field_of_study: this.educationFieldOfStudy,
        education_degree_name: this.educationDegreeName,
        education_school_name: this.educationSchoolName,
        education_school_profile_url: this.educationSchoolProfileUrl,
        current_role_before: this.currentRoleBefore,
        current_role_after: this.currentRoleAfter,
        current_job_description: this.currentJobDescription,
        past_job_description: this.pastJobDescription,
        industries: this.industries,
        interests: this.interests,
        skills: this.skills,
        skills_all_in_list: this.skillsAllInList,
        languages: this.languages,
        groups: this.groups,
        current_company_country: this.currentCompanyCountry,
        current_company_region: this.currentCompanyRegion,
        current_company_city: this.currentCompanyCity,
        current_company_type: this.currentCompanyType,
        current_company_industry: this.currentCompanyIndustry,
        current_company_primary_industry: this.currentCompanyPrimaryIndustry,
        current_company_specialities: this.currentCompanySpecialities,
        current_company_employee_count_category: this.currentCompanyEmployeeCountCategory,
        current_company_employee_count_min: this.currentCompanyEmployeeCountMin,
        current_company_employee_count_max: this.currentCompanyEmployeeCountMax,
        current_company_description: this.currentCompanyDescription,
        current_company_founded_after_year: this.currentCompanyFoundedAfterYear,
        current_company_founded_before_year: this.currentCompanyFoundedBeforeYear,
        current_company_funding_amount_min: this.currentCompanyFundingAmountMin,
        current_company_funding_amount_max: this.currentCompanyFundingAmountMax,
        current_company_funding_raised_after: this.currentCompanyFundingRaisedAfter,
        current_company_funding_raised_before: this.currentCompanyFundingRaisedBefore,
        current_company_domain_name: this.currentCompanyDomainName,
        current_company_follower_count_min: this.currentCompanyFollowerCountMin,
        current_company_follower_count_max: this.currentCompanyFollowerCountMax,
        follower_count_min: this.followerCountMin,
        follower_count_max: this.followerCountMax,
        public_identifier_in_list: this.publicIdentifierInList,
        public_identifier_not_in_list: this.publicIdentifierNotInList,
        enrich_profiles: this.enrichProfiles,
        page_size: this.pageSize,
        use_cache: this.useCache,
      },
    });
    $.export("$summary", "Successfully searched people");
    return response;
  },
};
