const TIME_TYPE = [
  "work",
  "parental_leave",
  "worked_rest_period",
  "clocking",
  "statutory_leave",
  "public_holiday_abroad",
  "medical_leave",
  "bad_weather",
  "company_vacation",
  "unpaid_vacation",
  "care_leave",
  "out_office",
  "work_accident_sickness",
  "military_exercize",
  "flextime",
  "unpaid_time_off",
  "home_office",
  "study_leave",
  "paid_time_off",
  "other_leave",
  "vacation_abroad",
  "travel",
  "sick",
  "military_service",
  "jubilee_day",
  "vacation",
  "move",
  "special_leave",
  "free_time",
];

export default {
  TIME_TYPE,
};
