export default {
  data: {
    scrub_sheet: null,
    rating: null,
    shared: false,
    drm: null,
    hls_manifest: null,
    scrub_video: null,
    filesize: 31719,
    private: false,
    workfront_approval_status: null,
    status: "created",
    timecode: null,
    transcode_statuses: null,
    h264_1080_best: null,
    filetype: "image/jpeg",
    workfront_task_connected: null,
    upload_completed_at: null,
    page_full: null,
    waveform: null,
    allow_original_playback: true,
    archived_at: null,
    _type: "file",
    team_id: "string",
    frames: 0,
    workfront_task_id: null,
    is_session_watermarked: false,
    downloads: {
      h264_1080_best: null,
      h264_2160: null,
      h264_360: null,
      h264_540: null,
      h264_720: null,
      image_full: null,
      image_high: null,
      image_small: null,
    },
    id: "string",
    view_count: 0,
    fps: null,
    hard_deleted_at: null,
    copy: false,
    webm_1080_best: null,
    name: "string",
    h265_hdr_1080: null,
    includes: null,
    autoversion_id: null,
    subtitle_tracks: null,
    public_item_count: 0,
    audio_tracks: null,
    versions: 0,
    page_thumb: null,
    cover_asset_id: null,
    webm_540: null,
    image_full: null,
    resource_id: null,
    parent_id: "string",
    metadata_flags: null,
    creator: {
      from_adobe: false,
      digest_frequency: "0 * * * *",
      image_256:
        "string",
      timezone_value: "America/New_York",
      _type: "user",
      image_128:
        "string",
      user_default_color: "#40ff9f",
      id: "string",
      email_confirm_by: null,
      name: "string",
      profile_image_original: null,
      features_seen: null,
      roles: null,
      mfa_enforced_at: null,
      integrations: {},
      image_64:
        "string",
      first_login_at: "datetime",
      last_seen: null,
      account_id: "string",
      bio: null,
      upload_url:
        "string",
      image_32:
        "string",
      email_preferences: null,
      next_digest_date: "datetime",
      from_google: true,
      deleted_at: null,
      inserted_at: "datetime",
      joined_via: "organic",
      updated_at: "datetime",
      highest_account_role: null,
      phone: null,
      context: null,
      location: null,
      profile_image:
        "string",
      email: "string",
    },
    image_small: null,
    properties: null,
    archive_status: null,
    creator_id: "string",
    upload_failed_at: null,
    uploaded_at: "datetime",
    page_high: null,
    webm_720: null,
    index: -4,
    thumb: null,
    h265_hdr_360: null,
    workfront_task_title: null,
    video_h264_180: null,
    account_id: "string",
    thumb_scrub: null,
    project: {
      _type: "project",
      archive_status: "standard",
      archived_at: null,
      archived_file_count: 0,
      archived_storage: 0,
      collaborator_count: 0,
      deleted_at: null,
      description: null,
      file_count: 5,
      folder_count: 5,
      id: "string",
      ignore_archive: false,
      inserted_at: "datetime",
      invite_url: null,
      name: "string",
      owner_id: "string",
      private: false,
      read_only: false,
      resource_id: null,
      root_asset_id: "string",
      shared: false,
      storage: 105947,
      team_id: "string",
      updated_at: "datetime",
      user_permissions: {
        can_download: true,
        can_manage_devices: true,
        can_modify_template: false,
        can_public_share_presentation: true,
        can_public_share_review_link: true,
        can_see_watermarking_settings: true,
        can_share_downloadable_presentation: true,
        can_share_downloadable_review_link: true,
        can_share_unwatermarked_presentation: true,
        can_share_unwatermarked_review_link: true,
        can_share_without_drm_presentation: false,
        can_share_without_drm_review_link: false,
        can_share_without_forensic_watermark_presentation: true,
        can_share_without_forensic_watermark_review_link: true,
        can_view_devices: true,
      },
    },
    label: "none",
    frame_custom: null,
    workfront_asset_locked_at: null,
    archive_scheduled_at: null,
    frame_cover: null,
    user_permissions: {
      can_download: true,
      can_manage_devices: true,
      can_modify_template: false,
      can_public_share_presentation: true,
      can_public_share_review_link: true,
      can_see_watermarking_settings: true,
      can_share_downloadable_presentation: true,
      can_share_downloadable_review_link: true,
      can_share_unwatermarked_presentation: true,
      can_share_unwatermarked_review_link: true,
      can_share_without_drm_presentation: false,
      can_share_without_drm_review_link: false,
      can_share_without_forensic_watermark_presentation: true,
      can_share_without_forensic_watermark_review_link: true,
      can_view_devices: true,
    },
    original:
      "string",
    asset_type: null,
    page_small: null,
    master_manifest_concentrate: null,
    h265_hdr_2160: null,
    cover: null,
    project_id: "string",
    h264_2160: null,
    deleted_at: null,
    is_360: false,
    transcoded_at: null,
    h265_hdr_720: null,
    inserted_at: "datetime",
    thumb_540: null,
    updated_at: "datetime",
    type: "file",
    is_hls_required: false,
    workfront_connected: null,
    image_high: null,
    h265_hdr_540: null,
    duration: null,
    h264_720: null,
    description: null,
    source: {
      _type: "asset_source",
      external_id: null,
      id: "string",
      provider: null,
      url: "string",
    },
    archive_from: "datetime",
    frame_thumb: null,
    realtime_upload: null,
    webm_360: null,
    item_count: 0,
    h264_540: null,
    h264_360: null,
    thumb_orig_ar_540: null,
    checksums: null,
    is_forensically_watermarked: false,
    comment_count: 0,
  },
  project: {
    id: "string",
  },
  resource: {
    id: "string",
    type: "asset",
  },
  team: {
    id: "string",
  },
  type: "asset.created",
  user: {
    id: "string",
  },
};
