<template><h1 id="common-errors" tabindex="-1"><a class="header-anchor" href="#common-errors" aria-hidden="true">#</a> Common Errors</h1>
<p>Pipedream <a href="/event-sources/" target="_blank" rel="noopener noreferrer">sources<ExternalLinkIcon/></a> and <a href="/workflows" target="_blank" rel="noopener noreferrer">workflows<ExternalLinkIcon/></a> can throw errors for a variety of reasons. In some cases, you'll encounter an error sending data to a third-party API; in other cases, Pipedream will raise an error related to platform limits you've exceeded, or other internal errors.</p>
<p>This doc reviews common errors you'll encounter, and how to troubleshoot them.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#warnings">Warnings</RouterLink><ul><li><RouterLink to="#this-step-was-still-trying-to-run-code-when-the-step-ended-make-sure-you-await-all-promises-or-promisify-callback-functions">This step was still trying to run code when the step ended. Make sure you await all Promises, or promisify callback functions.</RouterLink></li></ul></li><li><RouterLink to="#pipedream-internal-errors">Pipedream Internal Errors</RouterLink><ul><li><RouterLink to="#invocations-quota-exceeded">Invocations Quota Exceeded</RouterLink></li><li><RouterLink to="#runtime-quota-exceeded">Runtime Quota Exceeded</RouterLink></li><li><RouterLink to="#timeout">Timeout</RouterLink></li><li><RouterLink to="#out-of-memory">Out of Memory</RouterLink></li><li><RouterLink to="#rate-limit-exceeded">Rate Limit Exceeded</RouterLink></li><li><RouterLink to="#request-entity-too-large">Request Entity Too Large</RouterLink></li><li><RouterLink to="#function-payload-limit-exceeded">Function Payload Limit Exceeded</RouterLink></li><li><RouterLink to="#json-nested-property-limit-exceeded">JSON Nested Property Limit Exceeded</RouterLink></li><li><RouterLink to="#event-queue-full">Event Queue Full</RouterLink></li></ul></li></ul></nav>
<h2 id="warnings" tabindex="-1"><a class="header-anchor" href="#warnings" aria-hidden="true">#</a> Warnings</h2>
<p>Pipedream displays warnings below steps in certain conditions. These warnings do not stop the execution of your workflow, but can signal an issue you should be aware of.</p>
<h3 id="this-step-was-still-trying-to-run-code-when-the-step-ended-make-sure-you-await-all-promises-or-promisify-callback-functions" tabindex="-1"><a class="header-anchor" href="#this-step-was-still-trying-to-run-code-when-the-step-ended-make-sure-you-await-all-promises-or-promisify-callback-functions" aria-hidden="true">#</a> This step was still trying to run code when the step ended. Make sure you await all Promises, or promisify callback functions.</h3>
<p>See the reference on <a href="/workflows/steps/code/async/" target="_blank" rel="noopener noreferrer">running asynchronous code on Pipedream<ExternalLinkIcon/></a>.</p>
<h2 id="pipedream-internal-errors" tabindex="-1"><a class="header-anchor" href="#pipedream-internal-errors" aria-hidden="true">#</a> Pipedream Internal Errors</h2>
<p>Pipedream sets <a href="/limits/" target="_blank" rel="noopener noreferrer">limits<ExternalLinkIcon/></a> on runtime, memory, and other execution-related properties. If you exceed these limits, you'll receive one of the errors below. <a href="/limits/" target="_blank" rel="noopener noreferrer">See the limits doc<ExternalLinkIcon/></a> for details on specific limits.</p>
<h3 id="invocations-quota-exceeded" tabindex="-1"><a class="header-anchor" href="#invocations-quota-exceeded" aria-hidden="true">#</a> Invocations Quota Exceeded</h3>
<p>On the <a href="/pricing/#developer-tier" target="_blank" rel="noopener noreferrer">Developer (free) tier<ExternalLinkIcon/></a>, Pipedream imposes a limit on the <a href="/limits/#daily-invocations" target="_blank" rel="noopener noreferrer">daily invocations<ExternalLinkIcon/></a> across all workflows and sources. If you hit this limit, you'll see an <strong>Invocations Quota Exceeded</strong> error.</p>
<p>Paid plans, like the <a href="#professional-tier">Professional Tier</a>, have no invocations limit. <a href="https://pipedream.com/pricing" target="_blank" rel="noopener noreferrer">Upgrade here<ExternalLinkIcon/></a>.</p>
<h3 id="runtime-quota-exceeded" tabindex="-1"><a class="header-anchor" href="#runtime-quota-exceeded" aria-hidden="true">#</a> Runtime Quota Exceeded</h3>
<p>On the <a href="/pricing/#developer-tier" target="_blank" rel="noopener noreferrer">Developer (free) tier<ExternalLinkIcon/></a>, Pipedream imposes a limit on the <a href="/limits/#compute-time-per-day" target="_blank" rel="noopener noreferrer">daily compute time<ExternalLinkIcon/></a> across all workflows and sources. If you hit this limit, you'll see a <strong>Runtime Quota Exceeded</strong> error.</p>
<p>Paid plans, like the <a href="#professional-tier">Professional Tier</a>, have no compute time limit. <a href="https://pipedream.com/pricing" target="_blank" rel="noopener noreferrer">Upgrade here<ExternalLinkIcon/></a>.</p>
<h3 id="timeout" tabindex="-1"><a class="header-anchor" href="#timeout" aria-hidden="true">#</a> Timeout</h3>
<p>Event sources and workflows have a <a href="/limits/#time-per-execution" target="_blank" rel="noopener noreferrer">default time limit on a given execution<ExternalLinkIcon/></a>. If your code exceeds that limit, you may encounter a <strong>Timeout</strong> error.</p>
<p>To address timeouts, you'll either need to:</p>
<ol>
<li>Figure out why your code is running for longer than expected. It's important to note that <strong>timeouts are not an issue with Pipedream — they are specific to your workflow</strong>. Often, you're making a request to a third party API doesn't respond in the time you expect, or you're processing a large amount of data in your workflow, and it doesn't complete before you hit the execution limit.</li>
<li>If it's expected that your code is taking a long time to run, you can raise the execution limit of a workflow in your <a href="/workflows/settings/#execution-timeout-limit" target="_blank" rel="noopener noreferrer">workflow's settings<ExternalLinkIcon/></a>. If you need to change the execution limit for an event source, please <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">reach out to our team<ExternalLinkIcon/></a>.</li>
</ol>
<h3 id="out-of-memory" tabindex="-1"><a class="header-anchor" href="#out-of-memory" aria-hidden="true">#</a> Out of Memory</h3>
<p>Pipedream <a href="/limits/#memory" target="_blank" rel="noopener noreferrer">limits the default memory<ExternalLinkIcon/></a> available to workflows and event sources. If you exceed this memory, you'll see an <strong>Out of Memory</strong> error.</p>
<p>This can happen for a variety of reasons. Normally, it can occur when you try to load a large file or object into a variable / memory. Where possible, consider streaming the file to / from disk, instead of storing it in memory, using a <a href="/workflows/steps/code/nodejs/http-requests/#download-a-file-to-the-tmp-directory" target="_blank" rel="noopener noreferrer">technique like this<ExternalLinkIcon/></a>.</p>
<p><strong>You can raise the memory of your workflow <a href="/workflows/settings/#memory" target="_blank" rel="noopener noreferrer">in your workflow's Settings<ExternalLinkIcon/></a></strong>.</p>
<h3 id="rate-limit-exceeded" tabindex="-1"><a class="header-anchor" href="#rate-limit-exceeded" aria-hidden="true">#</a> Rate Limit Exceeded</h3>
<p>Pipedream limits the number of events that can be processed by a given interface (e.g. HTTP endpoints) during a given interval. This limit is most commonly reached for HTTP interfaces - see the <a href="/limits/#qps-queries-per-second" target="_blank" rel="noopener noreferrer">QPS limits documentation<ExternalLinkIcon/></a> for more information on that limit.</p>
<p><strong>This limit can be raised for HTTP endpoints</strong>. <a href="https://pipedream.com/support/" target="_blank" rel="noopener noreferrer">Reach out to our team<ExternalLinkIcon/></a> to request an increase.</p>
<h3 id="request-entity-too-large" tabindex="-1"><a class="header-anchor" href="#request-entity-too-large" aria-hidden="true">#</a> Request Entity Too Large</h3>
<p>By default, Pipedream limits the size of incoming HTTP payloads. If you exceed this limit, you'll see a <strong>Request Entity Too Large</strong> error.</p>
<p>Pipedream supports two different ways to bypass this limit. Both of these interfaces support uploading data up to <code>5TB</code>, though you may encounter other <a href="/limits/" target="_blank" rel="noopener noreferrer">platform limits<ExternalLinkIcon/></a>.</p>
<ul>
<li>You can send large HTTP payloads by passing the <code>pipedream_upload_body=1</code> query string or an <code>x-pd-upload-body: 1</code> HTTP header in your HTTP request. <a href="/workflows/steps/triggers/#sending-large-payloads" target="_blank" rel="noopener noreferrer">Read more here<ExternalLinkIcon/></a>.</li>
<li>You can upload multiple large files, like images and videos, using the <a href="/workflows/steps/triggers/#large-file-support" target="_blank" rel="noopener noreferrer">large file upload interface<ExternalLinkIcon/></a>.</li>
</ul>
<h3 id="function-payload-limit-exceeded" tabindex="-1"><a class="header-anchor" href="#function-payload-limit-exceeded" aria-hidden="true">#</a> Function Payload Limit Exceeded</h3>
<p>The total size of <code>console.log()</code> statements, <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">step exports<ExternalLinkIcon/></a>, and the original event data sent to workflows and sources cannot exceed a combined size of <code>{{$site.themeConfig.FUNCTION_PAYLOAD_LIMIT}}</code>. If you produce logs or step exports larger than this - for example, passing around large API responses, CSVs, or other data - you may encounter a <strong>Function Payload Limit Exceeded</strong> in your workflow.</p>
<p>Often, this occurs when you pass large data between steps using <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">step exports<ExternalLinkIcon/></a>. You can avoid this error by <a href="/workflows/steps/code/nodejs/working-with-files/#writing-a-file-to-tmp" target="_blank" rel="noopener noreferrer">writing that data to the <code>/tmp</code> directory<ExternalLinkIcon/></a> in one step, and <a href="/workflows/steps/code/nodejs/working-with-files/#reading-a-file-from-tmp" target="_blank" rel="noopener noreferrer">reading the data into another step<ExternalLinkIcon/></a>, which avoids the use of step exports and should keep you under the payload limit.</p>
<p>Pipedream also compresses the function payload from your workflow, which can yield roughly a 2x-3x increase in payload size (somewhere between <code>12MB</code> and <code>18MB</code>), depending on the data.</p>
<h3 id="json-nested-property-limit-exceeded" tabindex="-1"><a class="header-anchor" href="#json-nested-property-limit-exceeded" aria-hidden="true">#</a> JSON Nested Property Limit Exceeded</h3>
<p>Working with nested JavaScript objects that have more than 256 nested objects will trigger a <strong>JSON Nested Property Limit Exceeded</strong> error.</p>
<p>Often, objects with this many nested objects result from a programming error that explodes the object in an unexpected way. Please confirm the code you're using to convert data into an object is correctly parsing the object.</p>
<h3 id="event-queue-full" tabindex="-1"><a class="header-anchor" href="#event-queue-full" aria-hidden="true">#</a> Event Queue Full</h3>
<p>Workflows have a maximum event queue size when using concurrency and throttling controls. If the number of unprocessed events exceeds the <a href="/workflows/events/concurrency-and-throttling/#increasing-the-queue-size-for-a-workflow" target="_blank" rel="noopener noreferrer">maximum queue size<ExternalLinkIcon/></a>, you may encounter an <strong>Event Queue Full</strong> error.</p>
<p><a href="https://pipedream.com/pricing" target="_blank" rel="noopener noreferrer">Paid plans<ExternalLinkIcon/></a> can <a href="/workflows/events/concurrency-and-throttling/#increasing-the-queue-size-for-a-workflow" target="_blank" rel="noopener noreferrer">increase their queue size up to {{$site.themeConfig.MAX_WORKFLOW_QUEUE_SIZE}}<ExternalLinkIcon/></a> for a given workflow.</p>
<Footer />
</template>
