export const LIMIT = 100;
export const CLASH_RESOLUTION_OPTIONS = [
  {
    label: "Add To Waiting List",
    value: "add_to_waiting_list",
  },
  {
    label: "Book With Overtime",
    value: "book_with_overtime",
  },
  {
    label: "Increase Availability",
    value: "increase_availability",
  },
];

export const TIMEZONE_OPTIONS = [
  "American Samoa",
  "International Date Line West",
  "Midway Island",
  "Hawaii",
  "Alaska",
  "Pacific Time (US & Canada)",
  "Tijuana",
  "Arizona",
  "Chihuahua",
  "Mazatlan",
  "Mountain Time (US & Canada)",
  "Central America",
  "Central Time (US & Canada)",
  "Guadalajara",
  "Mexico City",
  "Monterrey",
  "Saskatchewan",
  "Bogota",
  "Eastern Time (US & Canada)",
  "Indiana (East)",
  "Lima",
  "Quito",
  "Caracas",
  "Atlantic Time (Canada)",
  "Georgetown",
  "La Paz",
  "Santiago",
  "Newfoundland",
  "Brasilia",
  "Buenos Aires",
  "Greenland",
  "Mid-Atlantic",
  "Azores",
  "Cape Verde Is.",
  "Casablanca",
  "Dublin",
  "Edinburgh",
  "Lisbon",
  "London",
  "Monrovia",
  "UTC",
  "Amsterdam",
  "Belgrade",
  "Berlin",
  "Bern",
  "Bratislava",
  "Brussels",
  "Budapest",
  "Copenhagen",
  "Ljubljana",
  "Madrid",
  "Paris",
  "Prague",
  "Rome",
  "Sarajevo",
  "Skopje",
  "Stockholm",
  "Vienna",
  "Warsaw",
  "West Central Africa",
  "Zagreb",
  "Athens",
  "Bucharest",
  "Cairo",
  "Harare",
  "Helsinki",
  "Istanbul",
  "Jerusalem",
  "Kyiv",
  "Pretoria",
  "Riga",
  "Sofia",
  "Tallinn",
  "Vilnius",
  "Baghdad",
  "Kuwait",
  "Minsk",
  "Nairobi",
  "Riyadh",
  "Tehran",
  "Abu Dhabi",
  "Baku",
  "Moscow",
  "Muscat",
  "St. Petersburg",
  "Tbilisi",
  "Volgograd",
  "Yerevan",
  "Kabul",
  "Islamabad",
  "Karachi",
  "Tashkent",
  "Chennai",
  "Kolkata",
  "Mumbai",
  "New Delhi",
  "Sri Jayawardenepura",
  "Kathmandu",
  "Almaty",
  "Astana",
  "Dhaka",
  "Ekaterinburg",
  "Rangoon",
  "Bangkok",
  "Hanoi",
  "Jakarta",
  "Novosibirsk",
  "Beijing",
  "Chongqing",
  "Hong Kong",
  "Krasnoyarsk",
  "Kuala Lumpur",
  "Perth",
  "Singapore",
  "Taipei",
  "Ulaan Bataar",
  "Urumqi",
  "Irkutsk",
  "Osaka",
  "Sapporo",
  "Seoul",
  "Tokyo",
  "Adelaide",
  "Darwin",
  "Brisbane",
  "Canberra",
  "Guam",
  "Hobart",
  "Melbourne",
  "Port Moresby",
  "Sydney",
  "Yakutsk",
  "New Caledonia",
  "Vladivostok",
  "Auckland",
  "Fiji",
  "Kamchatka",
  "Magadan",
  "Marshall Is.",
  "Solomon Is.",
  "Wellington",
  "Nuku'alofa",
  "Samoa",
  "Tokelau Is.",
];
