import zohoInventory from "../../zoho_inventory.app.mjs";

export default {
  key: "zoho_inventory-create-item",
  name: "Create Item",
  description: "Creates a new item in Zoho Inventory. [See the documentation](https://www.zoho.com/inventory/api/v1/items/#create-an-item)",
  version: "0.0.1",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: false,
  },
  props: {
    zohoInventory,
    organization: {
      propDefinition: [
        zohoInventory,
        "organization",
      ],
    },
    name: {
      type: "string",
      label: "Name",
      description: "Name of the item.",
    },
    groupId: {
      propDefinition: [
        zohoInventory,
        "groupId",
      ],
    },
    groupName: {
      type: "string",
      label: "Group Name",
      description: "Name of the product group.",
      optional: true,
    },
    unit: {
      type: "string",
      label: "Unit",
      description: "Unit of measurement for the item (e.g., `kg`, `box`, `pcs`).",
      optional: true,
    },
    itemType: {
      type: "string",
      label: "Item Type",
      description: "Item type. If the item is associated with a group, type should be `inventory`.",
      options: [
        "inventory",
        "sales",
        "purchases",
        "sales_and_purchases",
      ],
      optional: true,
    },
    productType: {
      type: "string",
      label: "Product Type",
      description: "Type of the product.",
      options: [
        "goods",
        "service",
      ],
      optional: true,
    },
    isTaxable: {
      type: "boolean",
      label: "Is Taxable",
      description: "Whether the item is taxable.",
      optional: true,
    },
    taxId: {
      propDefinition: [
        zohoInventory,
        "taxId",
      ],
    },
    description: {
      type: "string",
      label: "Description",
      description: "Description of the item.",
      optional: true,
    },
    purchaseAccountId: {
      propDefinition: [
        zohoInventory,
        "accountId",
      ],
      label: "Purchase Account",
      description: "Unique ID generated by the server for the purchase account.",
    },
    inventoryAccountId: {
      propDefinition: [
        zohoInventory,
        "accountId",
      ],
      label: "Inventory Account",
      description: "Unique ID generated by the server for the inventory account.",
    },
    vendorId: {
      propDefinition: [
        zohoInventory,
        "vendorId",
      ],
    },
    vendorName: {
      type: "string",
      label: "Vendor Name",
      description: "Name of the preferred vendor for purchasing this item.",
      optional: true,
    },
    rate: {
      type: "string",
      label: "Rate",
      description: "Sales price of the item.",
      optional: true,
    },
    purchaseRate: {
      type: "string",
      label: "Purchase Rate",
      description: "Purchase price of the item.",
      optional: true,
    },
    reorderLevel: {
      type: "string",
      label: "Reorder Level",
      description: "Reorder level of the item.",
      optional: true,
    },
    sku: {
      type: "string",
      label: "SKU",
      description: "The Stock Keeping Unit (SKU) of the item. Must be unique across all items.",
      optional: true,
    },
    upc: {
      type: "string",
      label: "UPC",
      description: "The 12-digit Unique Product Code (UPC) of the item.",
      optional: true,
    },
    ean: {
      type: "string",
      label: "EAN",
      description: "Unique EAN value for the item.",
      optional: true,
    },
    isbn: {
      type: "string",
      label: "ISBN",
      description: "Unique ISBN value for the item.",
      optional: true,
    },
    partNumber: {
      type: "string",
      label: "Part Number",
      description: "Part number of the item.",
      optional: true,
    },
    attributeName1: {
      type: "string",
      label: "Attribute Name",
      description: "Name of the attribute present in the item group.",
      optional: true,
    },
    attributeOptionName1: {
      type: "string",
      label: "Attribute Option Name",
      description: "Name of the attribute's option.",
      optional: true,
    },
    purchaseDescription: {
      type: "string",
      label: "Purchase Description",
      description: "Description displayed to the vendor in purchase orders.",
      optional: true,
    },
    documents: {
      type: "string[]",
      label: "Documents",
      description: "List of documents associated with the item. Each entry should be a JSON string, e.g. `{\"name\":\"manual.pdf\",\"document_type\":\"pdf\"}`.",
      optional: true,
    },
    locations: {
      type: "string[]",
      label: "Locations",
      description: "List of locations for the item. Each entry should be a JSON string, e.g. `{\"warehouse_id\":\"WH123\",\"quantity\":10}`.",
      optional: true,
    },
    itemTaxPreferences: {
      type: "string[]",
      label: "Item Tax Preferences",
      description: "🇮🇳 List of tax preferences for the item. Each entry should be a JSON string, e.g. `{\"tax_name\":\"GST\",\"tax_percentage\":18}`.",
      optional: true,
    },
    hsnOrSac: {
      type: "string",
      label: "HSN or SAC Code",
      description: "🇮🇳 HSN code of the item.",
      optional: true,
    },
    satItemKeyCode: {
      type: "string",
      label: "SAT Item Key Code",
      description: "🇲🇽 SAT item key code for goods/services.",
      optional: true,
    },
    unitKeyCode: {
      type: "string",
      label: "Unit Key Code",
      description: "🇲🇽 Unit key code for goods/services.",
      optional: true,
    },
    customFields: {
      type: "string[]",
      label: "Custom Fields",
      description: "Custom fields for the item. Each entry should be a JSON string, e.g. `{\"customfield_id\":\"cf_1\",\"value\":\"foo\"}`.",
      optional: true,
    },
  },
  async run({ $ }) {
    const parseArray = (arr) =>
      arr?.map((item) => (typeof item === "string"
        ? JSON.parse(item)
        : item));

    const safeParseFloat = (val) => {
      if (val === undefined || val === null) return undefined;
      const trimmed = String(val).trim();
      if (!trimmed) return undefined;
      const parsed = parseFloat(trimmed);
      return Number.isFinite(parsed)
        ? parsed
        : undefined;
    };

    const data = {
      name: this.name,
      group_id: this.groupId,
      group_name: this.groupName,
      unit: this.unit,
      item_type: this.itemType,
      product_type: this.productType,
      is_taxable: this.isTaxable,
      tax_id: this.taxId,
      description: this.description,
      purchase_account_id: this.purchaseAccountId,
      inventory_account_id: this.inventoryAccountId,
      vendor_id: this.vendorId,
      vendor_name: this.vendorName,
      rate: safeParseFloat(this.rate),
      purchase_rate: safeParseFloat(this.purchaseRate),
      reorder_level: safeParseFloat(this.reorderLevel),
      sku: this.sku,
      upc: this.upc,
      ean: this.ean,
      isbn: this.isbn,
      part_number: this.partNumber,
      attribute_name1: this.attributeName1,
      attribute_option_name1: this.attributeOptionName1,
      purchase_description: this.purchaseDescription,
      documents: parseArray(this.documents),
      locations: parseArray(this.locations),
      item_tax_preferences: parseArray(this.itemTaxPreferences),
      hsn_or_sac: this.hsnOrSac,
      sat_item_key_code: this.satItemKeyCode,
      unitkey_code: this.unitKeyCode,
      custom_fields: parseArray(this.customFields),
    };

    const response = await this.zohoInventory.createItem({
      $,
      params: {
        organization_id: this.organization,
      },
      data,
    });
    $.export("$summary", `Successfully created item ${this.name}`);
    return response;
  },
};
