export default {
  "id": 24298436,
  "business_name": "",
  "first_name": "",
  "image_name": "My new image",
  "image_url": "https://img.hyperise.io/i/sW140JarK.png?time=1710274146651&editor_preview=1",
  "enrichment_data": {
    "email": "",
    "title": "",
    "first_name": "",
    "last_name": "",
    "gender": "",
    "job_title": "",
    "profile_url": "",
    "business_name": "",
    "category": "",
    "business_address": "",
    "street": "",
    "street2": "",
    "city": "",
    "state": "",
    "zip": "",
    "country": "",
    "revenue": "",
    "employees_range": "",
    "business_lat": 52.951214,
    "business_long": -1.1461797,
    "business_phone": "",
    "business_website": "",
    "website_screenshot": "",
    "logo_url": "",
    "custom_image_1": false,
    "custom_image_2": false,
    "custom_image_3": false,
    "custom_text_1": "",
    "custom_text_2": "",
    "custom_text_3": "",
    "custom_text_4": "",
    "custom_text_5": "",
    "qr_url": ""
  },
  "processed_at": "2024-03-12T20:12:28Z"
}