export default {
  "id": 1234567890,
  "note": null,
  "email": "email@email.com",
  "taxes_included": false,
  "currency": "Currency",
  "invoice_sent_at": null,
  "created_at": "2024-08-21T01:22:42-04:00",
  "updated_at": "2025-10-01T10:22:26-04:00",
  "tax_exempt": false,
  "completed_at": "2025-10-01T10:22:26-04:00",
  "name": "#11",
  "allow_discount_codes_in_checkout?": false,
  "b2b?": false,
  "status": "completed",
  "line_items": [
    {
      "id": 1234567890,
      "variant_id": 1234567890,
      "product_id": 1234567890,
      "title": "Product Title",
      "variant_title": "Variant Title",
      "sku": "1012",
      "vendor": "Vendor Name",
      "quantity": 1,
      "requires_shipping": true,
      "taxable": true,
      "gift_card": false,
      "fulfillment_service": "manual",
      "grams": 5000,
      "tax_lines": [
        {
          "rate": 0.1,
          "title": "VAT",
          "price": "101"
        }
      ],
      "applied_discount": null,
      "name": "Product Title - Variant Title",
      "properties": [],
      "custom": false,
      "price": "1011",
      "admin_graphql_api_id": "gid://shopify/DraftOrderLineItem/1234567890"
    }
  ],
  "api_client_id": 1354745,
  "shipping_address": {
    "first_name": "First Name",
    "address1": "123 Address",
    "phone": null,
    "city": "City",
    "zip": null,
    "province": null,
    "country": "Country",
    "last_name": "Last Name",
    "address2": null,
    "company": null,
    "latitude": 14.058324,
    "longitude": 108.277199,
    "name": "First Name Last Name",
    "country_code": "Country",
    "province_code": null
  },
  "billing_address": {
    "first_name": "First Name",
    "address1": "123 Address",
    "phone": null,
    "city": "City",
    "zip": null,
    "province": null,
    "country": "Country",
    "last_name": "Last Name",
    "address2": null,
    "company": null,
    "latitude": 14.058324,
    "longitude": 108.277199,
    "name": "First Name Last Name",
    "country_code": "Country",
    "province_code": null
  },
  "invoice_url": "https://vendor-name.myshopify.com/1234567890/invoices/1234567890",
  "created_on_api_version_handle": null,
  "applied_discount": null,
  "order_id": 1234567890,
  "shipping_line": null,
  "tax_lines": [
    {
      "rate": 0.1,
      "title": "VAT",
      "price": "101"
    }
  ],
  "tags": "",
  "note_attributes": [],
  "total_price": "1112",
  "subtotal_price": "1011",
  "total_tax": "101",
  "payment_terms": null,
  "admin_graphql_api_id": "gid://shopify/DraftOrder/1160212185373",
  "customer": {
    "id": 1234567890,
    "created_at": "2023-11-12T22:15:55-05:00",
    "updated_at": "2025-10-01T10:22:26-04:00",
    "first_name": "First Name",
    "last_name": "Last Name",
    "orders_count": 8,
    "state": "disabled",
    "total_spent": "12345.00",
    "last_order_id": 1234567890,
    "note": null,
    "verified_email": true,
    "multipass_identifier": null,
    "tax_exempt": false,
    "tags": "",
    "last_order_name": "#11",
    "email": "email@email.com",
    "phone": null,
    "currency": "Currency",
    "tax_exemptions": [],
    "email_marketing_consent": {
      "state": "not_subscribed",
      "opt_in_level": "single_opt_in",
      "consent_updated_at": null
    },
    "sms_marketing_consent": null,
    "admin_graphql_api_id": "gid://shopify/Customer/1234567890",
    "default_address": {
      "id": 1234567890,
      "customer_id": 1234567890,
      "first_name": "First Name",
      "last_name": "Last Name",
      "company": null,
      "address1": "123 Address",
      "address2": null,
      "city": "City",
      "province": null,
      "country": "Country",
      "zip": null,
      "phone": null,
      "name": "First Name Last Name",
      "province_code": null,
      "country_code": "Country",
      "country_name": "Country",
      "default": true
    }
  }
}