export default {
  id: "87f1cee7-e9e1-4ce9-aade-b080850b2686",
  type: "news_event",
  attributes: {
    summary: "x.ai has issues with lawsuit over data center air pollution.",
    category: "has_issues_with",
    found_at: "2025-06-19T04:06:39Z",
    confidence: 0.3819,
    article_sentence: "Elon Musk's AI firm xAI faces lawsuit over data center air pollution.",
    human_approved: false,
    planning: false,
    amount: null,
    amount_normalized: null,
    assets: null,
    assets_tags: [],
    award: null,
    contact: null,
    division: null,
    effective_date: null,
    event: null,
    financing_type: null,
    financing_type_normalized: null,
    financing_type_tags: [],
    headcount: null,
    job_title: null,
    job_title_tags: [],
    location: null,
    location_data: [],
    product: null,
    product_data: {
      full_text: null,
      name: null,
      release_type: null,
      release_version: null,
      fuzzy_match: null,
    },
    product_tags: [],
    recognition: null,
    vulnerability: "lawsuit over data center air pollution",
  },
  relationships: {
    company1: {
      data: {
        id: "b3b9bc14-b61b-50d3-956f-5ce0e25b7f65",
        type: "company",
      },
    },
    most_relevant_source: {
      data: {
        id: "cb963974-57e2-456f-a160-5dc95b5298e4",
        type: "news_article",
      },
    },
  },
};