export default {
  "id": "2566241561",
  "event": "customer_create",
  "payload[customer][id]": "83698432",
  "payload[customer][first_name]": "FirstName",
  "payload[customer][last_name]": "LastName",
  "payload[customer][organization]": "",
  "payload[customer][email]": "test@email.com",
  "payload[customer][created_at]": "2024-10-11 15:12:51 -0400",
  "payload[customer][updated_at]": "2024-10-11 15:12:51 -0400",
  "payload[customer][reference]": "",
  "payload[customer][address]": "",
  "payload[customer][address_2]": "",
  "payload[customer][address_3]": "",
  "payload[customer][city]": "",
  "payload[customer][state]": "",
  "payload[customer][zip]": "",
  "payload[customer][country]": "",
  "payload[customer][phone]": "",
  "payload[customer][portal_invite_last_sent_at]": "",
  "payload[customer][portal_invite_last_accepted_at]": "",
  "payload[customer][verified]": "false",
  "payload[customer][portal_customer_created_at]": "",
  "payload[customer][vat_number]": "",
  "payload[customer][cc_emails]": "",
  "payload[customer][tax_exempt]": "false",
  "payload[customer][tax_exempt_reason]": "",
  "payload[customer][parent_id]": "",
  "payload[customer][locale]": "",
  "payload[customer][salesforce_id]": "",
  "payload[customer][default_auto_renewal_profile_id]": "",
  "payload[site][id]": "87942",
  "payload[site][subdomain]": "testing",
  "payload[event_id]": "4833962613"
}