export default {
  "2": "value01",
  "3": "value02",
  "id": "1",
  "form_id": "1",
  "post_id": null,
  "date_created": "2010-10-10 14:31:04",
  "date_updated": "2010-10-10 14:31:04",
  "is_starred": "0",
  "is_read": "0",
  "ip": "1.23.456.78",
  "source_url": "https://gravityform.com/wp-json/gf/v2/forms/1/entries",
  "user_agent": "API",
  "currency": "USD",
  "payment_status": null,
  "payment_date": null,
  "payment_amount": null,
  "payment_method": "",
  "transaction_id": null,
  "is_fulfilled": "0",
  "created_by": "1",
  "transaction_type": null,
  "status": "active",
  "1.3": "value03",
  "1.6": "value04",
  "1.2": "",
  "1.4": "",
  "1.8": ""
}