export default {
  "id": "93d14a6d-473e-4eb3-aef5-70164b3bcbbf",
  "name": "Campaign Caroline Spencer",
  "nameVisible": true,
  "timeRangeVisible": true,
  "report": {
    "filters": [],
    "groupBy": [
      "campaign"
    ],
    "sort": "visits",
    "direction": "DESC",
    "offset": 0,
    "limit": 100,
    "textFilter": "",
    "tags": [],
    "columns": [
      "campaignName",
      "campaignId",
      "actions",
      "campaignUrl",
      "campaignWorkspaceName",
      "mtti",
      "timeToInstallRange0",
      "timeToInstallRange1",
      "timeToInstallRange2",
      "visits",
      "suspiciousVisitsPercentage",
      "visits",
      "suspiciousVisits",
      "uniqueVisits",
      "clicks",
      "suspiciousClicksPercentage",
      "clicks",
      "suspiciousClicks",
      "conversions",
      "customConversions1",
      "customRevenue1",
      "customConversions2",
      "customRevenue2",
      "customConversions3",
      "customRevenue3",
      "revenue",
      "cost",
      "profit",
      "cpv",
      "ctr",
      "cr",
      "cv",
      "roi",
      "epv",
      "epc",
      "ap",
      "ecpm",
      "ecpc",
      "ecpa"
    ],
    "conversionTimeMode": "VISIT",
    "from": "now-7d",
    "to": "now",
    "timeZone": "Etc/GMT",
    "include": "ACTIVE",
    "currency": null,
    "type": "REPORT",
    "workspaces": [],
    "timezone": "Etc/GMT"
  },
  "url": "https://shared-reports.voluum.com/?report=k9FKbUc-TrOu9XAWSzvLvw",
  "created": "2020-05-22T09:03:36.167028Z"
};
