<template><h1 id="use-connected-accounts-in-code" tabindex="-1"><a class="header-anchor" href="#use-connected-accounts-in-code" aria-hidden="true">#</a> Use connected accounts in code</h1>
<p>In a previous example, we connected our Google Sheets account and used it in a no code action. In this example, let's use the same connected account to authenticate a Google Sheets API request in code to retrieve the full contents of our sheet. Then we'll transform the data and return it in our workflow response. This example builds on the workflow created in <a href="/quickstart/" target="_blank" rel="noopener noreferrer">previous sections<ExternalLinkIcon/></a> and will cover how to:</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#scaffold-an-api-request-for-an-app-in-node-js">Scaffold an API request for an app in Node.js</RouterLink></li><li><RouterLink to="#use-a-connected-account-in-a-code-step">Use a connected account in a code step</RouterLink></li><li><RouterLink to="#use-standard-api-docs-to-customize-scaffolded-code">Use standard API docs to customize scaffolded code</RouterLink></li><li><RouterLink to="#use-a-code-snippet-from-stack-overflow-to-transform-the-api-response">Use a code snippet from Stack Overflow to transform the API response</RouterLink></li></ul></nav>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>If you didn't complete the previous examples, we recommend you start from the <a href="/quickstart/" target="_blank" rel="noopener noreferrer">beginning of this guide<ExternalLinkIcon/></a>. If you still want to start here, <a href="https://pipedream.com/@gettingstarted/quickstart-end-workflow-early-p_RRCgNRQ" target="_blank" rel="noopener noreferrer">copy this workflow<ExternalLinkIcon/></a> and then follow the instructions below. If you have any issues completing this example, you can <a href="https://pipedream.com/@gettingstarted/quickstart-use-connected-accounts-in-code-p_ezCVLgy" target="_blank" rel="noopener noreferrer">view, copy and run a completed version<ExternalLinkIcon/></a>.</p>
</div>
<h3 id="scaffold-an-api-request-for-an-app-in-node-js" tabindex="-1"><a class="header-anchor" href="#scaffold-an-api-request-for-an-app-in-node-js" aria-hidden="true">#</a> Scaffold an API request for an app in Node.js</h3>
<p>First, expand the step selector right before <code>steps.respond</code>.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525184626570.png" alt="image-20210525184626570"></p>
<p>Select the <strong>Google Sheet</strong> app and select the <strong>Run Node.js with Google Sheets</strong> action:</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525184659283.png" alt="image-20210525184659283"></p>
<p>This will add a code step <strong>scaffolded using Google Sheets' standard API together with Pipedream managed authentication</strong> (so you can easily authenticate the API request using your connected account).</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525184735774.png" alt="image-20210525184735774"></p>
<h3 id="use-a-connected-account-in-a-code-step" tabindex="-1"><a class="header-anchor" href="#use-a-connected-account-in-a-code-step" aria-hidden="true">#</a> Use a connected account in a code step</h3>
<p>Next, let's test the scaffolded code. First, select the same account you used in the previous step (to save data to Google Sheets). It needs to be the same account because we're going to retrieve data from that sheet in just a moment.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/select-account.gif" alt="select-account"></p>
<p>Then <strong>Deploy</strong> and test your workflow (either load the endpoint or click <strong>Send Test Event</strong>). Select an event that executed this step to inspect the exports — you should see the response from Google's <code>/userinfo</code> API.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525185209154.png" alt="image-20210525185209154"></p>
<h3 id="use-standard-api-docs-to-customize-scaffolded-code" tabindex="-1"><a class="header-anchor" href="#use-standard-api-docs-to-customize-scaffolded-code" aria-hidden="true">#</a> Use standard API docs to customize scaffolded code</h3>
<p>Next, let's customize the API request to retrieve all the ISS positions we added to Google Sheets in our previous tests so we can return them in our workflow response. Based on a quick Google search, we can find the details we need in <a href="https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get" target="_blank" rel="noopener noreferrer">Google's developer documentation<ExternalLinkIcon/></a>. According to Google's docs, we need to make a <code>GET</code> request to <code>https://sheets.googleapis.com/v4/spreadsheets/{spreadsheetId}/values/{range}</code>.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210522195448627.png" alt="image-20210522195448627"></p>
<p>We need to replace the <code>url</code> in the scaffolded code, and we also need to modify the URL we found in Google's docs to pass real values for  <code>{spreadsheetId}</code> and <code>{range}</code>. Since we added a row to Google Sheets, we can get these values by referencing the exports for <code>steps.add_single_row</code>.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525185600151.png" alt="image-20210525185600151"></p>
<p>Here's the final code for the step that shows the updated value for the <code>url</code> parameter (more details below):</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">return</span> <span class="token keyword">await</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@pipedreamhq/platform"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">axios</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://sheets.googleapis.com/v4/spreadsheets/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>steps<span class="token punctuation">.</span>add_single_row<span class="token punctuation">.</span>$return_value<span class="token punctuation">.</span>spreadsheetId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/values/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>steps<span class="token punctuation">.</span>add_single_row<span class="token punctuation">.</span>$return_value<span class="token punctuation">.</span>updatedRange<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">"!"</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">headers</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">Authorization</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Bearer </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>auths<span class="token punctuation">.</span>google_sheets<span class="token punctuation">.</span>oauth_access_token<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525185700814.png" alt="image-20210525185700814"></p>
<p>Here are more details about the changes we made in the code above (you can also skip this and move on to deploying and testing the update):</p>
<ol>
<li>Add a <code>$</code> before both <code>{spreadsheetId}</code> and <code>{range}</code> to convert the references to <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals" target="_blank" rel="noopener noreferrer">template literals<ExternalLinkIcon/></a> (since the URL in enclosed in backticks, we can write code between <code>${...}</code>).</li>
<li>Replace <code>spreadsheetId</code> with <code>steps.add_single_row.$return_value.spreadsheetId</code>.</li>
<li>Since we want to get all the values in the sheet, we can use Javascript's <code>split()</code> function to replace <code>range</code> with the value to the left of the exclamation mark in <code>steps.add_single_row.$return_value.updatedRange</code> (i.e., we only want to pass the value <code>Sheet1</code>). To do that, we can reference <code>steps.add_single_row.$return_value.updatedRange.split(&quot;!&quot;)[0]</code>.</li>
</ol>
<p>When you're ready, <strong>Deploy</strong> and test your workflow again. If you select the event and expand the return value for <code>steps.google_sheets</code> you'll see the headers and data from the Google Sheet.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525185811243.png" alt="image-20210525185811243"></p>
<h3 id="use-a-code-snippet-from-stack-overflow-to-transform-the-api-response" tabindex="-1"><a class="header-anchor" href="#use-a-code-snippet-from-stack-overflow-to-transform-the-api-response" aria-hidden="true">#</a> Use a code snippet from Stack Overflow to transform the API response</h3>
<p>While we can update our workflow response to return <code>steps.google_sheets.$return_value</code>, let's add one more code step to transform it from an array of arrays to an array of objects (using the header values for the keys). Since we can easily transform data using Node.js, we can write the code if we know it or we can search Google for snippets to adapt. In this case, a quick Google Search turns up a <a href="https://stackoverflow.com/questions/58050534/javascript-make-a-key-value-data-structure-from-2-dimensional-arrayheader-row" target="_blank" rel="noopener noreferrer">Stack Overflow post<ExternalLinkIcon/></a> with sample code we can use as a starting point.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210522200959041.png" alt="image-20210522200959041"></p>
<p>Add a <strong>Run Node.js code</strong> step between <code>steps.google_sheets</code> and <code>steps.respond</code> and name it <code>steps.transform</code>. Then add the code we adapted from the Stack Overflow post (more details below):</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> data <span class="token operator">=</span> steps<span class="token punctuation">.</span>google_sheets<span class="token punctuation">.</span>$return_value<span class="token punctuation">.</span>values
<span class="token keyword">const</span> headers <span class="token operator">=</span> data<span class="token punctuation">.</span><span class="token function">shift</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> rows <span class="token operator">=</span> data
<span class="token keyword">return</span> <span class="token function">rowsToObjects</span><span class="token punctuation">(</span>headers<span class="token punctuation">,</span> rows<span class="token punctuation">)</span>

<span class="token keyword">function</span> <span class="token function">rowsToObjects</span><span class="token punctuation">(</span><span class="token parameter">headers<span class="token punctuation">,</span> rows</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  <span class="token keyword">return</span> rows<span class="token punctuation">.</span><span class="token function">reduce</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">acc<span class="token punctuation">,</span> e<span class="token punctuation">,</span> idx</span><span class="token punctuation">)</span> <span class="token operator">=></span>  <span class="token punctuation">{</span>
     acc<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>headers<span class="token punctuation">.</span><span class="token function">reduce</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">r<span class="token punctuation">,</span> h<span class="token punctuation">,</span> i</span><span class="token punctuation">)</span><span class="token operator">=></span> <span class="token punctuation">{</span>r<span class="token punctuation">[</span>h<span class="token punctuation">]</span> <span class="token operator">=</span> e<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token keyword">return</span> r<span class="token punctuation">;</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
     <span class="token keyword">return</span> acc<span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525185923633.png" alt="image-20210525185923633"></p>
<p>Here are more details about the changes (you can also skip ahead to deploy and test):</p>
<ol>
<li>Set <code>headers</code> to the the first array element of <code>steps.google_sheets.$return_value.values</code></li>
<li>Set <code>rows</code> to the remainder of the array (i.e., the elements with the data)</li>
<li>Return the result of <code>rowsToObjects(headers, rows) </code> to export it from the step so we can reference it in our response</li>
<li>We can delete the <code>console.log</code> statement and the comment</li>
</ol>
<p>Next, <strong>Deploy</strong> and test your workflow to validate the step returns the data you expect.</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525190008161.png" alt="image-20210525190008161"></p>
<p>Next, update <code>steps.respond</code> to return <code>steps.transform.$return_value</code> as the body of the HTTP response.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">await</span> <span class="token function">$respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
  <span class="token literal-property property">immediate</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
  <span class="token literal-property property">body</span><span class="token operator">:</span> steps<span class="token punctuation">.</span>transform<span class="token punctuation">.</span>$return_value
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525190105053.png" alt="image-20210525190105053"></p>
<p>Finally, <strong>Deploy</strong> and load the endpoint URL for your workflow in a browser. You should see the data from Google Sheets with all the positions you recorded for the ISS returned as your workflow response (including the most recent position recorded when you loaded the endpoint):</p>
<p><img src="@source/quickstart/use-managed-auth-in-code/images/image-20210525190356903.png" alt="image-20210525190356903"></p>
<p>This was all done without exposing any API keys on the client side.</p>
<p><strong>Next, we'll run a simple workflow on a schedule to keep this serverless workflow &quot;warm&quot;.</strong></p>
<p style="text-align:center;">
<a :href="$withBase('/quickstart/run-workflow-on-a-schedule/')"><img src="@source/quickstart/next.png"></a>
</p>
</template>
