export default {
  "archived": false,
  "author": null,
  "authorWithFallback": "The Pipedream team",
  "content": "{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"attrs\":{\"textAlign\":\"left\"},\"content\":[{\"text\":\"content markdown\",\"type\":\"text\"}]}]}",
  "contentHtml": "<p>content markdown</p>",
  "contentPlainText": "content markdown",
  "contentType": "tiptap",
  "createdAt": "2024-08-22T21:42:14Z",
  "deactivatedAt": null,
  "description": null,
  "descriptionWithFallback": "content markdown",
  "doNotIndex": false,
  "excerpt": null,
  "excerptWithFallback": "content markdown",
  "feedbackHappyCount": 0,
  "feedbackMehCount": 0,
  "feedbackSadCount": 0,
  "hasPendingContentGenerators": false,
  "headline": "HeadLine Test",
  "id": "ann_Y67GCQmyBKwYN",
  "inPublishedDigest": false,
  "name": "HeadLine Test",
  "notificationsExcerptOnly": false,
  "privatePermalink": "https://app.launchnotes.com/projects/pro_uHApc6EZ/announcements/ann_Y6yBKwYN/published",
  "publicPermalink": "https://pipedream.launchnotes.io/announcements/headline-test",
  "publishedAt": null,
  "scheduledAt": null,
  "scheduledAtTimezone": null,
  "shouldNotifyPageSubscribers": false,
  "slackChannelCount": 0,
  "slackChannelCounts": 0,
  "slackMessage": null,
  "slug": "headline-test",
  "state": "scheduled",
  "subjectLine": null,
  "subjectLineWithFallback": "HeadLine Test",
  "title": null,
  "titleWithFallback": "HeadLine Test",
  "totalSubscriberCounts": 0,
  "updatedAt": "2024-08-22T21:42:15Z"
}