const SUBDOMAIN_PLACEHOLDER = "{SUBDOMAIN_PLACEHOLDER}";
const BASE_URL = `https://${SUBDOMAIN_PLACEHOLDER}.ftrackapp.com`;
const VERSION_PATH = "/api";
const DEFAULT_MAX = 600;
const DEFAUL_LIMIT = 20;
const LAST_CREATED_AT = "lastCreatedAt";

export default {
  SUBDOMAIN_PLACEHOLDER,
  BASE_URL,
  VERSION_PATH,
  DEFAULT_MAX,
  DEFAUL_LIMIT,
  LAST_CREATED_AT,
};
