export default {
  "data": {
    "attributes": {
      "access_expires_at": null,
      "campaign_currency": "USD",
      "campaign_lifetime_support_cents": 12345,
      "campaign_pledge_amount_cents": 50,
      "full_name": "Test Person",
      "is_follower": false,
      "is_free_member": null,
      "is_free_trial": null,
      "last_charge_date": "2014-04-01T00:00:00.000+00:00",
      "last_charge_status": "Paid",
      "lifetime_support_cents": 12345,
      "patron_status": "active_patron",
      "pledge_amount_cents": 50,
      "pledge_relationship_start": "2014-03-14T00:00:00.000+00:00",
    },
    "id": null,
    "relationships": {
      "address": {
        "data": null,
      },
      "campaign": {
        "data": {
          "id": "11463541",
          "type": "campaign",
        },
        "links": {
          "related": "https://www.patreon.com/api/campaigns/11463541",
        },
      },
      "user": {
        "data": {
          "id": "109949250",
          "type": "user",
        },
        "links": {
          "related": "https://www.patreon.com/api/user/109949250",
        },
      },
    },
    "type": "member",
  },
  "included": [
    {
      "attributes": {
        "avatar_photo_image_urls": {
          "default": "",
          "default_small": "",
          "original": "",
          "thumbnail": "",
          "thumbnail_large": "",
          "thumbnail_small": "",
        },
        "avatar_photo_url": "",
        "campaign_pledge_sum": 0,
        "cover_photo_url": "",
        "cover_photo_url_sizes": {
          "large": "",
          "medium": "",
          "small": "",
          "xlarge": "",
          "xsmall": "",
        },
        "created_at": "2023-12-11T18:32:08.000+00:00",
        "creation_count": 1,
        "creation_name": "",
        "currency": "USD",
        "discord_server_id": null,
        "display_patron_goals": false,
        "earnings_visibility": "public",
        "image_small_url": "",
        "image_url": "",
        "is_charge_upfront": true,
        "is_charged_immediately": true,
        "is_monthly": true,
        "is_nsfw": false,
        "is_plural": false,
        "main_video_embed": null,
        "main_video_url": null,
        "name": "testing",
        "one_liner": null,
        "outstanding_payment_amount_cents": 0,
        "paid_member_count": 0,
        "patron_count": 0,
        "pay_per_name": "month",
        "pledge_sum": 0,
        "pledge_sum_currency": "USD",
        "pledge_url": "/checkout/testing",
        "published_at": "2023-12-11T18:43:16.000+00:00",
        "summary": null,
        "thanks_embed": null,
        "thanks_msg": null,
        "thanks_video_url": null,
        "url": "https://www.patreon.com/testing",
      },
      "id": "11463541",
      "relationships": {
        "creator": {
          "data": {
            "id": "109949250",
            "type": "user",
          },
          "links": {
            "related": "https://www.patreon.com/api/user/109949250",
          },
        },
        "goals": {
          "data": null,
        },
        "rewards": {
          "data": [
            {
              "id": "-1",
              "type": "reward",
            },
            {
              "id": "21806983",
              "type": "reward",
            },
            {
              "id": "21807044",
              "type": "reward",
            },
          ],
        },
      },
      "type": "campaign",
    },
    {
      "attributes": {
        "about": null,
        "age_verification_status": null,
        "apple_id": null,
        "can_see_nsfw": null,
        "created": "2023-12-11T18:31:00.000+00:00",
        "current_user_block_status": "none",
        "default_country_code": null,
        "discord_id": null,
        "email": "test@example.com",
        "facebook": null,
        "facebook_id": null,
        "first_name": "Test",
        "full_name": "Test Person",
        "gender": 2,
        "google_id": "117665792695448708367",
        "has_password": false,
        "image_url": "",
        "is_deleted": false,
        "is_email_verified": true,
        "is_nuked": false,
        "is_suspended": false,
        "last_name": "Person",
        "patron_currency": "USD",
        "social_connections": {
          "discord": null,
          "facebook": null,
          "google": null,
          "instagram": null,
          "reddit": null,
          "spotify": null,
          "spotify_open_access": null,
          "twitch": null,
          "twitter": null,
          "vimeo": null,
          "youtube": null,
        },
        "thumb_url": "",
        "twitch": null,
        "twitter": null,
        "url": "https://www.patreon.com/testing",
        "vanity": "testing",
        "youtube": null,
      },
      "id": "109949250",
      "relationships": {
        "campaign": {
          "data": {
            "id": "11463541",
            "type": "campaign",
          },
          "links": {
            "related": "https://www.patreon.com/api/campaigns/11463541",
          },
        },
      },
      "type": "user",
    },
    {
      "attributes": {
        "amount": 0,
        "amount_cents": 0,
        "created_at": null,
        "description": "Everyone",
        "patron_currency": "USD",
        "remaining": 0,
        "requires_shipping": false,
        "url": null,
        "user_limit": null,
      },
      "id": "-1",
      "type": "reward",
    },
    {
      "attributes": {
        "amount": 0,
        "amount_cents": 0,
        "created_at": "2023-12-11T18:32:08.576+00:00",
        "currency": "USD",
        "declined_patron_count": 0,
        "description": "",
        "discord_role_ids": null,
        "edited_at": "2023-12-11T18:32:08.576+00:00",
        "image_url": null,
        "is_free_tier": true,
        "patron_amount_cents": 0,
        "patron_count": 0,
        "patron_currency": "USD",
        "post_count": 0,
        "published": true,
        "published_at": "2023-12-11T18:32:08.576+00:00",
        "remaining": null,
        "requires_shipping": false,
        "title": "Free",
        "unpublished_at": null,
        "url": "/checkout/testing?rid=21806983",
        "user_limit": null,
        "welcome_message": null,
        "welcome_message_unsafe": null,
        "welcome_video_embed": null,
        "welcome_video_url": null,
      },
      "id": "21806983",
      "relationships": {
        "campaign": {
          "data": {
            "id": "11463541",
            "type": "campaign",
          },
          "links": {
            "related": "https://www.patreon.com/api/campaigns/11463541",
          },
        },
      },
      "type": "reward",
    },
    {
      "attributes": {
        "amount": 500,
        "amount_cents": 500,
        "created_at": "2023-12-11T18:42:14.911+00:00",
        "currency": "USD",
        "declined_patron_count": 0,
        "description": "Access to exclusive content and more",
        "discord_role_ids": null,
        "edited_at": "2023-12-11T18:42:14.911+00:00",
        "image_url": null,
        "is_free_tier": false,
        "patron_amount_cents": 500,
        "patron_count": 0,
        "patron_currency": "USD",
        "post_count": 0,
        "published": true,
        "published_at": "2023-12-11T18:42:14.911+00:00",
        "remaining": null,
        "requires_shipping": false,
        "title": "",
        "unpublished_at": null,
        "url": "/checkout/testing?rid=21807044",
        "user_limit": null,
        "welcome_message": null,
        "welcome_message_unsafe": null,
        "welcome_video_embed": null,
        "welcome_video_url": null,
      },
      "id": "21807044",
      "relationships": {
        "campaign": {
          "data": {
            "id": "11463541",
            "type": "campaign",
          },
          "links": {
            "related": "https://www.patreon.com/api/campaigns/11463541",
          },
        },
      },
      "type": "reward",
    },
  ],
  "links": {
    "self": "https://www.patreon.com/api/members/None",
  },
};
