export default {
  company_name: "The Reliable Painter",
  address_line_1: "4813 Laura Jeanne Blvd",
  first_name: "Michael",
  last_name: "Hall",
  created_date: "2023-02-23 15:11:38",
  number_of_visits: "1",
  customer_name: "test two",
  customer_email: "test2@testing.com",
  phone_number: null,
  have_open_ratingrequest_email: "0",
  is_send_auto_delay: "1",
  auto_delay_hours: "0",
  auto_delay_days: "0",
  have_rate: "0",
  estimateddate: "1677186698",
  rating: null,
  feedback: null,
  customerId: "824925",
};
