const WEBHOOK_TYPE = {
  ITEM: "ITEM",
  ASSETS: "ASSETS",
  TRANSACTIONS: "TRANSACTIONS",
};

const WEBHOOK_CODE = {
  [WEBHOOK_TYPE.TRANSACTIONS]: {
    INITIAL_UPDATE: "INITIAL_UPDATE",
    HISTORICAL_UPDATE: "HISTORICAL_UPDATE",
    DEFAULT_UPDATE: "DEFAULT_UPDATE",
    TRANSACTIONS_REMOVED: "TRANSACTIONS_REMOVED",
    SYNC_UPDATES_AVAILABLE: "SYNC_UPDATES_AVAILABLE",
  },
  [WEBHOOK_TYPE.ASSETS]: {
    PRODUCT_READY: "PRODUCT_READY",
    ERROR: "ERROR",
  },
  [WEBHOOK_TYPE.ITEM]: {
    ERROR: "ERROR",
    NEW_ACCOUNTS_AVAILABLE: "NEW_ACCOUNTS_AVAILABLE",
    PENDING_EXPIRATION: "PENDING_EXPIRATION",
    USER_PERMISSION_REVOKED: "USER_PERMISSION_REVOKED",
    WEBHOOK_UPDATE_ACKNOWLEDGED: "WEBHOOK_UPDATE_ACKNOWLEDGED",
  },
};

export default {
  WEBHOOK_TYPE,
  WEBHOOK_CODE,
};
