export default {
  "accountManagerName": "mike murphy",
  "clientId": "",
  "comments": "",
  "contactOwnerName": "",
  "companyKey": "dnhYYkJCSkdCaVFJWDlpUTFDM2RWdz090",
  "modifiedBy": "YWlRZmlOQlAzS0duTUtob0x6SDgrQT090",
  "webSite": "",
  "contactOwnerKey": "",
  "companyName": "Gary Test Company",
  "active": "1",
  "createdBy": "YWlRZmlOQlAzS0duTUtob0x6SDgrQT090",
  "fax": "",
  "companyTypeName": "",
  "createdByName": "mike murphy",
  "vendor": "0",
  "phone": "",
  "dateAdded": "2018-05-08T15:17:00",
  "dateUpdated": "2018-05-08T15:17:00",
  "accountManagerKey": "YWlRZmlOQlAzS0duTUtob0x6SDgrQT090",
  "billableClient": "",
  "contactCount": "1",
  "modifiedByName": ""
}