export default {
  "id": 54321,
  "firstName": "Bob",
  "lastName": "McTest",
  "phone": "",
  "email": "bob.mctest@example.com",
  "date": "June 17, 2013",
  "time": "10:15am",
  "endTime": "11:15am",
  "dateCreated": "July 2, 2013",
  "datetime": "2013-06-17T10:15:00-0700",
  "price": "10.00",
  "paid": "no",
  "amountPaid": "0.00",
  "type": "Regular Visit",
  "appointmentTypeID": 1,
  "classID": null,
  "duration": "60",
  "calendar": "My Calendar",
  "calendarID": 27238,
  "canClientCancel": false,
  "canClientReschedule": false,
  "location": "",
  "certificate": null,
  "confirmationPage": "https://acuityscheduling.com/schedule.php?owner=11145481&id[]=1220aa9f41091c50c0cc659385cfa1d0&action=appt",
  "formsText": "...",
  "notes": "Notes",
  "timezone": "America/New_York",
  "scheduledBy": null,
  "forms": [
    {
      "id": 1,
      "name": "Example Intake Form",
      "values": [
        {
          "value": "yes",
          "name": "Is this your first visit?",
          "fieldID": 1,
          "id": 21502993,
        },
        {
          "value": "Ninja",
          "name": "What is your goal for this appointment?",
          "fieldID": 2,
          "id": 21502994,
        },
      ],
    },
  ],
  "labels": [
    {
      "id": 3,
      "name": "Completed",
      "color": "pink",
    },
  ],
};
