export const FULFILMENT_STATUS_LIST = [
  "AWAITING_PROCESSING",
  "PROCESSING",
  "SHIPPED",
  "DELIVERED",
  "WILL_NOT_DELIVER",
  "RETURNED",
  "READY_FOR_PICKUP",
  "OUT_FOR_DELIVERY",
];

export const PAYMENT_STATUS_LIST = [
  "AWAITING_PAYMENT",
  "PAID",
  "CANCELLED",
  "REFUNDED",
  "PARTIALLY_REFUNDED",
];
