export default {
  "id": 18937181,
  "created_at": "1717016636",
  "updated_at": "1717016638",
  "storefront_id": 47210,
  "salt": "a33658e5a5ca6ca9af2c731cb556ea0e81ef5dd2",
  "status": "ACT",
  "currency": "USD",
  "subtotal": "1.00",
  "discount": "0.00",
  "tax": "0.00",
  "shipping": "0.00",
  "total": "1.00",
  "processor_fee": "0.00",
  "buyer_email": "test@sample.com",
  "buyer_firstname": "George",
  "buyer_lastname": "Washington",
  "customer": {
    "id": 9437584,
    "first_name": "George",
    "last_name": "Washington",
    "email": "test@sample.com",
    "receives_email": true,
    "created_at": "1717016636",
    "updated_at": "1717016636"
  },
  "customer_notes": null,
  "custom_fields": [],
  "shipping_firstname": null,
  "shipping_lastname": null,
  "shipping_street": null,
  "shipping_street2": null,
  "shipping_city": null,
  "shipping_state": null,
  "shipping_zip_code": null,
  "shipping_country_code": null,
  "shipping_country": "",
  "shipping_phone": null,
  "shipping_vatin": null,
  "shipping_business_name": null,
  "shipping_carrier": null,
  "shipping_tracking_number": null,
  "requires_shipping": true,
  "tangibles_to_ship": 1,
  "billing_firstname": "George",
  "billing_lastname": "Washington",
  "billing_street": "1600 Pennsylvania Ave",
  "billing_street2": null,
  "billing_city": "Washington",
  "billing_state": "DC",
  "billing_zip_code": "20500",
  "billing_country_code": "US",
  "billing_card_type": null,
  "billing_card_number": null,
  "line_items": [
    {
      "id": 28023183,
      "purchase_id": 18937181,
      "product_id": 239238,
      "price": "1.00",
      "quantity": 1,
      "subtotal": "1.00",
      "tax": "0.00",
      "discount": "0.00",
      "total": "1.00",
      "product_name": "product1",
      "download_limit": 0,
      "download_count": 0,
      "expires_at": "1717103036",
      "product_keys": [],
      "has_all_keys": false
    }
  ],
  "coupons": [],
  "ip_address": "47.225.32.185",
  "marketing_optin": false
}