// @generated by integrations/pipedream/scripts/generate-from-catalog.mts — do not edit

import app from "../../social_fetch.app.mjs";

export default {
  key: "social_fetch-get-profile",
  name: "Get Profile",
  description: "Fetches public profile data. Choose platform, then handle or profile URL. [See the documentation](https://www.socialfetch.dev/docs/api)",
  version: "0.0.1",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: true,
  },
  props: {
    app,
    platform: {
      propDefinition: [
        app,
        "platform",
      ],
    },
    handle: {
      propDefinition: [
        app,
        "handle",
      ],
    },
    profileUrl: {
      propDefinition: [
        app,
        "profileUrl",
      ],
    },
  },
  async run({ $ }) {
    const response = await this.app.getProfile({
      $,
      platform: this.platform,
      handle: this.handle,
      profileUrl: this.profileUrl,
    });
    const label = this.app.profileSummaryLabel(
      this.platform,
      this.handle,
      this.profileUrl,
    );
    $.export("$summary", `Successfully fetched profile for **${label}**`);
    return response;
  },
};
