import surecart from "../../surecart.app.mjs";

export default {
  key: "surecart-create-product",
  name: "Create Product",
  description: "Create a new product. [See the documentation](https://developer.surecart.com/api-reference/products/create)",
  version: "0.0.1",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: false,
  },
  props: {
    surecart,
    name: {
      type: "string",
      label: "Name",
      description: "The product name, shown to customers. Example: `Premium Plan`",
    },
    description: {
      type: "string",
      label: "Description",
      description: "The product description, shown to customers.",
      optional: true,
    },
    status: {
      type: "string",
      label: "Status",
      description: "The status of the product.",
      optional: true,
      options: [
        "draft",
        "published",
      ],
    },
    sku: {
      type: "string",
      label: "SKU",
      description: "The stock keeping unit for this product. Example: `PLAN-001`",
      optional: true,
    },
    slug: {
      type: "string",
      label: "Slug",
      description: "A unique, URL-friendly identifier. Auto-generated from the name if omitted. Example: `premium-plan`",
      optional: true,
    },
    recurring: {
      type: "boolean",
      label: "Recurring",
      description: "Set to `true` for a subscription product, `false` for a one-time purchase.",
      optional: true,
    },
    featured: {
      type: "boolean",
      label: "Featured",
      description: "Set to `true` to mark the product as featured.",
      optional: true,
    },
    taxEnabled: {
      type: "boolean",
      label: "Tax Enabled",
      description: "Set to `true` to make this product taxable.",
      optional: true,
    },
    taxCategory: {
      type: "string",
      label: "Tax Category",
      description: "The tax category that matches this product.",
      optional: true,
      options: [
        "digital",
        "tangible",
        "service",
        "saas",
      ],
    },
    shippingEnabled: {
      type: "boolean",
      label: "Shipping Enabled",
      description: "Set to `true` to require a full shipping address at checkout.",
      optional: true,
    },
    weight: {
      type: "string",
      label: "Weight",
      description: "The product weight, used for shipping calculations. Accepts decimals. Example: `1.5`",
      optional: true,
    },
    weightUnit: {
      type: "string",
      label: "Weight Unit",
      description: "The weight unit for this product.",
      optional: true,
      options: [
        "lb",
        "oz",
        "kg",
        "g",
      ],
    },
    stockEnabled: {
      type: "boolean",
      label: "Stock Enabled",
      description: "Set to `true` to track stock for this product.",
      optional: true,
    },
    stockAdjustment: {
      type: "integer",
      label: "Stock Adjustment",
      description: "Amount to adjust the stock by (positive or negative). Example: `100`",
      optional: true,
    },
    allowOutOfStockPurchases: {
      type: "boolean",
      label: "Allow Out Of Stock Purchases",
      description: "Set to `true` to allow purchases when stock runs out.",
      optional: true,
    },
    purchaseLimit: {
      type: "integer",
      label: "Purchase Limit",
      description: "Max number of times a customer can purchase this product. Example: `5`",
      min: 1,
      optional: true,
    },
    reviewsEnabled: {
      type: "boolean",
      label: "Reviews Enabled",
      description: "Set to `true` to enable reviews for this product.",
      optional: true,
    },
    licensingEnabled: {
      type: "boolean",
      label: "Licensing Enabled",
      description: "Set to `true` to enable licensing for this product.",
      optional: true,
    },
    licenseActivationLimit: {
      type: "integer",
      label: "License Activation Limit",
      description: "Max activations allowed per license. Leave empty for unlimited. Example: `5`",
      min: 1,
      optional: true,
    },
    productGroup: {
      type: "string",
      label: "Product Group ID",
      description: "The UUID of the product group to assign this product to.",
      optional: true,
    },
    shippingProfile: {
      type: "string",
      label: "Shipping Profile ID",
      description: "The UUID of the shipping profile to assign this product to.",
      optional: true,
    },
    productCollections: {
      type: "string[]",
      label: "Product Collection IDs",
      description: "UUIDs of the product collections this product belongs to.",
      optional: true,
    },
    metadata: {
      type: "object",
      label: "Metadata",
      description: "Additional key-value metadata. Example: `{ \"internal_id\": \"123\" }`",
      optional: true,
    },
  },
  async run({ $ }) {
    const response = await this.surecart.createProduct({
      $,
      data: {
        product: {
          name: this.name,
          description: this.description,
          status: this.status,
          sku: this.sku,
          slug: this.slug,
          recurring: this.recurring,
          featured: this.featured,
          tax_enabled: this.taxEnabled,
          tax_category: this.taxCategory,
          shipping_enabled: this.shippingEnabled,
          weight: this.weight && Number(this.weight),
          weight_unit: this.weightUnit,
          stock_enabled: this.stockEnabled,
          stock_adjustment: this.stockAdjustment,
          allow_out_of_stock_purchases: this.allowOutOfStockPurchases,
          purchase_limit: this.purchaseLimit,
          reviews_enabled: this.reviewsEnabled,
          licensing_enabled: this.licensingEnabled,
          license_activation_limit: this.licenseActivationLimit,
          product_group: this.productGroup,
          shipping_profile: this.shippingProfile,
          product_collections: this.productCollections,
          metadata: this.metadata,
        },
      },
    });
    $.export("$summary", `Successfully created product ${response.id}`);
    return response;
  },
};
