export default {
  "id": "21511366947",
  "properties": {
    "about_us": null,
    "address": null,
    "address2": null,
    "annualrevenue": null,
    "city": null,
    "country": null,
    "createdate": "2024-06-20T03:09:18.816Z",
    "description": null,
    "domain": null,
    "founded_year": null,
    "hs_createdate": null,
    "hs_lastmodifieddate": "2024-06-20T03:09:23.664Z",
    "hs_object_id": "21511366947",
    "industry": null,
    "is_public": null,
    "lifecyclestage": "lead",
    "name": "Company",
    "numberofemployees": null,
    "owneremail": null,
    "ownername": null,
    "phone": null,
    "state": null,
    "timezone": null,
    "total_money_raised": null,
    "total_revenue": null,
    "type": null,
    "web_technologies": null,
    "website": null,
    "zip": null
  },
  "createdAt": "2024-06-20T03:09:18.816Z",
  "updatedAt": "2024-06-20T03:09:23.664Z",
  "archived": false
}