const BASE_URL = "https://rest.clicksend.com";
const VERSION_PATH = "/v3";
const WEBHOOK_ID = "webhookId";
const DEFAULT_LIMIT = 50;

const DISABLED = 0;
const ENABLED = 1;

const MSG_SEARCH_TYPE = {
  ANY_MSG: 0,
  STARTS_WITH: 1,
  CONTAINS: 2,
  DOES_NOT_CONTAIN: 3,
};

const ACTION = {
  AUTO_REPLY: "AUTO_REPLY",
  EMAIL_USER: "EMAIL_USER",
  EMAIL_FIXED: "EMAIL_FIXED",
  URL: "URL",
  SMS: "SMS",
  POLL: "POLL",
  GROUP_SMS: "GROUP_SMS",
  MOVE_CONTACT: "MOVE_CONTACT",
  CREATE_CONTACT: "CREATE_CONTACT",
  CREATE_CONTACT_PLUS_EMAIL: "CREATE_CONTACT_PLUS_EMAIL",
  CREATE_CONTACT_PLUS_NAME_EMAIL: "CREATE_CONTACT_PLUS_NAME_EMAIL",
  CREATE_CONTACT_PLUS_NAME: "CREATE_CONTACT_PLUS_NAME",
  SMPP: "SMPP",
  NONE: "NONE",
};

const WEBHOOK_TYPE = {
  POST: "post",
  GET: "get",
  JSON: "json",
};

const MATCH_TYPE = {
  ALL_REPORTS: 0,
};

export default {
  BASE_URL,
  VERSION_PATH,
  DEFAULT_LIMIT,
  WEBHOOK_ID,
  DISABLED,
  ENABLED,
  MSG_SEARCH_TYPE,
  ACTION,
  WEBHOOK_TYPE,
  MATCH_TYPE,
};
