<template><h1 id="emit-events" tabindex="-1"><a class="header-anchor" href="#emit-events" aria-hidden="true">#</a> Emit events</h1>
<p>Like <a href="/event-sources/" target="_blank" rel="noopener noreferrer">event sources<ExternalLinkIcon/></a>, workflows can emit events. These events can trigger other workflows, or be consumed using Pipedream's <a href="/api/rest/#get-workflow-emits" target="_blank" rel="noopener noreferrer">REST API<ExternalLinkIcon/></a>.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#using-send-emit-in-workflows">Using $.send.emit() in workflows</RouterLink></li><li><RouterLink to="#using-send-emit-in-component-actions">Using $.send.emit in component actions</RouterLink></li><li><RouterLink to="#trigger-a-workflow-from-emitted-events">Trigger a workflow from emitted events</RouterLink></li><li><RouterLink to="#consuming-emitted-events-via-rest-api">Consuming emitted events via REST API</RouterLink></li><li><RouterLink to="#emit-logs-troubleshooting">Emit logs / troubleshooting</RouterLink></li></ul></nav>
<h2 id="using-send-emit-in-workflows" tabindex="-1"><a class="header-anchor" href="#using-send-emit-in-workflows" aria-hidden="true">#</a> Using <code>$.send.emit()</code> in workflows</h2>
<p>You can emit arbitrary events from any <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">Node.js code steps<ExternalLinkIcon/></a> using <code>$.send.emit()</code>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">raw_event</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Yoda"</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p><code>$.send.emit()</code> accepts an object with the following properties:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>$<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  raw_event<span class="token punctuation">,</span> <span class="token comment">// An object that contains the event you'd like to emit</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="using-send-emit-in-component-actions" tabindex="-1"><a class="header-anchor" href="#using-send-emit-in-component-actions" aria-hidden="true">#</a> Using <code>$.send.emit</code> in component actions</h2>
<p>If you're authoring a <a href="/components/actions/" target="_blank" rel="noopener noreferrer">component action<ExternalLinkIcon/></a>, you can emit data using <code>$.send.emit</code>.</p>
<p><code>$.send.emit</code> functions the same as <a href="#using-send-emit-in-workflows"><code>$.send.emit</code> in workflow code steps</a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">raw_event</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Yoda"</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p><strong>Destination delivery is asynchronous</strong>: emits are sent after your workflow finishes.</p>
<p>You can call <code>$.send.emit()</code> multiple times within a workflow, for example: to iterate over an array of values and emit an event for each.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> names <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Luke"</span><span class="token punctuation">,</span> <span class="token string">"Han"</span><span class="token punctuation">,</span> <span class="token string">"Leia"</span><span class="token punctuation">,</span> <span class="token string">"Obi Wan"</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> name <span class="token keyword">of</span> names<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">raw_event</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          name<span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h2 id="trigger-a-workflow-from-emitted-events" tabindex="-1"><a class="header-anchor" href="#trigger-a-workflow-from-emitted-events" aria-hidden="true">#</a> Trigger a workflow from emitted events</h2>
<p>We call the events you emit from a workflow <strong>emitted events</strong>. Sometimes, you'll want emitted events to trigger another workflow. This can be helpful when:</p>
<ul>
<li>You process events from different workflows in the same way. For example, you want to log events from many workflows to Amazon S3 or a logging service. You can write one workflow that handles logging, then <code>$.send.emit()</code> events from other workflows that are consumed by the single, logging workflow. This helps remove duplicate logic from the other workflows.</li>
<li>Your workflow is complex and you want to separate it into multiple workflows to group logical functions together. You can <code>$.send.emit()</code> events from one workflow to another to chain the workflows together.</li>
</ul>
<p>Here's how to configure a workflow to listen for emitted events.</p>
<ol>
<li>Currently, you can't select emitted events as a workflow trigger from the Pipedream UI. We'll show you how add the trigger via API. First, pick an existing workflow where you'd like to receive emitted events. <strong>If you want to start with a <a href="https://pipedream.com/new" target="_blank" rel="noopener noreferrer">new workflow<ExternalLinkIcon/></a>, just select the HTTP / Webhook trigger</strong>.</li>
<li>This workflow is called the <strong>listener</strong>. The workflow where you'll use <code>$.send.emit()</code> is called the <strong>emitter</strong>. If you haven't created the emitter workflow yet, <a href="https://pipedream.com/new" target="_blank" rel="noopener noreferrer">do that now<ExternalLinkIcon/></a>.</li>
<li>Get the workflow IDs of both the listener and emitter workflows. <strong>You'll find the workflow ID in the workflow's URL in your browser bar — it's the <code>p_abc123</code> in <code>https://pipedream.com/@username/p_abc123/</code></strong>.</li>
<li>You can use the Pipedream REST API to configure the listener to receive events from the emitter. We call this <a href="/api/rest/#listen-for-events-from-another-source-or-workflow" target="_blank" rel="noopener noreferrer">creating a subscription<ExternalLinkIcon/></a>. If your listener's ID is <code>p_abc123</code> and your emitter's ID is <code>p_def456</code>, you can run the following command to create this subscription:</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> <span class="token string">"https://api.pipedream.com/v1/subscriptions?emitter_id=dc_def456&amp;listener_id=p_abc123"</span> <span class="token punctuation">\</span>
  -X POST <span class="token punctuation">\</span>
  -H <span class="token string">"Authorization: Bearer &lt;api_key>"</span> <span class="token punctuation">\</span>
  -H <span class="token string">"Content-Type: application/json"</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><ol start="5">
<li>Run your emitter workflow, emitting an event using <code>$.send.emit()</code>:</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">raw_event</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Yoda"</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>This should trigger your listener, and you should see the same event in <a href="/workflows/events/inspect/#the-inspector" target="_blank" rel="noopener noreferrer">the event inspector<ExternalLinkIcon/></a>.</p>
<p><strong>Note</strong>: since configuring this trigger happens via API, you also won't see the emitted event appear as the trigger for your your listener. Please upvote <a href="https://github.com/PipedreamHQ/pipedream/issues/241" target="_blank" rel="noopener noreferrer">this issue<ExternalLinkIcon/></a> if you'd like to see UI support for that. Please upvote <a href="https://github.com/PipedreamHQ/pipedream/issues/682" target="_blank" rel="noopener noreferrer">this issue<ExternalLinkIcon/></a> to see support for <em>adding</em> emitted events as a workflow trigger in the UI.</p>
<h2 id="consuming-emitted-events-via-rest-api" tabindex="-1"><a class="header-anchor" href="#consuming-emitted-events-via-rest-api" aria-hidden="true">#</a> Consuming emitted events via REST API</h2>
<p><code>$.send.emit()</code> can emit any data you'd like. You can retrieve that data using Pipedream's REST API endpoint for <a href="/api/rest/#get-workflow-emits" target="_blank" rel="noopener noreferrer">retrieving emitted events<ExternalLinkIcon/></a>.</p>
<p>This can be helpful when you want a workflow to process data asynchronously using a workflow. You can save the results of your workflow with <code>$.send.emit()</code>, and only retrieve the results in batch when you need to using the REST API.</p>
<h2 id="emit-logs-troubleshooting" tabindex="-1"><a class="header-anchor" href="#emit-logs-troubleshooting" aria-hidden="true">#</a> Emit logs / troubleshooting</h2>
<p>Below your code step, you'll see both the data that was sent in the emit. If you ran <code>$.send.emit()</code> multiple times within the same code step, you'll see the data that was emitted for each.</p>
<Footer />
</template>
