export default {
  "Id": 1,
  "ShowFrom": "2024-09-03T00:00:00-04:00",
  "Active": true,
  "ShowTill": null,
  "Title": null,
  "Content": "Hello world",
  "Type": 1,
  "File": null,
  "Url": null,
  "ConfirmText": "",
  "Keyword": "Hello world",
  "DisableComment": false,
  "Creator": 1,
  "Created": "2024-09-03T15:25:14-04:00",
  "Modified": "2024-09-03T15:25:14-04:00",
  "_DPMetaData": {
    "System": "Memo",
    "CreatorInfo": {
      "Id": 1,
      "DisplayName": "Test User",
      "EmployeeProfile": 1,
      "Employee": 1,
      "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=M+B&width=135&height=135",
      "Pronouns": 0,
      "CustomPronouns": null
    },
    "Companies": [
      {
        "Id": 1,
        "Portfolio": null,
        "Code": "223",
        "Active": true,
        "ParentCompany": 0,
        "CompanyName": "Testing",
        "TradingName": "",
        "BusinessNumber": "",
        "CompanyNumber": null,
        "IsWorkplace": true,
        "IsPayrollEntity": true,
        "PayrollExportCode": "",
        "Address": 157,
        "Contact": 14,
        "Creator": 1,
        "Created": "2009-04-08T00:53:33-04:00",
        "Modified": "2024-09-03T13:23:43-04:00",
        "_DPMetaData": {
          "System": "Company",
          "CreatorInfo": {
            "Id": 1,
            "DisplayName": "Test User",
            "EmployeeProfile": 1,
            "Employee": 1,
            "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=M+B&width=135&height=135",
            "Pronouns": 0,
            "CustomPronouns": null
          },
          "AddressObject": {
            "Id": 157,
            "ContactName": null,
            "UnitNo": null,
            "StreetNo": null,
            "SuiteNo": null,
            "PoBox": null,
            "Street1": "San Francisco\n",
            "Street2": null,
            "City": null,
            "State": "34",
            "Postcode": null,
            "Country": 224,
            "Phone": null,
            "Notes": null,
            "Format": null,
            "Saved": null,
            "Creator": 1,
            "Created": "2024-09-03T13:23:43-04:00",
            "Modified": "2024-09-03T13:23:43-04:00",
            "Verified": null,
            "Print": "San Francisco\n\n"
          },
          "Geo": {
            "Id": 1,
            "Orm": "DeputecCompany",
            "RecId": 1,
            "Longitude": -85.771997,
            "Latitude": 43.5502974,
            "Accuracy": null,
            "No": null,
            "Street": null,
            "Suburb": null,
            "State": null,
            "Postcode": null,
            "Country": null,
            "Action": null,
            "Creator": 1,
            "Created": "2024-09-03T13:22:56-04:00",
            "Modified": "2024-09-03T13:23:43-04:00"
          },
          "CustomData": {
            "GooglePlaceId": null
          }
        }
      },
      {
        "Id": 2,
        "Portfolio": null,
        "Code": "Pip",
        "Active": true,
        "ParentCompany": 1,
        "CompanyName": "Pipedream",
        "TradingName": null,
        "BusinessNumber": null,
        "CompanyNumber": null,
        "IsWorkplace": true,
        "IsPayrollEntity": true,
        "PayrollExportCode": null,
        "Address": 158,
        "Contact": null,
        "Creator": 1,
        "Created": "2024-09-03T14:45:43-04:00",
        "Modified": "2024-09-03T14:45:43-04:00",
        "_DPMetaData": {
          "System": "Company",
          "CreatorInfo": {
            "Id": 1,
            "DisplayName": "Test User",
            "EmployeeProfile": 1,
            "Employee": 1,
            "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=M+B&width=135&height=135",
            "Pronouns": 0,
            "CustomPronouns": null
          },
          "AddressObject": {
            "Id": 158,
            "ContactName": null,
            "UnitNo": null,
            "StreetNo": null,
            "SuiteNo": null,
            "PoBox": null,
            "Street1": "44 Montgomery St., San Francisco, CA 94104",
            "Street2": null,
            "City": null,
            "State": "15",
            "Postcode": null,
            "Country": 224,
            "Phone": null,
            "Notes": null,
            "Format": null,
            "Saved": null,
            "Creator": 1,
            "Created": "2024-09-03T14:45:43-04:00",
            "Modified": "2024-09-03T14:45:43-04:00",
            "Verified": null,
            "Print": "44 Montgomery St., San Francisco, CA 94104\n"
          },
          "Geo": {
            "Id": 2,
            "Orm": "DeputecCompany",
            "RecId": 2,
            "Longitude": -122.401906,
            "Latitude": 37.7897312,
            "Accuracy": null,
            "No": null,
            "Street": null,
            "Suburb": null,
            "State": null,
            "Postcode": null,
            "Country": null,
            "Action": null,
            "Creator": 1,
            "Created": "2024-09-03T14:45:43-04:00",
            "Modified": "2024-09-03T14:45:43-04:00"
          },
          "CustomData": {
            "GooglePlaceId": null
          }
        }
      }
    ],
    "Teams": [],
    "CanDelete": true,
    "Files": [],
    "AssignedUsers": [
      {
        "Id": 1,
        "DisplayName": "Test User",
        "EmployeeProfile": 1,
        "Employee": 1,
        "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=M+B&width=135&height=135",
        "Pronouns": 0,
        "CustomPronouns": null
      }
    ],
    "Reactions": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0
    },
    "UserReaction": [],
    "Comments": [],
    "RequireConfirmation": false,
    "RequireMyConfirm": false,
    "MemoLogs": []
  }
}