const SIZE_OPTIONS = [
  "s",
  "m",
  "l",
  "xl",
  "xxl",
  "xxxl",
  "custom",
];

const QUITE_ZONE_OPTIONS = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
];

const ERROR_CORRECTION_OPTIONS = [
  "L",
  "M",
  "Q",
  "H",
];

const DATA_PATTERN_OPTIONS = [
  "RECT",
  "ROUND",
  "MINI_LEAF",
  "CHIPS",
  "FIREFLY",
  "ROUNDED_CORNERS",
  "VERTICAL_PIPES",
  "HORIZONTAL_PIPES",
  "VERTICAL_NIGHT_LIFE",
  "HORIZONTAL_NIGHT_LIFE",
  "PANCARDS",
  "CURVED_RECTS",
  "NAWABI_DARWAZA",
  "ROTATED_SQUARES",
  "ROTATED_RECTS",
  "HAND_IN_HANDS",
  "RANDOM_ROTATE",
  "ALTERNATE_DIAGONAL",
  "CIRCLE_ON_CORNERS",
  "CONNECTED_HAMMERS",
  "CONNECTED_CIRCLES",
  "POINTED_BEAKS",
  "MAZE",
  "CURVED_MAZE",
  "TRIANGLES",
  "VERTICAL_TRIANGLES",
  "HORIZONTAL_TRIANGLES",
  "HUT",
  "CIRCULAR_DIAGONAL",
  "LIGHT_CIRCLE",
  "LIGHT_SQUARE",
  "LIGHT_ROUNDED_CORNERS",
  "LIGHT_CIRCLE_SQUARE",
  "NOOVERLAP_ROUND_CORNER",
];

const EYE_PATTERN_OPTIONS = [
  "RECT_RECT",
  "ROUND_RECT",
  "RECT_CIRC",
  "ROUNDRECT_CIRC",
  "CIRC_CIRC",
  "BR_LEAF",
  "TR_LEAF",
  "BL_LEAF",
  "TL_LEAF",
  "TLBR_LEAF",
  "TRBL_LEAF",
  "TRBL_LEAF_CIRC",
  "TLBR_LEAF_CIRC",
  "TRBL_LEAF_DIAD",
  "RECT_DIAD",
  "UNI_LEAF",
  "BLOAT_RECT",
  "WARP_RECT0",
  "CURVE_RECT",
  "DIST_RECT",
  "ZIGZAG",
  "WARP_RECT1",
  "BLACK_HOLE",
  "STAR",
  "GRID",
  "SCION",
  "OCTAGON",
  "FLOWER",
  "HUT",
  "DARK_HUT",
];

const DATA_GRADIENT_STYLE_OPTIONS = [
  "Horizontal",
  "Vertical",
  "Diagonal",
  "ReverseDiagonal",
  "Radial",
  "Eye_Horizontal",
  "Eye_Vertical",
  "Eye_Diagonal",
  "Eye_ReverseDiagonal",
  "Eye_Radial",
  "None",
];

const POSTER_EYE_SHAPE_OPTIONS = [
  "RECT_RECT",
  "ROUND_RECT",
  "RECT_CIRC",
  "ROUNDRECT_CIRC",
  "CIRC_CIRC",
  "BR_LEAF",
  "TR_LEAF",
  "BL_LEAF",
  "TL_LEAF",
  "TLBR_LEAF",
  "TRBL_LEAF",
  "TRBL_LEAF_CIRC",
  "TLBR_LEAF_CIRC",
  "TRBL_LEAF_DIAD",
  "RECT_DIAD",
  "UNI_LEAF",
  "BLOAT_RECT",
  "WARP_RECT0",
  "CURVE_RECT",
  "DIST_RECT",
  "ZIGZAG",
  "WARP_RECT1",
  "BLACK_HOLE",
  "STAR",
  "GRID",
  "SCION",
  "OCTAGON",
  "FLOWER",
  "HUT",
  "DARK_HUT",
];

const POSTER_DATA_PATTERN_OPTIONS = [
  "ROUND",
  "SQUARE",
  "DIAMONDS",
  "OVAL",
];

const FORMAT_OPTIONS = [
  "png",
  "jpg",
  "svg",
  "pdf",
  "eps",
];

const AUTHENTICATION_OPTIONS = [
  "WPA",
  "WEP",
  "unencrypted",
];

export default {
  SIZE_OPTIONS,
  QUITE_ZONE_OPTIONS,
  ERROR_CORRECTION_OPTIONS,
  DATA_PATTERN_OPTIONS,
  EYE_PATTERN_OPTIONS,
  DATA_GRADIENT_STYLE_OPTIONS,
  POSTER_EYE_SHAPE_OPTIONS,
  POSTER_DATA_PATTERN_OPTIONS,
  FORMAT_OPTIONS,
  AUTHENTICATION_OPTIONS,
};
