<template><h1 id="end-workflow-early" tabindex="-1"><a class="header-anchor" href="#end-workflow-early" aria-hidden="true">#</a> End workflow early</h1>
<p>Next, let's update our workflow to filter out <code>favicon.ico</code> requests. This example builds on the workflow created in <a href="/quickstart/" target="_blank" rel="noopener noreferrer">previous sections<ExternalLinkIcon/></a> and will cover how to use the <code>$end()</code> function to end a workflow execution early.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>If you didn't complete the previous examples, we recommend you start from the <a href="/quickstart/" target="_blank" rel="noopener noreferrer">beginning of this guide<ExternalLinkIcon/></a>. If you still want to start here, <a href="https://pipedream.com/@gettingstarted/quickstart-insert-data-into-google-sheets-p_KwCAR9z" target="_blank" rel="noopener noreferrer">copy this workflow<ExternalLinkIcon/></a> and then follow the instructions below. If you have any issues completing this example, you can <a href="https://pipedream.com/@gettingstarted/quickstart-end-workflow-early-p_RRCgNRQ" target="_blank" rel="noopener noreferrer">view, copy and run a completed version<ExternalLinkIcon/></a>.</p>
</div>
<p>In the last example, two rows may be added to Google Sheets when we load the endpoint URL in our browser. That's because most modern web browsers automatically make a request for a <a href="https://en.wikipedia.org/wiki/Favicon" target="_blank" rel="noopener noreferrer"><code>favicon.ico</code><ExternalLinkIcon/></a> file. While this is an artifact of loading the workflow's endpoint in our browser, it provides a good opportunity to demonstrate <code>$end()</code>.</p>
<p>First, select an event that represents a <code>favicon.ico</code> request:</p>
<p><img src="@source/quickstart/end-workflow-early/images/image-20210525184158904.png" alt="image-20210525184158904"></p>
<p>Next, add a <strong>Run Node.js code</strong> step immediately after the trigger and change the name from <code>steps.nodejs</code> to <code>steps.filter_favicon_requests</code>. Then add code to conditionally end the workflow execution if <code>steps.trigger.event.url</code> contains the string <code>favicon.ico</code>. We can also pass a reason for ending the execution to the <code>$end()</code> function. For this example, we'll pass the value <code>favicon.ico request</code>.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>url<span class="token punctuation">.</span><span class="token function">endsWith</span><span class="token punctuation">(</span><span class="token string">"/favicon.ico"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  <span class="token function">$end</span><span class="token punctuation">(</span><span class="token string">"favicon.ico request"</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p><img src="@source/quickstart/end-workflow-early/images/image-20210525184256769.png" alt="image-20210525184256769"></p>
<p>Next, <strong>Deploy</strong> your workflow and load the endpoint URL in your browser to trigger your workflow. While 2 events will still appear in the event list, you'll see that one of them indicates that <code>$end()</code> was invoked along with the reason we defined. Additionally, no steps after <code>steps.filter_favicon_requests</code> were executed for that event.</p>
<p><img src="@source/quickstart/end-workflow-early/images/image-20210525184412763.png" alt="image-20210525184412763"></p>
<p>Next, if you select the event that did <strong>not</strong> invoke <code>$end()</code>, you will see it successfully executed the entire workflow. And when you load Google Sheets, you should only see a single new row added:</p>
<p><img src="@source/quickstart/end-workflow-early/images/image-20210525184446575.png" alt="image-20210525184446575"></p>
<p>Finally, the data for that row will match the data returned to your endpoint.</p>
<p><img src="@source/quickstart/end-workflow-early/images/image-20210525184509990.png" alt="image-20210525184509990"></p>
<p><strong>Next, let's use a connected account in a code step to authenticate a Google Sheets API request.</strong></p>
<p style="text-align:center;">
<a :href="$withBase('/quickstart/use-managed-auth-in-code/')"><img src="@source/quickstart/next.png"></a>
</p></template>
