export default {
  "id": "2566279204",
  "event": "subscription_state_change",
  "payload[subscription][id]": "79431128",
  "payload[subscription][state]": "on_hold",
  "payload[subscription][trial_started_at]": "",
  "payload[subscription][trial_ended_at]": "",
  "payload[subscription][activated_at]": "2024-10-11 15:20:08 -0400",
  "payload[subscription][created_at]": "2024-10-11 15:20:06 -0400",
  "payload[subscription][updated_at]": "2024-10-11 15:28:31 -0400",
  "payload[subscription][expires_at]": "",
  "payload[subscription][balance_in_cents]": "0",
  "payload[subscription][current_period_ends_at]": "2024-11-11 14:20:06 -0500",
  "payload[subscription][next_assessment_at]": "2024-11-11 14:20:06 -0500",
  "payload[subscription][canceled_at]": "",
  "payload[subscription][cancellation_message]": "",
  "payload[subscription][next_product_id]": "",
  "payload[subscription][next_product_handle]": "",
  "payload[subscription][cancel_at_end_of_period]": "false",
  "payload[subscription][payment_collection_method]": "automatic",
  "payload[subscription][snap_day]": "",
  "payload[subscription][cancellation_method]": "",
  "payload[subscription][current_period_started_at]": "2024-10-11 15:20:06 -0400",
  "payload[subscription][previous_state]": "active",
  "payload[subscription][signup_payment_id]": "1170014104",
  "payload[subscription][signup_revenue]": "0.00",
  "payload[subscription][delayed_cancel_at]": "",
  "payload[subscription][coupon_code]": "",
  "payload[subscription][total_revenue_in_cents]": "0",
  "payload[subscription][product_price_in_cents]": "0",
  "payload[subscription][product_version_number]": "1",
  "payload[subscription][payment_type]": "",
  "payload[subscription][referral_code]": "",
  "payload[subscription][coupon_use_count]": "",
  "payload[subscription][coupon_uses_allowed]": "",
  "payload[subscription][reason_code]": "",
  "payload[subscription][automatically_resume_at]": "",
  "payload[subscription][offer_id]": "",
  "payload[subscription][payer_id]": "",
  "payload[subscription][receives_invoice_emails]": "",
  "payload[subscription][product_price_point_id]": "3322919",
  "payload[subscription][next_product_price_point_id]": "",
  "payload[subscription][credit_balance_in_cents]": "0",
  "payload[subscription][prepayment_balance_in_cents]": "0",
  "payload[subscription][net_terms]": "",
  "payload[subscription][stored_credential_transaction_id]": "",
  "payload[subscription][locale]": "",
  "payload[subscription][reference]": "",
  "payload[subscription][currency]": "USD",
  "payload[subscription][on_hold_at]": "2024-10-11 15:28:31 -0400",
  "payload[subscription][scheduled_cancellation_at]": "",
  "payload[subscription][product_price_point_type]": "default",
  "payload[subscription][dunning_communication_delay_enabled]": "false",
  "payload[subscription][dunning_communication_delay_time_zone]": "",
  "payload[subscription][customer][id]": "83697711",
  "payload[subscription][customer][first_name]": "FirstName",
  "payload[subscription][customer][last_name]": "LastName",
  "payload[subscription][customer][organization]": "",
  "payload[subscription][customer][email]": "test@email.com",
  "payload[subscription][customer][created_at]": "2024-10-11 15:08:35 -0400",
  "payload[subscription][customer][updated_at]": "2024-10-11 15:08:35 -0400",
  "payload[subscription][customer][reference]": "",
  "payload[subscription][customer][address]": "",
  "payload[subscription][customer][address_2]": "",
  "payload[subscription][customer][address_3]": "",
  "payload[subscription][customer][city]": "",
  "payload[subscription][customer][state]": "",
  "payload[subscription][customer][state_name]": "",
  "payload[subscription][customer][zip]": "",
  "payload[subscription][customer][country]": "",
  "payload[subscription][customer][country_name]": "",
  "payload[subscription][customer][phone]": "",
  "payload[subscription][customer][portal_invite_last_sent_at]": "",
  "payload[subscription][customer][portal_invite_last_accepted_at]": "",
  "payload[subscription][customer][verified]": "false",
  "payload[subscription][customer][portal_customer_created_at]": "",
  "payload[subscription][customer][vat_number]": "",
  "payload[subscription][customer][cc_emails]": "",
  "payload[subscription][customer][tax_exempt]": "false",
  "payload[subscription][customer][tax_exempt_reason]": "",
  "payload[subscription][customer][parent_id]": "",
  "payload[subscription][customer][locale]": "",
  "payload[subscription][customer][salesforce_id]": "",
  "payload[subscription][product][id]": "6748126",
  "payload[subscription][product][name]": "Pro Plan",
  "payload[subscription][product][handle]": "",
  "payload[subscription][product][description]": "",
  "payload[subscription][product][accounting_code]": "",
  "payload[subscription][product][request_credit_card]": "true",
  "payload[subscription][product][expiration_interval]": "",
  "payload[subscription][product][expiration_interval_unit]": "never",
  "payload[subscription][product][created_at]": "2024-10-11 12:56:32 -0400",
  "payload[subscription][product][updated_at]": "2024-10-11 12:56:32 -0400",
  "payload[subscription][product][price_in_cents]": "0",
  "payload[subscription][product][interval]": "1",
  "payload[subscription][product][interval_unit]": "month",
  "payload[subscription][product][initial_charge_in_cents]": "",
  "payload[subscription][product][trial_price_in_cents]": "",
  "payload[subscription][product][trial_interval]": "",
  "payload[subscription][product][trial_interval_unit]": "month",
  "payload[subscription][product][archived_at]": "",
  "payload[subscription][product][require_credit_card]": "false",
  "payload[subscription][product][return_params]": "",
  "payload[subscription][product][taxable]": "false",
  "payload[subscription][product][update_return_url]": "",
  "payload[subscription][product][tax_code]": "",
  "payload[subscription][product][initial_charge_after_trial]": "false",
  "payload[subscription][product][version_number]": "1",
  "payload[subscription][product][update_return_params]": "",
  "payload[subscription][product][default_product_price_point_id]": "3322919",
  "payload[subscription][product][request_billing_address]": "false",
  "payload[subscription][product][require_billing_address]": "false",
  "payload[subscription][product][require_shipping_address]": "false",
  "payload[subscription][product][use_site_exchange_rate]": "true",
  "payload[subscription][product][item_category]": "",
  "payload[subscription][product][product_price_point_id]": "3322919",
  "payload[subscription][product][product_price_point_name]": "Original",
  "payload[subscription][product][product_price_point_handle]": "uuid:b0c26c80-6a1f-013d-c9f9-063702f7df93",
  "payload[subscription][product][product_family][id]": "2699089",
  "payload[subscription][product][product_family][name]": "Billing Plans",
  "payload[subscription][product][product_family][description]": "",
  "payload[subscription][product][product_family][handle]": "testing-billing-plans",
  "payload[subscription][product][product_family][accounting_code]": "",
  "payload[subscription][product][product_family][created_at]": "2024-10-11 11:23:44 -0400",
  "payload[subscription][product][product_family][updated_at]": "2024-10-11 11:23:44 -0400",
  "payload[subscription][group]": "",
  "payload[site][id]": "87942",
  "payload[site][subdomain]": "testing",
  "payload[event_id]": "4834010965"
}