export const ACTOR_OPTIONS = [
  {
    label: "Shopee",
    value: "scraper.shopee",
  },
  {
    label: "BR Sites - Solucoes cnpjreva",
    value: "scraper.solucoes",
  },
  {
    label: "BR Sites - Solucoes certidaointernet",
    value: "scraper.solucoes.certidaointernet",
  },
  {
    label: "BR Sites - Servicos receita",
    value: "scraper.servicos.receita",
  },
  {
    label: "BR Sites - Consopt",
    value: "scraper.consopt",
  },
  {
    label: "Avnet",
    value: "scraper.avnet",
  },
  {
    label: "Arrow",
    value: "scraper.arrow",
  },
  {
    label: "Airline Iberia",
    value: "scraper.iberia",
  },
  {
    label: "Airline Expedia",
    value: "scraper.expedia",
  },
  {
    label: "Airline Kayak",
    value: "scraper.kayak",
  },
  {
    label: "Amazon Product",
    value: "scraper.amazon.product",
  },
  {
    label: "Amazon Seller",
    value: "scraper.amazon.seller",
  },
  {
    label: "Amazon Keywords",
    value: "scraper.amazon.keywords",
  },
  {
    label: "Temu",
    value: "scraper.temu.mobile.detail",
  },
  {
    label: "Google Search",
    value: "scraper.google.search",
  },
  {
    label: "Google Trends",
    value: "scraper.google.trends",
  },
  {
    label: "Google FLights",
    value: "scraper.google.flights",
  },
  {
    label: "Google FLights Chart",
    value: "scraper.google.flights.chart",
  },
  {
    label: "Google Maps",
    value: "scraper.google.maps",
  },
  {
    label: "Google Scholar",
    value: "scraper.google.scholar",
  },
  {
    label: "Google Jobs",
    value: "scraper.google.jobs",
  },
  {
    label: "Google Shopping",
    value: "scraper.google.shopping",
  },
  {
    label: "Google Hotels",
    value: "scraper.google.hotels",
  },
  {
    label: "Google News",
    value: "scraper.google.news",
  },
  {
    label: "Google Lens",
    value: "scraper.google.lens",
  },
  {
    label: "Google Finance",
    value: "scraper.google.finance",
  },
  {
    label: "Google Product",
    value: "scraper.google.product",
  },
  {
    label: "Google Play Games",
    value: "scraper.google.play.games",
  },
  {
    label: "Google Play Books",
    value: "scraper.google.play.books",
  },
  {
    label: "Google Play Movies",
    value: "scraper.google.play.movies",
  },
  {
    label: "Google Play Product",
    value: "scraper.google.play.product",
  },
  {
    label: "Google Play Apps",
    value: "scraper.google.play",
  },
  {
    label: "Google Ads",
    value: "scraper.google.ads",
  },
  {
    label: "Mouser",
    value: "scraper.mouser",
  },
];
export const countryOptions = [
  {
    regionId: -1,
    value: "ANY",
    label: "World Wide",
    signal: 5,
    emoji: "🌎",
  },
  {
    "regionId": 3,
    "value": "AL",
    "label": "Albania",
    "signal": 2,
    "emoji": "🇦🇱",
  },
  {
    "regionId": 4,
    "value": "DZ",
    "label": "Algeria",
    "signal": 3,
    "emoji": "🇩🇿",
  },
  {
    "regionId": 26,
    "value": "BT",
    "label": "Bhutan",
    "signal": 2,
    "emoji": "🇧🇹",
  },
  {
    "regionId": 27,
    "value": "BO",
    "label": "Bolivia",
    "signal": 3,
    "emoji": "🇧🇴",
  },
  {
    "regionId": 15,
    "value": "AT",
    "label": "Austria",
    "signal": 3,
    "emoji": "🇦🇹",
  },
  {
    "regionId": 18,
    "value": "BH",
    "label": "Bahrain",
    "signal": 2,
    "emoji": "🇧🇭",
  },
  {
    "regionId": 11,
    "value": "AR",
    "label": "Argentina",
    "signal": 2,
    "emoji": "🇦🇷",
  },
  {
    "regionId": 16,
    "value": "AZ",
    "label": "Azerbaijan",
    "signal": 3,
    "emoji": "🇦🇿",
  },
  {
    "regionId": 57,
    "value": "CY",
    "label": "Cyprus",
    "signal": 2,
    "emoji": "🇨🇾",
  },
  {
    "regionId": 36,
    "value": "BI",
    "label": "Burundi",
    "signal": 1,
    "emoji": "🇧🇮",
  },
  {
    "regionId": 38,
    "value": "CM",
    "label": "Cameroon",
    "signal": 2,
    "emoji": "🇨🇲",
  },
  {
    "regionId": 55,
    "value": "HR",
    "label": "Croatia",
    "signal": 3,
    "emoji": "🇭🇷",
  },
  {
    "regionId": 62,
    "value": "DO",
    "label": "Dominican Republic",
    "signal": 2,
    "emoji": "🇩🇴",
  },
  {
    "regionId": 14,
    "value": "AU",
    "label": "Australia",
    "signal": 3,
    "emoji": "🇦🇺",
  },
  {
    "regionId": 21,
    "value": "BY",
    "label": "Belarus",
    "signal": 3,
    "emoji": "🇧🇾",
  },
  {
    "regionId": 7,
    "value": "AO",
    "label": "Angola",
    "signal": 2,
    "emoji": "🇦🇴",
  },
  {
    "regionId": 34,
    "value": "BG",
    "label": "Bulgaria",
    "signal": 3,
    "emoji": "🇧🇬",
  },
  {
    "regionId": 51,
    "value": "CD",
    "label": "Democratic Republic of the Congo",
    "signal": 2,
    "emoji": "🇨🇩",
  },
  {
    "regionId": 13,
    "value": "AW",
    "label": "Aruba",
    "signal": 2,
    "emoji": "🇦🇼",
  },
  {
    "regionId": 12,
    "value": "AM",
    "label": "Armenia",
    "signal": 2,
    "emoji": "🇦🇲",
  },
  {
    "regionId": 19,
    "value": "BD",
    "label": "Bangladesh",
    "signal": 3,
    "emoji": "🇧🇩",
  },
  {
    "regionId": 22,
    "value": "BE",
    "label": "Belgium",
    "signal": 3,
    "emoji": "🇧🇪",
  },
  {
    "regionId": 37,
    "value": "KH",
    "label": "Cambodia",
    "signal": 2,
    "emoji": "🇰🇭",
  },
  {
    "regionId": 58,
    "value": "CZ",
    "label": "Czech Republic",
    "signal": 3,
    "emoji": "🇨🇿",
  },
  {
    "regionId": 59,
    "value": "DK",
    "label": "Denmark",
    "signal": 2,
    "emoji": "🇩🇰",
  },
  {
    "regionId": 35,
    "value": "BF",
    "label": "Burkina Faso",
    "signal": 2,
    "emoji": "🇧🇫",
  },
  {
    "regionId": 39,
    "value": "CA",
    "label": "Canada",
    "signal": 3,
    "emoji": "🇨🇦",
  },
  {
    "regionId": 56,
    "value": "CU",
    "label": "Cuba",
    "signal": 1,
    "emoji": "🇨🇺",
  },
  {
    "regionId": 45,
    "value": "CN",
    "label": "China",
    "signal": 2,
    "emoji": "🇨🇳",
  },
  {
    "regionId": 80,
    "value": "GM",
    "label": "Gambia The",
    "signal": 1,
    "emoji": "🇬🇲",
  },
  {
    "regionId": 81,
    "value": "GE",
    "label": "Georgia",
    "signal": 2,
    "emoji": "🇬🇪",
  },
  {
    "regionId": 44,
    "value": "CL",
    "label": "Chile",
    "signal": 3,
    "emoji": "🇨🇱",
  },
  {
    "regionId": 50,
    "value": "CG",
    "label": "Congo",
    "signal": 2,
    "emoji": "🇨🇬",
  },
  {
    "regionId": 54,
    "value": "CI",
    "label": "Cote D'Ivoire (Ivory Coast)",
    "signal": 2,
    "emoji": "🇨🇮",
  },
  {
    "regionId": 79,
    "value": "GA",
    "label": "Gabon",
    "signal": 2,
    "emoji": "🇬🇦",
  },
  {
    "regionId": 48,
    "value": "CO",
    "label": "Colombia",
    "signal": 3,
    "emoji": "🇨🇴",
  },
  {
    "regionId": 53,
    "value": "CR",
    "label": "Costa Rica",
    "signal": 3,
    "emoji": "🇨🇷",
  },
  {
    "regionId": 102,
    "value": "ID",
    "label": "Indonesia",
    "signal": 3,
    "emoji": "🇮🇩",
  },
  {
    "regionId": 77,
    "value": "PF",
    "label": "French Polynesia",
    "signal": 1,
    "emoji": "🇵🇫",
  },
  {
    "regionId": 127,
    "value": "LU",
    "label": "Luxembourg",
    "signal": 3,
    "emoji": "🇱🇺",
  },
  {
    "regionId": 135,
    "value": "MT",
    "label": "Malta",
    "signal": 2,
    "emoji": "🇲🇹",
  },
  {
    "regionId": 134,
    "value": "ML",
    "label": "Mali",
    "signal": 2,
    "emoji": "🇲🇱",
  },
  {
    "regionId": 142,
    "value": "MX",
    "label": "Mexico",
    "signal": 4,
    "emoji": "🇲🇽",
  },
  {
    "regionId": 140,
    "value": "MU",
    "label": "Mauritius",
    "signal": 1,
    "emoji": "🇲🇺",
  },
  {
    "regionId": 130,
    "value": "MG",
    "label": "Madagascar",
    "signal": 2,
    "emoji": "🇲🇬",
  },
  {
    "regionId": 131,
    "value": "MW",
    "label": "Malawi",
    "signal": 2,
    "emoji": "🇲🇼",
  },
  {
    "regionId": 147,
    "value": "ME",
    "label": "Montenegro",
    "signal": 2,
    "emoji": "🇲🇪",
  },
  {
    "regionId": 156,
    "value": "NL",
    "label": "Netherlands",
    "signal": 3,
    "emoji": "🇳🇱",
  },
  {
    "regionId": 128,
    "value": "MO",
    "label": "Macau S.A.R.",
    "signal": 2,
    "emoji": "🇲🇴",
  },
  {
    "regionId": 144,
    "value": "MD",
    "label": "Moldova",
    "signal": 3,
    "emoji": "🇲🇩",
  },
  {
    "regionId": 132,
    "value": "MY",
    "label": "Malaysia",
    "signal": 2,
    "emoji": "🇲🇾",
  },
  {
    "regionId": 146,
    "value": "MN",
    "label": "Mongolia",
    "signal": 3,
    "emoji": "🇲🇳",
  },
  {
    "regionId": 136,
    "value": "IM",
    "label": "Man (Isle of)",
    "signal": 2,
    "emoji": "🇮🇲",
  },
  {
    "regionId": 73,
    "value": "FJ",
    "label": "Fiji Islands",
    "signal": 1,
    "emoji": "🇫🇯",
  },
  {
    "regionId": 74,
    "value": "FI",
    "label": "Finland",
    "signal": 2,
    "emoji": "🇫🇮",
  },
  {
    "regionId": 75,
    "value": "FR",
    "label": "France",
    "signal": 4,
    "emoji": "🇫🇷",
  },
  {
    "regionId": 101,
    "value": "IN",
    "label": "India",
    "signal": 2,
    "emoji": "🇮🇳",
  },
  {
    "regionId": 100,
    "value": "IS",
    "label": "Iceland",
    "signal": 2,
    "emoji": "🇮🇸",
  },
  {
    "regionId": 129,
    "value": "MK",
    "label": "North Macedonia",
    "signal": 3,
    "emoji": "🇲🇰",
  },
  {
    "regionId": 158,
    "value": "NZ",
    "label": "New Zealand",
    "signal": 3,
    "emoji": "🇳🇿",
  },
  {
    "regionId": 159,
    "value": "NI",
    "label": "Nicaragua",
    "signal": 2,
    "emoji": "🇳🇮",
  },
  {
    "regionId": 165,
    "value": "NO",
    "label": "Norway",
    "signal": 2,
    "emoji": "🇳🇴",
  },
  {
    "regionId": 95,
    "value": "HT",
    "label": "Haiti",
    "signal": 2,
    "emoji": "🇭🇹",
  },
  {
    "regionId": 97,
    "value": "HN",
    "label": "Honduras",
    "signal": 2,
    "emoji": "🇭🇳",
  },
  {
    "regionId": 99,
    "value": "HU",
    "label": "Hungary",
    "signal": 3,
    "emoji": "🇭🇺",
  },
  {
    "regionId": 94,
    "value": "GY",
    "label": "Guyana",
    "signal": 2,
    "emoji": "🇬🇾",
  },
  {
    "regionId": 98,
    "value": "HK",
    "label": "Hong Kong S.A.R.",
    "signal": 2,
    "emoji": "🇭🇰",
  },
  {
    "regionId": 161,
    "value": "NG",
    "label": "Nigeria",
    "signal": 4,
    "emoji": "🇳🇬",
  },
  {
    "regionId": 166,
    "value": "OM",
    "label": "Oman",
    "signal": 3,
    "emoji": "🇴🇲",
  },
  {
    "regionId": 173,
    "value": "PE",
    "label": "Peru",
    "signal": 2,
    "emoji": "🇵🇪",
  },
  {
    "regionId": 167,
    "value": "PK",
    "label": "Pakistan",
    "signal": 4,
    "emoji": "🇵🇰",
  },
  {
    "regionId": 169,
    "value": "PS",
    "label": "Palestinian Territory Occupied",
    "signal": 3,
    "emoji": "🇵🇸",
  },
  {
    "regionId": 171,
    "value": "PG",
    "label": "Papua new Guinea",
    "signal": 2,
    "emoji": "🇵🇬",
  },
  {
    "regionId": 176,
    "value": "PL",
    "label": "Poland",
    "signal": 4,
    "emoji": "🇵🇱",
  },
  {
    "regionId": 172,
    "value": "PY",
    "label": "Paraguay",
    "signal": 2,
    "emoji": "🇵🇾",
  },
  {
    "regionId": 170,
    "value": "PA",
    "label": "Panama",
    "signal": 2,
    "emoji": "🇵🇦",
  },
  {
    "regionId": 174,
    "value": "PH",
    "label": "Philippines",
    "signal": 3,
    "emoji": "🇵🇭",
  },
  {
    "regionId": 70,
    "value": "ET",
    "label": "Ethiopia",
    "signal": 2,
    "emoji": "🇪🇹",
  },
  {
    "regionId": 90,
    "value": "GT",
    "label": "Guatemala",
    "signal": 3,
    "emoji": "🇬🇹",
  },
  {
    "regionId": 85,
    "value": "GR",
    "label": "Greece",
    "signal": 4,
    "emoji": "🇬🇷",
  },
  {
    "regionId": 93,
    "value": "GW",
    "label": "Guinea-Bissau",
    "signal": 2,
    "emoji": "🇬🇼",
  },
  {
    "regionId": 69,
    "value": "EE",
    "label": "Estonia",
    "signal": 3,
    "emoji": "🇪🇪",
  },
  {
    "regionId": 92,
    "value": "GN",
    "label": "Guinea",
    "signal": 2,
    "emoji": "🇬🇳",
  },
  {
    "regionId": 194,
    "value": "SA",
    "label": "Saudi Arabia",
    "signal": 3,
    "emoji": "🇸🇦",
  },
  {
    "regionId": 196,
    "value": "RS",
    "label": "Serbia",
    "signal": 2,
    "emoji": "🇷🇸",
  },
  {
    "regionId": 17,
    "value": "BS",
    "label": "The Bahamas",
    "signal": 2,
    "emoji": "🇧🇸",
  },
  {
    "regionId": 64,
    "value": "EC",
    "label": "Ecuador",
    "signal": 2,
    "emoji": "🇪🇨",
  },
  {
    "regionId": 87,
    "value": "GD",
    "label": "Grenada",
    "signal": 1,
    "emoji": "🇬🇩",
  },
  {
    "regionId": 28,
    "value": "BA",
    "label": "Bosnia and Herzegovina",
    "signal": 3,
    "emoji": "🇧🇦",
  },
  {
    "regionId": 31,
    "value": "BR",
    "label": "Brazil",
    "signal": 3,
    "emoji": "🇧🇷",
  },
  {
    "regionId": 82,
    "value": "DE",
    "label": "Germany",
    "signal": 3,
    "emoji": "🇩🇪",
  },
  {
    "regionId": 83,
    "value": "GH",
    "label": "Ghana",
    "signal": 2,
    "emoji": "🇬🇭",
  },
  {
    "regionId": 183,
    "value": "RW",
    "label": "Rwanda",
    "signal": 2,
    "emoji": "🇷🇼",
  },
  {
    "regionId": 195,
    "value": "SN",
    "label": "Senegal",
    "signal": 3,
    "emoji": "🇸🇳",
  },
  {
    "regionId": 219,
    "value": "TH",
    "label": "Thailand",
    "signal": 2,
    "emoji": "🇹🇭",
  },
  {
    "regionId": 217,
    "value": "TJ",
    "label": "Tajikistan",
    "signal": 2,
    "emoji": "🇹🇯",
  },
  {
    "regionId": 218,
    "value": "TZ",
    "label": "Tanzania",
    "signal": 2,
    "emoji": "🇹🇿",
  },
  {
    "regionId": 65,
    "value": "EG",
    "label": "Egypt",
    "signal": 3,
    "emoji": "🇪🇬",
  },
  {
    "regionId": 66,
    "value": "SV",
    "label": "El Salvador",
    "signal": 2,
    "emoji": "🇸🇻",
  },
  {
    "regionId": 84,
    "value": "GI",
    "label": "Gibraltar",
    "signal": 1,
    "emoji": "🇬🇮",
  },
  {
    "regionId": 188,
    "value": "VC",
    "label": "Saint Vincent And The Grenadines",
    "signal": 2,
    "emoji": "🇻🇨",
  },
  {
    "regionId": 200,
    "value": "SK",
    "label": "Slovakia",
    "signal": 3,
    "emoji": "🇸🇰",
  },
  {
    "regionId": 201,
    "value": "SI",
    "label": "Slovenia",
    "signal": 2,
    "emoji": "🇸🇮",
  },
  {
    "regionId": 223,
    "value": "TT",
    "label": "Trinidad And Tobago",
    "signal": 2,
    "emoji": "🇹🇹",
  },
  {
    "regionId": 224,
    "value": "TN",
    "label": "Tunisia",
    "signal": 4,
    "emoji": "🇹🇳",
  },
  {
    "regionId": 225,
    "value": "TR",
    "label": "Turkey",
    "signal": 3,
    "emoji": "🇹🇷",
  },
  {
    "regionId": 229,
    "value": "UG",
    "label": "Uganda",
    "signal": 2,
    "emoji": "🇺🇬",
  },
  {
    "regionId": 227,
    "value": "TC",
    "label": "Turks And Caicos Islands",
    "signal": 2,
    "emoji": "🇹🇨",
  },
  {
    "regionId": 230,
    "value": "UA",
    "label": "Ukraine",
    "signal": 2,
    "emoji": "🇺🇦",
  },
  {
    "regionId": 220,
    "value": "TG",
    "label": "Togo",
    "signal": 2,
    "emoji": "🇹🇬",
  },
  {
    "regionId": 233,
    "value": "US",
    "label": "United States",
    "signal": 4,
    "emoji": "🇺🇸",
  },
  {
    "regionId": 177,
    "value": "PT",
    "label": "Portugal",
    "signal": 3,
    "emoji": "🇵🇹",
  },
  {
    "regionId": 178,
    "value": "PR",
    "label": "Puerto Rico",
    "signal": 2,
    "emoji": "🇵🇷",
  },
  {
    "regionId": 231,
    "value": "AE",
    "label": "United Arab Emirates",
    "signal": 3,
    "emoji": "🇦🇪",
  },
  {
    "regionId": 232,
    "value": "GB",
    "label": "United Kingdom",
    "signal": 2,
    "emoji": "🇬🇧",
  },
  {
    "regionId": 240,
    "value": "VN",
    "label": "Vietnam",
    "signal": 3,
    "emoji": "🇻🇳",
  },
  {
    "regionId": 112,
    "value": "KZ",
    "label": "Kazakhstan",
    "signal": 4,
    "emoji": "🇰🇿",
  },
  {
    "regionId": 106,
    "value": "IL",
    "label": "Israel",
    "signal": 4,
    "emoji": "🇮🇱",
  },
  {
    "regionId": 108,
    "value": "JM",
    "label": "Jamaica",
    "signal": 2,
    "emoji": "🇯🇲",
  },
  {
    "regionId": 242,
    "value": "VI",
    "label": "Virgin Islands (US)",
    "signal": 1,
    "emoji": "🇻🇮",
  },
  {
    "regionId": 118,
    "value": "KG",
    "label": "Kyrgyzstan",
    "signal": 3,
    "emoji": "🇰🇬",
  },
  {
    "regionId": 120,
    "value": "LV",
    "label": "Latvia",
    "signal": 2,
    "emoji": "🇱🇻",
  },
  {
    "regionId": 154,
    "value": "NP",
    "label": "Nepal",
    "signal": 2,
    "emoji": "🇳🇵",
  },
  {
    "regionId": 246,
    "value": "ZM",
    "label": "Zambia",
    "signal": 2,
    "emoji": "🇿🇲",
  },
  {
    "regionId": 124,
    "value": "LY",
    "label": "Libya",
    "signal": 1,
    "emoji": "🇱🇾",
  },
  {
    "regionId": 152,
    "value": "NA",
    "label": "Namibia",
    "signal": 1,
    "emoji": "🇳🇦",
  },
  {
    "regionId": 180,
    "value": "RE",
    "label": "Reunion",
    "signal": 1,
    "emoji": "🇷🇪",
  },
  {
    "regionId": 179,
    "value": "QA",
    "label": "Qatar",
    "signal": 2,
    "emoji": "🇶🇦",
  },
  {
    "regionId": 182,
    "value": "RU",
    "label": "Russia",
    "signal": 2,
    "emoji": "🇷🇺",
  },
  {
    "regionId": 110,
    "value": "JE",
    "label": "Jersey",
    "signal": 1,
    "emoji": "🇯🇪",
  },
  {
    "regionId": 117,
    "value": "KW",
    "label": "Kuwait",
    "signal": 4,
    "emoji": "🇰🇼",
  },
  {
    "regionId": 126,
    "value": "LT",
    "label": "Lithuania",
    "signal": 2,
    "emoji": "🇱🇹",
  },
  {
    "regionId": 149,
    "value": "MA",
    "label": "Morocco",
    "signal": 3,
    "emoji": "🇲🇦",
  },
  {
    "regionId": 105,
    "value": "IE",
    "label": "Ireland",
    "signal": 3,
    "emoji": "🇮🇪",
  },
  {
    "regionId": 107,
    "value": "IT",
    "label": "Italy",
    "signal": 3,
    "emoji": "🇮🇹",
  },
  {
    "regionId": 151,
    "value": "MM",
    "label": "Myanmar",
    "signal": 2,
    "emoji": "🇲🇲",
  },
  {
    "regionId": 247,
    "value": "ZW",
    "label": "Zimbabwe",
    "signal": 1,
    "emoji": "🇿🇼",
  },
  {
    "regionId": 122,
    "value": "LS",
    "label": "Lesotho",
    "signal": 1,
    "emoji": "🇱🇸",
  },
  {
    "regionId": 245,
    "value": "YE",
    "label": "Yemen",
    "signal": 2,
    "emoji": "🇾🇪",
  },
  {
    "regionId": 181,
    "value": "RO",
    "label": "Romania",
    "signal": 2,
    "emoji": "🇷🇴",
  },
  {
    "regionId": 150,
    "value": "MZ",
    "label": "Mozambique",
    "signal": 2,
    "emoji": "🇲🇿",
  },
  {
    "regionId": 109,
    "value": "JP",
    "label": "Japan",
    "signal": 1,
    "emoji": "🇯🇵",
  },
  {
    "regionId": 111,
    "value": "JO",
    "label": "Jordan",
    "signal": 3,
    "emoji": "🇯🇴",
  },
  {
    "regionId": 113,
    "value": "KE",
    "label": "Kenya",
    "signal": 4,
    "emoji": "🇰🇪",
  },
  {
    "regionId": 239,
    "value": "VE",
    "label": "Venezuela",
    "signal": 2,
    "emoji": "🇻🇪",
  },
  {
    "regionId": 236,
    "value": "UZ",
    "label": "Uzbekistan",
    "signal": 3,
    "emoji": "🇺🇿",
  },
  {
    "regionId": 235,
    "value": "UY",
    "label": "Uruguay",
    "signal": 2,
    "emoji": "🇺🇾",
  },
  {
    "regionId": 208,
    "value": "LK",
    "label": "Sri Lanka",
    "signal": 3,
    "emoji": "🇱🇰",
  },
  {
    "regionId": 209,
    "value": "SD",
    "label": "Sudan",
    "signal": 2,
    "emoji": "🇸🇩",
  },
  {
    "regionId": 214,
    "value": "CH",
    "label": "Switzerland",
    "signal": 2,
    "emoji": "🇨🇭",
  },
  {
    "regionId": 116,
    "value": "KR",
    "label": "South Korea",
    "signal": 3,
    "emoji": "🇰🇷",
  },
  {
    "regionId": 210,
    "value": "SR",
    "label": "Suriname",
    "signal": 2,
    "emoji": "🇸🇷",
  },
  {
    "regionId": 204,
    "value": "ZA",
    "label": "South Africa",
    "signal": 2,
    "emoji": "🇿🇦",
  },
  {
    "regionId": 207,
    "value": "ES",
    "label": "Spain",
    "signal": 4,
    "emoji": "🇪🇸",
  },
  {
    "regionId": 216,
    "value": "TW",
    "label": "Taiwan",
    "signal": 3,
    "emoji": "🇹🇼",
  },
  {
    "regionId": 213,
    "value": "SE",
    "label": "Sweden",
    "signal": 3,
    "emoji": "🇸🇪",
  },
  {
    "regionId": 203,
    "value": "SO",
    "label": "Somalia",
    "signal": 2,
    "emoji": "🇸🇴",
  },
  {
    "regionId": 121,
    "value": "LB",
    "label": "Lebanon",
    "signal": 3,
    "emoji": "🇱🇧",
  },
  {
    "regionId": 199,
    "value": "SG",
    "label": "Singapore",
    "signal": 3,
    "emoji": "🇸🇬",
  },
];
