export default {
  CREATED: "CREATED",
  REGISTERED: "REGISTERED",
  RENEWED: "RENEWED",
  EXPIRED: "EXPIRED",
  DELETED: "DELETED",
  NAMESERVER_UPDATE: "NAMESERVER_UPDATE",
  REGISTRANT_VERIFICATION_STATUS_CHANGE: "REGISTRANT_VERIFICATION_STATUS_CHANGE",
  ZONE_CHECK_STATUS_CHANGE: "ZONE_CHECK_STATUS_CHANGE",
  MESSAGE_STATUS_CHANGE: "MESSAGE_STATUS_CHANGE",
  CLAIM_STATUS_CHANGE: "CLAIM_STATUS_CHANGE",
  STATUS_CHANGE: "STATUS_CHANGE",
};
