export default {
  "collection_id": 1658751,
  "user_id": 651250,
  "parent_id": null,
  "name": "pipedream.com",
  "description": null,
  "thumbnail": null,
  "sort": 1,
  "type": "link",
  "created_at": "2024-03-07 22:29:46 UTC",
  "updated_at": "2024-03-07 22:29:46 UTC",
  "deleted_at": null,
  "reactions_total_count": 0,
  "username": "username",
  "user_name": "Test User",
  "user_email": "test@user.com",
  "user_avatar": "https://gravatar.com/avatar/0559374f622501dc80e6981d1cdc484.png",
  "user_plan": "free",
  "url": "https://username.dropmark.com/1658751/33923876",
  "short_url": "https://dpmk.in/i/dL9JNhdMb",
  "thumbnails": {
    "mini": "https://webimg.dropmark.com/mini/aHR0cHM6Ly9waXBlZHJlYW0uY29t.jpg",
    "small": "https://webimg.dropmark.com/small/aHR0cHM6Ly9waXBlZHJlYW0uY29t.jpg",
    "cropped": "https://webimg.dropmark.com/cropped/aHR0cHM6Ly9waXBlZHJlYW0uY29t.jpg",
    "uncropped": "https://webimg.dropmark.com/uncropped/aHR0cHM6Ly9waXBlZHJlYW0uY29t.jpg",
    "large": "https://webimg.dropmark.com/large/aHR0cHM6Ly9waXBlZHJlYW0uY29t.jpg"
  },
  "reactions": [],
  "id": 33923876,
  "content": "https://pipedream.com",
  "link": "https://pipedream.com",
  "preview": null,
  "shareable": null,
  "size": 0,
  "mime": "url",
  "latitude": null,
  "longitude": null,
  "is_url": true,
  "comments": [],
  "tags": [],
  "metadata": []
}