export default {
  "course_title": "Class title",
  "course_subject": "Course subject",
  "course_level": "Course level",
  "school_id": 16385,
  "start_date": "2024-10-21",
  "end_date": "2024-10-28",
  "recurrence": "weekly",
  "payment_frequency": "free",
  "id": 153319,
  "photo": null,
  "payment_fee": "0",
  "course_description": "",
  "course_full_title": "Class title [Online Lesson]",
  "created": "2024-10-17 18:20:13",
  "modified": "2024-10-17 18:20:15",
  "color": "color1",
  "course_started": false,
  "course_ended": false,
  "course_status": 1,
  "num_enrolled_students": 0,
  "teachers": "66792",
  "classrooms": "39627",
  "billing_month_start_date": "2024-10-01",
  "billing_month_end_date": "2024-10-01",
  "custom_payments": null,
  "archived": false,
  "awarding_body": "",
  "course_code": "",
  "book_code": "",
  "total_lessons": 2,
  "total_lessons_hrs": "02:00",
  "skype_meeting_link": "",
  "year": null,
  "credit_hours": "",
  "class_type": "",
  "is_ended": null,
  "teacher_hourly_fees": null,
  "is_booking_class": false,
  "subscription_plan_id": null,
  "is_stripe_sub_allow": 0,
  "created_by": 66114,
  "modified_by": 66114,
  "exception_dates": null,
  "removed_exception_dates": null
}