export const prepareData = ({
  fullPage,
  blockAds,
  blockUrls,
  hideCookieBanners,
  clickAccept,
  hideSelector,
  darkMode,
  thumbWidth,
  thumbHeight,
  maxHeight,
  pdfPageSize,
  pdfPageWidth,
  pdfPageHeight,
  pdfMargin,
  pdfMarginTop,
  pdfMarginRight,
  pdfMarginBottom,
  pdfMarginLeft,
  pdfScale,
  pdfOrientation,
  pdfBackground,
  disableLigatures,
  userAgent,
  acceptLang,
  waitUntil,
  waitFor,
  waitToLeave,
  waitTimeout,
  scrollto,
  clickAll,
  bgColor,
  disable_js,
  fullWidth,
  allowInfinite,
  skipScroll,
  detectFullHeight,
  maxSectionHeight,
  scrollIncrement,
  scrollDelay,
  useS3,
  s3Path,
  s3Bucket,
  s3StorageClass,
  failIfSelectorMissing,
  failIfSelectorPresent,
  failOn4xx,
  failOn5xx,
  ...data
}) => {
  return {
    ...data,
    full_page: fullPage ?? fullPage,
    block_ads: blockAds ?? blockAds,
    block_urls: blockUrls ?? blockUrls,
    hide_cookie_banners: hideCookieBanners ?? hideCookieBanners,
    click_accept: clickAccept ?? clickAccept,
    hide_selector: hideSelector ?? hideSelector,
    dark_mode: darkMode ?? darkMode,
    thumb_width: thumbWidth ?? thumbWidth,
    thumb_height: thumbHeight ?? thumbHeight,
    max_height: maxHeight ?? maxHeight,
    pdf_page_size: pdfPageSize ?? pdfPageSize,
    pdf_page_width: pdfPageWidth ?? pdfPageWidth,
    pdf_page_height: pdfPageHeight ?? pdfPageHeight,
    pdf_margin: pdfMargin ?? pdfMargin,
    pdf_margin_top: pdfMarginTop ?? pdfMarginTop,
    pdf_margin_right: pdfMarginRight ?? pdfMarginRight,
    pdf_margin_bottom: pdfMarginBottom ?? pdfMarginBottom,
    pdf_margin_left: pdfMarginLeft ?? pdfMarginLeft,
    pdf_scale: pdfScale ?? pdfScale,
    pdf_orientation: pdfOrientation ?? pdfOrientation,
    pdf_background: pdfBackground ?? pdfBackground,
    disable_ligatures: disableLigatures ?? disableLigatures,
    user_agent: userAgent ?? userAgent,
    accept_lang: acceptLang ?? acceptLang,
    wait_until: waitUntil ?? waitUntil,
    wait_for: waitFor ?? waitFor,
    wait_to_leave: waitToLeave ?? waitToLeave,
    wait_timeout: waitTimeout ?? waitTimeout,
    scroll_to: scrollto ?? scrollto,
    click_all: clickAll ?? clickAll,
    bg_color: bgColor ?? bgColor,
    disable_js: disable_js ?? disable_js,
    full_width: fullWidth ?? fullWidth,
    allow_infinite: allowInfinite ?? allowInfinite,
    skip_scroll: skipScroll ?? skipScroll,
    detect_full_height: detectFullHeight ?? detectFullHeight,
    max_section_height: maxSectionHeight ?? maxSectionHeight,
    scroll_increment: scrollIncrement ?? scrollIncrement,
    scroll_delay: scrollDelay ?? scrollDelay,
    use_s3: useS3 ?? useS3,
    s3_path: s3Path ?? s3Path,
    s3_bucket: s3Bucket ?? s3Bucket,
    s3_storageclass: s3StorageClass ?? s3StorageClass,
    fail_if_selector_missing: failIfSelectorMissing ?? failIfSelectorMissing,
    fail_if_selector_present: failIfSelectorPresent ?? failIfSelectorPresent,
    fail_on_4xx: failOn4xx ?? failOn4xx,
    fail_on_5xx: failOn5xx ?? failOn5xx,
  };
};
