export default {
  "id": 97645,
  "organisation_name": "Gladiool Tuinarchitecten",
  "street": "",
  "street_number": "",
  "street_number_addition": null,
  "extra_address_line": "",
  "postal_code": "",
  "town": "",
  "country": "",
  "organisation_kvk_number": null,
  "organisation_btw_number": null,
  "is_supplier": true,
  "is_client": true,
  "email": null,
  "telephone_number": null,
  "mobile_number": null,
  "status": 1,
  "first_name": null,
  "last_name": null,
  "associated_ledger_account": [],
  "btw_shifted_preset": "NONE",
  "total_sales_amount_excl_btw": 0,
  "total_sales_amount_payable": 0,
  "total_purchase_amount_excl_btw": 0,
  "total_purchase_amount_payable": 0,
  "extra_info": ""
}