export default {
   "invoice":{
      "id":123,
      "createdAt":"2025-09-17T20:04:13+00:00",
      "updatedAt":"2025-09-17T20:04:13+00:00",
      "number":"INV00001",
      "status":"paid",
      "isVatShifted":true,
      "priceExcl":0,
      "priceIncl":0,
      "doNotifyNew":false,
      "doNotifyPaid":false,
      "invoice":false,
      "isCreditNote":false,
      "creditNote":false,
      "order":{
         "resource":{
            "id":123,
            "url":"orders\/123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
         }
      },
      "customer":{
         "resource":{
            "id":123,
            "url":"customers\/123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123.json"
         }
      },
      "items":{
         "resource":{
            "id":false,
            "url":"invoices\/123\/items",
            "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123\/items.json"
         }
      },
      "metafields":{
         "resource":{
            "id":false,
            "url":"invoices\/123\/metafields",
            "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123\/metafields.json"
         }
      },
      "events":{
         "resource":{
            "id":false,
            "url":"orders\/events?invoice=123",
            "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/events.json?invoice=123"
         }
      }
   }
}