<template><h1 id="server-sent-events-sse" tabindex="-1"><a class="header-anchor" href="#server-sent-events-sse" aria-hidden="true">#</a> Server-Sent Events (SSE)</h1>
<p>Pipedream supports <a href="https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events" target="_blank" rel="noopener noreferrer">Server-sent events<ExternalLinkIcon/></a> (SSE) as a destination, enabling you to send events from a workflow directly to a client subscribed to the event stream.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#what-is-sse">What is SSE?</RouterLink></li><li><RouterLink to="#what-can-i-do-with-the-sse-destination">What can I do with the SSE destination?</RouterLink></li><li><RouterLink to="#sending-data-to-an-sse-destination-in-workflows">Sending data to an SSE Destination in workflows</RouterLink></li><li><RouterLink to="#using-send-sse-in-component-actions">Using $.send.sse in component actions</RouterLink></li><li><RouterLink to="#receiving-events">Receiving events</RouterLink><ul><li><RouterLink to="#retrieving-your-workflow-s-event-stream-url">Retrieving your workflow&#39;s event stream URL</RouterLink></li><li><RouterLink to="#sample-code-to-connect-to-your-event-stream">Sample code to connect to your event stream</RouterLink></li></ul></li><li><RouterLink to="#keepalive-messages">:keepalive messages</RouterLink></li></ul></nav>
<h2 id="what-is-sse" tabindex="-1"><a class="header-anchor" href="#what-is-sse" aria-hidden="true">#</a> What is SSE?</h2>
<p><a href="https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events" target="_blank" rel="noopener noreferrer">Server-sent Events<ExternalLinkIcon/></a> (SSE) is a specification that allows servers to send events directly to clients that subscribe to those events, similar to <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" target="_blank" rel="noopener noreferrer">WebSockets<ExternalLinkIcon/></a> and related server to client push technologies.</p>
<p>Unlike WebSockets, SSE enables one-way communication from server to clients (WebSockets enable bidirectional communication between server and client, allowing you to pass messages back and forth). Luckily, if you only need a client to subscribe to events from a server, and don't require bidirectional communication, SSE is simple way to make that happen.</p>
<h2 id="what-can-i-do-with-the-sse-destination" tabindex="-1"><a class="header-anchor" href="#what-can-i-do-with-the-sse-destination" aria-hidden="true">#</a> What can I do with the SSE destination?</h2>
<p>SSE is typically used by web developers to update a webpage with new events in real-time, without forcing a user to reload a page to fetch new data. If you'd like to update data on a webpage in that manner, you can subscribe to your workflow's event stream and handle new events as they come in.</p>
<p>Beyond web browsers, any program that's able to create an <a href="https://developer.mozilla.org/en-US/docs/Web/API/EventSource" target="_blank" rel="noopener noreferrer"><code>EventSource</code> interface<ExternalLinkIcon/></a> can listen for server-sent events delivered from Pipedream. You can run a Node.js script or a Ruby on Rails app that receives server-sent events, for example.</p>
<h2 id="sending-data-to-an-sse-destination-in-workflows" tabindex="-1"><a class="header-anchor" href="#sending-data-to-an-sse-destination-in-workflows" aria-hidden="true">#</a> Sending data to an SSE Destination in workflows</h2>
<p>You can send data to an SSE Destination in <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">Node.js code steps<ExternalLinkIcon/></a> using the <code>$.send.sse()</code> function.</p>
<p><a href="/workflows/steps/actions/#adding-a-new-action" target="_blank" rel="noopener noreferrer">Add a new step to your workflow<ExternalLinkIcon/></a>, then search for &quot;<strong>Code</strong>&quot;:</p>
<p>Then add this code to that step:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">sse</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">channel</span><span class="token operator">:</span> <span class="token string">"events"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">payload</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke Skywalker"</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p><strong>See <a href="https://pipedream.com/@dylburger/sse-example-p_ezCdBz/edit" target="_blank" rel="noopener noreferrer">this workflow<ExternalLinkIcon/></a></strong> for an example of how to use <code>$.send.sse()</code>.</p>
<p>Send a test event to your workflow, then review the section on <a href="#receiving-events">Receiving events</a> to see how you can setup an <code>EventSource</code> to retrieve events sent to the SSE Destination.</p>
<p><code>$.send.sse()</code> accepts an object with the following properties:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">sse</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      channel<span class="token punctuation">,</span> <span class="token comment">// Required, corresponds to the event in the SSE spec</span>
      payload <span class="token comment">// Required, the event payload</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p>Again, it's important to remember that <strong>Destination delivery is asynchronous</strong>. If you iterate over an array of values and send an SSE for each:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> names <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Luke"</span><span class="token punctuation">,</span> <span class="token string">"Han"</span><span class="token punctuation">,</span> <span class="token string">"Leia"</span><span class="token punctuation">,</span> <span class="token string">"Obi Wan"</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    names<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token parameter">name</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">sse</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">channel</span><span class="token operator">:</span> <span class="token string">"names"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">payload</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          name
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>you won't have to <code>await</code> the execution of the SSE Destination requests in your workflow. We'll collect every <code>$.send.sse()</code> call and defer those requests, sending them after your workflow finishes.</p>
<h2 id="using-send-sse-in-component-actions" tabindex="-1"><a class="header-anchor" href="#using-send-sse-in-component-actions" aria-hidden="true">#</a> Using <code>$.send.sse</code> in component actions</h2>
<p>If you're authoring a <a href="/components/actions/" target="_blank" rel="noopener noreferrer">component action<ExternalLinkIcon/></a>, you can send events to an SSE destination using <code>$.send.sse</code>.</p>
<p><code>$.send.sse</code> functions the same as <a href="#sending-data-to-an-sse-destination-in-workflows"><code>$.send.sse</code> in workflow code steps</a>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    $<span class="token punctuation">.</span>send<span class="token punctuation">.</span><span class="token function">sse</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">channel</span><span class="token operator">:</span> <span class="token string">"events"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">payload</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Luke Skywalker"</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="receiving-events" tabindex="-1"><a class="header-anchor" href="#receiving-events" aria-hidden="true">#</a> Receiving events</h2>
<p>Once you've sent events to an SSE Destination, you can start receiving a stream of those events in a client by configuring an <a href="https://developer.mozilla.org/en-US/docs/Web/API/EventSource" target="_blank" rel="noopener noreferrer"><code>EventSource</code><ExternalLinkIcon/></a> that connects to the Pipedream SSE stream.</p>
<h3 id="retrieving-your-workflow-s-event-stream-url" tabindex="-1"><a class="header-anchor" href="#retrieving-your-workflow-s-event-stream-url" aria-hidden="true">#</a> Retrieving your workflow's event stream URL</h3>
<p>First, it's important to note that all events sent to an SSE destination within a workflow are sent to an SSE event stream specific to that workflow. The event stream is tied to the workflow's ID, which you can find by examining the URL of the pipeline in the Pipedream UI. For example, the <code>p_aBcDeF</code> in this URL is the pipeline ID:</p>
<div>
<img alt="New code step" width="500" src="@source/destinations/sse/images/pipeline-id.png">
</div>
<p><strong>Note that the <code>p_</code> prefix is part of the workflow ID</strong>.</p>
<p>Once you have the workflow ID, you can construct the event source URL for your SSE destination. That URL is of the following format:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>http://sdk.m.pipedream.net/pipelines/[YOUR WORKFLOW ID]/sse
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>In the example above, the URL of our event stream would be:</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>http://sdk.m.pipedream.net/pipelines/p_aBcDeF/sse
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>You should be able to open that URL in your browser. Most modern browsers support connecting to an event stream directly, and will stream events without any work on your part to help you confirm that the stream is working.</p>
<p>If you've already sent events to your SSE destination, you should see those events here! We'll return the most recent 100 events delivered to the corresponding SSE destination immediately. This allows your client to catch up with events previously sent to the destination. Then, any new events sent to the SSE destination while you're connected will be delivered to the client.</p>
<h3 id="sample-code-to-connect-to-your-event-stream" tabindex="-1"><a class="header-anchor" href="#sample-code-to-connect-to-your-event-stream" aria-hidden="true">#</a> Sample code to connect to your event stream</h3>
<p>It's easy to setup a simple webpage to <code>console.log()</code> all events from an event stream. You can find a lot more examples of how to work with SSE on the web, but this should help you understand the basic concepts.</p>
<p>You'll need to create two files in the same directory on your machine: an <code>index.html</code> file for the HTML, and an <code>sse.js</code> file to keep the JavaScript that connects to the event stream.</p>
<p><strong>index.html</strong></p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>SSE test<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sse.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>app<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p><strong>sse.js</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> eventSource <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventSource</span><span class="token punctuation">(</span>
  <span class="token string">"http://sdk.m.pipedream.net/pipelines/[YOUR WORKFLOW ID]/sse"</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

eventSource<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">"[YOUR CHANNEL]"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">e</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"New event from cron test event stream: "</span><span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p><strong>Make sure to add your workflow ID and the name of your channel you specified in your SSE Destination</strong>. Then, open the <code>index.html</code> page in your browser. In your browser's developer tools JavaScript console, you should see new events appear as you send them.</p>
<p>Note that the <code>addEventListener</code> code will listen specifically for events sent to the <strong>cron_test</strong> <code>channel</code> specified in our SSE destination. You can listen for multiple types of events at once by adding multiple event listeners on the client.</p>
<p><strong>Try triggering more test events from your workflow while this page is open to see how this works end-to-end</strong>.</p>
<h2 id="keepalive-messages" tabindex="-1"><a class="header-anchor" href="#keepalive-messages" aria-hidden="true">#</a> <code>:keepalive</code> messages</h2>
<p><a href="https://www.w3.org/TR/2009/WD-eventsource-20090421/#notes" target="_blank" rel="noopener noreferrer">The SSE spec<ExternalLinkIcon/></a> notes that</p>
<blockquote>
<p>Legacy proxy servers are known to, in certain cases, drop HTTP connections after a short timeout. To protect against such proxy servers, authors can include a comment line (one starting with a ':' character) every 15 seconds or so.</p>
</blockquote>
<p>Roughly every 15 seconds, we'll send a message with the <code>:keepalive</code> comment to keep open SSE connections alive. These comments should be ignored when you're listening for messages using the <code>EventSource</code> interface.</p>
</template>
