export default {
  sourceNameProps: [
    "Order Desk",
    "FoxyCart",
    "WooCommerce",
    "BigCommerce",
    "Amazon",
    "Shopify",
    "eBay",
    "Magento",
    "Magento 2",
    "Gumroad",
    "Wufoo",
    "Interspire",
    "PayPal",
    "Stripe",
    "Etsy",
    "Jet",
    "Zapier",
    "Spark Pay",
    "Snipcart",
    "Recurly",
    "Volusion",
    "Chargebee",
    "Weebly",
    "Walmart",
    "Walmart.com",
    "Modular Merchant",
    "Ecwid",
    "UltraCart",
    "nopCommerce",
    "Squarespace",
    "Celery",
    "E-junkie",
    "CommerceHQ",
    "BrightStores",
    "SamCart",
    "Wayfair",
    "Spree",
  ],
  paymentStatus: [
    "Approved",
    "Authorized",
    "Captured",
    "Fully Refunded",
    "Partially Refunded",
    "Pending",
    "Rejected",
    "Voided",
  ],
  orderDir: [
    "asc",
    "desc",
  ],
};
