export default {
  "Id": 3,
  "RecordNumber": "2-1",
  "EquipmentRefId": 2,
  "MasterStandard": "dgfh",
  "Type": "gfhs",
  "Manufacturer": "erye",
  "Website": "sdfh",
  "Model": "sdfh",
  "SerialNumber": "dsgds",
  "TypesMeasurement": "dsrh",
  "UnitOfMeasure": "erth",
  "RangeOrSize": "reh",
  "Tolerance": "sdfh",
  "Location": "stradrhaeing",
  "ResponsibleUser": "dfh",
  "Interval": "qgr",
  "Years": 12,
  "Months": 2,
  "Days": 4,
  "CalibrationInstructions": "qerge",
  "CalibrationEnvironment": "fbsdf",
  "CalibrationTestMode": "aerh",
  "CreatedBy": "API Demo",
  "UpdatedBy": "API Demo",
  "IsDeleted": false,
  "UpdatedDate": "2024-08-15T22:21:16Z",
  "CreatedDate": "2024-08-15T17:21:16-05:00",
  "ControlNumber": "dsf",
  "NISTNumber": "erh",
  "AssetNo": "dfsh",
  "ConditionAquired": "dfh",
  "SourceOrVendor": "adfhad",
  "DateAquired": "2024-03-14T00:00:00",
  "Area": "arhae"
}