export default {
  "index": "What is Pipedream?",
  "quickstart": "Quickstart",
  "integrations": "Integrations",
  "workspaces": "Workspaces",
  "projects": "Projects",
  "workflows": "Workflows",
  "connect": "Connect",
  "rest-api": "REST API",
  "contributing": "Contributing",
  "pricing": "Pricing",
  "account": "Account",
  "privacy-and-security": "Security",
  "troubleshooting": "Troubleshooting",
  "glossary": "Glossary of Terms",
  "support": {
    title: "Support",
    type: "page",
    href: "https://pipedream.com/support",
    newWindow: true,
  },
  "pricing-page": {
    title: "Pricing",
    href: "https://pipedream.com/pricing",
    newWindow: true,
    type: "page",
  },
  "statuspage": {
    title: "Status",
    type: "page",
    href: "https://status.pipedream.com",
    newWindow: true,
  },
  "deprecated": {
    display: "hidden",
  },
  "hidden": {
    display: "hidden",
  },
} as const
