export default {
    "account_id": 98220,
    "account": "Test User",
    "profile_id": 146471,
    "profile": "Test User",
    "lead_id": 178849242,
    "lead_type": "Phone Call",
    "lead_status": "Unique",
    "lead_score": 0,
    "date_created": "2025-05-28T19:19:51Z",
    "lead_state": "Completed",
    "quotable": "Not Set",
    "quote_value": null,
    "sales_value": null,
    "lead_source": "(direct)",
    "lead_medium": "(none)",
    "lead_url": "https://www.test.com/?utm_source=google&utm_medium=cpc&utm_keyword=test+number&utm_campaign=Test%20Numbers",
    "landing_url": "https://www.test.com/?wc_verification=true",
    "operating_system": "macOS 10.15 Catalina",
    "browser": "Chrome 136",
    "device_type": "Desktop",
    "device_make": "Apple Mac",
    "ip_address": "47.225.143.157",
    "contact_name": "",
    "contact_company_name": "",
    "contact_email_address": "",
    "contact_phone_number": "",
    "phone_number": "",
    "caller_number": "",
    "user_id": "146471-a0a65931-94f3-8351-69c0-fcfa621d828a",
    "spam": false,
    "duplicate": false,
    "spotted_keywords": "",
    "lead_analysis": [],
    "last_updated": "2025-05-28T19:20:03Z",
    "call_status": "Completed",
    "phone_name": "All Traffic",
    "call_duration": "13 seconds",
    "call_duration_seconds": 13,
    "tracking_number": "",
    "destination_number": "",
    "caller_name": "M Bergeron",
    "caller_city": "Santa Cruz",
    "caller_state": "CA",
    "caller_country": "US",
    "answer_status": "Answered",
    "line_type": "Landline",
    "recording": "https://app.whatconverts.com/recording/r-fbe05094-61e20aad-dc7a-4961-8da7-aeb5a20e0d3d/download",
    "play_recording": "https://app.whatconverts.com/recording/r-fbe05094-61e20aad-dc7a-4961-8da7-aeb5a20e0d3d/play",
    "call_transcription": "Recipient\nEnter password, then press.",
    "city": "Santa Cruz",
    "state": "CA",
    "country": "US",
    "additional_fields": []
  }