// @generated by integrations/pipedream/scripts/generate-from-catalog.mts — do not edit

import app from "../../social_fetch.app.mjs";

export default {
  key: "social_fetch-get-post",
  name: "Get Post",
  description: "Fetches public post, video, or tweet data from a URL. [See the documentation](https://www.socialfetch.dev/docs/api)",
  version: "0.0.1",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: true,
  },
  props: {
    app,
    platform: {
      propDefinition: [
        app,
        "postPlatform",
      ],
    },
    postUrl: {
      propDefinition: [
        app,
        "postUrl",
      ],
    },
  },
  async run({ $ }) {
    const response = await this.app.getPost({
      $,
      platform: this.platform,
      postUrl: this.postUrl,
    });
    $.export("$summary", "Successfully fetched post");
    return response;
  },
};
