export default {
  TYPES: [
    "ResetPassword",
    "ActivateUser",
    "InviteToTenant",
    "PwnedPassword",
    "MagicLink",
    "OTC",
    "ConnectNewDevice",
    "UserUsedInvitation",
    "ResetPhoneNumber",
    "BulkInvitesToTenant",
    "MFAEnroll",
    "MFAUnenroll",
    "NewMFAMethod",
    "MFARecoveryCode",
    "RemoveMFAMethod",
    "EmailVerification",
    "BruteForceProtection",
    "SuspiciousIP",
    "MFAOTC",
    "ImpossibleTravel",
    "BotDetection",
    "SmsAuthenticationEnabled",
  ],
};
