export default {
  "url":"https://api.freeagent.com/v2/contacts/2",
  "first_name":"test",
  "last_name":"me",
  "organisation_name":"Acme Ltd",
  "email":"test@example.com",
  "billing_email":"billing@example.com",
  "phone_number":"12345678",
  "mobile":"9876543210",
  "address1":"11 George Street",
  "address2": "South Court",
  "address3": "Flat 6",
  "town":"London",
  "region": "Southwark",
  "postcode":"SE1 6HA",
  "country":"United Kingdom",
  "contact_name_on_invoices":true,
  "default_payment_terms_in_days":30,
  "locale":"en",
  "account_balance":"-100.0",
  "uses_contact_invoice_sequence":false,
  "charge_sales_tax":"Auto",
  "sales_tax_registration_number":"ST12345",
  "active_projects_count":1,
  "direct_debit_mandate_state":"active",
  "status":"Active",
  "is_cis_subcontractor":true,
  "cis_deduction_rate":"cis_standard",
  "unique_tax_reference":"1234567890",
  "subcontractor_verification_number":"V1234567890",
  "created_at":"2011-09-14T16:00:41Z",
  "updated_at":"2011-09-16T09:34:41Z"
}
