<template><h1 id="environment-variables" tabindex="-1"><a class="header-anchor" href="#environment-variables" aria-hidden="true">#</a> Environment Variables</h1>
<p><strong>Environment variables</strong> enable you to separate secrets and other data from your code.</p>
<p>You should not include API keys or other sensitive data directly in your workflow's code. This is especially important if you <a href="/public-workflows/" target="_blank" rel="noopener noreferrer">make your workflow public<ExternalLinkIcon/></a>, since anyone would be able to see your API key in plain sight. By referencing the value of an environment variable, instead, your workflow includes a reference to that variable — <code>process.env.API_KEY</code> — instead of the API key itself.</p>
<p>Environment variables are defined at the account-level, and can be referenced in <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">workflow code<ExternalLinkIcon/></a> or <a href="/workflows/steps/params/" target="_blank" rel="noopener noreferrer">step params<ExternalLinkIcon/></a>.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#creating-updating-environment-variables">Creating, updating environment variables</RouterLink></li><li><RouterLink to="#referencing-environment-variables-in-code">Referencing environment variables in code</RouterLink></li><li><RouterLink to="#referencing-environment-variables-in-actions">Referencing environment variables in actions</RouterLink></li><li><RouterLink to="#copying-workflows-that-use-environment-variables">Copying workflows that use environment variables</RouterLink></li><li><RouterLink to="#limits">Limits</RouterLink></li></ul></nav>
<h2 id="creating-updating-environment-variables" tabindex="-1"><a class="header-anchor" href="#creating-updating-environment-variables" aria-hidden="true">#</a> Creating, updating environment variables</h2>
<p>Environment variables are managed at the account-level. You can access your environment variables at <a href="https://pipedream.com/settings/env-vars">{{$site.themeConfig.PIPEDREAM_BASE_URL}}/settings/env-vars</a>.</p>
<p>To add an environment variable, click the <strong>New Environment Variable</strong> button.</p>
<p>To edit an environment variable, click the <strong>Reveal / Edit</strong> button next to a specific variable.</p>
<p>Updates to environment variables will be made available to your workflows as soon as the save operation is complete — typically a few seconds after you click <strong>Save</strong>. If you update the value of an environment variable in the UI, your workflow should automatically use that new value where it's referenced.</p>
<h2 id="referencing-environment-variables-in-code" tabindex="-1"><a class="header-anchor" href="#referencing-environment-variables-in-code" aria-hidden="true">#</a> Referencing environment variables in code</h2>
<p>You can reference the value of any environment variable using the object <a href="https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_process_env" target="_blank" rel="noopener noreferrer"><code>process.env</code><ExternalLinkIcon/></a>. This object contains environment variables as key-value pairs.</p>
<p>For example, let's say you have an environment variable named <code>API_KEY</code>. You can reference its value using <code>process.env.API_KEY</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> url <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">http://yourapi.com/endpoint/?api_key=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>process<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">API_KEY</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>Variable names are case-sensitive. Use the name you defined in your Environment settings in the app when referencing your variable in <code>process.env</code>.</p>
<p>Referencing an environment variable that doesn't exist returns the value <code>undefined</code> in Node.js. For example, if you try to reference <code>process.env.API_KEY</code> without first defining the <code>API_KEY</code> variable in your environment settings, it will return the value <code>undefined</code>.</p>
<div class="custom-container warning"><p class="custom-container-title">WARNING</p>
<p>Logging the value of any environment variables — for example, using <code>console.log</code> — will include that value in the logs associated with the cell. Please keep this in mind and take care not to print the values of sensitive secrets.</p>
</div>
<h2 id="referencing-environment-variables-in-actions" tabindex="-1"><a class="header-anchor" href="#referencing-environment-variables-in-actions" aria-hidden="true">#</a> Referencing environment variables in actions</h2>
<p><a href="/components/actions/" target="_blank" rel="noopener noreferrer">Actions<ExternalLinkIcon/></a> are prebuilt code steps that provide a form for passing <a href="/workflows/steps/params/" target="_blank" rel="noopener noreferrer">params<ExternalLinkIcon/></a> as input.</p>
<p>You can reference the value of environment variables using <code v-pre>{{process.env.YOUR_ENV_VAR}}</code>. You'll see a list of your environment variables in the <a href="/workflows/steps/params/#use-the-object-explorer" target="_blank" rel="noopener noreferrer">object explorer<ExternalLinkIcon/></a>:</p>
<div>
<img alt="Environment variables in the object explorer" width="300px" src="@source/environment-variables/images/env-vars-object-explorer.png">
</div>
<h2 id="copying-workflows-that-use-environment-variables" tabindex="-1"><a class="header-anchor" href="#copying-workflows-that-use-environment-variables" aria-hidden="true">#</a> Copying workflows that use environment variables</h2>
<p>Your environment variables are made available to any running workflow. <strong>If you copy a public workflow that uses an environment variable, make sure you review the code to see what environment variables it's using</strong>.</p>
<p>Reviewing the code ensures you have the necessary variables defined for the workflow to run correctly, and makes sure the original workflow author isn't reading variables that you don't need for the workflow to function. You can always modify the code for the workflow after copying to remove these variables, or change their names.</p>
<h2 id="limits" tabindex="-1"><a class="header-anchor" href="#limits" aria-hidden="true">#</a> Limits</h2>
<p>Currently, <strong>environment variables are only exposed in Pipedream workflows, <a href="https://github.com/PipedreamHQ/pipedream/issues/583" target="_blank" rel="noopener noreferrer">not event sources<ExternalLinkIcon/></a></strong>.</p>
<p>The value of any environment variable may be no longer than <code>64KB</code>.</p>
<p>The names of environment variables must start with a letter or underscore. Pipedream also reserves environment variables that start with <code>PIPEDREAM_</code> for internal use. You cannot create an environment variable that begins with that prefix.</p>
<Footer />
</template>
