export default {
  "id": 411081,
  "school_id": 16385,
  "identification_number": "123",
  "fname": "Jhon",
  "lname": "Doe",
  "gender": "Male",
  "registration_date": "2024-10-17",
  "date_of_birth": "1991-02-02",
  "email_address": "jhon@email.com",
  "mobile_phonecode": "",
  "mobile_phone": "",
  "home_phonecode": "",
  "home_phone": "",
  "street_name_and_number": "",
  "flat_floor": "",
  "area": "",
  "city": "",
  "country_code": "",
  "postcode": "",
  "whole_address": "",
  "general_notes": "",
  "medical_notes": "",
  "delayed_payments": "",
  "num_enrolled_courses": 1,
  "discount_percentage": "10",
  "discount_type": "percentage",
  "custom_fields": [],
  "timezone": null,
  "course_subject": null,
  "course_level": null,
  "photo_link": "/img/user-no-img-m.jpg",
  "preferred_payment_method": "Credit Card",
  "classes": [
    {
      "course_title": "class title",
      "course_full_title": "class title [Online Lesson]",
      "course_subject": "",
      "course_level": "",
      "course_description": "",
      "course_started": true,
      "course_ended": false,
      "school_id": 16385,
      "recurrence": "weekly",
      "payment_frequency": "free",
      "enrolment_date": "2024-10-20",
      "unenrolment_date": null,
      "student_id": 411081
    }
  ]
}