export default {
	"id": 103717,
	"orderNumber": "Test-Order-001",
	"orderReference": "",
	"customer": {
		"id": 7089,
		"title": "",
		"name": "Test Customer 1",
		"surname": "",
		"email": "testcustomer1@testserver.com",
		"company": "Test Company",
		"accountNumber": ""
	},
	"client": null,
	"orderedDate": "2021-12-13T00:00:00-07:00",
	"createdDate": "2024-09-13T13:02:58-07:00",
	"modifiedDate": "2024-09-13T13:02:58-07:00",
	"orderPlaced": true,
	"createdBy": {
		"id": 520,
		"name": "Pipedream Support"
	},
	"completed": false,
	"completedDate": "",
	"cancelled": false,
	"cancelledDate": "",
	"cancelledReason": "",
	"cancelledBy": null,
	"onHold": false,
	"onHoldUntil": "",
	"postageAccount": "sender",
	"buyerPaidShipping": 0,
	"shippingAddress": {
		"id": 12517,
		"company": "",
		"name": "",
		"line1": "515 E Grant St",
		"line2": "",
		"line3": "",
		"city": "Phoenix",
		"state": "AZ",
		"zip": "85004",
		"country": "United States",
		"countryCode": "US",
		"phone": "",
		"code": "",
		"verifiedStatus": "awaiting",
		"verifiedDate": "",
		"verifiedMessage": ""
	},
	"billingAddress": {
		"id": 12518,
		"company": "",
		"name": "",
		"line1": "N/A",
		"line2": "",
		"line3": "",
		"city": "",
		"state": "",
		"zip": "",
		"country": "United States",
		"countryCode": "US",
		"phone": "",
		"code": "",
		"verifiedStatus": "awaiting",
		"verifiedDate": "",
		"verifiedMessage": ""
	},
	"shipVia": "Standard",
	"shipViaPackaging": "",
	"shipViaConfirmation": "",
	"dryIceWeight": 0,
	"packageSku": "",
	"shipFromWarehouse": {
		"id": 187,
		"name": "Main Warehouse"
	},
	"projectNumber": "",
	"discountPercentage": 0,
	"orderSource": "CSV Import",
	"internalNote": "",
	"noteFromCustomer": "",
	"noteToCustomer": "",
	"notificationEmail": "",
	"userField1": "",
	"userField2": "",
	"userField3": "",
	"myList1": "",
	"myList2": "",
	"tags": [],
	"items": [
		{
			"id": 214405,
			"itemId": 12063,
			"sku": "TEST-SKU-101",
			"description": "Baseball Cap",
			"orderQuantity": 1,
			"uom": "Each",
			"quantity": 1,
			"allocatedQuantity": 1,
			"pickedQuantity": 0,
			"price": 49,
			"discountPercentage": 0,
			"partOfKit": false,
			"componentOf": 0,
			"additionalFields": null
		}
	]
}