<template><h1 id="hello-world" tabindex="-1"><a class="header-anchor" href="#hello-world" aria-hidden="true">#</a> hello world!</h1>
<p>First, let's create an HTTP-triggered workflow and return a response of <code>hello world!</code>. This example will cover how to:</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#create-a-new-workflow">Create a new workflow</RouterLink></li><li><RouterLink to="#generate-a-unique-endpoint-url-to-trigger-the-workflow">Generate a unique endpoint URL to trigger the workflow</RouterLink></li><li><RouterLink to="#send-http-requests-to-your-workflow">Send HTTP requests to your workflow</RouterLink></li><li><RouterLink to="#inspect-workflow-events">Inspect workflow events</RouterLink></li><li><RouterLink to="#return-a-custom-response-on-each-http-request">Return a custom response on each HTTP request</RouterLink></li></ul></nav>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>If you have any issues completing this example, you can <a href="https://pipedream.com/@gettingstarted/quickstart-hello-world-p_2gCWpmk/" target="_blank" rel="noopener noreferrer">view, copy and run a completed version<ExternalLinkIcon/></a>.</p>
</div>
<h3 id="create-a-new-workflow" tabindex="-1"><a class="header-anchor" href="#create-a-new-workflow" aria-hidden="true">#</a> Create a new workflow</h3>
<p>First, create a new workflow by clicking <strong>New</strong> from <a href="https://pipedream.com/workflows" target="_blank" rel="noopener noreferrer">https://pipedream.com/workflows<ExternalLinkIcon/></a>:</p>
<p><img src="@source/quickstart/hello-world/images/image-20210516114638660.png" alt="image-20210516114638660"></p>
<p>Pipedream will launch the workflow builder:</p>
<p><img src="@source/quickstart/hello-world/images/image-20210516191619202.png" alt="image-20210516191619202"></p>
<p>Following is a brief overview of the screen layout:</p>
<p><img src="@source/quickstart/hello-world/images/builder_overview.png" alt="image-20210518181827110"></p>
<h3 id="generate-a-unique-endpoint-url-to-trigger-the-workflow" tabindex="-1"><a class="header-anchor" href="#generate-a-unique-endpoint-url-to-trigger-the-workflow" aria-hidden="true">#</a> Generate a unique endpoint URL to trigger the workflow</h3>
<p>To create an HTTP or webhook-triggered workflow, select the <strong>HTTP API</strong> trigger.</p>
<p><img src="@source/quickstart/hello-world/images/image-20210516191641863.png" alt="image-20210516191641863"></p>
<p>Your workflow will automatically deploy and Pipedream will generate a unique endpoint URL.</p>
<p><img src="@source/quickstart/hello-world/images/image-20210525161122066.png" alt="image-20210525161122066"></p>
<h3 id="send-http-requests-to-your-workflow" tabindex="-1"><a class="header-anchor" href="#send-http-requests-to-your-workflow" aria-hidden="true">#</a> Send HTTP requests to your workflow</h3>
<p>Any requests you make to the endpoint URL will trigger your workflow. To test it out:</p>
<ol>
<li>Copy the endpoint URL generated by Pipedream</li>
<li>Open a new browser tab and load the URL</li>
</ol>
<p><img src="@source/quickstart/hello-world/images/image-20210525161201979.png" alt="image-20210525161201979"></p>
<p>When you return to your workflow, you'll see the requests in the event list (events appear in real-time — you don't need to refresh the page).</p>
<p><img src="@source/quickstart/hello-world/images/image-20210525161233808.png" alt="image-20210525161233808"></p>
<p><strong>IMPORTANT:</strong> You may see multiple events appear in the event list each time you load the endpoint URL in a web browser's address bar. That happens because modern browsers automatically request a <code>favicon.ico</code> resource when you load a URL. We'll update our workflow to handle this case in a later section of the quickstart.</p>
<h3 id="inspect-workflow-events" tabindex="-1"><a class="header-anchor" href="#inspect-workflow-events" aria-hidden="true">#</a> Inspect workflow events</h3>
<p>Select an event from the list to inspect the associated exports and logs (click on an event again to de-select it). The HTTP trigger exports data including the <code>url</code> invoked, <code>method</code>, <code>body</code>, <code>headers</code>, <code>query parameters</code> and more. This data can also be referenced by steps in your workflow via the <code>steps</code> object (for example, to use the trigger event in a later step you can reference <code>steps.trigger.event</code> — we'll cover this in the next example).</p>
<p><img src="@source/quickstart/hello-world/images/inspect-events.gif" alt="inspect-events"></p>
<h3 id="return-a-custom-response-on-each-http-request" tabindex="-1"><a class="header-anchor" href="#return-a-custom-response-on-each-http-request" aria-hidden="true">#</a> Return a custom response on each HTTP request</h3>
<p>Next, let's use Pipedream's <code>$respond()</code> function to return a custom response from the workflow. First, click on <strong>Run Node.js code</strong> to add a code step (if the step menu is not expanded, click the <strong>+</strong> button below the trigger).</p>
<p><img src="@source/quickstart/hello-world/images/image-20210525161751080.png" alt="image-20210525161751080"></p>
<p>Pipedream will add a code step to your workflow.</p>
<p><img src="@source/quickstart/hello-world/images/image-20210525161833932.png" alt="image-20210525161833932"></p>
<p>You can write any Node.js code and use any npm package (we'll cover npm in a later part of this guide). For this example, add the following code to return a custom response of <code>hello world!</code> on each HTTP request:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">await</span> <span class="token function">$respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
  <span class="token literal-property property">immediate</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
  <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">hello world!</span><span class="token template-punctuation string">`</span></span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>Next, rename the step from <code>steps.nodejs</code> to <code>steps.respond</code>. <strong>IMPORTANT:</strong> Step names affect workflow functionality and must be unique within a workflow. When you share data between steps, you'll use step names to reference data.</p>
<p><img src="@source/quickstart/hello-world/images/rename-respond-1984875.gif" alt="rename-respond"></p>
<p>Then click <strong>Deploy</strong> to run your changes on each new event.</p>
<p><img src="@source/quickstart/hello-world/images/image-20210525162206777.png" alt="image-20210525162206777"></p>
<p>The deploy should complete in about 1-2 seconds. Then reload the endpoint URL in your browser — the response should change to <code>hello world!</code>.</p>
<p><img src="@source/quickstart/hello-world/images/hello-world-refresh.gif" alt="hello-world-refresh"></p>
<p>Finally, give your workflow a friendly name like <code>HTTP Quickstart</code>.</p>
<p><img src="@source/quickstart/hello-world/images/name-workflow.gif" alt="name-workflow"></p>
<p>Congratulations! You just built your first serverless workflow!</p>
<p><strong>Next, let's pass data in the HTTP request and use it to customize the workflow response.</strong></p>
<p style="text-align:center;">
<a :href="$withBase('/quickstart/hello-name/')"><img src="@source/quickstart/next.png"></a>
</p>
</template>
