export default {
  "id": 27,
  "custom_id": null,
  "document_type": "invoice",
  "proforma_followup_document": null,
  "correction_id": null,
  "number": "2023-0021",
  "number_format_id": 31,
  "variable_symbol": "20230021",
  "your_name": "Alexandr Hejsek",
  "your_street": "Hopsinková 14",
  "your_city": "Praha",
  "your_zip": "10000",
  "your_country": "CZ",
  "your_registration_no": "87654321",
  "your_vat_no": "CZ12121212",
  "your_local_vat_no": null,
  "client_name": "Apple Czech s.r.o.",
  "client_street": "Klimentská 1216/46",
  "client_city": "Praha",
  "client_zip": "11000",
  "client_country": "CZ",
  "client_registration_no": "28897501",
  "client_vat_no": "CZ28897501",
  "client_local_vat_no": null,
  "client_has_delivery_address": false,
  "client_delivery_name": null,
  "client_delivery_street": null,
  "client_delivery_city": null,
  "client_delivery_zip": null,
  "client_delivery_country": null,
  "subject_id": 16,
  "subject_custom_id": null,
  "generator_id": null,
  "related_id": null,
  "paypal": false,
  "gopay": false,
  "token": "69UqMuxhiA",
  "status": "sent",
  "order_number": null,
  "issued_on": "2023-11-30",
  "taxable_fulfillment_due": "2023-11-30",
  "due": 14,
  "due_on": "2023-12-14",
  "sent_at": "2023-12-01T09:05:47.117+01:00",
  "paid_on": null,
  "reminder_sent_at": null,
  "cancelled_at": null,
  "uncollectible_at": null,
  "locked_at": null,
  "webinvoice_seen_on": null,
  "note": "Fakturujeme Vám následující položky",
  "footer_note": "",
  "private_note": null,
  "tags": [],
  "bank_account": "1234/2010",
  "iban": null,
  "swift_bic": null,
  "iban_visibility": "automatically",
  "show_already_paid_note_in_pdf": false,
  "payment_method": "bank",
  "custom_payment_method": null,
  "hide_bank_account": false,
  "currency": "CZK",
  "exchange_rate": "1.0",
  "language": "cz",
  "transferred_tax_liability": false,
  "supply_code": null,
  "oss": "disabled",
  "vat_price_mode": "with_vat",
  "subtotal": "9133.6",
  "total": "11000.0",
  "native_subtotal": "9133.6",
  "native_total": "11000.0",
  "remaining_amount": "11000.0",
  "remaining_native_amount": "11000.0",
  "eet_records": [],
  "lines": [
    {
      "id": 46,
      "name": "Grafická karta",
      "quantity": "1.0",
      "unit_name": "",
      "unit_price": "8264.0",
      "vat_rate": 21,
      "unit_price_without_vat": "8264.0",
      "unit_price_with_vat": "10000.0",
      "total_price_without_vat": "8264.0",
      "total_vat": "1736.0",
      "native_total_price_without_vat": "8264.0",
      "native_total_vat": "1736.0",
      "inventory": {
        "item_id": 26,
        "sku": "KU994RUR8465",
        "article_number_type": null,
        "article_number": null,
        "move_id": 56
      }
    },
    {
      "id": 47,
      "name": "Jídlo",
      "quantity": "5.0",
      "unit_name": "",
      "unit_price": "173.92",
      "vat_rate": 15,
      "unit_price_without_vat": "173.92",
      "unit_price_with_vat": "200.0",
      "total_price_without_vat": "869.6",
      "total_vat": "130.4",
      "native_total_price_without_vat": "869.6",
      "native_total_vat": "130.4",
      "inventory": null
    }
  ],
  "vat_rates_summary": [
    {
      "vat_rate": 21,
      "base": "8264.0",
      "vat": "1736.0",
      "currency": "CZK",
      "native_base": "8264.0",
      "native_vat": "1736.0",
      "native_currency": "CZK"
    },
    {
      "vat_rate": 15,
      "base": "869.6",
      "vat": "130.4",
      "currency": "CZK",
      "native_base": "869.6",
      "native_vat": "130.4",
      "native_currency": "CZK"
    }
  ],
  "paid_advances": [],
  "payments": [],
  "attachments": null,
  "html_url": "https://app.fakturoid.cz/applecorp/invoices/27",
  "public_html_url": "https://app.fakturoid.cz/applecorp/p/69UqMuxhiA/2023-0021",
  "url": "https://app.fakturoid.cz/api/v3/accounts/applecorp/invoices/27.json",
  "pdf_url": "https://app.fakturoid.cz/api/v3/accounts/applecorp/invoices/27/download.pdf",
  "subject_url": "https://app.fakturoid.cz/api/v3/accounts/applecorp/subjects/16.json",
  "created_at": "2023-11-30T13:50:45.848+01:00",
  "updated_at": "2023-12-01T09:05:47.187+01:00"
}