export default {
  "Id": 4,
  "Company": 1,
  "FirstName": "Wendla",
  "LastName": "Bergman",
  "DisplayName": "Wendla Bergman",
  "OtherName": null,
  "Salutation": null,
  "MainAddress": null,
  "PostalAddress": null,
  "Contact": 0,
  "EmergencyAddress": null,
  "DateOfBirth": null,
  "Gender": null,
  "Pronouns": 0,
  "CustomPronouns": null,
  "Photo": null,
  "UserId": null,
  "JobAppId": null,
  "Active": true,
  "StartDate": "2024-09-03T15:38:27-04:00",
  "TerminationDate": null,
  "EmploymentEndDate": null,
  "EmploymentEndReason": null,
  "StressProfile": 8,
  "Position": null,
  "HigherDuty": null,
  "Role": 50,
  "AllowAppraisal": true,
  "HistoryId": 2571,
  "CustomFieldData": null,
  "OnboardingId": null,
  "ExternalLinkId": null,
  "Creator": 1,
  "Created": "2024-09-03T15:38:28-04:00",
  "Modified": "2024-09-03T15:38:28-04:00",
  "CompanyObject": {
    "Id": 1,
    "Portfolio": null,
    "Code": "223",
    "Active": true,
    "ParentCompany": 0,
    "CompanyName": "Testing",
    "TradingName": "",
    "BusinessNumber": "",
    "CompanyNumber": null,
    "IsWorkplace": true,
    "IsPayrollEntity": true,
    "PayrollExportCode": "",
    "Address": 157,
    "Contact": 14,
    "Creator": 1,
    "Created": "2009-04-08T00:53:33-04:00",
    "Modified": "2024-09-03T13:23:43-04:00"
  },
  "StressProfileObject": {
    "Id": 8,
    "Name": "Standard 40 hours, All day",
    "MaxHoursPerShift": 8,
    "MaxHoursPerPeriod": 40,
    "MaxDaysPerPeriod": 5,
    "MaxHoursPerDay": 24,
    "GapHoursBetweenShifts": 12,
    "CustomRules": null,
    "Creator": 1,
    "Created": "2020-10-25T17:26:48-04:00",
    "Modified": "2020-10-25T17:26:48-04:00"
  },
  "RoleObject": {
    "Id": 50,
    "Role": "Employee",
    "Ranking": 97,
    "ReportTo": 3,
    "Permissions": "Time Sheets-> Access:Yes\nMobile Bump-> Access:Yes\nJournal-> Access:No\nAnnouncements-> Access:Yes\nRoster Manager-> Access:No\nCan View Cost-> Access:No\nCan Roster All Departments-> Access:No\nCan Roster Non-Recommended Employees-> Access:No\nCan Add Shift or Edit Shift Times-> Access:No\nApprove Time Sheets-> Access:No\nCan Approve Pay Conditions-> Access:No\nCan Approve for All Departments-> Access:No\nCan Approve for All Employee Roles-> Access:No\nCan Approve Outside the Current Period-> Access:No\nExport Time Sheets-> Access:No\nApprove Date Range of Leave Request-> Access:No\nApprove Leave Type for a Leave Request-> Access:No\nView Employee Details-> Access:No\nManage Employee Details-> Access:No\nManage Employee Pay Details-> Access:No\nManage Workplaces and Pay Centres-> Access:Yes Add/Edit:No\nManage Departments-> Access:Yes Add/Edit:No\nManage Employment Terms-> Access:No Add/Edit:No\nManage Training Requirements-> Access:No Add/Edit:No\nManage Events-> Access:No Add/Edit:No\nManage Employee Roles-> Access:No Add/Edit:No\nManage KPI Reports-> Access:No Add/Edit:No\nManage Procedures-> Access:No Add/Edit:No\nCan Select Employees and Departments from All Workplaces-> Access:No\nCan Manage Employees from All Roles-> Access:No\nGeneral Settings-> Access:No\nDeveloper-> Access:No\nSetup Kiosks-> Access:No\nPublic Holidays-> Access:No Add/Edit:No\nComment Categories-> Access:No Add/Edit:No\n-> Access:No",
    "Require2fa": false,
    "Creator": 1,
    "Created": "2009-11-30T17:37:03-05:00",
    "Modified": "2012-09-25T00:54:40-04:00"
  },
  "_DPMetaData": {
    "System": "Employee",
    "CreatorInfo": {
      "Id": 1,
      "DisplayName": "Test User",
      "EmployeeProfile": 1,
      "Employee": 1,
      "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=M+B&width=135&height=135",
      "Pronouns": 0,
      "CustomPronouns": null
    }
  }
}