import surecart from "../../surecart.app.mjs";

export default {
  key: "surecart-create-price",
  name: "Create Price",
  description: "Create a new price for a product. [See the documentation](https://developer.surecart.com/api-reference/prices/create)",
  version: "0.0.2",
  type: "action",
  annotations: {
    destructiveHint: false,
    openWorldHint: true,
    readOnlyHint: false,
  },
  props: {
    surecart,
    product: {
      propDefinition: [
        surecart,
        "productId",
      ],
    },
    name: {
      type: "string",
      label: "Name",
      description: "Display name for the price shown to customers. Example: `Monthly Plan`",
      optional: true,
    },
    amount: {
      type: "integer",
      label: "Amount",
      description: "Price in cents for fixed-price plans. Leave empty when **Ad Hoc** is `true` to allow custom amounts. Example: `9900` for $99.00",
      optional: true,
    },
    currency: {
      type: "string",
      label: "Currency",
      description: "Three-letter ISO 4217 currency code. Defaults to the account currency. Example: `usd`",
      optional: true,
    },
    adHoc: {
      type: "boolean",
      label: "Ad Hoc",
      description: "Set to `true` to allow customers to enter a custom amount instead of a fixed price.",
      optional: true,
    },
    adHocMinAmount: {
      type: "integer",
      label: "Ad Hoc Minimum Amount",
      description: "Minimum custom amount in cents when **Ad Hoc** is enabled. Example: `500` for $5.00",
      optional: true,
    },
    adHocMaxAmount: {
      type: "integer",
      label: "Ad Hoc Maximum Amount",
      description: "Maximum custom amount in cents when **Ad Hoc** is enabled. Example: `100000` for $1,000.00",
      optional: true,
    },
    scratchAmount: {
      type: "integer",
      label: "Scratch Amount",
      description: "Original pre-discount price in cents, shown as a strikethrough. Example: `19900` for $199.00",
      optional: true,
    },
    recurringInterval: {
      type: "string",
      label: "Recurring Interval",
      description: "Billing frequency for a subscription price.",
      optional: true,
      options: [
        "day",
        "week",
        "month",
        "year",
      ],
    },
    recurringIntervalCount: {
      type: "integer",
      label: "Recurring Interval Count",
      description: "Number of intervals between billings. Example: `3` with **Recurring Interval** `month` bills every 3 months.",
      optional: true,
    },
    recurringPeriodCount: {
      type: "integer",
      label: "Recurring Period Count",
      description: "Total number of billing periods before the subscription completes (installment plans). Example: `12` for a 12-month plan.",
      optional: true,
    },
    trialDurationDays: {
      type: "integer",
      label: "Trial Duration (Days)",
      description: "Number of free trial days before billing begins. Example: `14`",
      optional: true,
    },
    setupFeeEnabled: {
      type: "boolean",
      label: "Setup Fee Enabled",
      description: "Set to `true` to charge a one-time setup fee alongside the recurring price.",
      optional: true,
    },
    setupFeeAmount: {
      type: "integer",
      label: "Setup Fee Amount",
      description: "One-time setup fee in cents. Example: `2500` for $25.00",
      optional: true,
    },
    setupFeeName: {
      type: "string",
      label: "Setup Fee Name",
      description: "Display label for the setup fee. Example: `Onboarding Fee`",
      optional: true,
    },
    setupFeeTrialEnabled: {
      type: "boolean",
      label: "Setup Fee Trial Enabled",
      description: "Set to `true` to defer the setup fee until the trial period ends.",
      optional: true,
    },
    licenseActivationLimit: {
      type: "integer",
      label: "License Activation Limit",
      description: "Maximum number of license activations allowed. Defaults to the product setting if not set. Example: `5`",
      optional: true,
    },
    revokeAfterDays: {
      type: "integer",
      label: "Revoke After (Days)",
      description: "Number of days after which access is automatically revoked. Example: `365`",
      optional: true,
    },
    revokePurchasesOnCompleted: {
      type: "boolean",
      label: "Revoke Purchases On Completed",
      description: "Set to `true` to revoke access when an installment subscription completes.",
      optional: true,
    },
    restartSubscriptionOnCompleted: {
      type: "boolean",
      label: "Restart Subscription On Completed",
      description: "Set to `true` to automatically restart the subscription after an installment plan completes.",
      optional: true,
    },
    portalSubscriptionUpdateEnabled: {
      type: "boolean",
      label: "Portal Subscription Update Enabled",
      description: "Set to `false` to prevent customers from switching to this price in the customer portal.",
      optional: true,
    },
    renewalPrice: {
      type: "string",
      label: "Renewal Price ID",
      description: "UUID of the price to transition to upon renewal. Example: `price_abc123`",
      optional: true,
    },
    position: {
      type: "integer",
      label: "Position",
      description: "Display ordering position among prices. Example: `1`",
      optional: true,
    },
    archived: {
      type: "boolean",
      label: "Archived",
      description: "Set to `true` to create the price in an archived state.",
      optional: true,
    },
    metadata: {
      type: "object",
      label: "Metadata",
      description: "Additional key-value metadata. Example: `{ \"sku\": \"PLAN-001\" }`",
      optional: true,
    },
  },
  async run({ $ }) {
    const response = await this.surecart.createPrice({
      $,
      data: {
        price: {
          product: this.product,
          name: this.name,
          amount: this.amount,
          currency: this.currency,
          ad_hoc: this.adHoc,
          ad_hoc_min_amount: this.adHocMinAmount,
          ad_hoc_max_amount: this.adHocMaxAmount,
          scratch_amount: this.scratchAmount,
          recurring_interval: this.recurringInterval,
          recurring_interval_count: this.recurringIntervalCount,
          recurring_period_count: this.recurringPeriodCount,
          trial_duration_days: this.trialDurationDays,
          setup_fee_enabled: this.setupFeeEnabled,
          setup_fee_amount: this.setupFeeAmount,
          setup_fee_name: this.setupFeeName,
          setup_fee_trial_enabled: this.setupFeeTrialEnabled,
          license_activation_limit: this.licenseActivationLimit,
          revoke_after_days: this.revokeAfterDays,
          revoke_purchases_on_completed: this.revokePurchasesOnCompleted,
          restart_subscription_on_completed: this.restartSubscriptionOnCompleted,
          portal_subscription_update_enabled: this.portalSubscriptionUpdateEnabled,
          renewal_price: this.renewalPrice,
          position: this.position,
          archived: this.archived,
          metadata: this.metadata,
        },
      },
    });
    $.export("$summary", `Successfully created price ${response.id}`);
    return response;
  },
};
