<template><h1 id="network-ip-range" tabindex="-1"><a class="header-anchor" href="#network-ip-range" aria-hidden="true">#</a> Network / IP range</h1>
<p>By default, any network request (e.g. an HTTP request or a connection to a database) you make from Pipedream will originate from the <code>us-east-1</code> region of AWS. <a href="https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html" target="_blank" rel="noopener noreferrer">AWS publishes the IP address range<ExternalLinkIcon/></a> for all regions, but Pipedream shares this range with other services using AWS.</p>
<p>If you use a service that requires you whitelist a range of IP addresses, you have two options.</p>
<h2 id="http-requests" tabindex="-1"><a class="header-anchor" href="#http-requests" aria-hidden="true">#</a> HTTP requests</h2>
<p>If you need to send HTTP requests to a service from a fixed range of IP addresses, <a href="/workflows/steps/code/nodejs/http-requests/#ip-addresses-for-http-requests-made-from-pipedream-workflows" target="_blank" rel="noopener noreferrer">see these docs<ExternalLinkIcon/></a>.</p>
<h2 id="non-http-traffic-databases-etc" tabindex="-1"><a class="header-anchor" href="#non-http-traffic-databases-etc" aria-hidden="true">#</a> Non-HTTP traffic (databases, etc.)</h2>
<p>If you need to connect to a service from a fixed range of IP addresses, you can setup a <a href="https://medium.com/codex/how-to-setup-bastion-server-with-aws-ec2-b1590d2ff815" target="_blank" rel="noopener noreferrer">bastion server<ExternalLinkIcon/></a>. A bastion server only runs an SSH service (like <a href="https://www.openssh.com/" target="_blank" rel="noopener noreferrer">OpenSSH<ExternalLinkIcon/></a>) that listens for incoming SSH connections. You can connect to the bastion host from any IP address, but when you configure the firewall for your service (like your database), you open it up only to the IP address of your bastion server.</p>
<p>Then, in your Pipedream workflow, you can <a href="https://linuxize.com/post/how-to-setup-ssh-tunneling/#:~:text=SSH%20tunneling%20or%20SSH%20port,services%20ports%20can%20be%20relayed.&amp;text=%2D%20Forwards%20a%20connection%20from%20the,Remote%20Port%20Forwarding." target="_blank" rel="noopener noreferrer">tunnel the connection<ExternalLinkIcon/></a> to your service through the bastion host.</p>
<p>Here are two example workflows that show you how to connect to services through a bastion server:</p>
<ul>
<li><a href="https://pipedream.com/@dylburger/run-a-query-on-mysql-via-ssh-tunnel-p_rvCxrNB/edit" target="_blank" rel="noopener noreferrer">Run a MySQL query through an SSH tunnel<ExternalLinkIcon/></a></li>
<li><a href="https://pipedream.com/@dylburger/run-a-query-on-postgres-via-ssh-tunnel-p_13CvRz/edit" target="_blank" rel="noopener noreferrer">Run a PostgreSQL query through an SSH tunnel<ExternalLinkIcon/></a></li>
</ul>
<h2 id="feature-request-for-pipedream-restricting-its-ip-range" tabindex="-1"><a class="header-anchor" href="#feature-request-for-pipedream-restricting-its-ip-range" aria-hidden="true">#</a> Feature request for Pipedream restricting its IP range</h2>
<p>Pipedream plans to restrict the range of IP addresses for workflows in the future. Please <a href="https://github.com/PipedreamHQ/pipedream/issues/178" target="_blank" rel="noopener noreferrer">upvote this GitHub issue<ExternalLinkIcon/></a> to follow the status of that work.</p>
</template>
