<template><h1 id="server-sent-events-sse" tabindex="-1"><a class="header-anchor" href="#server-sent-events-sse" aria-hidden="true">#</a> Server-Sent Events (SSE)</h1>
<nav class="table-of-contents"><ul><li><RouterLink to="#overview">Overview</RouterLink></li><li><RouterLink to="#what-is-sse">What is SSE?</RouterLink></li><li><RouterLink to="#connecting-to-the-sse-stream-directly">Connecting to the SSE stream directly</RouterLink></li><li><RouterLink to="#subscribe-to-new-events-using-the-pipedream-cli">Subscribe to new events using the Pipedream CLI</RouterLink></li><li><RouterLink to="#sse-handshake-messages">:sse-handshake messages</RouterLink></li></ul></nav>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>As soon as you deploy an event source, Pipedream creates a private <a href="#what-is-sse">SSE stream</a> linked to that source. Each event emitted by the source is published to this SSE stream, so your app can subscribe to the stream to process new events.</p>
<h2 id="what-is-sse" tabindex="-1"><a class="header-anchor" href="#what-is-sse" aria-hidden="true">#</a> What is SSE?</h2>
<p><a href="https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events" target="_blank" rel="noopener noreferrer">Server-sent Events<ExternalLinkIcon/></a> (SSE) defines a spec for how servers can send events directly to clients that subscribe to those events, similar to <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" target="_blank" rel="noopener noreferrer">WebSockets<ExternalLinkIcon/></a> and related server-to-client push technologies.</p>
<p>Unlike WebSockets, SSE enables one-way communication from server to clients (WebSockets enable bidirectional communication between server and client, allowing you to pass messages back and forth). If you only need a client to subscribe to events from a server, and don't require bidirectional communication, SSE is simple way to make that happen.</p>
<h2 id="connecting-to-the-sse-stream-directly" tabindex="-1"><a class="header-anchor" href="#connecting-to-the-sse-stream-directly" aria-hidden="true">#</a> Connecting to the SSE stream directly</h2>
<p>To process events from your source's SSE stream, you'll need to:</p>
<ul>
<li>Get the SSE URL for your source's events using <a href="/cli/reference/#pd-list" target="_blank" rel="noopener noreferrer"><code>pd list streams</code><ExternalLinkIcon/></a>. You'll see your stream's URL under the <strong>SSE</strong> header.</li>
<li>Connect to the SSE stream, passing your Pipedream API key in the <code>Authorization</code> HTTP header using <a href="/api/auth/#authorizing-api-requests" target="_blank" rel="noopener noreferrer">Bearer Auth<ExternalLinkIcon/></a>.</li>
</ul>
<p><a href="https://github.com/PipedreamHQ/node-sse-example" target="_blank" rel="noopener noreferrer"><strong>See this repo</strong><ExternalLinkIcon/></a> for an example Node.js app that processes events from a Pipedream SSE stream.</p>
<p><a href="https://en.wikipedia.org/wiki/Server-sent_events#Libraries" target="_blank" rel="noopener noreferrer">Most programming languages provide SSE clients<ExternalLinkIcon/></a> that facilitate interaction with SSE streams. For example, the Node.js example repo uses the <a href="https://www.npmjs.com/package/eventsource" target="_blank" rel="noopener noreferrer"><code>eventsource</code> npm package<ExternalLinkIcon/></a>, which implements the <a href="https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events" target="_blank" rel="noopener noreferrer"><code>EventSource</code> API<ExternalLinkIcon/></a>.</p>
<h2 id="subscribe-to-new-events-using-the-pipedream-cli" tabindex="-1"><a class="header-anchor" href="#subscribe-to-new-events-using-the-pipedream-cli" aria-hidden="true">#</a> Subscribe to new events using the Pipedream CLI</h2>
<p>The <a href="/cli/reference/#pd-events" target="_blank" rel="noopener noreferrer"><code>pd events</code> command<ExternalLinkIcon/></a> connects to the SSE stream for a source and prints new events as they're emitted:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>pd events -f <span class="token operator">&lt;</span>source-id-or-name<span class="token operator">></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>This is the easiest way to interact with streams, especially if you only need to manually inspect events, or just want to save them to a file on disk.</p>
<h2 id="sse-handshake-messages" tabindex="-1"><a class="header-anchor" href="#sse-handshake-messages" aria-hidden="true">#</a> <code>:sse-handshake</code> messages</h2>
<p>Every 15 seconds, we'll send a message with the <code>:sse-handshake</code> comment to keep open SSE connections alive. These comments should be automatically ignored when you're listening for messages using the <a href="https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events" target="_blank" rel="noopener noreferrer"><code>EventSource</code> API<ExternalLinkIcon/></a>.</p>
<p>We send these because <a href="https://www.w3.org/TR/2009/WD-eventsource-20090421/#notes" target="_blank" rel="noopener noreferrer">the SSE spec<ExternalLinkIcon/></a> notes that</p>
<blockquote>
<p>Legacy proxy servers are known to, in certain cases, drop HTTP connections after a short timeout. To protect against such proxy servers, authors can include a comment line (one starting with a ':' character) every 15 seconds or so.</p>
</blockquote>
<Footer />
</template>
