<template><h1 id="twitter" tabindex="-1"><a class="header-anchor" href="#twitter" aria-hidden="true">#</a> Twitter</h1>
<p>Pipedream facilitates access to the Twitter API and Twitter events in two ways:</p>
<ul>
<li>Within <a href="/workflows" target="_blank" rel="noopener noreferrer">Pipedream workflows<ExternalLinkIcon/></a>, you can use <a href="/components/actions/" target="_blank" rel="noopener noreferrer">prebuilt actions<ExternalLinkIcon/></a> to post tweets, search tweets by keyword, and more. You can also run <a href="/workflows/steps/code/" target="_blank" rel="noopener noreferrer">any custom Node.js code<ExternalLinkIcon/></a> that interacts with the Twitter API.</li>
<li>You can also <em>trigger</em> Pipedream workflows on new tweets, new followers, and other Twitter events. This allows you to run custom code in response to these events.</li>
</ul>
<nav class="table-of-contents"><ul><li><RouterLink to="#using-the-twitter-api-in-pipedream-workflows">Using the Twitter API in Pipedream workflows</RouterLink><ul><li><RouterLink to="#pipedream-s-built-in-twitter-app-and-actions">Pipedream&#39;s built-in Twitter app and actions</RouterLink></li><li><RouterLink to="#run-your-own-custom-code-to-interact-with-the-twitter-api">Run your own custom code to interact with the Twitter API</RouterLink></li><li><RouterLink to="#limitations-on-mentions">Limitations on @ mentions</RouterLink></li><li><RouterLink to="#pipedream-inc-label-on-tweets">Pipedream, Inc label on tweets</RouterLink></li><li><RouterLink to="#twitter-developer-app-integration">Twitter Developer App integration</RouterLink></li></ul></li><li><RouterLink to="#run-code-on-new-tweets-followers-and-more">Run code on new tweets, followers, and more</RouterLink></li></ul></nav>
<h2 id="using-the-twitter-api-in-pipedream-workflows" tabindex="-1"><a class="header-anchor" href="#using-the-twitter-api-in-pipedream-workflows" aria-hidden="true">#</a> Using the Twitter API in Pipedream workflows</h2>
<h3 id="pipedream-s-built-in-twitter-app-and-actions" tabindex="-1"><a class="header-anchor" href="#pipedream-s-built-in-twitter-app-and-actions" aria-hidden="true">#</a> Pipedream's built-in Twitter app and actions</h3>
<p>Pipedream provides a <strong>Twitter</strong> OAuth app for interacting with the Twitter API. To use this app, <a href="/workflows/steps/" target="_blank" rel="noopener noreferrer">add a new step<ExternalLinkIcon/></a> to your workflow, search for &quot;Twitter&quot;, and select the Twitter app from the list. This will display a list of <a href="/components/actions/" target="_blank" rel="noopener noreferrer">prebuilt actions<ExternalLinkIcon/></a> (for example, <strong>Post Tweet</strong>, <strong>Search Twitter</strong>) associated with Twitter:</p>
<div>
<img alt="Twitter app / actions" width="600" src="@source/apps/twitter/images/twitter-app-actions.png">
</div>
<p>Select the <strong>Post Tweet</strong> action. Press <strong>Connect Account</strong> to authorize the Pipedream Twitter app access the Twitter API on your behalf. Then, add the text of your tweet in the <strong>Status</strong> field:</p>
<div>
<img alt="Twitter post tweet example" width="500" src="@source/apps/twitter/images/twitter-post-tweet.png">
</div>
<p>Like with all actions, you can set additional options using the <strong>add individual property</strong> menu, and you can view and edit the code for the action in the editor below this menu.</p>
<h3 id="run-your-own-custom-code-to-interact-with-the-twitter-api" tabindex="-1"><a class="header-anchor" href="#run-your-own-custom-code-to-interact-with-the-twitter-api" aria-hidden="true">#</a> Run your own custom code to interact with the Twitter API</h3>
<p>You can <a href="/connected-accounts/#from-a-code-step" target="_blank" rel="noopener noreferrer">connect the Twitter app to any code step<ExternalLinkIcon/></a>, which allows you to use your Twitter account to interact with the API in a custom way that the built-in actions don't provide.</p>
<h3 id="limitations-on-mentions" tabindex="-1"><a class="header-anchor" href="#limitations-on-mentions" aria-hidden="true">#</a> Limitations on <code>@</code> mentions</h3>
<p>Twitter's <a href="https://help.twitter.com/en/rules-and-policies/twitter-automation" target="_blank" rel="noopener noreferrer">Automation Rules<ExternalLinkIcon/></a> forbids replies or mentions in certain circumstances. For example, you cannot <code>@</code> mention users in an unsolicited way. Because of these limitations, <strong>Pipedream prevents the use of <code>@</code> mentions when posting tweets</strong>.</p>
<p>If you attempt to post tweets with <code>@</code> mentions using the <strong>Post Tweet</strong> action, the action will remove the <code>@</code> and post the remaining text of the tweet.</p>
<p>If you write custom code that attempts to post a tweet with an <code>@</code> mention, you'll encounter a <code>400 Bad Request</code> error. You must remove the <code>@</code> mention to post your tweet successfully.</p>
<p>This limitation only applies to Pipedream's <strong>Twitter</strong> app. You can use the <a href="#twitter-developer-app-integration"><strong>Twitter Developer App</strong> integration</a> to interact with the Twitter API using credentials for a Twitter bot you've created in your own developer account, and use <code>@</code> mentions. When you use this integration, <a href="https://help.twitter.com/en/rules-and-policies/twitter-automation" target="_blank" rel="noopener noreferrer">Twitter's Automation Rules<ExternalLinkIcon/></a> still govern your bot's use of the Twitter API.</p>
<h3 id="pipedream-inc-label-on-tweets" tabindex="-1"><a class="header-anchor" href="#pipedream-inc-label-on-tweets" aria-hidden="true">#</a> Pipedream, Inc label on tweets</h3>
<p>When you use the Pipedream Twitter app to send tweets, you'll notice a <strong>Pipedream, Inc</strong> label on these tweets:</p>
<div>
<img alt="Twitter Pipedream label" width="500px" src="@source/apps/twitter/images/twitter-pipedream-label.png">
</div>
<p>Twitter displays the name of the source app that produced the tweet, and cannot be removed when using the Pipedream app. You can use the <a href="#twitter-developer-app-integration"><strong>Twitter Developer App</strong> integration</a> to post tweets using your own app.</p>
<h3 id="twitter-developer-app-integration" tabindex="-1"><a class="header-anchor" href="#twitter-developer-app-integration" aria-hidden="true">#</a> Twitter Developer App integration</h3>
<p>If you operate your own Twitter bot, and you want to interact with the Twitter API using that bot's credentials, you can use the <strong>Twitter Developer App</strong> integration.</p>
<p>To use this app, <a href="/workflows/steps/" target="_blank" rel="noopener noreferrer">add a new step<ExternalLinkIcon/></a> to your workflow, search for &quot;Twitter Developer App&quot;, and select that app from the list. When you select an action and press <strong>Connect Account</strong>, you'll be prompted to enter the API Key, API Secret, Access Token, and Access Token Secret tied to your app in the <a href="https://developer.twitter.com/en/docs/basics/apps/guides/the-app-management-dashboard" target="_blank" rel="noopener noreferrer">Twitter Developer Dashboard<ExternalLinkIcon/></a>.</p>
<p>Once connected, you can run any custom code that uses these credentials to interact with the Twitter API. The <strong>Post Tweet</strong> action associated with this app, for example, uses the <a href="https://github.com/ttezel/twit" target="_blank" rel="noopener noreferrer"><code>twit</code> Twitter API client<ExternalLinkIcon/></a> to send tweets:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> Twit <span class="token keyword">from</span> <span class="token string">"twit"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token punctuation">{</span>
  api_key<span class="token punctuation">,</span>
  api_secret_key<span class="token punctuation">,</span>
  access_token<span class="token punctuation">,</span>
  access_token_secret<span class="token punctuation">,</span>
<span class="token punctuation">}</span> <span class="token operator">=</span> auths<span class="token punctuation">.</span>twitter_developer_app<span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token constant">T</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Twit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">consumer_key</span><span class="token operator">:</span> api_key<span class="token punctuation">,</span>
  <span class="token literal-property property">consumer_secret</span><span class="token operator">:</span> api_secret_key<span class="token punctuation">,</span>
  access_token<span class="token punctuation">,</span>
  access_token_secret<span class="token punctuation">,</span>
  <span class="token literal-property property">timeout_ms</span><span class="token operator">:</span> <span class="token number">60</span> <span class="token operator">*</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token comment">// optional HTTP request timeout to apply to all requests.</span>
  <span class="token literal-property property">strictSSL</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">// optional - requires SSL certificates to be valid.</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">return</span> <span class="token keyword">await</span> <span class="token constant">T</span><span class="token punctuation">.</span><span class="token function">post</span><span class="token punctuation">(</span><span class="token string">"statuses/update"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">status</span><span class="token operator">:</span> params<span class="token punctuation">.</span>status<span class="token punctuation">,</span>
  <span class="token literal-property property">in_reply_to_status_id</span><span class="token operator">:</span> params<span class="token punctuation">.</span>in_reply_to_status_id<span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div><h2 id="run-code-on-new-tweets-followers-and-more" tabindex="-1"><a class="header-anchor" href="#run-code-on-new-tweets-followers-and-more" aria-hidden="true">#</a> Run code on new tweets, followers, and more</h2>
<p>Pipedream <a href="/event-sources" target="_blank" rel="noopener noreferrer">event sources<ExternalLinkIcon/></a> emit Twitter events — tweets, follows, likes, and more — in real time. Sources can trigger <a href="/workflows" target="_blank" rel="noopener noreferrer">Pipedream workflows<ExternalLinkIcon/></a>, and can be accessed via <a href="/api/sse/" target="_blank" rel="noopener noreferrer">SSE<ExternalLinkIcon/></a> and <a href="/api/rest/" target="_blank" rel="noopener noreferrer">REST APIs<ExternalLinkIcon/></a>.</p>
<p>Create a new Twitter event source at <a href="https://pipedream.com/sources" target="_blank" rel="noopener noreferrer">https://pipedream.com/sources<ExternalLinkIcon/></a>, or by clicking on any of the links below:</p>
<ul>
<li><a href="https://pipedream.com/sources?action=create&amp;key=twitter-search-mentions&amp;app=twitter" target="_blank" rel="noopener noreferrer">Search mentions for a keyword, user, hashtag, and more<ExternalLinkIcon/></a></li>
</ul>
<p>When you create a Pipedream workflow, you can also <a href="/workflows/steps/triggers/#app-based-triggers" target="_blank" rel="noopener noreferrer">create an event source in the trigger step<ExternalLinkIcon/></a> directly.</p>
<p>A single event source can trigger any number of Pipedream workflows. For example, you might create a single source to listen for new Twitter mentions for a keyword, then trigger multiple workflows each time a new tweet is found: one to <a href="https://pipedream.com/@pravin/twitter-mentions-slack-p_dDCA5e/edit" target="_blank" rel="noopener noreferrer">send new tweets to Slack<ExternalLinkIcon/></a>, another to <a href="https://pipedream.com/@dylan/twitter-to-s3-p_KwCZGA/readme" target="_blank" rel="noopener noreferrer">save those tweets to an Amazon S3 bucket<ExternalLinkIcon/></a>, etc.</p>
</template>
