export default {
  SEARCH_FILE_FOLDERS: {
    DEFAULT_MAX_RESULTS: 1000,
  },
  LIST_FILES_IN_FOLDER: {
    DEFAULT_MAX_RESULTS: 100,
  },
  GET_PATH_OPTIONS: {
    DEFAULT_MAX_RESULTS: 1000,
  },
};
