const METRIC = {
  AD_IMPRESSIONS: "adImpressions",
  ANNOTATION_CLICKABLE_IMPRESSIONS: "annotationClickableImpressions",
  ANNOTATION_CLICKS: "annotationClicks",
  ANNOTATION_CLICK_THROUGH_RATE: "annotationClickThroughRate",
  ANNOTATION_CLOSABLE_IMPRESSIONS: "annotationClosableImpressions",
  ANNOTATION_CLOSES: "annotationCloses",
  ANNOTATION_CLOSE_RATE: "annotationCloseRate",
  ANNOTATION_IMPRESSIONS: "annotationImpressions",
  AUDIENCE_WATCH_RATIO: "audienceWatchRatio",
  AVERAGE_VIEW_DURATION: "averageViewDuration",
  AVERAGE_VIEW_PERCENTAGE: "averageViewPercentage",
  CARD_CLICK_RATE: "cardClickRate",
  CARD_CLICKS: "cardClicks",
  CARD_IMPRESSIONS: "cardImpressions",
  CARD_TEASER_CLICK_RATE: "cardTeaserClickRate",
  CARD_TEASER_CLICKS: "cardTeaserClicks",
  CARD_TEASER_IMPRESSIONS: "cardTeaserImpressions",
  COMMENTS: "comments",
  CPM: "cpm",
  DISLIKES: "dislikes",
  ESTIMATED_AD_REVENUE: "estimatedAdRevenue",
  ESTIMATED_MINUTES_WATCHED: "estimatedMinutesWatched",
  ESTIMATED_REVENUE: "estimatedRevenue",
  GROSS_REVENUE: "grossRevenue",
  LIKES: "likes",
  MONETIZED_PLAYBACKS: "monetizedPlaybacks",
  PLAYBACK_BASED_CPM: "playbackBasedCpm",
  PLAYLIST_STARTS: "playlistStarts",
  SAVES_ADDED: "savesAdded",
  SAVES_REMOVED: "savesRemoved",
  SHARES: "shares",
  SUBSCRIBERS_GAINED: "subscribersGained",
  SUBSCRIBERS_LOST: "subscribersLost",
  VIDEOS_ADDED_TO_PLAYLISTS: "videosAddedToPlaylists",
  VIDEOS_REMOVED_FROM_PLAYLISTS: "videosRemovedFromPlaylists",
  VIEWER_PERCENTAGE: "viewerPercentage",
  VIEWS: "views",
};

const DIMENSION = {
  AD_TYPE: "adType",
  AGE_GROUP: "ageGroup",
  ASSET: "asset",
  AUDIENCE_TYPE: "audienceType",
  CHANNEL: "channel",
  CLAIMED_STATUS: "claimedStatus",
  CONTENT_OWNER: "contentOwner",
  COUNTRY: "country",
  DAY: "day",
  DEVICE_TYPE: "deviceType",
  ELAPSED_VIDEO_TIME_RATIO: "elapsedVideoTimeRatio",
  GENDER: "gender",
  INSIGHT_PLAYBACK_LOCATION_DETAIL: "insightPlaybackLocationDetail",
  INSIGHT_PLAYBACK_LOCATION_TYPE: "insightPlaybackLocationType",
  INSIGHT_TRAFFIC_SOURCE_DETAIL: "insightTrafficSourceDetail",
  INSIGHT_TRAFFIC_SOURCE_TYPE: "insightTrafficSourceType",
  LIVE_OR_ON_DEMAND: "liveOrOnDemand",
  OPERATING_SYSTEM: "operatingSystem",
  PLAYLIST: "playlist",
  PROVINCE: "province",
  SHARING_SERVICE: "sharingService",
  SUBSCRIBED_STATUS: "subscribedStatus",
  SUBTITLE_LANGUAGE: "subtitleLanguage",
  UPLOADER_TYPE: "uploaderType",
  VIDEO: "video",
};

const ID_TYPE = {
  CHANNEL: {
    label: "My Channel",
    value: "MINE",
  },
  CHANNEL_ID: {
    label: "Channel ID",
    value: "channelId",
  },
  CONTENT_OWNER: {
    label: "Content Owner",
    value: "contentOwner",
  },
};

const CHANNEL_REPORT_TYPE = {
  VIDEO_BASIC_USER_ACTIVITY_STATS: {
    label: "Basic User Activity Statistics For Video",
    value: "basicUserActivityStatsForVideo",
    metadata: {
      metrics: [
        "views",
        "redViews",
        "comments",
        "likes",
        "dislikes",
        "videosAddedToPlaylists",
        "videosRemovedFromPlaylists",
        "shares",
        "estimatedMinutesWatched",
        "estimatedRedMinutesWatched",
        "averageViewDuration",
        "averageViewPercentage",
        "annotationClickThroughRate",
        "annotationCloseRate",
        "annotationImpressions",
        "annotationClickableImpressions",
        "annotationClosableImpressions",
        "annotationClicks",
        "annotationCloses",
        "cardClickRate",
        "cardTeaserClickRate",
        "cardImpressions",
        "cardTeaserImpressions",
        "cardClicks",
        "cardTeaserClicks",
        "subscribersGained",
        "subscribersLost",
        "estimatedRevenue*",
        "estimatedAdRevenue*",
        "grossRevenue*",
        "estimatedRedPartnerRevenue*",
        "monetizedPlaybacks*",
        "playbackBasedCpm*",
        "adImpressions*",
        "cpm*",
      ],
      filters: [
        "country",
        "continent",
        "subContinent",
        "video",
        "group",
      ],
    },
  },
  PLAYLIST_BASIC_STATS: {
    label: "Basic Statistics For Playlist",
    value: "basicStatsForPlaylist",
    metadata: {
      metrics: [
        "views",
        "estimatedMinutesWatched",
        "averageViewDuration",
        "averageTimeInPlaylist",
        "playlistAverageViewDuration",
        "playlistEstimatedMinutesWatched",
        "playlistSaves",
        "playlistStarts",
        "playlistViews",
        "viewsPerPlaylistStart",
      ],
      filters: [
        "playlist",
        "group",
      ],
    },
  },
};

export default {
  METRIC,
  DIMENSION,
  ID_TYPE,
  CHANNEL_REPORT_TYPE,
};
