/**
 * Return schema for Get Products flow
 * Contains product fields returned by the export (excluded optional fields are
 * listed in the upstream schema: see URL below).
 */
export const productReturnSchema = {
  Product: [
    {
      ProdID: true,
      ProdCode: true,
      IntDesc: true,
      SellDesc: true,
      PriMfg: true,
      DfltAltPart: true,
      RoHSCompOpt: true,
      RoHSCompOptDesc: true,
      FCHSyncOpt: true,
      FCHSyncOptDesc: true,
      TaxTypeOpt: true,
      TaxTypeOptDesc: true,
      OverShipOpt: true,
      OverShipOptDesc: true,
      TrackExpOpt: true,
      TrackExpOptDesc: true,
      ReplTypeOpt: true,
      ReplTypeOptDesc: true,
      TrkMfgLotHeatOpt: true,
      TrkMfgLotHeatOptDesc: true,
      TrkCoOOpt: true,
      TrkCoOOptDesc: true,
      InspReqOpt: true,
      InspReqOptDesc: true,
      StockUOMID: true,
      PurchUOMID: true,
      SellUOMID: true,
      EDIPkgTypeCode: true,
      EDIPkgTypeDesc: true,
      EDIPkgTypeID: true,
      EDIPkgTypeInfo: true,
      TariffCode: true,
      TariffDesc: true,
      TariffID: true,
      TariffInfo: true,
      FrtClassCode: true,
      FrtClassDesc: true,
      FrtClassID: true,
      FrtClassInfo: true,
      BuyerCode: true,
      BuyerDesc: true,
      BuyerID: true,
      BuyerInfo: true,
      SamplePlanCode: true,
      SamplePlanDesc: true,
      SamplePlanID: true,
      SamplePlanInfo: true,
      PriceTblCode: true,
      PriceTblDesc: true,
      PriceTblID: true,
      PriceTblInfo: true,
      ProdCatCode: true,
      ProdCatDesc: true,
      ProdCatID: true,
      ProdCatInfo: true,
      FindTxt: true,
      IntAlert: true,
      UPCCode: true,
      PriceNote: true,
      OnHandValue: true,
      OnHandValueDec: true,
      OnHandValueString: true,
      TheoWght: true,
      TheoWghtDec: true,
      TheoWghtString: true,
      Volume: true,
      VolumeDec: true,
      VolumeString: true,
      More: {
        EntityAvail: {
          SaleAvail: true,
          SaleAvailDec: true,
          SaleAvailString: true,
        },
      },
    },
  ],
};

// Full product args/schema:
// https://hangerbolttest.ci-inc.com/masterfiles/productV3/args.json?MimicReq=true&InclSchema=true
