/**
 * Return schema for Get Products flow
 * Contains all product fields that are not child objects
 */
export const productReturnSchema = {
  Product: [
    {
      ProdID: true,
      ProdCode: true,
      IntDesc: true,
      SellDesc: true,
      PriMfg: true,
      DfltAltPart: true,
      RoHSCompOpt: true,
      RoHSCompOptDesc: true,
      FCHSyncOpt: true,
      FCHSyncOptDesc: true,
      TaxTypeOpt: true,
      TaxTypeOptDesc: true,
      OverShipOpt: true,
      OverShipOptDesc: true,
      TrackExpOpt: true,
      TrackExpOptDesc: true,
      ReplTypeOpt: true,
      ReplTypeOptDesc: true,
      // I removed these because I don't think the client is currently using these, eventually this entire schema file may be replaced
      // SyncVMIOpt: true,
      // SyncVMIOptDesc: true,
      TrkMfgLotHeatOpt: true,
      TrkMfgLotHeatOptDesc: true,
      TrkCoOOpt: true,
      TrkCoOOptDesc: true,
      InspReqOpt: true,
      InspReqOptDesc: true,
      // I removed these because I don't think the client is currently using these, eventually this entire schema file may be replaced
      // ClassID: true,
      // ClassCode: true,
      // ClassDesc: true,
      // ClassInfo: true,
      // ClassDescDisp: true,
      // GLAssetID: true,
      // GLAssetCode: true,
      // GLAssetDesc: true,
      // GLAssetInfo: true,
      // GLAssetDescDisp: true,
      // GLCOGSID: true,
      // GLCOGSCode: true,
      // GLCOGSDesc: true,
      // GLCOGSInfo: true,
      // GLCOGSDescDisp: true,
      // GLRevenueID: true,
      // GLRevenueCode: true,
      // GLRevenueDesc: true,
      // GLRevenueInfo: true,
      // GLRevenueDescDisp: true,
      // GLReturnID: true,
      // GLReturnCode: true,
      // GLReturnDesc: true,
      // GLReturnInfo: true,
      // GLReturnDescDisp: true,
      StockUOMID: true,
      PurchUOMID: true,
      SellUOMID: true,
      EDIPkgTypeCode: true,
      EDIPkgTypeDesc: true,
      EDIPkgTypeID: true,
      EDIPkgTypeInfo: true,
      TariffCode: true,
      TariffDesc: true,
      TariffID: true,
      TariffInfo: true,
      FrtClassCode: true,
      FrtClassDesc: true,
      FrtClassID: true,
      FrtClassInfo: true,
      BuyerCode: true,
      BuyerDesc: true,
      BuyerID: true,
      BuyerInfo: true,
      SamplePlanCode: true,
      SamplePlanDesc: true,
      SamplePlanID: true,
      SamplePlanInfo: true,
      PriceTblCode: true,
      PriceTblDesc: true,
      PriceTblID: true,
      PriceTblInfo: true,
      ProdCatCode: true,
      ProdCatDesc: true,
      ProdCatID: true,
      ProdCatInfo: true,
      FindTxt: true,
      IntAlert: true,
      UPCCode: true,
      PriceNote: true,
      OnHandValue: true,
      OnHandValueDec: true,
      OnHandValueString: true,
      TheoWght: true,
      TheoWghtDec: true,
      TheoWghtString: true,
      // I removed these because I don't think the client is currently using these, eventually this entire schema file may be replaced
      // Create: true,
      // CreateUser: true,
      // CreateUserFull: true,
      // CreateDate: true,
      // CreateTime: true,
      // CreateTimeString: true,
      // CreateEpoch: true,
      // CreateFormatted: true,
      Volume: true,
      VolumeDec: true,
      VolumeString: true,
      More: {
        EntityAvail: {
          SaleAvail: true,
          SaleAvailDec: true,
          SaleAvailString: true
        }
      }
    },
  ],
};

// The full product args and schema can be found here: https://hangerbolttest.ci-inc.com/masterfiles/productV3/args.json?MimicReq=true&InclSchema=true