// Docs: https://developers.quaderno.io/guides/webhooks/#events
export default {
  ACCOUNT_UPDATED: "account.updated",
  ACCOUNT_APPLICATION_DEAUTHORIZED: "account.application.deauthorized",
  CHECKOUT_SUCCEEDED: "checkout.succeeded",
  CHECKOUT_FAILED: "checkout.failed",
  CHECKOUT_ABANDONED: "checkout.abandoned",
  CONTACT_CREATED: "contact.created",
  CONTACT_UPDATED: "contact.updated",
  CONTACT_DELETED: "contact.deleted",
  CREDIT_CREATED: "credit.created",
  CREDIT_UPDATED: "credit.updated",
  EXPENSE_CREATED: "expense.created",
  EXPENSE_UPDATED: "expense.updated",
  EXPENSE_DELETED: "expense.deleted",
  INVOICE_CREATED: "invoice.created",
  INVOICE_UPDATED: "invoice.updated",
  PAYMENT_CREATED: "payment.created",
  PAYMENT_DELETED: "payment.deleted",
  REPORTING_REQUEST_SUCCEDED: "reporting.request.suceeded",
  REPORTING_REQUEST_FAILED: "reporting.request.failed",
  THRESHOLD_WARNING: "threshold.warning",
  THRESHOLD_EXCEEDED: "threshold.exceeded",
  THRESHOLD_EU_100K: "threshold.eu.100k",
};
