export default {
  "_id": "5ac599d1a488620e6cd01d87",
  "eventId": "5ac598ccd8fe7c0c0f212e2a",
  "userId": "nEOqx8s9UueyRu48789C0sY9set1",
  "currency": "AUD",
  "eventDateId": "5ac598ccd8fe7c0c0f212e2f",
  "status": "complete",
  "financialStatus": "free",
  "firstName": "Bilbo",
  "lastName": "Baggins",
  "organisation": "ABC School",
  "mobile": "0412345678",
  "email": "bilbo.baggins@middleearth.com",
  "accessCode": "EARLYACCESS",
  "discounts": {
    "autoDiscount": {
      "discountAmount": 20
    },
    "discountCode": {
      "code": "FIFTYOFF",
      "discountAmount": 20
    }
  },
  "businessPurpose": true,
  "businessTaxId": "12345678901",
  "businessName": "ABC School",
  "paymentType": "cash",
  "paymentGateway": "manual",
  "manualOrder": true,
  "tipFees": true,
  "clientDonation": 5,
  "notes": "Example note",
  "organiserMailListOptIn": true,
  "incompleteAt": "2021-02-01T23:26:13.485Z",
  "completedAt": "2021-02-01T23:26:13.485Z",
  "waitlistOfferId": "5d0ae7ef9d3e67012780u70d",
  "isInternationalTransaction": true,
  "totals": {
    "subtotal": 50,
    "amexFee": 0,
    "zipFee": 0,
    "humanitixFee": 3.98,
    "bookingFee": 3.98,
    "passedOnFee": 0,
    "clientDonation": 0,
    "netClientDonation": 0,
    "donation": 1.19,
    "dgrDonation": 0,
    "giftCardCredit": 0,
    "credit": 0,
    "outstandingAmount": 0,
    "feesIncluded": true,
    "bookingTaxes": 0.36,
    "passedOnTaxes": 0,
    "taxes": 0,
    "totalTaxes": 0.36,
    "discounts": 0,
    "refunds": 0,
    "netSales": 50,
    "grossSales": 53.98,
    "referralAmount": 0,
    "total": 53.98
  },
  "purchaseTotals": {
    "subtotal": 50,
    "amexFee": 0,
    "zipFee": 0,
    "humanitixFee": 3.98,
    "bookingFee": 3.98,
    "passedOnFee": 0,
    "clientDonation": 0,
    "netClientDonation": 0,
    "donation": 1.19,
    "dgrDonation": 0,
    "giftCardCredit": 0,
    "credit": 0,
    "outstandingAmount": 0,
    "feesIncluded": true,
    "bookingTaxes": 0.36,
    "passedOnTaxes": 0,
    "taxes": 0,
    "totalTaxes": 0.36,
    "discounts": 0,
    "refunds": 0,
    "netSales": 50,
    "grossSales": 53.98,
    "referralAmount": 0,
    "total": 53.98
  },
  "additionalFields": [
    {
      "questionId": "5ac5c5e85aec29000ff064f4",
      "value": "Gluten Free",
      "details": {
        "street": "501 Buckland Road",
        "suburb": "Hinuera",
        "postalCode": "3472",
        "city": "Matamata",
        "state": "Waikato",
        "country": "New Zealand"
      }
    }
  ],
  "salesChannel": "online",
  "location": "AU",
  "createdAt": "2021-02-01T23:26:13.485Z",
  "updatedAt": "2021-02-01T23:26:13.485Z"
}
