export default {
  "order":{
     "id":123,
     "createdAt":"2025-09-17T19:12:38+00:00",
     "updatedAt":"2025-09-17T19:20:56+00:00",
     "number":"ORD00002",
     "status":"completed_shipped",
     "customStatusId":null,
     "channel":"",
     "remoteIp":"35.245.159.47",
     "userAgent":"WebshopappApi",
     "referralId":false,
     "priceCost":0,
     "priceExcl":0,
     "priceIncl":0,
     "weight":0,
     "volume":0,
     "colli":0,
     "gender":"male",
     "birthDate":"2006-09-19",
     "nationalId":"",
     "email":"customer@email.com",
     "firstname":"John",
     "middlename":"",
     "lastname":"Doe",
     "phone":"+1 111111111",
     "mobile":"11111111111",
     "newsletterSubscribed":false,
     "isCompany":false,
     "companyName":"",
     "companyCoCNumber":"",
     "companyVatNumber":"",
     "addressBillingName":"John Doe",
     "addressBillingStreet":"",
     "addressBillingStreet2":"",
     "addressBillingNumber":"",
     "addressBillingExtension":"",
     "addressBillingZipcode":"",
     "addressBillingCity":"",
     "addressBillingRegion":"",
     "addressBillingCountry":{
        "id":226,
        "code":"us",
        "code3":"usa",
        "title":"United States"
     },
     "addressBillingRegionData":{
        "id":4204,
        "name":"",
        "code":"CA"
     },
     "addressShippingCompany":false,
     "addressShippingName":"John Doe",
     "addressShippingStreet":"",
     "addressShippingStreet2":"",
     "addressShippingNumber":"",
     "addressShippingExtension":"",
     "addressShippingZipcode":"",
     "addressShippingCity":"",
     "addressShippingRegion":"",
     "addressShippingCountry":{
        "id":226,
        "code":"us",
        "code3":"usa",
        "title":"United States"
     },
     "addressShippingRegionData":{
        "id":4204,
        "name":"",
        "code":"CA"
     },
     "paymentId":"external",
     "paymentStatus":"paid",
     "paymentIsPost":false,
     "paymentIsInvoiceExternal":false,
     "paymentTaxRate":0,
     "paymentTaxRates":[
        {
           "name":"VAT",
           "rate":0,
           "amount":0
        }
     ],
     "paymentBasePriceExcl":0,
     "paymentBasePriceIncl":0,
     "paymentPriceExcl":0,
     "paymentPriceIncl":0,
     "paymentTitle":"Customer choice",
     "paymentData":{
        "user_id":null
     },
     "shipmentId":"core|85518|424529",
     "shipmentStatus":"not_shipped",
     "shipmentIsCashOnDelivery":false,
     "shipmentIsPickup":false,
     "shipmentTaxRate":0,
     "shipmentTaxRates":[
        {
           "name":"VAT",
           "rate":0,
           "amount":0
        }
     ],
     "shipmentBasePriceExcl":0,
     "shipmentBasePriceIncl":0,
     "shipmentPriceExcl":0,
     "shipmentPriceIncl":0,
     "shipmentDiscountExcl":0,
     "shipmentDiscountIncl":0,
     "shipmentTitle":"Shipment Title",
     "shipmentData":{
        "method":"default",
        "shipment_id":85518,
        "shipping_value_id":424529
     },
     "shippingDate":null,
     "deliveryDate":null,
     "isDiscounted":false,
     "discountType":"amount",
     "discountAmount":0,
     "discountPercentage":0,
     "discountCouponCode":"",
     "taxRates":[
        {
           "name":"VAT",
           "rate":0,
           "amount":0
        }
     ],
     "isNewCustomer":false,
     "comment":"",
     "memo":"",
     "allowNotifications":false,
     "doNotifyNew":true,
     "doNotifyReminder":false,
     "doNotifyCancelled":false,
     "language":{
        "id":3,
        "code":"en",
        "locale":"en_GB",
        "title":"English"
     },
     "customer":{
        "resource":{
           "id":13353882,
           "url":"customers\/123",
           "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123.json",
           "embedded":{
              "id":13353882,
              "createdAt":"2025-09-16T20:17:55+00:00",
              "updatedAt":"2025-09-17T19:12:38+00:00",
              "isConfirmed":false,
              "type":"registered",
              "lastOnlineAt":"2025-09-17T19:12:38+00:00",
              "remoteIp":"35.245.159.47",
              "userAgent":"WebshopappApi",
              "referralId":false,
              "gender":"male",
              "birthDate":"2006-09-19",
              "nationalId":"",
              "email":"customer@email.com",
              "firstname":"John",
              "middlename":"",
              "lastname":"Doe",
              "phone":"+1 111111111",
              "mobile":"11111111111",
              "isCompany":false,
              "companyName":"",
              "companyCoCNumber":"",
              "companyVatNumber":"",
              "addressBillingName":"John Doe",
              "addressBillingStreet":"",
              "addressBillingStreet2":"",
              "addressBillingNumber":"",
              "addressBillingExtension":"",
              "addressBillingZipcode":"",
              "addressBillingCity":"",
              "addressBillingRegion":"",
              "addressBillingCountry":{
                 "id":226,
                 "code":"us",
                 "code3":"usa",
                 "title":"United States"
              },
              "addressShippingCompany":false,
              "addressShippingName":"John Doe",
              "addressShippingStreet":"",
              "addressShippingStreet2":"",
              "addressShippingNumber":"",
              "addressShippingExtension":"",
              "addressShippingZipcode":"",
              "addressShippingCity":"",
              "addressShippingRegion":"",
              "addressShippingCountry":{
                 "id":226,
                 "code":"us",
                 "code3":"usa",
                 "title":"United States"
              },
              "memo":null,
              "doNotifyRegistered":false,
              "doNotifyConfirmed":false,
              "doNotifyPassword":false,
              "groups":{
                 "resource":{
                    "id":false,
                    "url":"groups\/customers?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/groups\/customers.json?customer=123"
                 }
              },
              "invoices":{
                 "resource":{
                    "id":false,
                    "url":"invoices?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/invoices.json?customer=123"
                 }
              },
              "language":{
                 "id":3,
                 "code":"en",
                 "locale":"en_GB",
                 "title":"English"
              },
              "orders":{
                 "resource":{
                    "id":false,
                    "url":"orders?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/orders.json?customer=123"
                 }
              },
              "reviews":{
                 "resource":{
                    "id":false,
                    "url":"reviews?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/reviews.json?customer=123"
                 }
              },
              "shipments":{
                 "resource":{
                    "id":false,
                    "url":"shipments?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/shipments.json?customer=123"
                 }
              },
              "tickets":{
                 "resource":{
                    "id":false,
                    "url":"tickets?customer=123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/tickets.json?customer=123"
                 }
              },
              "metafields":{
                 "resource":{
                    "id":false,
                    "url":"customers\/123\/metafields",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123\/metafields.json"
                 }
              },
              "login":{
                 "resource":{
                    "id":false,
                    "url":"customers\/123\/login",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123\/login.json"
                 }
              }
           }
        }
     },
     "invoices":{
        "resource":{
           "id":false,
           "url":"invoices?order=123",
           "link":"http:\/\/api.shoplightspeed.com\/en\/invoices.json?order=123",
           "embedded":[
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "updatedAt":"2025-09-17T19:12:38+00:00",
                 "number":"INV00002",
                 "status":"paid",
                 "isVatShifted":true,
                 "priceExcl":0,
                 "priceIncl":0,
                 "doNotifyNew":false,
                 "doNotifyPaid":false,
                 "invoice":false,
                 "isCreditNote":false,
                 "creditNote":false,
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "customer":{
                    "resource":{
                       "id":123,
                       "url":"customers\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123.json"
                    }
                 },
                 "items":{
                    "resource":{
                       "id":false,
                       "url":"invoices\/123\/items",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123\/items.json"
                    }
                 },
                 "metafields":{
                    "resource":{
                       "id":false,
                       "url":"invoices\/123\/metafields",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123\/metafields.json"
                    }
                 },
                 "events":{
                    "resource":{
                       "id":false,
                       "url":"orders\/events?invoice=123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/events.json?invoice=123"
                    }
                 }
              }
           ]
        }
     },
     "shipments":{
        "resource":{
           "id":false,
           "url":"shipments?order=123",
           "link":"http:\/\/api.shoplightspeed.com\/en\/shipments.json?order=123",
           "embedded":[
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "updatedAt":"2025-09-17T19:12:38+00:00",
                 "number":"SHIP00002",
                 "status":"not_shipped",
                 "trackingCode":"",
                 "doNotifyShipped":false,
                 "doNotifyReadyForPickup":false,
                 "doNotifyTrackingCode":false,
                 "customer":{
                    "resource":{
                       "id":123,
                       "url":"customers\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123.json"
                    }
                 },
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "products":{
                    "resource":{
                       "id":false,
                       "url":"shipments\/123\/products",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/shipments\/123\/products.json"
                    }
                 },
                 "metafields":{
                    "resource":{
                       "id":false,
                       "url":"shipments\/123\/metafields",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/shipments\/123\/metafields.json"
                    }
                 },
                 "events":{
                    "resource":{
                       "id":false,
                       "url":"orders\/events?shipment=123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/events.json?shipment=123"
                    }
                 }
              }
           ]
        }
     },
     "products":{
        "resource":{
           "id":false,
           "url":"orders\/123\/products",
           "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123\/products.json",
           "embedded":[
              {
                 "id":123,
                 "supplierTitle":"",
                 "brandTitle":"Brand Title",
                 "productTitle":"Product Title",
                 "variantTitle":"",
                 "taxRate":0,
                 "taxRates":[
                    {
                       "name":"VAT",
                       "rate":0,
                       "amount":0
                    }
                 ],
                 "quantityOrdered":1,
                 "quantityInvoiced":1,
                 "quantityShipped":1,
                 "quantityRefunded":0,
                 "quantityReturned":0,
                 "articleCode":"",
                 "ean":"",
                 "sku":"",
                 "weight":null,
                 "volume":0,
                 "colli":0,
                 "sizeX":0,
                 "sizeY":0,
                 "sizeZ":0,
                 "priceCost":0,
                 "customExcl":0,
                 "customIncl":0,
                 "basePriceExcl":0,
                 "basePriceIncl":0,
                 "priceExcl":0,
                 "priceIncl":0,
                 "discountExcl":0,
                 "discountIncl":0,
                 "customFields":false,
                 "product":{
                    "resource":{
                       "id":123,
                       "url":"products\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/products\/123.json"
                    }
                 },
                 "variant":{
                    "resource":{
                       "id":123,
                       "url":"variants\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/variants\/123.json"
                    }
                 }
              }
           ]
        }
     },
     "metafields":{
        "resource":{
           "id":false,
           "url":"orders\/123\/metafields",
           "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123\/metafields.json",
           "embedded":[
              
           ]
        }
     },
     "quote":{
        "resource":{
           "id":123,
           "url":"quotes\/123",
           "link":"http:\/\/api.shoplightspeed.com\/en\/quotes\/123.json",
           "embedded":{
              "id":123,
              "createdAt":"2025-09-17T19:12:04+00:00",
              "updatedAt":"2025-09-17T19:12:38+00:00",
              "recalculatedAt":"2025-09-17T19:12:38+00:00",
              "isLocked":false,
              "channel":"backend",
              "recoveryHash":"4ec74f67f981bf925decaaa123",
              "remoteIp":"35.245.159.47",
              "userAgent":"WebshopappApi",
              "referralId":false,
              "weight":0,
              "volume":0,
              "colli":0,
              "paymentCountry":{
                 "id":226,
                 "code":"us",
                 "code3":"usa",
                 "title":"United States"
              },
              "shipmentCountry":{
                 "id":226,
                 "code":"us",
                 "code3":"usa",
                 "title":"United States"
              },
              "shipmentZipcode":"19111",
              "shipmentSameAddress":true,
              "priceCost":0,
              "priceExcl":0,
              "priceIncl":0,
              "discountExcl":0,
              "discountIncl":0,
              "productsCount":1,
              "productsQuantity":1,
              "shipmentIsSet":true,
              "shipmentId":"core|85518|424529",
              "shipmentIsVirtual":false,
              "shipmentIsCashOnDelivery":false,
              "shipmentDiscountPercentage":0,
              "shipmentIsServicePoint":false,
              "shipmentIsPickup":false,
              "shipmentTaxRate":0,
              "shipmentBasePriceExcl":0,
              "shipmentBasePriceIncl":0,
              "shipmentPriceTax":0,
              "shipmentPriceExcl":0,
              "shipmentPriceIncl":0,
              "shipmentDiscountExcl":0,
              "shipmentDiscountIncl":0,
              "shipmentTitle":"Shipment Title",
              "shipmentData":{
                 "method":"default",
                 "shipment_id":85518,
                 "shipping_value_id":424529
              },
              "paymentIsSet":true,
              "paymentId":"external",
              "paymentIsPost":false,
              "paymentIsInvoiceExternal":false,
              "paymentData":"{\"user_id\":null}",
              "paymentTaxRate":0,
              "paymentBasePriceExcl":0,
              "paymentBasePriceIncl":0,
              "paymentPriceTax":0,
              "paymentPriceExcl":0,
              "paymentPriceIncl":0,
              "additionalCostIncl":"0.0000",
              "additionalCostExcl":"0.0000",
              "paymentTitle":"Customer choice",
              "discountIsSet":false,
              "discountId":0,
              "discountType":"amount",
              "discountAmount":0,
              "discountPercentage":0,
              "discountShipment":"default",
              "discountMinimumAmount":"0.00",
              "discountCouponCode":"",
              "comment":"",
              "allowNotifications":false,
              "customer":{
                 "resource":{
                    "id":123,
                    "url":"customers\/123",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/customers\/123.json"
                 }
              },
              "language":{
                 "id":3,
                 "code":"en",
                 "locale":"en_GB",
                 "title":"English"
              },
              "products":{
                 "resource":{
                    "id":false,
                    "url":"quotes\/123\/products",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/quotes\/123\/products.json"
                 }
              },
              "shippingmethods":{
                 "resource":{
                    "id":false,
                    "url":"quotes\/123\/shippingmethods",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/quotes\/123\/shippingmethods.json"
                 }
              },
              "paymentmethods":{
                 "resource":{
                    "id":false,
                    "url":"quotes\/123\/paymentmethods",
                    "link":"http:\/\/api.shoplightspeed.com\/en\/quotes\/123\/paymentmethods.json"
                 }
              }
           }
        }
     },
     "events":{
        "resource":{
           "id":false,
           "url":"orders\/events?order=123",
           "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/events.json?order=123",
           "embedded":[
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "channel":"manual",
                 "type":"order",
                 "message":"new",
                 "comment":null,
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "invoice":false,
                 "shipment":false
              },
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "channel":"auto",
                 "type":"invoice",
                 "message":"new",
                 "comment":null,
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "invoice":{
                    "resource":{
                       "id":123,
                       "url":"invoices\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123.json"
                    }
                 },
                 "shipment":false
              },
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "channel":"auto",
                 "type":"shipment",
                 "message":"new",
                 "comment":null,
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "invoice":false,
                 "shipment":{
                    "resource":{
                       "id":123,
                       "url":"shipments\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/shipments\/123.json"
                    }
                 }
              },
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "channel":"auto",
                 "type":"invoice",
                 "message":"paid",
                 "comment":null,
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "invoice":{
                    "resource":{
                       "id":123,
                       "url":"invoices\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/invoices\/123.json"
                    }
                 },
                 "shipment":false
              },
              {
                 "id":123,
                 "createdAt":"2025-09-17T19:12:38+00:00",
                 "channel":"auto",
                 "type":"order",
                 "message":"paid",
                 "comment":"Total = 0",
                 "order":{
                    "resource":{
                       "id":123,
                       "url":"orders\/123",
                       "link":"http:\/\/api.shoplightspeed.com\/en\/orders\/123.json"
                    }
                 },
                 "invoice":false,
                 "shipment":false
              }
           ]
        }
     },
     "giftCardsPayment":[
        
     ]
  }
}