export default {
  "xRequest": 12410,
  "fOpenedVia": "Web Service",
  "xOpenedViaId": 0,
  "xPortal": 0,
  "xMailboxToSendFrom": 1,
  "xPersonOpenedBy": "Username",
  "xPersonAssignedTo": "",
  "fOpen": 1,
  "xStatus": "Escalated",
  "fUrgent": 1,
  "xCategory": "Server",
  "dtGMTOpened": "Oct  3, 2024",
  "dtGMTClosed": "",
  "iLastReplyBy": "Username",
  "fTrash": 0,
  "dtGMTTrashed": "",
  "sRequestPassword": "QrdtUSeDqXzYpfnBULov",
  "sTitle": "Re: subject test",
  "sUserId": "",
  "sFirstName": "First Name",
  "sLastName": "Last name",
  "sEmail": "user@email.com",
  "sPhone": "11111111111",
  "fullname": "Full Name",
  "request_history": {
    "item": {
      "24": {
        "xRequestHistory": 24,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 10:01 AM",
        "fPublic": 0,
        "fInitial": 1,
        "fNoteIsHTML": 1,
        "fMergedFromRequest": 0,
        "tLog": "",
        "tNote": "<p>note test</p>",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "25": {
        "xRequestHistory": 25,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 10:08 AM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 1,
        "fMergedFromRequest": 0,
        "tLog": "",
        "tNote": "<p>note 06</p>",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "26": {
        "xRequestHistory": 26,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 10:08 AM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 0,
        "fMergedFromRequest": 0,
        "tLog": "Request Changed:",
        "tNote": "note test",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "27": {
        "xRequestHistory": 27,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 10:10 AM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 0,
        "fMergedFromRequest": 0,
        "tLog": "",
        "tNote": "note test",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "28": {
        "xRequestHistory": 28,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 10:10 AM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 0,
        "fMergedFromRequest": 0,
        "tLog": "Request Changed:",
        "tNote": "",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "40": {
        "xRequestHistory": 40,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 04:43 PM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 0,
        "fMergedFromRequest": 0,
        "tLog": "Request Changed:",
        "tNote": "",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "48": {
        "xRequestHistory": 48,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 04:45 PM",
        "fPublic": 1,
        "fInitial": 0,
        "fNoteIsHTML": 1,
        "fMergedFromRequest": 0,
        "tNote": "<p>note test</p>",
        "tEmailHeaders": "",
        "fPinned": 0,
        "cc": "test@email.com",
        "bcc": "test@bcc.com",
        "to": "",
        "staff_notified": [
          ""
        ],
        "external": 0,
        "person_type": "staff",
        "files": []
      },
      "49": {
        "xRequestHistory": 49,
        "xRequest": 12410,
        "xPerson": "Username",
        "dtGMTChange": "Oct  3 2024, 04:45 PM",
        "fPublic": 0,
        "fInitial": 0,
        "fNoteIsHTML": 0,
        "fMergedFromRequest": 0,
        "tLog": "Request Changed:",
        "tNote": "",
        "tEmailHeaders": "",
        "fPinned": 0,
        "external": 0,
        "person_type": "staff",
        "files": []
      }
    }
  },
  "lastDate": 1727973900
}