import assert from 'node:assert/strict';
import app from '../alive5.app.mjs';
import send from '../actions/send-sms/send-sms.mjs';
import source from '../sources/new-sms-received/new-sms-received.mjs';
const api=Object.assign({$auth:{api_key:'test-key'}}, app.methods);
const adapter=(body)=>async(config)=>({data:body,status:200,statusText:'OK',headers:{},config});
await assert.rejects(api._request({adapter:adapter({data:{}})}),/rejected/);
await assert.rejects(api._request({adapter:adapter({code:200,data:{error:{message:'failed'}}})}),/rejected/);
assert.deepEqual(await api._request({adapter:adapter({code:200,error:{},data:{Items:[]}})}),{Items:[]});
await assert.rejects(send.run.call({smsLine:'channel|+14155550100',to:'+14155550123',message:'  '},{$:{export(){}}}),/text/);
let subscription={phoneNumber:'+14155550100',interceptorUuid:'owned-test-hook'};
const ctx={db:{get:()=>subscription,set:(_,v)=>{subscription=v}},alive5:{async deleteWebhook(){throw Error('temporary failure')}}};
await assert.rejects(source.hooks.deactivate.call(ctx),/temporary failure/);
assert.ok(subscription,'Failed cleanup must retain the owned subscription');
const emitted=[];const sourceCtx={db:{get:()=>subscription},http:{respond(){}},$emit:(data,meta)=>emitted.push({data,meta})};
const body={direction:'inbound',message_content:'test',created_by:'+14155550123',created_at:1789243375,thread_id:'test-thread'};
await source.run.call(sourceCtx,{body});await source.run.call(sourceCtx,{body});
assert.equal(emitted[0].meta.id,emitted[1].meta.id);
assert.equal(emitted[0].data.received_at,'2026-09-12T20:02:55.000Z');
await source.run.call(sourceCtx,{body:{...body,direction:'outbound'}});
assert.equal(emitted.length,2);
console.log('PASS: API envelopes, blank SMS, cleanup retention, timestamp normalization, dedup identity, direction filtering');
