export default {
  name: {
    type: "string",
    label: "Name",
    description: "Account name",
    optional: true,
  },
  domain: {
    type: "string",
    label: "Domain",
    description: "Domain",
    optional: true,
  },
  website: {
    type: "string",
    label: "Website",
    description: "Account's website",
    optional: true,
  },
  description: {
    type: "string",
    label: "Description",
    description: "Description of the account",
    optional: true,
  },
  city: {
    type: "string",
    label: "City",
    description: "City (address)",
    optional: true,
  },
  country: {
    type: "string",
    label: "Country",
    description: "Country (address)",
    optional: true,
  },
  stateRegion: {
    type: "string",
    label: "State Region",
    description: "State region (address)",
    optional: true,
  },
  street: {
    type: "string",
    label: "Street",
    description: "Street (address)",
    optional: true,
  },
  zip: {
    type: "string",
    label: "Zip",
    description: "Zip (address)",
    optional: true,
  },
  email: {
    type: "string",
    label: "Email",
    description: "Contact email max `1000` characters",
    optional: true,
  },
  phoneNumber: {
    type: "string",
    label: "Phone Number",
    description: "Phone number of the account",
    optional: true,
  },
  socialProfiles: {
    type: "string[]",
    label: "Social Profiles",
    description: "Social profile links of the account.",
    optional: true,
  },
  tags: {
    type: "string[]",
    label: "Tags",
    description: "Tags",
    optional: true,
  },
  links: {
    type: "string[]",
    label: "Links",
    description: "Links",
    optional: true,
  },
};
