export default {
  email: {
    type: "string",
    label: "Email",
    description: "Contact email max `1000` characters",
    optional: true,
  },
  prefix: {
    type: "string",
    label: "Prefix",
    description: "Contact prefix",
    optional: true,
  },
  firstname: {
    type: "string",
    label: "Firstname",
    description: "Firstname of the contact",
    optional: true,
  },
  middle: {
    type: "string",
    label: "Middlename",
    description: "Middlename of the contact",
    optional: true,
  },
  lastname: {
    type: "string",
    label: "Lastname",
    description: "Lastname of the contact",
    optional: true,
  },
  suffix: {
    type: "string",
    label: "Suffix",
    description: "Suffix of the contact",
    optional: true,
  },
  name: {
    type: "string",
    label: "Name",
    description: "Name of the contact",
    optional: true,
  },
  birthDate: {
    type: "string",
    label: "Birth Date",
    description: "Birth date of contact. Must be in ISO format. e.g. `1990-11-17T08:07:00Z`",
    optional: true,
  },
  tags: {
    type: "string[]",
    label: "Tags",
    description: "Tags",
    optional: true,
  },
  city: {
    type: "string",
    label: "City",
    description: "City (address)",
    optional: true,
  },
  country: {
    type: "string",
    label: "Country",
    description: "Country (address)",
    optional: true,
  },
  stateRegion: {
    type: "string",
    label: "State Region",
    description: "State region (address)",
    optional: true,
  },
  street: {
    type: "string",
    label: "Street",
    description: "Street (address)",
    optional: true,
  },
  zip: {
    type: "string",
    label: "Zip",
    description: "Zip (address)",
    optional: true,
  },
  phoneNumber: {
    type: "string",
    label: "Phone Number",
    description: "Phone number of the contact",
    optional: true,
  },
  faxNumber: {
    type: "string",
    label: "Fax Number",
    description: "Fax number of the contact",
    optional: true,
  },
  organisaton: {
    type: "string",
    label: "Organisation",
    description: "Organisation (position)",
    optional: true,
  },
  role: {
    type: "string",
    label: "Role",
    description: "Role (position)",
    optional: true,
  },
  socialProfiles: {
    type: "string[]",
    label: "Social Profiles",
    description: "Social profile links of contact",
    optional: true,
  },
  custom: {
    type: "object",
    label: "Custom",
    description: "Custom fields",
    optional: true,
  },
};
