export default {
  "id": 959508,
  "external_constituent_id": "t00072",
  "is_org": false,
  "constituent_contact_type_id": 1243,
  "constituent_contact_type_name": "Primary",
  "prefix": null,
  "first_name": "Mike",
  "middle_name": null,
  "last_name": "Brady",
  "suffix": null,
  "spouse_name": null,
  "org_name": null,
  "job_title": null,
  "addressee": "Mr. and Mrs. Mike Brady",
  "salutation": "Mike and Carol",
  "sort_name": "Brady, Mike",
  "constituent_interest_level_id": null,
  "constituent_interest_level_name": null,
  "constituent_rating_id": null,
  "constituent_rating_name": null,
  "is_deceased": false,
  "deceased_date": null,
  "annual_report_name": "Mr. and Mrs. Mike Brady",
  "birthday": null,
  "gender": null,
  "maiden_name": null,
  "nick_name": null,
  "spouse_nick_name": null,
  "date_added": "2023-09-18",
  "alt_salutation": "Mike and Carol",
  "alt_addressee": "Mr. and Mrs. Mike Brady",
  "honorary_name": "Mr. and Mrs. Mike Brady",
  "assistant_name": null,
  "marital_status_id": null,
  "marital_status_name": null,
  "is_anon": false,
  "created_at": "2023-09-18T18:25:25Z",
  "updated_at": "2023-10-31T18:01:04Z"
}