export default {
  ALL: "*",
  PROJECTS: "project.*",
  PROJECT_CREATED: "project.created",
  PROJECT_UPDATED: "project.updated",
  PROJECT_LABEL_ADDED: "project.label_added",
  PHOTOS: "photo.*",
  PHOTO_CREATED: "photo.created",
  PHOTO_UPDATED: "photo.updated",
  PHOTO_TAG_ADDED: "photo.tag_added",
  COMMENTS: "comment.*",
  COMMENT_CREATED: "comment.created",
  DOCUMENTS: "document.*",
  DOCUMENT_CREATED: "document.created",
  VIDEOS: "video.*",
  VIDEO_CREATED: "video.created",
  TODO_LISTS: "todo_list.*",
  TODO_LIST_CREATED: "todo_list.created",
  TODO_LIST_COMPLETED: "todo_list.completed",
  TODO_LIST_DELETED: "todo_list.deleted",
  TASKS: "task.*",
  TASK_COMPLETED: "task.completed",
};
