export default {
  "id": "667c312b-44b5-4405-a06a-5d6d3dbbee2e",
  "type": "task",
  "appearance": null,
  "model": "task",
  "createdAt": "2024-06-06T19:48:14.781Z",
  "createdUserId": "0a57c078-683f-4fb7-aefb-e83242215d8b",
  "commentedByUserIds": [],
  "deleted": false,
  "deletedAt": null,
  "deletedByUserId": null,
  "name": "task",
  "nameRichText": "<p>task</p>",
  "nameType": "markdown",
  "description": "",
  "descriptionRichText": "",
  "descriptionType": "markdown",
  "index": 12,
  "assigneesIds": [],
  "statusSetId": null,
  "status": "backLog",
  "parentTaskId": null,
  "teamIds": [],
  "listIds": [
    "d9e63325-46af-42d9-a6a9-bccfeee041a7"
  ],
  "commentsAggregateCount": 0,
  "lastActivityAt": "2024-06-06T20:35:14.515Z",
  "completed": false,
  "completedAt": null,
  "completedByUserId": null,
  "startedAt": null,
  "completedIn": null,
  "inProgressFor": null,
  "delayedFor": null,
  "orderIndex": 1936257377,
  "subtasksIds": [],
  "completedSubtasksIds": [],
  "fields": [],
  "gitBranches": [],
  "gitPullRequests": [],
  "parentTasks": [],
  "subscribersIds": [
    "0a57c078-683f-4fb7-aefb-e83242215d8b"
  ],
  "redacted": null,
  "links": [],
  "url": "https://height.app/aCs1znNK1Y/T-12",
  "trashedAt": null,
  "trashedByUserId": null,
  "lastDescriptionActivity": null
}