export default {
  "id": 70223,
  "createdAt": 1713817815015,
  "updatedAt": 1713817815015,
  "companyId": 3356,
  "invited": true,
  "unknownUser": false,
  "name": "Test User",
  "email": "user@example.com",
  "phone": "",
  "locale": "en",
  "timezoneoffset": 0,
  "lastOnline": null,
  "device": null,
  "isActive": true,
  "seesAllSubjects": false,
  "ignoreNotOpenLevels": false,
  "ignoreStopItems": false,
  "subjects": [],
  "isDemoMode": false,
  "demoStartAt": null,
  "noteAboutUser": "",
  "photo": null,
  "aboutMe": "",
  "personalLink": "",
  "fieldsToBePublic": {
    "email": true,
    "phone": true,
    "photo": true,
    "aboutMe": true,
    "personalLink": true
  },
  "levelPacksAccess": []
}