export default {
  "index": "Overview",
  "building-workflows": "Building Workflows",
  "projects": "Projects",
  "workspaces": "Workspaces",
  "data-management": "Data Management",
  "event-history": "Event History",
  "environment-variables": "Environment Variables",
  "git": "GitHub Sync",
  "domains": "Custom Domains",
  "vpc": "Virtual Private Clouds",
  "limits": "Limits",
  "contributing": "Contributing",
  "cli": "CLI",
} as const
