export default [
    {
       "id": "",
       "accountId": 0,
       "sampleData": false,
       "clientId": "",
       "name": "",
       "description": "",
       "active": false,
       "startDate": "2023-08-15",
       "dueDate": "2023-08-15",
       "dateCreated": "2023-08-15T07:34:25.36-04:00",
       "client": {
          "accountId": 0,
          "sampleData": false,
          "id": "",
          "clientType": "Client",
          "name": "",
          "initials": "",
          "locality": "",
          "country": "",
          "color": "",
          "hourlyAmount": 0,
          "archive": false,
          "currency": "",
          "logo": "",
          "leadSource": "",
          "contact": {
             "id": "",
             "accountId": 0,
             "clientId": "",
             "clientPortalUserId": 0,
             "firstName": "",
             "lastName": "",
             "role": "",
             "phone": "",
             "email": "",
             "mobile": "",
             "notes": "",
             "defaultContact": false,
             "invoiceContact": false,
             "portalAccess": false,
             "importRecordId": "",
             "sampleData": false
          }
       },
       "leadGenArchived": false,
       "feeSchedule": {
          "feeType": "HOURLY",
          "amount": 0,
          "retainerSchedule": "WEEKLY",
          "estimateMax": 0,
          "estimateMin": 0,
          "retainerStart": "2023-08-15",
          "retainerTiming": "ADVANCED",
          "retainerOverageRate": 0,
          "taxable": false,
          "fromProposalId": "",
          "fromProposalSignedDate": "2023-08-15T07:34:25.371-04:00",
          "updatedDate": "2023-08-15T07:34:25.371-04:00",
          "updatedBy": ""
       },
       "proposalId": "",
       "proposalName": "",
       "hexColor": "",
       "portalAccess": "FULL",
       "showTimeWorkedInPortal": false
    }
]