export default {
  "task": {
    "id": 28241318,
    "project_id": 500688,
    "project_name": "Example Project",
    "created_at": "2026-01-09T15:45:04.910Z",
    "updated_at": "2026-01-09T15:57:46.132Z",
    "local_task_id": 2,
    "priority_id": 3,
    "status_id": null,
    "title": null,
    "description": "Example task description",
    "tag_names": [],
    "external_id": null,
    "requester_email": "John@example.com",
    "attachments": [],
    "screenshot_url": null,
    "status": "feedback",
    "priority": "normal",
    "closed_at": null,
    "secret_link": "https://www.bugherd.com/t/0gYmqUu5xPjxUy9E8ZmjrQ",
    "admin_link": "https://www.bugherd.com/projects/500688/tasks/2",
    "deleted_at": null,
    "site": null,
    "url": null,
    "metadata": null,
    "screenshot_data": null,
    "fullstory_session_url": null,
    "logrocket_session_url": null,
    "requester_os": null,
    "requester_browser": null,
    "requester_browser_size": null,
    "requester_resolution": null,
    "selector_info": {},
    "due_at": null,
    "column_id": null,
    "logs": null,
    "assignees": [],
    "assigned_to": null,
    "requester": {
      "id": 580091,
      "email": "John@example.com",
      "display_name": "John Doe",
      "avatar_url": "https://www.bugherd.com/images/sidebar/avatar-generic.svg"
    },
    "updater": null
  }
}