#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx pnpm install -r --ignore-scripts

if ! (git diff HEAD --quiet pnpm-lock.yaml); then
    echo "modified pnpm-lock.yaml - please commit the file"
    exit 1
fi
