<template><h1 id="working-with-the-filesystem-in-node-js" tabindex="-1"><a class="header-anchor" href="#working-with-the-filesystem-in-node-js" aria-hidden="true">#</a> Working with the filesystem in Node.js</h1>
<p>You'll commonly need to work with files in a workflow, for example: downloading content from some service to upload to another. This doc explains how to work with files in Pipedream workflows and provides some sample code for common operations.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#the-tmp-directory">The /tmp directory</RouterLink></li><li><RouterLink to="#managing-tmp-across-workflow-runs">Managing /tmp across workflow runs</RouterLink></li><li><RouterLink to="#writing-a-file-to-tmp">Writing a file to /tmp</RouterLink></li><li><RouterLink to="#listing-files-in-tmp">Listing files in /tmp</RouterLink></li><li><RouterLink to="#reading-a-file-from-tmp">Reading a file from /tmp</RouterLink></li><li><RouterLink to="#delete-a-file">Delete a file</RouterLink></li><li><RouterLink to="#download-a-file-to-tmp">Download a file to /tmp</RouterLink></li><li><RouterLink to="#upload-a-file-from-tmp">Upload a file from /tmp</RouterLink></li><li><RouterLink to="#download-a-file-uploading-it-in-another-multipart-form-data-request">Download a file, uploading it in another multipart/form-data request</RouterLink></li><li><RouterLink to="#download-email-attachments-to-tmp-upload-to-amazon-s3">Download email attachments to /tmp, upload to Amazon S3</RouterLink></li></ul></nav>
<h2 id="the-tmp-directory" tabindex="-1"><a class="header-anchor" href="#the-tmp-directory" aria-hidden="true">#</a> The <code>/tmp</code> directory</h2>
<p>Within a workflow, you have full read-write access to the <code>/tmp</code> directory. You have <code>512 MB</code> of available space in <code>/tmp</code> to save any file.</p>
<h2 id="managing-tmp-across-workflow-runs" tabindex="-1"><a class="header-anchor" href="#managing-tmp-across-workflow-runs" aria-hidden="true">#</a> Managing <code>/tmp</code> across workflow runs</h2>
<p>The <code>/tmp</code> directory is stored on the virtual machine that runs your workflow. We call this the execution environment (&quot;EE&quot;). More than one EE may be created to handle high-volume workflows. And EEs can be destroyed at any time (for example, after about 10 minutes of receiving no events). This means that you should not expect to have access to files across invocations. At the same time, files <em>may</em> remain, so you should clean them up to make sure that doesn't affect your workflow. <strong>Use <a href="https://github.com/benjamingr/tmp-promise" target="_blank" rel="noopener noreferrer">the <code>tmp-promise</code> package<ExternalLinkIcon/></a> to cleanup files after use, or <a href="#delete-a-file">delete the files manually</a>.</strong></p>
<h2 id="writing-a-file-to-tmp" tabindex="-1"><a class="header-anchor" href="#writing-a-file-to-tmp" aria-hidden="true">#</a> Writing a file to <code>/tmp</code></h2>
<p>Use the <a href="https://nodejs.org/api/fs.html" target="_blank" rel="noopener noreferrer"><code>fs</code> module<ExternalLinkIcon/></a> to write data to <code>/tmp</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> file <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'tmp-promise'</span>

<span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> <span class="token punctuation">{</span> path<span class="token punctuation">,</span> cleanup <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">file</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">await</span> fs<span class="token punctuation">.</span>promises<span class="token punctuation">.</span><span class="token function">appendFile</span><span class="token punctuation">(</span>path<span class="token punctuation">,</span> Buffer<span class="token punctuation">.</span><span class="token function">from</span><span class="token punctuation">(</span><span class="token string">"hello, world"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token keyword">await</span> <span class="token function">cleanup</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="listing-files-in-tmp" tabindex="-1"><a class="header-anchor" href="#listing-files-in-tmp" aria-hidden="true">#</a> Listing files in <code>/tmp</code></h2>
<p>Return a list of the files saved in <code>/tmp</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>

<span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> fs<span class="token punctuation">.</span><span class="token function">readdirSync</span><span class="token punctuation">(</span><span class="token string">"/tmp"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="reading-a-file-from-tmp" tabindex="-1"><a class="header-anchor" href="#reading-a-file-from-tmp" aria-hidden="true">#</a> Reading a file from <code>/tmp</code></h2>
<p>This example uses <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">step exports<ExternalLinkIcon/></a> to return the contents of a test file saved in <code>/tmp</code>, returned as a string (<a href="https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options" target="_blank" rel="noopener noreferrer"><code>fs.readFileSync</code> returns a <code>Buffer</code><ExternalLinkIcon/></a>):</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>

<span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> files <span class="token operator">=</span> <span class="token keyword">await</span> fs<span class="token punctuation">.</span>promises<span class="token punctuation">.</span><span class="token function">readFile</span><span class="token punctuation">(</span><span class="token string">'/tmp/your-file'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>fileData <span class="token operator">=</span> files<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="delete-a-file" tabindex="-1"><a class="header-anchor" href="#delete-a-file" aria-hidden="true">#</a> Delete a file</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs"</span><span class="token punctuation">;</span>

<span class="token function">defineComponent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token keyword">async</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> steps<span class="token punctuation">,</span> $ <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token keyword">await</span> fs<span class="token punctuation">.</span>promises<span class="token punctuation">.</span><span class="token function">unlink</span><span class="token punctuation">(</span><span class="token string">'/tmp/your-file'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="download-a-file-to-tmp" tabindex="-1"><a class="header-anchor" href="#download-a-file-to-tmp" aria-hidden="true">#</a> Download a file to <code>/tmp</code></h2>
<p><a href="/workflows/steps/code/nodejs/http-requests/#download-a-file-to-the-tmp-directory" target="_blank" rel="noopener noreferrer">See this example<ExternalLinkIcon/></a> to learn how to download a file to <code>/tmp</code>.</p>
<h2 id="upload-a-file-from-tmp" tabindex="-1"><a class="header-anchor" href="#upload-a-file-from-tmp" aria-hidden="true">#</a> Upload a file from <code>/tmp</code></h2>
<p><a href="/workflows/steps/code/nodejs/http-requests/#upload-a-file-from-the-tmp-directory" target="_blank" rel="noopener noreferrer">See this example<ExternalLinkIcon/></a> to learn how to upload a file from <code>/tmp</code> in an HTTP request.</p>
<h2 id="download-a-file-uploading-it-in-another-multipart-form-data-request" tabindex="-1"><a class="header-anchor" href="#download-a-file-uploading-it-in-another-multipart-form-data-request" aria-hidden="true">#</a> Download a file, uploading it in another <code>multipart/form-data</code> request</h2>
<p><a href="https://pipedream.com/@dylburger/download-file-then-upload-file-via-multipart-form-data-request-p_QPCx7p/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> provides an example of how to download a file at a specified <strong>Download URL</strong>, uploading that file to an <strong>Upload URL</strong> as form data.</p>
<h2 id="download-email-attachments-to-tmp-upload-to-amazon-s3" tabindex="-1"><a class="header-anchor" href="#download-email-attachments-to-tmp-upload-to-amazon-s3" aria-hidden="true">#</a> Download email attachments to <code>/tmp</code>, upload to Amazon S3</h2>
<p><a href="https://pipedream.com/@dylan/upload-email-attachments-to-s3-p_V9CGAQ/edit" target="_blank" rel="noopener noreferrer">This workflow<ExternalLinkIcon/></a> is triggered by incoming emails. When copied, you'll get a workflow-specific email address you can send any email to. This workflow takes any attachments included with inbound emails, saves them to <code>/tmp</code>, and uploads them to Amazon S3.</p>
<p>You should also be aware of the <a href="/limits/#email-triggers" target="_blank" rel="noopener noreferrer">inbound payload limits<ExternalLinkIcon/></a> associated with the email trigger.</p>
</template>
