<template><h1 id="privacy-and-security-at-pipedream" tabindex="-1"><a class="header-anchor" href="#privacy-and-security-at-pipedream" aria-hidden="true">#</a> Privacy and Security at Pipedream</h1>
<p>Pipedream is committed to the privacy and security of your data. Below, we outline how we handle specific data and what we do to secure it. This is not an exhaustive list of practices, but an overview of key policies and procedures.</p>
<p>It is also your responsibility as a customer to ensure you're securing your workflows' code and data. See our <a href="/privacy-and-security/best-practices/" target="_blank" rel="noopener noreferrer">security best practices<ExternalLinkIcon/></a> for more information.</p>
<p>If you have any questions related to data privacy, please email <span style="font-weight: bold">privacy@pipedream.com</span>. If you have any security-related questions, or if you'd like to report a suspected vulnerability, please email <span style="font-weight: bold">security@pipedream.com</span>.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#reporting-a-vulnerability">Reporting a Vulnerability</RouterLink></li><li><RouterLink to="#reporting-abuse">Reporting abuse</RouterLink></li><li><RouterLink to="#hosting-details">Hosting Details</RouterLink></li><li><RouterLink to="#user-accounts-authentication-and-authorization">User Accounts, Authentication and Authorization</RouterLink></li><li><RouterLink to="#third-party-oauth-grants-api-keys-and-environment-variables">Third party OAuth grants, API keys, and environment variables</RouterLink></li><li><RouterLink to="#execution-environment">Execution Environment</RouterLink></li><li><RouterLink to="#encryption-of-data-in-transit-tls-ssl-certificates">Encryption of data in transit, TLS (SSL) Certificates</RouterLink></li><li><RouterLink to="#email-security">Email Security</RouterLink></li><li><RouterLink to="#incident-response">Incident Response</RouterLink></li><li><RouterLink to="#gdpr-data-protection-addendum">GDPR / Data Protection Addendum</RouterLink></li><li><RouterLink to="#submitting-a-gdpr-deletion-request">Submitting a GDPR deletion request</RouterLink></li><li><RouterLink to="#payment-processor">Payment Processor</RouterLink></li></ul></nav>
<h2 id="reporting-a-vulnerability" tabindex="-1"><a class="header-anchor" href="#reporting-a-vulnerability" aria-hidden="true">#</a> Reporting a Vulnerability</h2>
<p>If you'd like to report a suspected vulnerability, please contact <span style="font-weight: bold">security@pipedream.com</span>.</p>
<p>If you need to encrypt sensitive data as part of your report, you can use our <a href="/security/pgp-key/" target="_blank" rel="noopener noreferrer">PGP key<ExternalLinkIcon/></a>.</p>
<h2 id="reporting-abuse" tabindex="-1"><a class="header-anchor" href="#reporting-abuse" aria-hidden="true">#</a> Reporting abuse</h2>
<p>If you suspect Pipedream resources are being used for illegal purposes, or otherwise violate <a href="https://pipedream.com/terms" target="_blank" rel="noopener noreferrer">the Pipedream Terms<ExternalLinkIcon/></a>, <a href="/abuse/" target="_blank" rel="noopener noreferrer">report it here<ExternalLinkIcon/></a>.</p>
<h2 id="hosting-details" tabindex="-1"><a class="header-anchor" href="#hosting-details" aria-hidden="true">#</a> Hosting Details</h2>
<p>Pipedream is hosted on the <a href="https://aws.amazon.com/" target="_blank" rel="noopener noreferrer">Amazon Web Services<ExternalLinkIcon/></a> (AWS) platform. The physical hardware powering Pipedream, and the data stored by our platform, is hosted in data centers controlled and secured by AWS. You can read more about AWS’s security practices and compliance certifications <a href="https://aws.amazon.com/security/" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>.</p>
<p>Pipedream further secures access to AWS resources through a series of controls, including but not limited to: using multi-factor authentication to access AWS, hosting services within a private network inaccessible to the public internet, and more.</p>
<h2 id="user-accounts-authentication-and-authorization" tabindex="-1"><a class="header-anchor" href="#user-accounts-authentication-and-authorization" aria-hidden="true">#</a> User Accounts, Authentication and Authorization</h2>
<p>When you sign up for a Pipedream account, you can choose to link your Pipedream login to either an existing <a href="https://google.com" target="_blank" rel="noopener noreferrer">Google<ExternalLinkIcon/></a> or <a href="https://github.com" target="_blank" rel="noopener noreferrer">Github<ExternalLinkIcon/></a> account, or create an account directly with Pipedream.</p>
<p>When you link your Pipedream login to an existing identity provider, Pipedream does not store any passwords tied to your user account — that information is secured with the identity provider. We recommend you configure two-factor authentication in the provider to further protect access to your Pipedream account.</p>
<p>When you create an account on Pipedream directly, with a username and password, Pipedream implements best account security practices (for example: Pipedream hashes your password, and the hashed password is encrypted in our database, which resides in a private network accessible only to select Pipedream employees).</p>
<h2 id="third-party-oauth-grants-api-keys-and-environment-variables" tabindex="-1"><a class="header-anchor" href="#third-party-oauth-grants-api-keys-and-environment-variables" aria-hidden="true">#</a> Third party OAuth grants, API keys, and environment variables</h2>
<p>When you link an account from a third party application, you may be asked to either authorize a Pipedream OAuth application access to your account, or provide an API key or other credentials. This section describes how we handle these grants and keys.</p>
<p>When a third party application supports an <a href="https://oauth.net/2/" target="_blank" rel="noopener noreferrer">OAuth integration<ExternalLinkIcon/></a>, Pipedream prefers that interface. The OAuth protocol allows Pipedream to request scoped access to specific resources in your third party account without you having to provide long-term credentials directly. Pipedream must request short-term access tokens at regular intervals, and most applications provide a way to revoke Pipedream's access to your account at any time.</p>
<p>Some third party applications do not provide an OAuth interface. To access these services, you must provide the required authorization mechanism (often an API key). As a best practice, if your application provides such functionality, Pipedream recommends you limit that API key's access to only the resources you need access to within Pipedream.</p>
<p>Pipedream encrypts all OAuth grants, key-based credentials, and environment variables at rest in our production database. That database resides in a private network. Backups of that database are encrypted. The key used to encrypt this database is managed by <a href="https://aws.amazon.com/kms/" target="_blank" rel="noopener noreferrer">AWS KMS<ExternalLinkIcon/></a> and controlled by Pipedream. KMS keys are 256 bit in length and use the Advanced Encryption Standard (AES) in Galois/Counter Mode (GCM). Access to administer these keys is limited to specific members of our team. Keys are automatically rotated once a year. KMS has achieved SOC 1, 2, 3, and ISO 9001, 27001, 27017, 27018 compliance. Copies of these certifications are available from Amazon on request.</p>
<p>When you link credentials to a specific source or workflow, the credentials are loaded into that program's <a href="#execution-environment">execution environment</a>, which runs in its own virtual machine, with access to RAM and disk isolated from other users' code.</p>
<p>No credentials are logged in your source or workflow by default. If you log their values or <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">export data from a step<ExternalLinkIcon/></a>, you can always delete the data for that invocation from your source or workflow.</p>
<p>You can delete your OAuth grants or key-based credentials at any time by visiting <a href="https://pipedream.com/accounts" target="_blank" rel="noopener noreferrer">https://pipedream.com/accounts<ExternalLinkIcon/></a>. Deleting OAuth grants within Pipedream <strong>do not</strong> revoke Pipedream's access to your account. You must revoke that access wherever you manage OAuth grants in your third party application.</p>
<h2 id="execution-environment" tabindex="-1"><a class="header-anchor" href="#execution-environment" aria-hidden="true">#</a> Execution Environment</h2>
<p>The <strong>execution environment</strong> refers to the environment in which your sources, workflows, and other Pipedream code is executed.</p>
<p>Each version of a source or workflow is deployed to its own virtual machine. This means your execution environment has its own RAM and disk, isolated from other users' environments. You can read more about the details of the virtualization and isolation mechanisms used to secure your execution environment <a href="https://firecracker-microvm.github.io/" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>.</p>
<h2 id="encryption-of-data-in-transit-tls-ssl-certificates" tabindex="-1"><a class="header-anchor" href="#encryption-of-data-in-transit-tls-ssl-certificates" aria-hidden="true">#</a> Encryption of data in transit, TLS (SSL) Certificates</h2>
<p>When you use the Pipedream web application at <a href="https://pipedream.com" target="_blank" rel="noopener noreferrer">https://pipedream.com<ExternalLinkIcon/></a>, traffic between your client and Pipedream services is encrypted in transit. When you create an HTTP interface in Pipedream, the Pipedream UI defaults to displaying the HTTPS endpoint, which we recommend you use when sending HTTP traffic to Pipedream so that your data is encrypted in transit.</p>
<p>All Pipedream-managed certificates used to protect user data in transit are created using <a href="https://aws.amazon.com/certificate-manager/" target="_blank" rel="noopener noreferrer">AWS Certificate Manager<ExternalLinkIcon/></a>. This eliminates the need for our employees to manage certificate private keys: these keys are managed and secured by Amazon.</p>
<h2 id="email-security" tabindex="-1"><a class="header-anchor" href="#email-security" aria-hidden="true">#</a> Email Security</h2>
<p>Pipedream delivers emails to users for the purpose of email verification, error notifications, and more. Pipedream implements <a href="https://en.wikipedia.org/wiki/Sender_Policy_Framework" target="_blank" rel="noopener noreferrer">SPF<ExternalLinkIcon/></a> and <a href="https://en.wikipedia.org/wiki/DMARC" target="_blank" rel="noopener noreferrer">DMARC<ExternalLinkIcon/></a> DNS records to guard against email spoofing / forgery. You can review these records by using a DNS lookup tool like <a href="https://en.wikipedia.org/wiki/Dig_(command)" target="_blank" rel="noopener noreferrer"><code>dig</code><ExternalLinkIcon/></a>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token comment"># SPF</span>
<span class="token function">dig</span> pipedream.com TXT +short
<span class="token comment"># DMARC</span>
<span class="token function">dig</span> _dmarc.pipedream.com TXT +short
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="incident-response" tabindex="-1"><a class="header-anchor" href="#incident-response" aria-hidden="true">#</a> Incident Response</h2>
<p>Pipedream implements incident response best practices for identifying, documenting, resolving and communicating incidents. Pipedream publishes incident notifications to a status page at <a href="https://status.pipedream.com/" target="_blank" rel="noopener noreferrer">status.pipedream.com<ExternalLinkIcon/></a> and to the <a href="https://twitter.com/pipedreamstatus" target="_blank" rel="noopener noreferrer">@PipedreamStatus Twitter account<ExternalLinkIcon/></a>.</p>
<p>Pipedream notifies customers of any data breaches according to our <a href="https://pipedream.com/dpa" target="_blank" rel="noopener noreferrer">Data Protection Addendum<ExternalLinkIcon/></a>.</p>
<h2 id="gdpr-data-protection-addendum" tabindex="-1"><a class="header-anchor" href="#gdpr-data-protection-addendum" aria-hidden="true">#</a> GDPR / Data Protection Addendum</h2>
<p>Pipedream is considered both a Controller and a Processor as defined by the GDPR. As a Processor, Pipedream implements policies and practices that secure the personal data you send to the platform, and includes a <a href="https://pipedream.com/dpa" target="_blank" rel="noopener noreferrer">Data Protection Addendum<ExternalLinkIcon/></a> as part of our standard <a href="https://pipedream.com/terms" target="_blank" rel="noopener noreferrer">Terms of Service<ExternalLinkIcon/></a>.</p>
<p>The Pipedream Data Protection Addendum includes the <a href="https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en" target="_blank" rel="noopener noreferrer">Standard Contractual Clauses (SCCs)<ExternalLinkIcon/></a>. These clarify how Pipedream handles your data, and they update our GDPR policies to cover the latest standards set by the European Commission.</p>
<p>You can find a list of Pipedream subprocessors <a href="/subprocessors/" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>.</p>
<h2 id="submitting-a-gdpr-deletion-request" tabindex="-1"><a class="header-anchor" href="#submitting-a-gdpr-deletion-request" aria-hidden="true">#</a> Submitting a GDPR deletion request</h2>
<p>When you <a href="/user-settings/#delete-account" target="_blank" rel="noopener noreferrer">delete your account<ExternalLinkIcon/></a>, Pipedream deletes all personal data we hold on you in our system and our vendors.</p>
<p>If you need to delete data on behalf of one of your users, you can delete the event data yourself in your workflow or event source (for example, by deleting the events, or by removing the data from <code>$checkpoint</code>). Your customer event data is automatically deleted from Pipedream subprocessors.</p>
<h2 id="payment-processor" tabindex="-1"><a class="header-anchor" href="#payment-processor" aria-hidden="true">#</a> Payment Processor</h2>
<p>Pipedream uses <a href="https://stripe.com" target="_blank" rel="noopener noreferrer">Stripe<ExternalLinkIcon/></a> as our payment processor. When you sign up for a paid plan, the details of your payment method are transmitted to and stored by Stripe <a href="https://stripe.com/docs/security/stripe" target="_blank" rel="noopener noreferrer">according to their security policy<ExternalLinkIcon/></a>. Pipedream stores no information about your payment method.</p>
</template>
