export default [
  "collaborators",
  "filters",
  "items",
  "labels",
  "live_notifications",
  "locations",
  "notes",
  "notification_settings",
  "projects",
  "reminders",
  "sections",
  "user",
  "user_settings",
];
