<template><h1 id="hello-name" tabindex="-1"><a class="header-anchor" href="#hello-name" aria-hidden="true">#</a> hello ${name}!</h1>
<p>Next, let's pass a name in each HTTP request and return it in the workflow response. This example builds on the workflow we created in <a href="/quickstart/hello-world/" target="_blank" rel="noopener noreferrer">hello world!<ExternalLinkIcon/></a> and will cover how to:</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#pass-data-to-an-http-triggered-workflow-via-query-parameters">Pass data to an HTTP triggered workflow via query parameters</RouterLink></li><li><RouterLink to="#inspect-the-query-data-sent-to-the-workflow">Inspect the query data sent to the workflow</RouterLink></li><li><RouterLink to="#customize-the-http-response-using-data-sent-to-the-workflow">Customize the HTTP response using data sent to the workflow</RouterLink></li></ul></nav>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>If you didn't complete the previous example, we recommend you start from the <a href="/quickstart/" target="_blank" rel="noopener noreferrer">beginning of this guide<ExternalLinkIcon/></a>. If you still want to start here, <a href="https://pipedream.com/@gettingstarted/quickstart-hello-world-p_2gCWpmk/" target="_blank" rel="noopener noreferrer">copy this workflow<ExternalLinkIcon/></a> and then follow the instructions below. If you have any issues completing this example, you can <a href="https://pipedream.com/@gettingstarted/quickstart-hello-name-p_WxCqxbR" target="_blank" rel="noopener noreferrer">view, copy and run a completed version<ExternalLinkIcon/></a>.</p>
</div>
<h3 id="pass-data-to-an-http-triggered-workflow-via-query-parameters" tabindex="-1"><a class="header-anchor" href="#pass-data-to-an-http-triggered-workflow-via-query-parameters" aria-hidden="true">#</a> Pass data to an HTTP triggered workflow via query parameters</h3>
<p>First, modify the endpoint URL you loaded in your browser to trigger your workflow and add <code>?name=foo</code> to the end (e.g., <code>https://ENDPOINT-ID.m.pipedream.net/?name=foo</code>). Then load it to make another request to your workflow. You should still see <code>hello world!</code> returned as the response from your workflow.</p>
<p><img src="@source/quickstart/hello-name/images/name-foo.gif" alt="name-foo"></p>
<h3 id="inspect-the-query-data-sent-to-the-workflow" tabindex="-1"><a class="header-anchor" href="#inspect-the-query-data-sent-to-the-workflow" aria-hidden="true">#</a> Inspect the query data sent to the workflow</h3>
<p>Return to Pipedream and select the event you just generated from the event list. You should now see <code>{1}</code> next to the <code>query</code> field indicating it has nested values. Expand it to inspect the query parameter and value for the request.</p>
<p><img src="@source/quickstart/hello-name/images/image-20210525170616605.png" alt="image-20210525170616605"></p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>If you don't see any query data, check the <code>url</code> parameter in the <code>steps.trigger.event</code> observation to make sure you didn't select the event associated with the browser's <code>favicon.ico</code> request.</p>
</div>
<h3 id="customize-the-http-response-using-data-sent-to-the-workflow" tabindex="-1"><a class="header-anchor" href="#customize-the-http-response-using-data-sent-to-the-workflow" aria-hidden="true">#</a> Customize the HTTP response using data sent to the workflow</h3>
<p>Next, let's incorporate this data into the workflow response. Expand the code section of <code>steps.respond</code> if it's collapsed. Then modify the value for the <code>body</code> parameter of the <code>$respond()</code> function and replace <code>world</code> with <code>${steps.trigger.event.query.name}</code> to reference the name we're passing to the trigger:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">await</span> <span class="token function">$respond</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">status</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span>
  <span class="token literal-property property">immediate</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
  <span class="token literal-property property">body</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">hello </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>steps<span class="token punctuation">.</span>trigger<span class="token punctuation">.</span>event<span class="token punctuation">.</span>query<span class="token punctuation">.</span>name<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">!</span><span class="token template-punctuation string">`</span></span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p><img src="@source/quickstart/hello-name/images/image-20210525170745094.png" alt="image-20210525170745094"></p>
<p>Finally, <strong>Deploy</strong> and reload the URL in your browser:</p>
<p><img src="@source/quickstart/hello-name/images/hello-name.gif" alt="hello-name"></p>
<p>Your workflow will now return <code>hello foo!</code> (or whatever value you pass to <code>name</code>) instead of <code>hello world!</code>.</p>
<p><strong>Next, let's add an action to make an HTTP request from this workflow.</strong></p>
<p style="text-align:center;">
<a :href="$withBase('/quickstart/make-http-request/')"><img src="@source/quickstart/next.png"></a>
</p></template>
