export default {
  CLEAN_STATUS: [
    "Matched",
    "Different",
    "Acknowledged",
    "NotFound",
    "Inactive",
    "Pending",
    "SelectMatch",
    "Skipped",
  ],
  CALL_TYPES: [
    "Inbound",
    "Internal",
    "Outbound",
  ],
  RECURRENCE_REGENERATED_TYPE: [
    "None",
    "After due date",
    "After the task is closed",
    "(Task closed)",
  ],
  TASK_SUB_TYPES: [
    "Task",
    "Email",
    "List Email",
    "Cadence",
    "Call",
  ],
  CASE_FEED_ITEM_TYPES: [
    "ActivityEvent",
    "AdvancedTextPost",
    "ApprovalPost",
    "AttachArticleEvent",
    "CallLogPost",
    "CanvasPost",
    "CaseCommentPost",
    "ChangeStatusPost",
    "ChatTranscriptPost",
    "ContentPost",
    "CreatedRecordEvent",
    "EmailMessageEvent",
    "LinkPost",
    "MilestoneEvent",
    "PollPost",
    "QuestionPost",
    "SocialPost",
    "TextPost",
    "TrackedChange",
  ],
  CASE_DEFAULT_STATUSES: [
    "New",
    "Working",
    "Escalated",
    "Closed",
  ],
  CASE_LIST_FIELDS: [
    "Id",
    "CaseNumber",
    "Subject",
    "Status",
    "Priority",
    "Origin",
    "IsClosed",
    "AccountId",
    "ContactId",
    "OwnerId",
    "CreatedDate",
    "LastModifiedDate",
  ],
  DEFAULT_LIMIT: 100,
  MAX_LIMIT: 1000,
  SALESFORCE_ID_REGEX: /^[a-zA-Z0-9]{15}([a-zA-Z0-9]{3})?$/,
  DATE_ONLY_REGEX: /^\d{4}-\d{2}-\d{2}$/,
  DATE_TIME_REGEX: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/,
  OBJECT_TYPE: {
    CAMPAIGN: "Campaign",
    CONTACT: "Contact",
    CAMPAIGN_MEMBER: "CampaignMember",
    LEAD: "Lead",
    CASE: "Case",
    CASE_FEED: "CaseFeed",
    CASE_COMMENT: "CaseComment",
    EMAIL_MESSAGE: "EmailMessage",
    EMAIL_TEMPLATE: "EmailTemplate",
    KNOWLEDGE_ARTICLE: "KnowledgeArticle",
    FEED_ITEM: "FeedItem",
    FEED_COMMENT: "FeedComment",
  },
  FIELD_NAME: {
    CREATED_DATE: "CreatedDate",
    LAST_MODIFIED_DATE: "LastModifiedDate",
  },
  FEED_ITEM_MIN_FIELDS: Object.freeze([
    "Id",
    "Type",
    "Body",
    "ParentId",
    "CreatedById",
    "CreatedDate",
  ]),
  FEED_COMMENT_MIN_FIELDS: Object.freeze([
    "Id",
    "CommentBody",
    "ParentId",
    "FeedItemId",
    "CreatedById",
    "CreatedDate",
  ]),
  DEPLOY_HISTORICAL_LIMIT: 25,
  // Salesforce IDs are delivered in an 18 character, case-insensitive form whose
  // last 3 characters are a checksum over the case of the leading 15
  ID_SHORT_LENGTH: 15,
};
