export default {
  CLEAN_STATUS: [
    "Matched",
    "Different",
    "Acknowledged",
    "NotFound",
    "Inactive",
    "Pending",
    "SelectMatch",
    "Skipped",
  ],
  CALL_TYPES: [
    "Inbound",
    "Internal",
    "Outbound",
  ],
  RECURRENCE_REGENERATED_TYPE: [
    "None",
    "After due date",
    "After the task is closed",
    "(Task closed)",
  ],
  TASK_SUB_TYPES: [
    "Task",
    "Email",
    "List Email",
    "Cadence",
    "Call",
  ],
  OBJECT_TYPE: {
    CAMPAIGN: "Campaign",
    CONTACT: "Contact",
    CAMPAIGN_MEMBER: "CampaignMember",
    LEAD: "Lead",
    FEED_ITEM: "FeedItem",
    FEED_COMMENT: "FeedComment",
  },
  FIELD_NAME: {
    CREATED_DATE: "CreatedDate",
    LAST_MODIFIED_DATE: "LastModifiedDate",
  },
  FEED_ITEM_MIN_FIELDS: Object.freeze([
    "Id",
    "Type",
    "Body",
    "ParentId",
    "CreatedById",
    "CreatedDate",
  ]),
  FEED_COMMENT_MIN_FIELDS: Object.freeze([
    "Id",
    "CommentBody",
    "ParentId",
    "FeedItemId",
    "CreatedById",
    "CreatedDate",
  ]),
  DEPLOY_HISTORICAL_LIMIT: 25,
};
