<template><h1 id="security-best-practices" tabindex="-1"><a class="header-anchor" href="#security-best-practices" aria-hidden="true">#</a> Security Best Practices</h1>
<p>Pipedream implements a range of <a href="/privacy-and-security/" target="_blank" rel="noopener noreferrer">privacy and security measures<ExternalLinkIcon/></a> meant to protect your data from unauthorized access. Since Pipedream <a href="/workflows" target="_blank" rel="noopener noreferrer">workflows<ExternalLinkIcon/></a>, <a href="/event-sources" target="_blank" rel="noopener noreferrer">event sources<ExternalLinkIcon/></a>, and other resources can run any Node.js code and process any event data, you also have a responsibility to ensure you handle that code and data securely. We've outlined a handful of best practices for that below.</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#keep-your-workflow-private">Keep your workflow private</RouterLink></li><li><RouterLink to="#share-your-workflow-only-with-trusted-collaborators">Share your workflow only with trusted collaborators</RouterLink></li><li><RouterLink to="#store-secrets-as-pipedream-connected-accounts-or-environment-variables">Store secrets as Pipedream connected accounts or environment variables</RouterLink></li><li><RouterLink to="#deliver-data-to-pipedream-securely">Deliver data to Pipedream securely</RouterLink></li><li><RouterLink to="#send-data-out-of-pipedream-securely">Send data out of Pipedream securely</RouterLink></li><li><RouterLink to="#add-authentication-to-incoming-event-data">Add authentication to incoming event data</RouterLink></li><li><RouterLink to="#validate-signatures-for-incoming-events-where-available">Validate signatures for incoming events, where available</RouterLink></li><li><RouterLink to="#audit-code-or-packages-you-use-within-a-workflow">Audit code or packages you use within a workflow</RouterLink></li><li><RouterLink to="#limit-what-you-log-and-return-from-steps">Limit what you log and return from steps</RouterLink></li></ul></nav>
<h2 id="keep-your-workflow-private" tabindex="-1"><a class="header-anchor" href="#keep-your-workflow-private" aria-hidden="true">#</a> Keep your workflow private</h2>
<p>By default, all workflow code is private. But <a href="/public-workflows/" target="_blank" rel="noopener noreferrer">you can make that code public<ExternalLinkIcon/></a> when developing tutorials or examples to share with others. Public workflows can be useful in this context. In all other cases, we recommend you keep your workflow private.</p>
<p>If you only need to share your workflow with specific people, <a href="#share-your-workflow-only-with-trusted-collaborators">you can share your workflow with specific collaborators</a>.</p>
<h2 id="share-your-workflow-only-with-trusted-collaborators" tabindex="-1"><a class="header-anchor" href="#share-your-workflow-only-with-trusted-collaborators" aria-hidden="true">#</a> Share your workflow only with trusted collaborators</h2>
<p><a href="/workflows/managing/#sharing-workflows" target="_blank" rel="noopener noreferrer">You can share your workflow with specific individuals<ExternalLinkIcon/></a>. <strong>These collaborators have full read / write access to your workflow</strong>. Collaboration is useful when you're working with a contractor or a team, but you should share your workflow only with people you trust.</p>
<p>Audit the list of collaborators on a regular basis. If someone leaves your team, or if you end a contract with a consultant, we recommend you remove them from the list of collaborators.</p>
<h2 id="store-secrets-as-pipedream-connected-accounts-or-environment-variables" tabindex="-1"><a class="header-anchor" href="#store-secrets-as-pipedream-connected-accounts-or-environment-variables" aria-hidden="true">#</a> Store secrets as Pipedream connected accounts or environment variables</h2>
<p>Even if your workflow code is private, you should never store secrets like API keys in code. These secrets should be stored in one of two ways:</p>
<ul>
<li><a href="https://pipedream.com/apps" target="_blank" rel="noopener noreferrer">If Pipedream integrates with the app<ExternalLinkIcon/></a>, use <a href="/connected-accounts/" target="_blank" rel="noopener noreferrer">connected accounts<ExternalLinkIcon/></a> to link your apps / APIs.</li>
<li>If you need to store credentials for an app Pipedream doesn't support, or you need to store arbitrary configuration data, use <a href="/environment-variables/" target="_blank" rel="noopener noreferrer">environment variables<ExternalLinkIcon/></a>.</li>
</ul>
<p>Read more about how Pipedream secures connected accounts / environment variables <a href="/privacy-and-security/#third-party-oauth-grants-and-api-keys" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>.</p>
<h2 id="deliver-data-to-pipedream-securely" tabindex="-1"><a class="header-anchor" href="#deliver-data-to-pipedream-securely" aria-hidden="true">#</a> Deliver data to Pipedream securely</h2>
<p>Whenever possible, encrypt data in transit to Pipedream. For example, use HTTPS endpoints when sending HTTP traffic to a workflow.</p>
<h2 id="send-data-out-of-pipedream-securely" tabindex="-1"><a class="header-anchor" href="#send-data-out-of-pipedream-securely" aria-hidden="true">#</a> Send data out of Pipedream securely</h2>
<p>When you connect to APIs in a workflow, or deliver data to third-party destinations, encrypt that data in transit. For example, use HTTPS endpoints when sending HTTP traffic to third parties.</p>
<h2 id="add-authentication-to-incoming-event-data" tabindex="-1"><a class="header-anchor" href="#add-authentication-to-incoming-event-data" aria-hidden="true">#</a> Add authentication to incoming event data</h2>
<p>You can add many public-facing triggers to your workflows. For example, when you add an HTTP trigger to your workflow, anyone with the associated trigger URL can invoke it. You should protect your workflow with an authentication mechanism like <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication" target="_blank" rel="noopener noreferrer">Basic Auth<ExternalLinkIcon/></a>, JWT, or others.</p>
<p>See <a href="https://pipedream.com/@dylburger/protect-an-http-endpoint-with-basic-auth-p_pWCYAez/edit" target="_blank" rel="noopener noreferrer">this workflow<ExternalLinkIcon/></a> for a Basic Auth example. This reads the username and password encoded in the <code>Authorization</code> header and compares it to the expected values, returning a <code>401 Unauthorized</code> error if auth fails.</p>
<p>This pattern is typical for protecting workflows: add the authentication logic in a step at the top of your workflow, ending early if auth fails. If auth succeeds, Pipedream runs the remaining steps of your workflow.</p>
<h2 id="validate-signatures-for-incoming-events-where-available" tabindex="-1"><a class="header-anchor" href="#validate-signatures-for-incoming-events-where-available" aria-hidden="true">#</a> Validate signatures for incoming events, where available</h2>
<p>Many apps pass a <strong>signature</strong> with event data delivered via webhooks (or other push delivery systems). The signature is an opaque value computed from the incoming event data and a secret that only you and the app know. When you receive the event, you can validate the signature by computing it yourself and comparing it to the signature sent by the app. If the two values match, it verifies that the app sent the data, and not some third party.</p>
<p>Signatures are specific to the app sending the data, and the app should provide instructions for signature validation. <strong>Not all apps compute signatures, but when they do, you should always verify them</strong>.</p>
<p>When you use a Pipedream <a href="/event-sources/" target="_blank" rel="noopener noreferrer">event source<ExternalLinkIcon/></a> as your workflow trigger, Pipedream should verify the signature for you. You can always <a href="#audit-any-code-or-packages-you-use-within-a-workflow">audit the code behind the event source</a> to confirm this, and suggest further security improvements that you find.</p>
<p>See <a href="https://stripe.com/docs/webhooks/signatures" target="_blank" rel="noopener noreferrer">Stripe's signature docs<ExternalLinkIcon/></a> for a real-world example. Pipedream's Stripe event source <a href="https://github.com/PipedreamHQ/pipedream/blob/bb1ebedf8cbcc6f1f755a8878c759522b8cc145b/components/stripe/sources/custom-webhook-events/custom-webhook-events.js#L49" target="_blank" rel="noopener noreferrer">verifies this signature for you<ExternalLinkIcon/></a>.</p>
<h2 id="audit-code-or-packages-you-use-within-a-workflow" tabindex="-1"><a class="header-anchor" href="#audit-code-or-packages-you-use-within-a-workflow" aria-hidden="true">#</a> Audit code or packages you use within a workflow</h2>
<p>Pipedream workflows are just code. Pipedream provides prebuilt triggers and actions that facilitate common use cases, but these are written and run as code within your workflow. You can examine and modify this code in any way you'd like.</p>
<p>This also means that you can audit the code for any triggers or actions you use in your workflow. We encourage this as a best practice. Even code authored by Pipedream can be improved, and if you notice a vulnerability or other issue, you can submit a patch or raise an issue <a href="https://github.com/PipedreamHQ/pipedream/tree/master/components" target="_blank" rel="noopener noreferrer">in our GitHub repo<ExternalLinkIcon/></a>.</p>
<p>The same follows for <a href="https://www.npmjs.com/" target="_blank" rel="noopener noreferrer">npm<ExternalLinkIcon/></a> packages. Before you use a new npm package in your workflow, review its page on npm and its repo, if available. Good packages should have recent updates. The package should have a healthy number of downloads and related activity (like GitHub stars), and the package author should be responsive to issues raised by the community. If you don't observe these signals, be wary of using the package in your workflow.</p>
<h2 id="limit-what-you-log-and-return-from-steps" tabindex="-1"><a class="header-anchor" href="#limit-what-you-log-and-return-from-steps" aria-hidden="true">#</a> Limit what you log and return from steps</h2>
<p><a href="/limits/#event-execution-history" target="_blank" rel="noopener noreferrer">Pipedream retains a limited history of event data<ExternalLinkIcon/></a> and associated logs for event sources and workflows. But if you cannot log specific data in Pipedream for privacy / security reasons, or if you want to limit risk, remember that <strong>Pipedream only stores data returned from or logged in steps</strong>. Specifically, Pipedream will only store:</p>
<ul>
<li>The event data emitted from event sources, and any <code>console</code> logs / errors</li>
<li>The event data that triggers your workflow, any <code>console</code> logs / errors, <a href="/workflows/steps/#step-exports" target="_blank" rel="noopener noreferrer">step exports<ExternalLinkIcon/></a>, and any data included in error stack traces.</li>
</ul>
<p>Variables stored in memory that aren't logged or returned from steps are not included in Pipedream logs. Since you can modify any code in your Pipedream workflow, if you want to limit what gets logged from a Pipedream action or other step, you can adjust the code accordingly, removing any logs or step exports.</p>
</template>
