export default {
  guid: 'c0c123ca-4ec7-08a4-b6bb-9a68ce4c321a',
  name: 'Notebook Name',
  updateSequenceNum: 11,
  defaultNotebook: false,
  serviceCreated: 1742321666000,
  serviceUpdated: 1742321666000,
  publishing: null,
  published: null,
  stack: null,
  sharedNotebookIds: null,
  sharedNotebooks: null,
  businessNotebook: null,
  contact: null,
  restrictions: {
    noReadNotes: null,
    noCreateNotes: null,
    noUpdateNotes: null,
    noExpungeNotes: null,
    noShareNotes: null,
    noEmailNotes: null,
    noSendMessageToRecipients: null,
    noUpdateNotebook: null,
    noExpungeNotebook: null,
    noSetDefaultNotebook: null,
    noSetNotebookStack: null,
    noPublishToPublic: null,
    noPublishToBusinessLibrary: true,
    noCreateTags: null,
    noUpdateTags: null,
    noExpungeTags: null,
    noSetParentTag: null,
    noCreateSharedNotebooks: null,
    updateWhichSharedNotebookRestrictions: null,
    expungeWhichSharedNotebookRestrictions: null,
    noShareNotesWithBusiness: true,
    noRenameNotebook: null
  },
  recipientSettings: {
    reminderNotifyEmail: true,
    reminderNotifyInApp: true,
    inMyList: true,
    stack: null
  }
}